cake-build/cake

- src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs
- src/Cake.Core.Tests/Fixtures/ScriptRunnerFixture.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/IO/NuGet/INuGetToolResolver.cs
- src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
- src/Cake.Core/Scripting/Processors/AddInDirectiveProcessor.cs
- src/Cake.Core/Scripting/ScriptProcessor.cs
- src/Cake/Program.cs
Makes it possible to load and reference addins via NuGet
Sample script
```csharp
#addin "Cake.AliaSql"
AliaSql("Rebuild", new AliaSqlSettings{ToolPath=""});
```
This will give an output  similar to (It outputs an error as I'm sending in bogus settings, but it's from the AddIn code)
```
Installing 'Cake.AliaSql 0.4.1'.
Successfully installed 'Cake.AliaSql 0.4.1'.
Addin: Cake.AliaSql, adding Reference C:/temp/dev/github/cake/tools/Addins/Cake.AliaSql/Cake.AliaSql.dll
Error: Path cannot be empty.
Parameter name: path
```
What it does is basically
1. Check if AddIns folder exists if not it creates it
2. Then if checks if the choosen Addin exists and if it contains any assemblies, if not it will try to find nuget.exe and install the package
3. It will reference any found assemblies
> Added #addin directive for NuGet addins

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettings.cs
Added support for assembly info company setting
```csharp
var file = "./src/SolutionInfo.cs";
CreateAssemblyInfo(file, new AssemblyInfoSettings {
Company= "WCOM AB"
});
``` 
will add
`[assembly: AssemblyCompany("WCOM AB")]`
> Added AssemblyCompany to AssemblyInfoCreator

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs
Currently uses `System.Text.Encoding.Default` which isn't predictable and often doesn't support non ascii characters.
> Added predictable encoding to AssemblyInfoCreator

- src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs
- src/Cake.Common/Tools/NuGet/Pack/NuSpecContent.cs
- src/Cake.Common/Tools/NuGet/Pack/NuSpecTransformer.cs
Added support for specifying the nuspec files from cake via NuGetPackSettings like below
```csharp
NuGetPack("App.nuspec", new NuGetPackSettings
{
Files = new[]
{
new NuSpecContent {Src = "App.Core.dll", Target = "lib/net45"},
new NuSpecContent {Src = "App.Core.xml", Target = "lib/net45"},
new NuSpecContent {Src = "App.Core.pdb", Target = "lib/net45"},
new NuSpecContent {Src = "LICENSE"}
new NuSpecContent {Src = "App.Common.*", Target = "lib/net45", Exclude = "*.pdb"},
}
});
```
> Add support for transforming nuspec files

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/NuGetFixture.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerSettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/NuGet/Install/NuGetInstaller.cs
- src/Cake.Common/Tools/NuGet/Install/NugetInstallSettings.cs
- src/Cake.Common/Tools/NuGet/NuGetAliases.cs
This addition allows you to install NuGet packages within build scripts.
Example usage:
```csharp
NuGetInstall("MyNugetPackage", new NuGetInstallSettings {
Version         = semVersion,
ExcludeVersion  = true,
OutputDirectory = deployDir
});`
```
> Added Nuget install with tests

- src/Cake.Common.Tests/Fixtures/FileSystemFixture.cs
- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/DirectoryCleaner.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/IO/Directory.cs
- src/Cake.Core/IO/File.cs
- src/Cake.Core/IO/IDirectory.cs
- src/Cake.Core/IO/IFile.cs
- src/Cake.Core/IO/IFileSystemInfo.cs
- src/Cake.Testing/Fakes/FakeDirectory.cs
- src/Cake.Testing/Fakes/FakeFile.cs
- src/Cake.Testing/Fakes/FakeFileSystem.cs
This commit adds possibility to filter which files / directories get deleted by the `CleanDirectory` alias.
```csharp
CleanDirectory("C:/temp/deploy/TestDeployRepo", entry=>!entry.Hidden);
```
Will result in something like
```
Deleting contents of C:/temp/deploy/TestDeployRepo
Skipping C:/temp/deploy/TestDeployRepo/.git because specified predicate
Deleting contents of C:/temp/deploy/TestDeployRepo/bin
```
This is done with adding a where predicate to `Cake.Core.IO.IDirectory` `GetDirectories` & `GetFiles`
Also added `Hidden` property to `Directory` & `File` to expose if file/directory is hidden and a common `IFileSystemInfo` do enable a common predicate for `CleanDirectory`
Added new overloads & tests for this, also added option to specify action to get "callback" when files are excluded, …
> Added filter support to CleanDirectory

- src/Cake.Common/ProcessAliases.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs
- src/Cake.Core/Extensions/TypeExtensions.cs
- src/Cake.Core/IO/IProcess.cs
- src/Cake.Core/IO/ProcessSettings.cs
- src/Cake.Core/IO/ProcessWrapper.cs
- src/Cake.Core/Scripting/CodeGen/MethodAliasGenerator.cs
* Added option for getting the console output of an process
* Added option for setting an timeout when executing an process
* Fixed codegen issue with alias proxies and generic out parameters
Example usage of console output
```csharp
IEnumerable<string> redirectedOutput;
var exitCodeWithArgument = StartProcess("ping", new ProcessSettings{
Arguments = "localhost",
RedirectStandardOutput = true
},
out redirectedOutput
);
//Output last line of process output
Information("Last line of output: {0}", redirectedOutput.LastOrDefault());
// This should output 0 as valid arguments supplied
Information("Exit code: {0}", exitCodeWithArgument);
```
This will output something similar to:
```
Last line of output:     Minimum = 0ms, Maximum = 0ms, Average = 0ms
Exit code: 0
```
Example usage of process …
> Added process output&timeout, fixed codegen issue

- src/Cake.Tests/Unit/CakeApplicationTests.cs
- src/Cake/CakeApplication.cs
Since default script functionality was added it's kinda hard to reach the help / version functionality.
In this PR I propose a raised priority of help / version command to be invoked regardless of other parameters.
Also modified tests to work accordingly
> Changed argument precedence in favor of help/version

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/CakeRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/Cake/CakeRunnerTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/Cake/CakeAliases.cs
- src/Cake.Common/Tools/Cake/CakeRunner.cs
- src/Cake.Common/Tools/Cake/CakeSettings.cs
Proposed added functionality to the DSL to run cake scripts & expression out of process.
Example usage script:
```csharp
CakeExecuteScript("build.cake", new CakeSettings { ToolPath="./src/Cake/bin/debug/cake.exe" });
```
Example usage expression:
```csharp
CakeExecuteExpression("Information(\"Hello!\");", new CakeSettings { ToolPath="./src/Cake/bin/debug/cake.exe" });
```
> Added aliases for executing cake scripts out of process

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Unit/Security/FileHashCalculatorTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Security/FileHash.cs
- src/Cake.Common/Security/FileHashCalculator.cs
- src/Cake.Common/Security/HashAlgorithm.cs
- src/Cake.Common/Security/SecurityAliases.cs
A small but useful alias for calculating file hashes. This can be used when (for example) publishing packages online and one wants to publish the file hash alongside it.
The default hash is SHA256 which is the same as Powershell uses as default hash in the `Get-FileHash` cmdlet.
```csharp
// Calculate the default SHA256 hash.
FileHash sha256Hash = CalculateFileHash("./some-file.txt");
Information("Hash: " + sha256Hash.ToHex());
// Calculate the MD5 hash.
FileHash md5Hash = CalculateFileHash("./some-file.txt", HashAlgorithm.MD5);
Information("Hash: " + md5Hash.ToHex());
```
> Implemented a file hash calculator.

- src/Cake.Common.Tests/Fixtures/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
- src/Cake.Testing/ExceptionAsserts.cs
Using `Cake.Core.Diagnostics.Verbosity` as argument type, since the MSBuild verbosity parameters (`quiet`, `minimal`, `normal`, `verbose`, `diagnostic`) map 1:1 to this.
```csharp
MSBuild("./src/Cake.sln", settings =>
settings.SetConfiguration(configuration)
.SetVerbosity(Verbosity.Minimal)
.WithProperty("TreatWarningsAsErrors", "true")
.UseToolVersion(MSBuildToolVersion.NET45));
```
The default verbosity is `Normal`.
> Added MSBuild verbosity setting.

- src/Cake/Diagnostics/CakeBuildLog.cs
This fixes an issue with background colors in the console.
> Should write line break after resetting console colors.

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Testing/Cake.Testing.csproj
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake/Cake.csproj
Made debug configuration more relaxed by turning off StyleCop, FXCop and warnings as errors. This will reduce frustration while developing new functionality, as well as reduce overall build time. 
**The release configuration still performs all those tests**, so the build will be broken if the rules are not followed. It is advised to always run the Cake build script or build the project with the release configuration before creating a pull request.
> Made debug configuration more relaxed.

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/FileAliases.cs
- src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs
- src/Cake.Core/IO/DirectoryPath.cs
Added aliases to make working with paths easier and the script code more readable.
Also, no more strings concatenation to get a `DirectoryPath`/`FilePath`. :tada: :balloon: 
```csharp
// Get the path to the plugins directory.
var root = Directory("./");
var bin = root + Directory("app/bin");
var plugins = bin + Directory("plugins");
// Get the executable path.
var executable = bin + File("MyApp.exe");
// Do some work.
CleanDirectory(plugins);
DeleteFile(executable);
```
**Note/Question:**
Not sure if I should rename the aliases `Directory` and `File` to `GetDirectory` and `GetFile`.
This would probably be more consistent with [GetDirectories](http://cakebuild.net/api/cake.common.io/b6f866f7/0a89ebe2/) and [GetFiles](http://cakebuild.net/api/cake.common.io/b6f866f7/796bd28f/).
> Added convenience aliases for working with directory and file paths.

- src/Cake.Core/IO/ProcessWrapper.cs
When process output is redirected and handled, I propose it should only log this output on diagnostic loglevel.
> Only output handled process if diagnostic

- src/Cake/Program.cs
.Net args parsing seems to have issues with the cake arguments and quotes, this tries to remedy that by bypassing the standard parsing.
> Added own commandline to args parsing. Fixes #172

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/LogActionFixture.cs
- src/Cake.Common.Tests/Unit/Diagnostics/LoggingAliasesTests.cs
- src/Cake.Common/Diagnostics/LoggingAliases.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/Diagnostics/ICakeLog.cs
- src/Cake.Core/Diagnostics/LogAction.cs
- src/Cake.Core/Diagnostics/LogExtensions.cs
- src/Cake.Core/Diagnostics/NullLog.cs
- src/Cake.Testing/Fakes/FakeLog.cs
- src/Cake.Tests/Unit/CakeApplicationTests.cs
- src/Cake.Tests/Unit/Diagnostics/CakeBuildLogTests.cs
- src/Cake/CakeApplication.cs
- src/Cake/Diagnostics/CakeBuildLog.cs
- src/Cake/Diagnostics/IVerbosityAware.cs
Some logging takes time / resources and because of that we might only want to run them if i.e. `verbosity` is set to `Diagnostic`
Currently it will just omit the data when logging higher verbosity then `Cake` is launched with, but the work to evaluate the log message is till done.
That's why a propose that add an option where an function could be passed instead of `format` & `args` to the logging aliases.
A simple example of these new alias would be:
```csharp
Information(
write => {
//do some hard word
write("This will only be called Verbosity>={0}", "Normal");
});
``` 
The above message would only be evaluated and displayes if cake is launched withe the verbosities Normal, Verbose or Verbose
An more advanced example would be
```csharp
var tests = new KeyValuePair<string, …
```
> Added support for lazy by verbosity logging

- src/Cake.Core.Tests/Fixtures/CakeEngineFixture.cs
- src/Cake.Core.Tests/Fixtures/ScriptHostFixture.cs
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/ICakeEngine.cs
- src/Cake.Core/IExecutionStrategy.cs
- src/Cake.Core/Scripting/ScriptHost.cs
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
- src/Cake.Tests/Unit/CakeApplicationTests.cs
- src/Cake.Tests/Unit/Scripting/BuildScriptHostTests.cs
- src/Cake.Tests/Unit/Scripting/DryRunExecutionStrategyTests.cs
- src/Cake.Tests/Unit/Scripting/DryRunScriptHostTests.cs
- src/Cake/Arguments/ArgumentParser.cs
- src/Cake/Cake.csproj
- src/Cake/CakeApplication.cs
- src/Cake/CakeOptions.cs
- src/Cake/Commands/CommandFactory.cs
- src/Cake/Commands/DryRunCommand.cs
- src/Cake/Commands/HelpCommand.cs
- src/Cake/Commands/ICommandFactory.cs
- src/Cake/Program.cs
- src/Cake/Scripting/BuildScriptHost.cs
- src/Cake/Scripting/DescriptionScriptHost.cs
- src/Cake/Scripting/DryRunExecutionStrategy.cs
- src/Cake/Scripting/DryRunScriptHost.cs
By providing the parameter `dryrun`, `noop` or `whatif`, a [dry run](http://en.wikipedia.org/wiki/Dry_run_%28testing%29) will be performed. This is useful to see what tasks will be executed given the current context (environment variables, arguments etc). 
No tasks will actually be executed.
```
PS> .\Cake.exe build.cake -dryrun
Performing dry run...
Target is: Build
1. Clean
2. Build
3. Copy-Files
4. Package-Files
This was a dry run.
No tasks were actually executed.
```
Related to issue #155.
> Added dry run support.

- ReleaseNotes.md
- src/SolutionInfo.cs
- tools/packages.config
Do enable building Cake on Windows 10 we should bump the version being used.
> Build Cake with Cake version 0.3.2

- src/Cake.Common.Tests/Unit/IO/Paths/ConvertableDirectoryPathTests.cs
- src/Cake.Common.Tests/Unit/IO/Paths/ConvertableFilePathTests.cs
- src/Cake.Common/IO/Paths/ConvertableDirectoryPath.cs
- src/Cake.Common/IO/Paths/ConvertableFilePath.cs
So we get a sane representation of convertable paths.
```csharp
Information("Writing {0}...", File("./foo.bar"));
Warning("The directory {0} do not exist.", Directory("./foo/bar"));
```
> Added ToString for convertable paths.

- src/Cake/Cake.csproj
Kind of embarassing, but I found the reason for Cake not working on .NET 4.6 with the old bits. Not sure why the prefer 32-bit flag was set at all in the first place to be honest...
Should probably be tested on a machine without .NET 4.6 as well.
> Made Cake work on .NET 4.6 without experimental flag.

- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs
- src/Cake.Core.Tests/Fixtures/ScriptRunnerFixture.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/NuGetToolResolverTests.cs
- src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
NuGet exe will now be resolved in the following order:
1. Check tools path (`./tools/**/nuget.exe`)
2. Use `NUGET_EXE` environment variable (if present).
3. Check all paths in the `path` environment variable.
> Changed the way nuget.exe is resolved.

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/FileAliases.cs
Added two aliases for making paths absolute.
```csharp
// Get absolute file path.
var file = GetAbsoluteFilePath(File("./foo.txt"));
// Get absoltue directory path.
var dir = GetAbsoluteDirectoryPath(Directory("./foo"));
```
Not sure of the name of the aliases are good or consistent.
Any thoughts about this?
> Added aliases for making paths absolute.

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/GlobbingAliases.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globber.cs
- src/Cake.Core/IO/GlobberExtensions.cs
- src/Cake.Core/IO/IGlobber.cs
Sometimes when working with recursive globbering it can lead into a rabbit hole of loads of folders, given at best bad performance and at worst hitting the .Net max path length limitation.
This PR proposes you to set a predicate for folders / files you know there's no need to explorer / include.
Sample DSL usage `GetFiles` with predicate:
```csharp
Func<IFileSystemInfo, bool> exclude_node_modules =
fileSystemInfo=>!fileSystemInfo.Path.FullPath.EndsWith(
"node_modules",
StringComparison.OrdinalIgnoreCase);
var solutions = GetFiles("./**/*.sln", exclude_node_modules);
```
Sample DSL `CleanDirectories` with predicate:
```csharp
Task("Clean")
.Does(() =>
{
// Clean solution directories.
foreach(var path in solutionPaths)
{
Information("Cleaning {0}", path);
CleanDirectories(path + "/**/bin/" …
```
> Added filter predicate overloads to globber & clean directory methods

- src/Cake.Core.Tests/Unit/IO/FilePathTests.cs
- src/Cake.Core/IO/FilePath.cs
Added the method `FilePath.GetFilenameWithoutExtension` to retrieve a new `FilePath` containing the filename without it's extension.
```csharp
var path = new FilePath("./src/dummy.txt");
var filename = path.GetFilenameWithoutExtension();
Debug.Assert(filename.FullPath == "dummy");
```
> Added method to retrieve the filename without it's extension.

- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/IO/Net/HttpAliases.cs
I do a lot of downloading of external files in my build scripts. 
This adds a new `HttpAliases` class with (so far) a single `DownloadFile(string url, DirectoryPath outputPath)` alias which does exactly what it looks like.
Eventually there could be more HTTP related aliases here such as `DownloadString`
> Added DownloadFile alias

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
MSBuild uses the flag 'detailed' instead of 'verbose'. This applies
the correct mapping to fix the discrepancy.
Closes #282 - "Cake uses wrong MSBuild verbosity parameter"
> changed msbuild verbosity

- src/Cake.Core/Scripting/Processors/UsingStatementProcessor.cs
if space comes between `using` and `(` in using `IDisposable` statement it gets treated as an namespace. example
```csharp
using (new MemoryStream())
{
new StringBuilder();
}
```
fails before this fix.
> Fix for using (IDisposable) statement

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/DirectoryCleaner.cs
- src/Cake.Testing/Fakes/FakeFileSystemTree.cs
A bug in the CleanDirectory aliases prevented some directories
to be deleted under some circumstances. This has been fixed.
Resolves #289
> Fix for CleanDirectory bug.

- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs
- src/Cake.Common/Tools/XUnit/XUnit2Runner.cs
- src/Cake.Common/Tools/XUnit/XUnit2Settings.cs
Added support for the -noappdomain option to enable tests
to run on Mono. Currently only supported in 2.1.0-beta4-build3109.
Also removed quoting of xUnit options.
Closes #329
> xUnit: Added support for -noappdomain option.

- build.cake
- build.ps1
- nuspec/Cake.Common.nuspec
- src/Cake.sln
Hello everybody,
A very small PR that packages Cake.Common into a .nupkg. This does not change anything to the project except that Cake.Common becomes usable from an autonomous application that may need it (once it will be pushed on nuget.org of course!).
> Packaging Cake.Common.dll into Cake.Common.nupkg.

- src/Cake.Common.Tests/Fixtures/Tools/NuGet/NuGetPackerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs
- src/Cake.Common/Tools/NuGet/NuGetAliases.cs
- src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
- src/Cake.Common/Tools/NuGet/Pack/NuspecProcessor.cs
This will allow to pack Nuget packages without having a nuspec file as long as enough parameters supplied in the Cake file and nuspec directory exists making less friction to create packages and cleaner repos.
> Remove nuspec requirement if sufficent parameters supplied

- src/Cake.Common/ArgumentAliases.cs
Just something that annoyed me the other day -- I forgot to pass in an argument and the resulting exception message `"Argument was not set."` wasn't very helpful.
Now it'll be `"Argument 'MY_ARGUMENT_NAME' was not set."`
> Enhance exception message to include name of missing cake argument

- src/Cake.Common.Tests/Fixtures/ProcessFixture.cs
- src/Cake.Common.Tests/Unit/ProcessAliasesTests.cs
- src/Cake.Common/ProcessAliases.cs
added `StartNewProcess` alias methods to `ProcessAlias`.
Note: I'm not in love with the method name, but I was limited by the existing methods' names.
The existing ones, named `StartProcess` don't just start the process, they really execute the process and report the exit code.
My new ones do actually just start the process, leaving the user to interact with the resulting process in the manner of their choosing.  So in a perfect world where we didn't have to worry about breaking changes, my new methods would be named `StartProcess`, and the old ones would be renamed to `ExecuteCommand` or `ExecuteProcess`.
> Extended ProcessAliases with methods returning IProcess

- src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
On OSX 10.11 (El Capitan) we can no longer have `/usr/bin/nuget` as `/usr/bin/` is not writeable.  The new location for this symlink will be `/usr/local/bin/nuget` so we should check for that.
> Add path to nuget resolver for mono on osx 10.11

- src/Cake.Common/Tools/Cake/CakeRunner.cs
Currently if you install cake via homebrew and execute it using the global alias `cake` and then proceed to use `CakeExecuteScript (..)` it will fail to find `Cake.exe` to run.
This patch simply looks for `Cake.exe` in the paths that homebrew will install cake and sorts it so that the newest version is returned first.
> Added homebrew install paths to Cake tool resolver

- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globber.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/GlobVisitorContext.cs
- src/Cake.Core/IO/IGlobber.cs
Before the Globber rewrite, the predicate was used as a way of
telling the Globber what directories to recurse into when using
double star (`**`) or directory wildcard (`*`). When rewriting
the globber, the predicate was used to determine filtering of
directories and files in the results. This has now been changed.
This will (sadly) lead to a breaking change for people who rely
on filtering the results, but this could be easily corrected by
simply using a `Where` clause on the resulting collection.
> Restored accidental sematic change with globber predicates.

- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Core/CakeEnvironment.cs
- src/Cake.Core/ICakeEnvironment.cs
- src/Cake.Testing/Fakes/FakeEnvironment.cs
In some cases you don't know which environment variables exists or you need to work with a set of environment variables.
In this proposal I add a typed version of `System.Environment.GetEnvironmentVariables()` which will give you an case insensitive `IDictionary<string, string>`
Example usage:
```csharp
var envVars = Context.Environment.GetEnvironmentVariables();
string path;
if (envVars.TryGetValue("PATH", out path))
{
Information("Path: {0}", path);
}
foreach(var envVar in envVars)
{
Information(
"Key: {0}\tValue: \"{1}\"",
envVar.Key,
envVar.Value
);
}
```
> Added Environment IDictionary<string, string> GetEnvironmentVariables()

- src/Cake.Common.Tests/Fixtures/XmlDocExampleCodeParserFixture.cs
- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/FileCopier.cs
- src/Cake.Common/IO/FileDeleter.cs
- src/Cake.Common/IO/FileMover.cs
- src/Cake.Common/IO/ZipAliases.cs
- src/Cake.Common/Solution/Project/XmlDoc/XmlDocAliases.cs
- src/Cake.Common/Solution/Project/XmlDoc/XmlDocExampleCodeParser.cs
- src/Cake.Common/Tools/DupFinder/DupFinderAliases.cs
- src/Cake.Common/Tools/Fixie/FixieAliases.cs
- src/Cake.Common/Tools/MSTest/MSTestAliases.cs
- src/Cake.Common/Tools/NUnit/NUnitAliases.cs
- src/Cake.Common/Tools/WiX/WiXAliases.cs
- src/Cake.Common/Tools/XUnit/XUnit2Aliases.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/GlobToken.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/GlobVisitorContext.cs
Sometimes when providing a glob pattern to certain aliases such
as NUnit or XUnit, a mistake in the pattern will result in
zero files being matched. This is kind of annoying since the
call to the alias will silently pass. This might be by design
but we should at least write a verbose message saying that no
files or directories were matched.
Closes #408
> Added verbose message when glob pattern did not match anything.

- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskTests.cs
- src/Cake.Core.Tests/Unit/Scripting/ScriptHostTests.cs
- src/Cake.Core.Tests/Unit/TaskSetupContextTests.cs
- src/Cake.Core.Tests/Unit/TaskTeardownContextTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeTask.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/ICakeEngine.cs
- src/Cake.Core/ICakeTaskInfo.cs
- src/Cake.Core/IExecutionStrategy.cs
- src/Cake.Core/ITaskSetupContext.cs
- src/Cake.Core/ITaskTeardownContext.cs
- src/Cake.Core/Scripting/IScriptHost.cs
- src/Cake.Core/Scripting/ScriptHost.cs
- src/Cake.Core/TaskSetupContext.cs
- src/Cake.Core/TaskTeardownContext.cs
- src/Cake/Scripting/DryRunExecutionStrategy.cs
Initial design approach for #389, submitted for feedback. Code is not tested or documented.
I'm not in love with the procedural logic in `CakeEngine` -- I think my implementation could benefit from a bit of internal refactoring of that class's existing code.
> Closes #389: TaskSetup, TaskTeardown functionality

- build.cake
I wan't do be able to automatically build my fork of Cake too on AppVeyor. Currently it fails when trying to publish to MyGet because it lacks the proper ApiKey, obviously forks shouldn't publish to Cake MyGet feed.
So what I propose is that we check which repo is built and only if it's `cake-build/cake` should we publish to MyGet, this enables automatic builds of forks with the standard `build.cake`
> Added main cake repo requirement for MyGet publish

- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/IO/Globbing/GlobNodeValidator.cs
- src/Cake.Core/IO/Globbing/GlobParser.cs
- src/Cake.Core/IO/Globbing/GlobTokenKind.cs
- src/Cake.Core/IO/Globbing/GlobTokenizer.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/Nodes/ParentSegment.cs
Parent directory references `..` could not be used properly which
required using work arounds for patterns like `../path`.
Closes #390
> Allow referencing parent directory in glob expression

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
This is a semantic change to how the MSBuild runner works, but it will allow
for more flexibility.
Closes #412
> Removed quotes from MSBuild arguments

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettings.cs
This is useful for checking the configuration (eg Debug, Release) that an assembly was built using
> Allow setting the AssemblyConfiguration attribute

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/Nodes/PathSegment.cs
- A dot inside a pattern token is passed to the regex as common dot, where
it is treated as an arbitrary character instead of real dot character.
- By prefixing with a backslash in the regex, the dot is treated as real
character.
> Treat a . (dot) in glob pattern as dot instead of character wildcard

- src/Cake.Core/Scripting/ScriptRunner.cs
- src/Cake/Scripting/Mono/MonoScriptSession.cs
We've been using Assembly.LoadFile to load script assembly references
which work great until you load an assembly where there is a
dependency to a previously loaded assembly. By using Assembly.LoadFrom
we make sure that assemblies are loaded properly.
Closes #415
> Change the way assembly references are loaded.

- build.ps1
Since PowerShell maintains backwards compatibility this was the
suggested solution.
> Fixes #437 Converting PS 3 to PS 2 commands

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerAssetsAdderFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerCreatorFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerExporterFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerMilestoneCloserFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerPublisherFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManagerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAssetsAdderTests.cs
- src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Close/GitReleaseManagerMilestoneCloserTests.cs
- src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Create/GitReleaseManagerCreatorTests.cs
- src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Export/GitReleaseManagerExporterTests.cs
- src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Publish/GitReleaseManagerPublisherTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAddAssetsSettings.cs
- src/Cake.Common/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAssetsAdder.cs
- src/Cake.Common/Tools/GitReleaseManager/Close/GitReleaseManagerCloseMilestoneSettings.cs
- src/Cake.Common/Tools/GitReleaseManager/Close/GitReleaseManagerMilestoneCloser.cs
- src/Cake.Common/Tools/GitReleaseManager/Create/GitReleaseManagerCreateSettings.cs
- src/Cake.Common/Tools/GitReleaseManager/Create/GitReleaseManagerCreator.cs
- src/Cake.Common/Tools/GitReleaseManager/Export/GitReleaseManagerExportSettings.cs
- src/Cake.Common/Tools/GitReleaseManager/Export/GitReleaseManagerExporter.cs
- src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerAliases.cs
- src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerTool.cs
- src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerToolResolver.cs
- src/Cake.Common/Tools/GitReleaseManager/IGitReleaseManagerToolResolver.cs
- src/Cake.Common/Tools/GitReleaseManager/Publish/GitReleaseManagerPublishSettings.cs
- src/Cake.Common/Tools/GitReleaseManager/Publish/GitReleaseManagerPublisher.cs
GitReleaseManager commands that will be included in this first release of GitReleaseManager support
*NOTE:* Only the commands that apply an action will be included in this release, as these are the most likely commands that are needed within a build script.
GitReleaseManager commands which are unlikely to be implemented in this PR:
* Init
* Showconfig
> GitReleaseManager Addin for Cake

- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
I believe that this completes the TeamCity support [issue](https://github.com/cake-build/cake/issues/56).
Added the ability to use the TeamCity Service Message for setting the
build number, as described here:
https://confluence.jetbrains.com/display/TCD7/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildNumber
> Add ability to set TeamCity Build Number

- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecTransformer.cs
- src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
@devlead this is quite crude, but also almost effective :smile_cat: 
The end result is the following:
Are you doing some escaping of the strings that are added into the nuspec file?  Add initial glance, I couldn't see anything obvious.
>  Added CDATA attribute to releasenotes

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/OpenCoverFixture.cs
- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/OpenCover/OpenCoverAliases.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverContext.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverProcessRunner.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettingsExtensions.cs
Not all options are included in this PR.
The options included are:
- filter
- target
- targetargs
- excludebyattribute
- excludebyfilter
- output
```csharp
Task("OpenCover-NUnit-Tests")
.IsDependentOn("Build")
.Does(() =>
{
OpenCover(tool => {
tool.NUnit("./**/bin/**/OpenCoverTest.NUnit.dll",
new NUnitSettings {
ShadowCopy = false
});
},
new FilePath("./result.xml"),
new OpenCoverSettings()
.WithFilter("+[OpenCovertTest]*")
.WithFilter("-[OpenCoverTest.XUnit]*")
.WithFilter("-[OpenCoverTest.NUnit]*"));
});
```
Closes #340
> Added OpenCover support.

- README.md
- nuspec/Cake.Common.nuspec
- nuspec/Cake.Core.nuspec
- nuspec/Cake.Testing.nuspec
- nuspec/Cake.nuspec
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs
So, although this was taken care of by @devlead here https://github.com/cake-build/cake/commit/e87b3159ebd8a3f636700fa547dee763b060f7d5 for any future packages, for the same reason that we keep the SolutionInfo.cs file in source, I think it makes sense to update the nuspec's to contain the full information as well.  This was after a conversation with @patriksvensson in Slack.
> [WIP] Changing Copyright Information

- build.cake
- nuspec/Cake.Portable.nuspec
- src/Cake.sln
- tools/packages.config
This is a first pass at creating the Chocolatey Package for Cake.
It isn't quite as simple to create a Chocolatey Package, as it is for a Nuget package, as there is no concept of BasePath and OutputDirectory for Chocolatey, so there is a little bit more work to do, but the end result is the same.
Fixes GH-505
> Create Chocolatey Package for Cake

- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/NuGetAssemblyCompatibilityFilterTests.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/NuGetPackageAssembliesLocatorTests.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/PackageReferenceBundlerTests.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/PackageReferenceSetTests.cs
- src/Cake.Core.Tests/Unit/IO/NuGet/Parsing/AssemblyFilePathFrameworkNameParserTests.cs
- src/Cake.Core.Tests/Unit/Scripting/ScriptProcessorTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/CakeEnvironment.cs
- src/Cake.Core/ICakeEnvironment.cs
- src/Cake.Core/IO/NuGet/IFrameworkTargetable.cs
- src/Cake.Core/IO/NuGet/INuGetAssemblyCompatibilityFilter.cs
- src/Cake.Core/IO/NuGet/INuGetFrameworkCompatibilityFilter.cs
- src/Cake.Core/IO/NuGet/INuGetPackageAssembliesLocator.cs
- src/Cake.Core/IO/NuGet/IPackageReferenceBundler.cs
- src/Cake.Core/IO/NuGet/NuGetAssemblyCompatibilityFilter.cs
- src/Cake.Core/IO/NuGet/NuGetPackageAssembliesLocator.cs
- src/Cake.Core/IO/NuGet/PackageReferenceBundler.cs
- src/Cake.Core/IO/NuGet/PackageReferenceSet.cs
- src/Cake.Core/IO/NuGet/Parsing/AssemblyFilePathFrameworkNameParser.cs
- src/Cake.Core/IO/NuGet/Parsing/IAssemblyFilePathFrameworkNameParser.cs
- src/Cake.Core/IO/NuGet/Parsing/IFrameworkNameParser.cs
- src/Cake.Core/Scripting/ScriptProcessor.cs
- src/Cake.Testing/FakeEnvironment.cs
- src/Cake/Cake.csproj
- src/Cake/NuGet/NuGetVersionUtilityAdapter.cs
- src/Cake/Program.cs
Addresses #373 
This is currently just a proof of concept, not ready for production.
It "works," but lacks documentation and appropriate tests -- just looking to get design feedback.
The first commit is simply a refactoring of `AddInDirectiveProcessor`, to extract some of its responsibilities into other components, to help prepare for the additional functionality -- no new functionality should have been added.
The responsibility of locating assemblies to be referenced is extracted from `AddInDirectiveProcessor` into `AddInAssembliesLocator`
The next two commits, which should probably be squashed together, introduce a couple more components:
- `AddInPackageInstaller`: further extracted from  `AddInDirectiveProcessor`; uses NuGet tool to install the specified addin package
- …
> Nuget framework targeting for Addins

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/NUnit3RunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3SettingsTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/NUnit/NUnit3Aliases.cs
- src/Cake.Common/Tools/NUnit/NUnit3AppDomainUsage.cs
- src/Cake.Common/Tools/NUnit/NUnit3Labels.cs
- src/Cake.Common/Tools/NUnit/NUnit3ProcessOption.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Fixes #471
~~Not quite ready to merge~~, but putting it up to let you know it is pending. I think this is complete, I just want to do some 'real  world' testing with it in a test project. I have implemented all of the command line options that make sense in NUnit 3 and everything is unit tested.
If I get time today, I will add this into an NUnit testing project that I have created a Cake build script for. It has a mix of NUnit 2 and 3 test projects so will be a good exercise of this. I am a bit worried about #525. The NUnit runner NuGet package has been updated to be an empty meta package that pulls down the NUnit console package. The existing NUnit alias will no longer find nunit-console in the tools directory and even if it did, the command line is fairly different.
If a fix for #525 …
> Added NUnit 3 alias and unit tests

- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyPackSettings.cs
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyPacker.cs
> Added WorkingDirectory option for running Chocolatey

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
Fixes an error I'm getting in a project that used to build correctly with Cake.
========================================
Build
========================================
Executing task: Build
Building Ex2007 SP3 from C:/Projects/Exchange.RemoveSection/src/RemoveSection.sln
Executing: C:/Program Files (x86)/MSBuild/14.0/Bin/amd64/MSBuild.exe /m /v:normal /p:Configuration=Ex2007 SP3 /p:Platform="Any CPU" /p:TreatWarningsAsErrors=true /target:Build "C:/Projects/Exchange.RemoveSection/src/RemoveSection.sln"
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1008: Only one project can be specified.
Switch: C:/Projects/Exchange.RemoveSection/src/RemoveSection.sln
For switch syntax, type "MSBuild /help"
An error occured when …
> Support spaces in MSBuild configuration

- src/Cake.Core/IO/ProcessRunner.cs
> Disable Quoting of process filename on unix

- src/Cake.Common/Tools/Cake/CakeAliases.cs
The cake aliases didn't have and CakeAliasCategory attribute, which made them hard to find in docs.
> Added missing CakeAliasCategory attribute

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoParser.cs
AssemblyInformationalVersionAttribute itself can accept arbitrary text strings, unlike AssemblyVersionAttribute / AssemblyFileVersionAttribute. However, the existing AssemblyInfoParser will only parse values from AssemblyInformationalVersionAttribute that conform to the same restrictions that AssemblyVersionAttribute / AssemblyFileVersionAttribute are subject to.
A real-world situation where this will cause issues is when using semantic versioning with pre-release or build metadata, such as "1.0.0-beta1" or "1.2.3-rc1". These values should be perfectly valid in AssemblyInformationalVersion, and should be accepted by AssemblyInfoParser.
This pull request adds support for arbitrary text strings when parsing AssemblyInformationalVersionAttribute using AssemblyInfoParser.
> Support arbitrary text when parsing AssemblyInformationalVersion.

- src/Cake/Arguments/VerbosityParser.cs
Code analytics raised CA1305, this PR fixes the potential user locale issue by:
1. Adds CultureInfo.InvariantCulture for locale insensitive "ToString"
2. string.Format handles null so removed that assignment
> Add invariant IFormatterProvider to avoid issues based on user locale

- src/Cake.Core/Extensions/ConsoleExtensions.cs
- src/Cake.Core/IConsole.cs
- src/Cake.Testing/FakeConsole.cs
- src/Cake.Tests/Unit/Diagnostics/CakeBuildLogTests.cs
- src/Cake/CakeConsole.cs
- src/Cake/Diagnostics/CakeBuildLog.cs
This PR relates to #592 and #593 .
1. Log level <= Error will be sent to standard error output stream. Fixes #593
2. Adds missing LogLevel.Fatal `ConsolePalette`. Fixes #592
Example this script:
```cake
for(var i = 0; i < 5; i++)
{
Debug("Debug: {0}", i);
Verbose("Verbose: {0}", i);
Information("Information: {0}", i);
Warning("Warning: {0}", i);
Error("Error: {0}", i);
}
```
Will on i.e. Bamboo log output all but group errors last too and categorize them as error logs.
Besides other build servers supporting this, it will also let you use redirection to i.e. standard pipe to different logs, etc.
> Adds error log to stderr

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Build/BambooFixture.cs
- src/Cake.Common.Tests/Fixtures/Build/BambooInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/BambooProviderTests.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/Data/BambooBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/Data/BambooCommitInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/Data/BambooCustomBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/Data/BambooPlanInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/Bamboo/Data/BambooRepositoryInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common/Build/Bamboo/BambooInfo.cs
- src/Cake.Common/Build/Bamboo/BambooProvider.cs
- src/Cake.Common/Build/Bamboo/Data/BambooBuildInfo.cs
- src/Cake.Common/Build/Bamboo/Data/BambooCommitInfo.cs
- src/Cake.Common/Build/Bamboo/Data/BambooCustomBuildInfo.cs
- src/Cake.Common/Build/Bamboo/Data/BambooEnvironmentInfo.cs
- src/Cake.Common/Build/Bamboo/Data/BambooPlanInfo.cs
- src/Cake.Common/Build/Bamboo/Data/BambooRepositoryInfo.cs
- src/Cake.Common/Build/Bamboo/IBambooProvider.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Cake.Common.csproj
Adding Atlasssian Bamboo Build Server via BambooProvider,  Closes #544
> Add support for Atlasssian Bamboo Build Server

- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Net/HttpAliases.cs
- src/Cake.Common/Net/HttpClientExtensions.cs
I noticed in https://github.com/dotnet/cli/issues/270#issuecomment-167539366 that `WebClient` is used and that it's not part of the .NET Core surface area.
This moves Cake.Common from 96.39% to 97.50% :stuck_out_tongue_closed_eyes:
> Move from WebClient to HttpClient

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/XmlPeekAliasesFixture.cs
- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/XML/XmlPeekAliasesTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Xml/XmlPeekAliases.cs
- src/Cake.Common/Xml/XmlPeekSettings.cs
Allow a build script to extract values from XML files.
Example
```
Task("PrintServerValue")
.Does(() =>
{
var file = File("test.xml");
var serverValue = XmlPeek("/configuration/appSettings/add[@key = 'server']/@value");
Information(serverValue);
});
```
I copied over XmlPoke code and its testing code as well. From there, I removed the writing logic, and set it to return a `Value` string.
I am terrible with XPath stuff, and I haven't been able to confirm what I've written will actually work. Unfortunately, I am working on a Mac using Xamarin Studio for these changes. I ran into a number of issues building and testing. I feel bad even putting this in a pull request, but I've been changing so many things trying to test it locally with NUnit, I wouldn't be sure I was even testing the same …
> [WIP] Adding XmlPeek for reading XML values.

- src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzer.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzerContext.cs
This PR will make sure that `#line` directives are inserted at the correct position when loading other script files. This way the line numbering will be correct if an error occurs in the script.
**a.cake**
```
int x=0;
#l b.cake
int y=2;
```
**b.cake**
```
int z=1;
#l c.cake
int p=4;
```
**c.cake**
```
int o=3;
#r d.dll
```
**Will result in the following aggregated script (when analyzing a.cake):**
```csharp
#line 1 "/Working/a.cake"
int x=0;
#line 1 "/Working/b.cake"
int z=1;
#line 1 "/Working/c.cake"
int o=3;
// #r d.dll
#line 2 "/Working/b.cake"
// #l c.cake
int p=4;
#line 2 "/Working/a.cake"
// #l b.cake
int y=2;
```
Closes #375
> Fixed line numbers in error messages.

- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeReportTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeReport.cs
- src/Cake.Core/CakeReportEntry.cs
- src/Cake.Tests/Unit/CakeReportPrinterTests.cs
- src/Cake/CakeReportPrinter.cs
This PR ensures that skipped tasks are displayed in the task summary (issue #638). It does this by adding a `Skipped` property to the `CakeReport` class. 
When you run the updated CAKE version on a script that has two skipped tasks, the new output looks as follows:
I'm not sure the "(skipped)" text is the best option, but I preferred it over "-" and "- (skipped)".
Everything has been unit tested (save for the changing of the foreground color, which I don't know how to test). In the process, I have also added tests that verify that the `CakeReport` returned by the `RunTarget` method is correct.
> Display skipped tasks in task summary. #638

- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common/IO/FileAliases.cs
This PR modifies the `FileExists` method to use an absolute path to determine if a file exists. It implements #649
> FileExists alias uses absolute paths (#649)

- src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs
- src/Cake.Core.Tests/Unit/IO/FilePathTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/IO/DirectoryPath.cs
- src/Cake.Core/IO/FilePath.cs
- src/Cake.Core/IO/RelativePathResolver.cs
This PR implements #621 and adds methods to get relative paths for both the `FilePath` and `DirectoryPath` classes.
This is a WIP as I was wondering how you'd want me to do the refactoring. At the moment, there is a lot of duplication, but I was not sure what would be the best way to refactor things. I could move the methods to the abstract base class and add some extract abstract methods, but I'm not sure you'd want to go that way. Any ideas?
> Add methods to get relative paths (#621)

- src/Cake.Core.Tests/Unit/IO/PathCollapserTests.cs
This PR replaces the conditional `#if !UNIX` calls with the `[WindowsFact]` attribute.
> Replace #if !UNIX with [WindowsFact]

- src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
- src/Cake/Arguments/ArgumentParser.cs
This PR adds support for specifying the long-named version of parameters using the `"--"` prefix. It doesn't deprecate the existing `"-"` prefix, which also still works for long-named parameters.
> Allow double-dash arguments (#474)

- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeReportTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeReport.cs
- src/Cake.Core/CakeReportEntry.cs
- src/Cake.Core/CakeTaskExecutionStatus.cs
- src/Cake.Tests/Unit/CakeReportPrinterTests.cs
- src/Cake/CakeReportPrinter.cs
This PR implements #639 to show delegating tasks based on verbosity level. At the moment, it only shows delegating tasks on the `Verbose` and `Diagnostic` levels. Furthermore, when a delegating task is displayed on the other levels, it is displayed in gray.
I've tagged it as a WIP due to the fact that I would like to discuss the design of the `CakeReport` class. At the moment, there are the following methods:
```csharp
public void Add(string task, TimeSpan span)
public void AddSkipped(string task)
public void AddDelegated(string task, TimeSpan span)
public void Add(string task, TimeSpan span, CakeTaskExecutionStatus executionStatus)
```
The first `Add` method actually calls the fourth method with the `CakeTaskExecutionStatus.Executed` value. I created the `AddSkipped` and `AddDelegated` …
> Don't show delegating tasks (#639)

- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskExtensionsTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeTask.cs
- src/Cake.Core/CakeTaskBuilderExtensions.cs
- src/Cake.Core/CakeTaskExtensions.cs
This PR allows use of the `ICakeContext` in the `WithCriteria` extension method. As discussed in #512, the existing `Func<bool>` criteria still work, albeit now via an extension method.
> Allow use of ICakeContext in WithCriteria (#512)

- src/Cake.Common/Tools/ILRepack/ILRepackRunner.cs
When building the command line arguments the `ILRepackRunner` was missing the `/targetplatform:` switch before the actual value, without it ILRepack thinks the value is an assembly it's trying to merge.
> Add missing command line switch for ILRepack's targetplatform

- src/Cake.Common.Tests/Fixtures/Tools/MSTestRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common/Tools/MSTest/MSTestAliases.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
This changes the behavior of the MSTest tool to execute the test runner only once even if there are multiple test assemblies. 
Previously MSTestAlias iterated over each assembly and called MSTestRunner for each iteration with only one assembly. Although it worked it's not the best solution and might cause some issues with additional tools that processes the result of MSTests.
> One call to MSTest for multiple assemblies.

- build.cake
We were finding that NuGet.Core wasn't able to be resolved on our linux systems when using Cake because it was getting copied into the nuget package as Nu**g**et.Core.dll. It turns out that the resolution of this file is case sensitive on linux. I believe this issue may also have been encountered by @Silvenga in issue #623
> Change Nuget.Core.dll to NuGet.Core.dll in build script

- src/Cake.Common/Tools/DNU/DNUTool.cs
This is a trivial change that enables DNU tools in OSX/Linux environments.
see #689 for issue.
- add `dnu` to `DNUTool`'s executable names.
* tested Cake project on windows (doesn't build on mono even with change)
* tested example project on windows/osx
* tested my dnx project on windows/osx
* ran both `DNURestore` and `DNUBuild` tools.
> #689: enable dnu on osx/linux if dnu in path

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/DotCover/Cover/DotCoverCovererFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotCover/Cover/DotCoverCovererTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/DotCover/Analyse/DotCoverAnalyseSettings.cs
- src/Cake.Common/Tools/DotCover/Cover/DotCoverCoverSettings.cs
- src/Cake.Common/Tools/DotCover/Cover/DotCoverCoverer.cs
- src/Cake.Common/Tools/DotCover/DotCoverAliases.cs
- src/Cake.Common/Tools/DotCover/DotCoverSettings.cs
- src/Cake.Common/Tools/DotCover/DotCoverSettingsExtensions.cs
Added DotCover Cover command. Needed since TeamCity only want snapshots, not HTML/XML reports.
If possible, to remove duplicate code, I would like to reuse **DotCoverCoverSettings** in **DotCoverAnalyser** by having **DotCoverAnalyseSettings** to inherit from **DotCoverCoverSettings**.  Is this allowed since it will make documentation unclear?
NOTE: Quickly hacked using my Linux box, need to verify functionality on Windows (dotCover.exe doesn't run under Mono). But this have to wait until monday when I'm back at work.
//cc @patriksvensson
> Added DotCover Cover command

- src/Cake.Core/DefaultExecutionStrategy.cs
At the moment, the task setup/teardown blocks log information every time they're invoked. This makes the log difficult to read and to follow.
> Removed task setup/teardown logging.

- src/Cake.Common.Tests/Unit/Text/TextTransformationTests.cs
- src/Cake.Common/Text/TextTransformation.cs
fix for https://github.com/cake-build/cake/issues/709
`TextTransform.Save` inadvertently adds a BOM to the resulting file.
would be nice to prevent this as it can result in unexpected modifications of the input template.
change TextTransformation.Save to omit the BOM, and add a unit test to verify that.
Unit tests failed before fix ("Hello world" file length was returned as 14 instead of 11), and passed after fix.
> don't add BOM on text transformations (#709)

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/SpecFlow/SpecFlowFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/SpecFlow/StepDefinitionReport/SpecFlowStepDefinitionReporterFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporterFixture.cs
- src/Cake.Common.Tests/Unit/Tools/SpecFlow/StepDefinitionReport/SpecFlowStepDefinitionReporterTests.cs
- src/Cake.Common.Tests/Unit/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporterTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/SpecFlow/SpecFlowAliases.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowContext.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowContextExtensions.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowProcessRunner.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowSettings.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowTool.cs
- src/Cake.Common/Tools/SpecFlow/StepDefinitionReport/SpecFlowStepDefinitionReportSettings.cs
- src/Cake.Common/Tools/SpecFlow/StepDefinitionReport/SpecFlowStepDefinitionReporter.cs
- src/Cake.Common/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReportSettings.cs
- src/Cake.Common/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporter.cs
Added support for SpecFlow. Solves issue #695
At first I thought it would be nice if SpecFlow tool could intercept the Unit Test runner (NUnit/MSTest) just like OpenCover/DotCover, but SpecFlow sets some requirements on the arguments for the Unit Test runner. So it might be simpler to leave it as is.
Unit Tests still to be written.
> Added SpecFlow support

- src/Cake.Core.Tests/Unit/IO/NuGet/NuGetToolResolverTests.cs
- src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
Lower-case nuget.exe was already used throughout the resolver except in this one case.
The bootstrapping script also downloads lower-case nuget.exe.
Fixes: #737
> Uniform NuGet executable name for case-sensitive systems.

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Build/TeamCityFixture.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs
- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
This is needed to import to import Coverage to TeamCity. See https://confluence.jetbrains.com/display/TCD9/Manually+Configuring+Reporting+Coverage
Note, quick hack, I would like to test functionality on monday when I have access to TeamCity.
Also, unit tests are non-existent for TeamCity, wan't to add these also prior to merging this PR.
related to #713 
//cc @patriksvensson
> Added support for importing coverage to TeamCity

- src/Cake.Common.Tests/Fixtures/Build/TeamCityFixture.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
- src/Cake.Testing/Cake.Testing.csproj
- src/Cake.Testing/Extensions/FakeLogExtensions.cs
This fixes #766 by not using System.Console directly and instead using ICakeLog and mock that during tests.
* Change TeamCityProvider WriteServiceMessage to use ICakeLog instead of System.Console
* Change TeamCityProviderTests to not change System.Console stream so TeamCityFixture instead has a FakeLog/ICakeLog instance
* Add AggregateLogMessages method to FakeLog to get all current log entries message as a string
> Fix TeamCity tests on TeamCity

- README.md
I propose we add the build servers that the Cake repository currently continuously builds on.
> Added build servers to README.md

- src/Cake.Common/Build/TeamCity/TeamCityDisposableExtensions.cs
Currently TeamCityDisposableExtensions extends TeamCityProvider and
therefore aren't accessible by default. Switched to extend
ITeamCityProvider. Also now returns IDisposable.
> (GH-762) Fix TeamCity Disposable

- README.md
Cake now continuously builds on Ubuntu 14 via Bitrise
> Added Bitrise Linux to build server Matrix

- build.cake
- build/parameters.cake
- build/version.cake
Added possibility to skip runing git version via setting environment variable CAKE_SKIP_GITVERSION to `True` as a convenient way to by configuration disable GitVersion if needed i.e. if not supported by build environment.
> Added Skip GitVersion support

- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Restore/NuGetRestorerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Update/NuGetUpdaterTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/NuGet/Install/NuGetInstaller.cs
- src/Cake.Common/Tools/NuGet/Install/NugetInstallSettings.cs
- src/Cake.Common/Tools/NuGet/NuGetMSBuildVersion.cs
- src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs
- src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
- src/Cake.Common/Tools/NuGet/Restore/NuGetRestorer.cs
- src/Cake.Common/Tools/NuGet/Restore/NugetRestoreSettings.cs
- src/Cake.Common/Tools/NuGet/Update/NuGetUpdateSettings.cs
- src/Cake.Common/Tools/NuGet/Update/NuGetUpdater.cs
* Fixes #438
* Restore
* `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
* `-FallbackSource` A list of packages sources to use as fallbacks for this command.
* Install
* `-FallbackSource` A list of packages sources to use as fallbacks for this command.
* Pack
* `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
* Update
* `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By …
> Support NuGet 3 new parameters

- src/Cake.Common/Tools/GitLink/GitLinkAliases.cs
In this case, I think the API doc is actually correct and the implementation of GitLink is at fault. This changes the API doc to match the actual API, feel free to close the PR and fix the API instead.
> actual type of RepositoryUrl is String not Uri

- src/Cake.Common/Net/HttpAliases.cs
- src/Cake.Common/Tools/DotNetBuildAliases.cs
- src/Cake.Common/Tools/MSTest/MSTestAliases.cs
Reopened a new PR to squash and rebase to develop correctly (closed #790 as accidental merge/learning experience :8ball: :) )
Following have had examples added:
Cake.Common.Net​.DownloadFile(string)​
Cake.Common.Net​.DownloadFile(Uri)​
Cake.Common.Net​.DownloadFile(string, ​FilePath)​
Cake.Common.Net​.DownloadFile(Uri, ​FilePath)
Cake.Common.Tools​.DotNetBuild(FilePath)​
Cake.Common.Tools​.DotNetBuild(FilePath, ​Action<DotNetBuildSettings>)​
Cake.Common.Tools.MSTest​.MSTest(string)​
Cake.Common.Tools.MSTest​.MSTest(string, ​MSTestSettings)​
Cake.Common.Tools.MSTest​.MSTest(IEnumerable<FilePath>)​
Cake.Common.Tools.MSTest​.MSTest(IEnumerable<FilePath>, ​MSTestSettings)
Thanks.
> Alias examples for Http/DotNetBuild/MSTest #750

- src/Cake.Common/Tools/XBuild/XBuildToolVersion.cs
XBuildToolVersion's xml comments refer to MSBuild tool versions in some places, and XBuild tool versions in others. Should always be XBuild.
> Inconsistencies in XBuildToolVersion docs

- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/ICakeEngine.cs
- src/Cake.Core/IExecutionStrategy.cs
- src/Cake.Core/Scripting/IScriptHost.cs
- src/Cake.Core/Scripting/ScriptHost.cs
- src/Cake/Scripting/DryRunExecutionStrategy.cs
Also obsoleted (with warning) old methods that don't use the `ICakeContext` version of the methods. This to have a simpler interface and since there is little use to have two overloads.
Closes #743
> Provided ICakeContext to Setup/Teardown.

- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
* Added fallback to check environment for VisualStudio path if not found in default location
* Fixed parameter typo for ArgumentNullException
* Fixes #823
> Adjusted MSTest tool resolution

- src/Cake.Common/Xml/XmlPokeAliases.cs
* Fixes #835 
* Also fixes existing issue/typo in the sample where `\` wasn't escaped correctly.
Example:
```cake
var xmlString = @"<?xml version=""1.0"" encoding=""utf-8"" ?>
<configuration>
<appSettings>
<add key=""server"" value=""testhost.somecompany.com"" />
</appSettings>
</configuration>";
```
This will method will give a warning `Warning: The alias XmlPoke has been made obsolete. Use XmlPokeString alias instead`
```
var result = XmlPoke(xmlString, "/configuration/appSettings/add[@key = 'server']/@value", "productionhost.somecompany.com");
```
This method will not
```cake
var resultString = XmlPokeString(xmlString, "/configuration/appSettings/add[@key = 'server']/@value", "productionhost.somecompany.com");
```
Example with settings:
```cake
var xmlStringSetting = @"<?xml …
```
> Obsolete XmlPoke string overload add XmlPokeString alias

- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs
Due to a regression the ProcessArgumentBuilderExtensions
class had to be renamed back to ProcessArgumentListExtensions.
Closes #846
> Renamed ProcessArgumentBuilderExtensions class

- build.cake
- tools/packages.config
By moving tools needed from packages.config to the build script itself, we make the build script more portable.
Closes #854
> Made tool definitions preprocessor directives.

- src/Cake.Common/Tools/XBuild/XBuildAliases.cs
- src/Cake.Common/Tools/XBuild/XBuildRunner.cs
- src/Cake.Common/Tools/XBuild/XBuildSettingsExtensions.cs
Looks like the XBuild docs were copied from the MSBuild ones, and a few references missed. Did a similar pull request for others I noticed previously (#817) - did a full search this time, so this should cover all the rest!
> Docs: Typos in XBuild docs

- src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs
- src/Cake.Core/Scripting/ScriptRunner.cs
When passing a relative path to a script not in the same
directory as the bootstrapper, tools would be installed in
the wrong directory.
Closes #867
> Fix for tool installation path bug.

- README.md
- build.sh
@patriksvensson can you check this out, and merge if you are happy? Thanks!
> Corrected resource download urls

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
Simply wraps the DirectoryExists and CreateDirectory aliases to create a directory if it doesn't already exist.
This PR supersedes #822
> Added EnsureDirectoryExists alias

- src/Cake/Cake.csproj
- src/Cake/Scripting/Mono/CodeGen/CakeBuildScriptImplBase.cs
- src/Cake/Scripting/Mono/CodeGen/MonoCodeGenerator.cs
* Added CakeBuildScriptImplBase base class that inherits from IScriptHost
* Removed GetScriptHostProxy() from CakeBuildScriptImpl
* Added so CakeBuildScriptImpl inherits from CakeBuildScriptImplBase
This fixes #883 and should ensure we avoid missing members in the future and reduces chance of  errors thru "dynamic" code not compiled with Cake.
> Refactored Mono GetScriptHostProxy into base class

- src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
- src/Cake/Arguments/ArgumentParser.cs
This PR enabled the built in parameters to Cake.exe to take the form as a boolean key/value pair instead of only as a flag.
This means that `--debug=true` will be the same thing as `--debug` and will give the user an opportunity to explicitly tell Cake to NOT debug the script by passing `--debug=false`. This is useful when writing a custom bootstrapper for Cake.
Closes #917
> Built in parameters now accept boolean values

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Solution/Project/ProjectParserFixture.cs
- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/Solution/Project/ProjectParserTests.cs
- src/Cake.Common/Solution/Project/ProjectParser.cs
- src/Cake.Common/Solution/Project/ProjectParserResult.cs
- src/Cake.Common/Solution/Project/ProjectXElement.cs
Adds unit tests (and an associated fixture) for the csproj file parser. Also adds support for the Target Framework Profile property in project files (crucial when working with PCLs and the Client profile).
First PR, so let me know if it needs work. Build script didn't highlight anything and I tried to base the tests off some existing ones where possible, so it should be alright from what I can tell.
Thanks!
> GH879: Tests for the Project file Parser

- nuspec/Cake.Common.nuspec
> GH895: Adds minClientVersion to support developmentDependency flag

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Tools/VSTestRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Tools/VSTest/VSTestAliases.cs
- src/Cake.Common/Tools/VSTest/VSTestFrameworkVersion.cs
- src/Cake.Common/Tools/VSTest/VSTestLogger.cs
- src/Cake.Common/Tools/VSTest/VSTestPlatform.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
- src/Cake.Common/Tools/VSTest/VSTestSettings.cs
New feature request for consideration.
Update 5/17/2016: I just found the more detailed CONTRIBUTING.md doc (with the `Get buyoff or find open community issues or features` section). I can delete this pull request and create an issue first if preferred.
Visual Studio 2012 and newer introduces a new unit test runner (https://msdn.microsoft.com/en-us/library/jj155800.aspx). This runner can have some subtle differences when compared to MSTest.exe. This pull request allows the Cake build script to use the same runner as Visual Studio.
```
VSTest("src/**bin/Release/*.Test.dll", new VSTestSettings { Logger = VsTestLogger.Trx });
```
> GH894: Added new VSTest alias to support executing unit tests using the newer

- src/Cake.Common.Tests/Unit/Build/AppVeyor/AppVeyorProviderTests.cs
- src/Cake.Common/Build/AppVeyor/AppVeyorProvider.cs
- src/Cake.Common/Build/AppVeyor/AppVeyorTestResultsType.cs
- src/Cake.Common/Build/AppVeyor/IAppVeyorProvider.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Cake.Common.csproj
This change adds an alias to the AppVeyor environment for uploading test results so that it integrates nicely with AppVeyor. This is supported by the AppVeyor API here: http://www.appveyor.com/docs/running-tests#uploading-xml-test-results
Currently test results display is supported by AppVeyor, but only if you use the test runners and framework using the `appveyor.yml` config.
This change allows tests to be run from Cake and then upload the outputted XML file to AppVeyor's test results page (see screenshot).
Fixes: #908
> GH908: Add ability to upload test results when running under AppVeyor

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs
source, fallbacksource and inferedruntimes all allow multiple arguments by specifying the same arg multiple times.
Same fix as this: https://github.com/cake-build/cake/pull/838
> GH945: Fix dotnet restore settings

- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
This fixes so [DotNetCoreTest()](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs#L475) calls [DotNetCoreTest(string project, DotNetCoreTestSettings settings)](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs#L517)
* Fixes #948
> Fixes DotNetCoreTest() calling wrong method

- src/Cake.Common.Tests/Fixtures/XmlPeekAliasesFixture.cs
- src/Cake.Common.Tests/Fixtures/XmlPokeFixture.cs
- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/XML/XmlPeekAliasesTests.cs
- src/Cake.Common.Tests/Unit/XML/XmlPokeTests.cs
- src/Cake.Common/Cake.Common.csproj
- src/Cake.Common/Xml/XmlDtdProcessing.cs
- src/Cake.Common/Xml/XmlPeekAliases.cs
- src/Cake.Common/Xml/XmlPeekSettings.cs
- src/Cake.Common/Xml/XmlPokeAliases.cs
- src/Cake.Common/Xml/XmlPokeSettings.cs
Added the DtdProcessing property to XmlPeekSettings and XmlPokeSettings class.
This property is used to instanciate a XmlReaderSettings used by XmlReader.Create to determine the processing of DTDs.
Relates to #930
> GH930: Allow XmlPeek and XmlPoke in XML files with DOCTYPE

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Run/DotNetCoreRunnerTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/Execute/DotNetCoreExecutor.cs
- src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunner.cs
- src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs
- src/Cake.Core/IO/ProcessArgumentBuilder.cs
This is a proposed fix for #952
Currently the DotNetCore DotNetCoreExecute and DotNetCoreRun uses a quoted single string for args, this breaks in some scenarios also wont allow filtering sensitive data.
This PR
* Refactors arguments from string to ProcessArgumentBuilder
* This takes benefit from all ProcessArgumentBuilder extensions available
* Enables RenderSafe to work for verbose logging
* Adds `CopyTo(ProcessArgumentBuilder target)` method to `ProcessArgumentBuilder`
* This allows without exposing internals to append the content of one `ProcessArgumentBuilder` to another
* Adds an `IsEmpty()` method to `ProcessArgumentBuilder`
* This indicates if `ProcessArgumentBuilder` has any args / would render empty.
> GH952: Refactor DotNetCore args string->ArgumentBuilder

- src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs
- src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs
- src/Cake.Common/Tools/SignTool/SignToolSignSettings.cs
From https://msdn.microsoft.com/en-us/library/8s9b9yaz(v=vs.110).aspx#Anchor_3:
>/du _URL_ - Specifies a Uniform Resource Locator (URL) for the expanded description of the signed content.
Adds `SignToolSignSettings.DescriptionUri` and corresponding changes in `SignToolSignRunner`.
> GH966: Signtool: Add support for description URL (/du)

- GitReleaseManager.yaml
> GH968: Added build label to exclusion list for GitReleaseManager

- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
Hi,
I noticed that the OpenCover tool didn't support the `-skipautoprops` flag that is documented in the [OpenCover Usage guide](https://github.com/opencover/opencover/wiki/Usage).
This pull request adds support for this flag to `OpenCoverSettings`. By default, it's false, so that the behaviour remains the same.
A unit test has been provided.
> Added support for skipautoprops flag to OpenCover

- src/Cake.Core.Tests/Fixtures/CakeConfigurationProviderFixture.cs
- src/Cake.Core.Tests/Unit/Configuration/CakeConfigurationProviderTests.cs
- src/Cake.Core/Configuration/CakeConfigurationProvider.cs
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake.Tests/Unit/Modules/ConfigurationModuleTests.cs
- src/Cake/Modules/ConfigurationModule.cs
- src/Cake/Program.cs
For some reason, we used the working directory to locate the cake.config which works fine if the script that is being executed resides in the root directory. This PR will make sure that Cake always will look for cake.config in the same directory as the build script.
Closes #1002
> Make sure that cake.config can be found

- src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesSettings.cs
- src/Cake.Core.Tests/Unit/Tooling/ToolTests.cs
- src/Cake.Core/Tooling/Tool.cs
- src/Cake.Core/Tooling/ToolSettings.cs
> GH844: Added working directory support for tools

- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/Obsolete_ExplicitWarning_WithMessage
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/Obsolete_ImplicitWarning_NoMessage
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/Obsolete_ImplicitWarning_WithMessage
- src/Cake.Core/Scripting/CodeGen/MethodAliasGenerator.cs
* Fixes #974
* Fixes cake-build/example#15
Currently when running Mono you get below warnings for obsolete methods even if they're not uses, this is a proposed fix for this by suppressing warnings for obsolete methods in generated code.
```
unknown.cake (512,38): `Cake.Common.Tools.DNU.DNUAliases.DNURestore(this Cake.Core.ICakeContext)' is obsolete: `Please use DotNetCoreRestore() instead.'
unknown.cake (519,38): `Cake.Common.Tools.DNU.DNUAliases.DNURestore(this Cake.Core.ICakeContext, Cake.Core.IO.FilePath)' is obsolete: `Please use DotNetCoreRestore(string) instead.'
unknown.cake (526,38): `Cake.Common.Tools.DNU.DNUAliases.DNURestore(this Cake.Core.ICakeContext, Cake.Common.Tools.DNU.Restore.DNURestoreSettings)' is obsolete: `Please use DotNetCoreRestore(DotNetCoreRestoreSettings) …
```
> GH974: Supress obsolete warnings from generated code

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
This PR replaces slash with dash in the command line argument switches for `gitversion.exe`, so it is more Unix friendly. It will still fail exeucting on OS X due to GitTools/GitVersion#890, but once that has been fixed, this should ensure that GitVersion executes successfully on OS X.
> Replace the command line argument switches for GitVersion

- src/Cake.Common/Tools/InspectCode/InspectCodeAliases.cs
Replace ';' by ',' in C# object initializer
> Fix InspectCode documentation

- src/Cake.Core.Tests/Fixtures/DummyToolFixture.cs
- src/Cake.Core.Tests/Stubs/DummyTool.cs
- src/Cake.Core.Tests/Unit/Tooling/ToolTests.cs
- src/Cake.Core/Tooling/Tool.cs
Added custom exit code validation for `Tool` by adding a `Func<int, bool>` lamda expression to the `Tool.Run` method. Similar to `postAction`.
This can be used when developing custom tool support e.g. for Robocopy which runs sucessful but provides other exit codes than zero.
> GH1023: Support custom exit code validation for tool.

- src/Cake.NuGet/NuGetPackageInstaller.cs
Currently it's very hard to diagnose addin/tool nuget install issues, this PR proposes logging error code if non 0 and if Verbosity set to Diagnostic also log nuget call and stdout.
* Fixes #1019
> GH1019: Add more logging to NuGet package installer

- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/GitReleaseManager/Close/GitReleaseManagerMilestoneCloser.cs
This fixes #957 and #1010. It's my first contribution; let me know if everything is OK.
> GH957 GH1010: Enhance docs for DotNetCore and GitReleaseManager aliases.

- GitReleaseManager.yaml
> GH1045: Change label order for GitReleaseManager

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
- src/Cake.Common/Tools/GitVersion/GitVersionSettings.cs
Implemented via .NoFetch boolean on GitVersionSettings.
Adds **/nofetch** option support to GitVersion tool Implemented via ```.NoFetch``` boolean on GitVersionSettings.
```c#
var settings = new GitVersionSettings();
settings.NoFetch = true; // defaults to false
```
The /nofetch flag is useful for repositories that are fully cloned but where GitVersion still wants to inspect the remote repository for version history.  Causes particular problems with private repositories.
While the flag can currently be set via ArgumentCustomization this will make the option readily accessible and documented within Cake.
> Adds /nofetch option support to GitVersion tool

- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
OldStyle flag for OpenCover is required for using it with dotnet cli for some reason.
> Add OldStyle flag for OpenCover

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Restore/DotNetCoreRestorerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreVerbosity.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs
> dotnet CLI preview 2 doesn't have the quiet option anymore

- src/Cake.Common/Tools/NSIS/NSISAliases.cs
- src/Cake.Common/Tools/Roundhouse/RoundhouseAliases.cs
- src/Cake.Common/Tools/XBuild/XBuildAliases.cs
- src/Cake.Common/Tools/XUnit/XUnitAliases.cs
This finishes the list that is posted by adding XBuild, XUnit, MakeNSIS, and Roundhouse.
> GH-750 Remaining documentation

- src/Cake.Core/CakeRuntime.cs
- src/Cake.Core/ICakeRuntime.cs
- src/Cake.Core/IO/ProcessRunner.cs
- src/Cake.Core/IO/ProcessSettings.cs
- src/Cake.Core/Tooling/Tool.cs
- src/Cake.Core/Tooling/ToolSettings.cs
- src/Cake.Testing/FakeRuntime.cs
* Add EnvironmentVariables to ProcessSettings
* Add EnvironmentVariables to ToolSettings
* Adds CakeVersion ICakeRuntime
* Fixes #1092
```cake
StartProcess("cmd", new ProcessSettings{
Arguments = "/c set",
EnvironmentVariables = new Dictionary<string, string>{
{ "CI", "True" },
{ "TEMP", MakeAbsolute(Directory("./Temp")).FullPath }
}
});
```
```cake
MSBuild("c:/temp/dev/gh/devlead/cake/src/Cake.sln", new MSBuildSettings {
EnvironmentVariables = new Dictionary<string, string>{
{ "TOOLSPATH", MakeAbsolute(Directory("./tools")).FullPath }
}});
```
This PR also adds 2 default variables CAKE & CAKE_VERSION which enables tools to pickup that it's running under and which version Cake.
> GH 1092: Add environment variable support for StartProcess & Tools

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
This means that there will be a semantic change in how the MSBuild alias work. Instead of spawning as
many processes as there are available CPUs in the computer, it will use a single process by default.
This is how MSBuild normally works when not specifying the `/m` switch explicitly.
Closes #1104
> GH1104: Made MSBuildSettings.MaxCpuCount nullable

- src/Cake.Common/Build/AppVeyor/AppVeyorProvider.cs
- src/Cake.Common/Net/HttpAliases.cs
- src/Cake.Common/Net/HttpClientExtensions.cs
The updates changes from using HttpClient to WebClient.
The WebClient.UploadFile packages and sends a payload in the format expected by AppVeyor.  WebClient is also supported on Mono (https://searchcode.com/codesearch/view/35714320/).
Resolves #1097
> GH1098: Updates AppVeyor UploadTestResults

- bitbucket-pipelines.yml
- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Fixtures/Build/BitbucketPipelinesInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/BitbucketPipelines/Data/BitriseRepositoryInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common/Build/BitbucketPipelines/BitbucketPipelinesInfo.cs
- src/Cake.Common/Build/BitbucketPipelines/BitbucketPipelinesProvider.cs
- src/Cake.Common/Build/BitbucketPipelines/Data/BitbucketPipelinesEnvironmentInfo.cs
- src/Cake.Common/Build/BitbucketPipelines/Data/BitbucketPipelinesRepositoryInfo.cs
- src/Cake.Common/Build/BitbucketPipelines/IBitbucketPipelinesProvider.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Cake.Common.csproj
* Fixes #918
This adds Bitbucket Pipelines builsystem support to Cake.
```cake
var isBitbucketPipelinesBuild = BitbucketPipelines.IsRunningOnBitbucketPipelines;
Information("isBitbucketPipelinesBuild: {0}", isBitbucketPipelinesBuild);
if(BuildSystem.IsRunningOnBitbucketPipelines)
{
// Get the build commit hash.
var commitHash = BuildSystem.BitbucketPipelines.Environment.Repository.Commit;
}
if(BuildSystem.IsRunningOnBitbucketPipelines)
{
// Get the URL friendly repo name.
var repoSlug = BuildSystem.BitbucketPipelines.Environment.Repository.RepoSlug;
}
```
```json
BitbucketPipelines: {
"IsRunningOnBitbucketPipelines": true,
"Environment": {
"Repository": {
"Branch": "develop",
"Tag": "Bitbucket Pipelines",
"Commit": "4efbc1ffb993dfbcf024e6a9202865cc0b6d9c50",
"RepoOwner": "cakebuild", …
```
> GH-918: Adds Atlassian Bitbucket Pipelines support

- src/Cake.Core/CakeRuntime.cs
Should preserve compatibility with older Mono versions.
Closes #1123
> GH1123: Made TargetFramework constant.

- src/Cake.Common.Tests/Fixtures/Build/AppVeyorFixture.cs
- src/Cake.Common.Tests/Unit/Build/AppVeyor/AppVeyorProviderTests.cs
- src/Cake.Common/Build/AppVeyor/AppVeyorProvider.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Net/HttpClientExtensions.cs
* ```UploadArtifact``` now sends ```-Type``` instead of ```-ArtifactType``` to define the type of artifact uploaded, I blame resharper for this one!
* ```UploadTestResults``` - the ```Content-Disposition``` header on the form-data content needs to specify at least a name.  Now generates a header similar to:
```
Content-Disposition: form-data; name=test-results.xml; filename=test-results.xml
```
> GH1126: corrects issues with UploadArtifact and UploadTestResults

- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
Support for TeamCity's "setParameter" service message was added in
https://github.com/cake-build/cake/pull/1114 but only the tests and implementor
were updated.
This change updates the interface to match, which is what is actually exposed to
Cake scripts.
Relates to https://github.com/cake-build/cake/issues/1121.
> Expose TeamCityProvider.SetParameter method via the ITeamCityProvider interface

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildLogger.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Relates to #702 and #473.
The gist of it is fairly simple. I've added an extension method for adding a logger switch to the MSBuildSettings class, similar to how property switches are added, like so:
```csharp
public static MSBuildSettings WithLogger(this MSBuildSettings settings, string loggerAssembly, string loggerClass = null, string loggerParameters = null)
```
Calling that method should append an argument to MSBuild, like so:
`/logger:loggerClass,loggerAssembly;loggerParameters`
In addition to this, I added a MSBuildLogger class to hold the above assembly, class and parameters values, and to the MSBuildSettings class I added a collection property to hold instances of those.
> GH702 GH473: Added logger switch to MSBuild runner

- src/Cake.Common/project.json
This PR updates `System.ComponentModel.TypeConverter` to 4.1.0 for .NET Core which solves some `dotnet restore` problems we've been seeing.
> Updates System.ComponentModel.TypeConverter to 4.1.0 for .NET Core.

- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core.Tests/Unit/Packaging/PackageReferenceTests.cs
- src/Cake.Core/Extensions/UriExtensions.cs
- src/Cake.Core/IO/Globbing/GlobParser.cs
- src/Cake.Core/IO/Globbing/GlobTokenKind.cs
- src/Cake.Core/IO/Globbing/GlobTokenizer.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/Nodes/CurrentSegment.cs
- src/Cake.Core/Packaging/PackageReference.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetContentResolverFixture.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetToolContentResolverFixture.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetV2ContentResolverFixture.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetV3ContentResolverFixture.cs
- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet.Tests/Unit/NuGetPackageInstallerTests.cs
- src/Cake.NuGet/INuGetContentResolver.cs
- src/Cake.NuGet/NuGetContentResolver.cs
- src/Cake.NuGet/NuGetPackageInstaller.cs
- src/Cake.NuGet/V2/NuGetV2ContentResolver.cs
- src/Cake.NuGet/V3/NuGetV3ContentResolver.cs
- src/Cake.sln.DotSettings
> GH1184: Added support for manually including/excluding files for tools

- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Default behavior without setting the MaxCpuCount will be to compile
projects one at a time. The documentation indicated how to set this to use
all your processors, but didn't indicate the behavior if you didn't.
Because the value of 0 means use all available CPUs I suspect many people
like myself would think that 0 is the default so no value was needed to be
explicitly specified.
See https://msdn.microsoft.com/en-us/library/bb651793.aspx
> [DOC] Adds default CPU count behavior to MSBuild settings documentation

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common.Tests/Unit/ReleaseNotesAliasesTests.cs
- src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs
- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Common/IO/DirectoryDeleter.cs
- src/Cake.Common/IO/FileCopier.cs
- src/Cake.Common/IO/FileDeleter.cs
- src/Cake.Common/IO/FileMover.cs
- src/Cake.Common/ReleaseNotesAliases.cs
- src/Cake.Common/Solution/Project/ProjectParser.cs
- src/Cake.Common/Solution/SolutionParser.cs
- src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs
- src/Cake.Core.Tests/Unit/Graph/CakeGraphBuilderTests.cs
- src/Cake.Core/Graph/CakeGraphBuilder.cs
- src/Cake.Testing/Extensions/FakeFileSystemExtensions.cs
- src/Cake.Testing/Extensions/ToolFixtureExtensions.cs
- src/Cake.Testing/FakeFileSystemTree.cs
Hey guys,
I was turned onto the project by the Hanselminutes podcast. I dove right in and noticed that the exception messages had a grammar error. So I updated the messages and associated tests to reflect the change.
> Corrects the grammar "do/does" in exception messages and tests

- src/Cake.Common.Tests/project.json
- src/Cake.Common/project.json
- src/Cake.Core.Tests/project.json
- src/Cake.Core/project.json
- src/Cake.NuGet.Tests/project.json
- src/Cake.NuGet/project.json
- src/Cake.Testing.Xunit/project.json
- src/Cake.Testing/project.json
- src/Cake.Tests/project.json
- src/Cake/project.json
- tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
This fixes #1247, because issue in .NET Core tooling AnyCPU needs to be specified
> Change to use AnyCPU to address Mono issue

- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
I wanted to add a different path VSTest argument and I looked at `SettingsFile` as a pattern to copy, but I believe I found some issues with its current implementation.
The `SettingsFile` argument is not quoted. Filenames that contain spaces will cause problems. I've confirmed the expected behavior at the command line. What I'm not sure about is what the resolution should be.
Is there written guidance on handling of whitespace and more specifically in conjunction with rooting relative paths?
Should it mimic the assembly path argument building, `assemblyPath.MakeAbsolute(_environment).FullPath.Quote()`? This means `Local.RunSettings` would become `/settings:"/Working/Local.RunSettings"`. Is that outcome correct in the context of Cake? The PR currently reflects this, but as you see it …
> Fix for unquoted VSTest settings file path

- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployPackerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoPackTests.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployPacker.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusPackFormat.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusPackSettings.cs
See #472. Pretty much implemented in the exact same way as OctoPush.
> GH472: Added OctoPack tool

- src/Cake.Common/Net/HttpAliases.cs
#1289 
Implements a method to get a new `HttpClient` with the `User-Agent` header set to "Cake" and the current Cake version for all HTTP aliases.
> GH1289: Sets the user agent for HTTP aliases, #1289

- src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs
- src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
#1154 
As mentioned in here https://github.com/cake-build/cake/issues/1154#issuecomment-239369383 ``Files`` collection is not required in ``NuGetPackSettings`` when ``Dependencies`` are specified
> GH1154: NuGetPacker, making Files collection optional when Dependencies collection specified

- src/Cake.Common.Tests/Fixtures/Build/GitLabCIFixture.cs
- src/Cake.Common.Tests/Fixtures/Build/GitLabCIInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIProjectInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIRunnerInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIServerInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/GitLabCIProviderTests.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIBuildInfo.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIEnvironmentInfo.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIProjectInfo.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIRunnerInfo.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIServerInfo.cs
- src/Cake.Common/Build/GitLabCI/GitLabCIInfo.cs
- src/Cake.Common/Build/GitLabCI/GitLabCIProvider.cs
- src/Cake.Common/Build/GitLabCI/IGitLabCIProvider.cs
This PR adds support for the build system GitLab CI (#1274).
I have added support for reading the environment variables added by GitLab as they are documented in [the GitLab CI readme](https://docs.gitlab.com/ce/ci/variables/README.html).
There are test fixtures for the new classes and I have extended the Build System test cases to cover GitLab as well.
I have run the test suite locally and everything passes as well as testing the new code on a GitLab instance to verify that the properties are all parsed correctly.
> GH1274: Add GitLab CI Build System

- src/Cake.Core.Tests/Unit/Extensions/ProcessArgumentListExtensionsTests.cs
- src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs
- src/Cake.Core/IO/ProcessArgumentBuilder.cs
See issue #1281.
This PR adds a corresponding `Prepend` extension method for all of the existing `Append` extension methods for the ProcessArgumentBuilder class.
This allows the script to insert new arguments at the start of a tool command for instances where the final argument of a tool has special significance (such as SignTool where the final argument is the file(s) to sign) and adding new arguments to the end can cause an issue.
> GH1281: Add a "Prepend" extension for the ProcessArgumentBuilder

- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleaseDeployerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoCreateReleaseTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployReleaseTests.cs
- src/Cake.Common/Tools/OctopusDeploy/CreateReleaseArgumentBuilder.cs
- src/Cake.Common/Tools/OctopusDeploy/CreateReleaseSettings.cs
- src/Cake.Common/Tools/OctopusDeploy/DeployReleaseArgumentBuilder.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployArgumentBuilder.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployReleaseDeployer.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployReleaseDeploymentSettings.cs
This PR is for issues #1227 and #1228.
One part adds an option to deploy a freshly created release - added more parameters to `CreateReleaseSettings` and modified argument builder around it.
Second part is to request a deployment of an already existing release to an environment: `OctopusDeployReleaseDeployer`.
Also refactored `CreateReleaseArgumentBuilder` to inherit from common argument builder and removed some duplicated code.
I'm not very happy that `OctopusDeployReleaseDeploymentSettings` has a lot of overlapping properties with `CreateReleaseSettings` and the argument builders for both of them contain a lot of identical code to create arguments related to deployment. However I don't see a way to reduce the duplication without adding more inheritance and doing some funky stuff. …
> GH1227 GH1228: Deploy releases or deploy on release creation in Octopus Deploy

- src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs
- src/Cake.Common.Tests/Fixtures/Build/TFBuildInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildAgentInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildDefinitionInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildRepositoryInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildTeamProjectInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildProviderTests.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildDefinitionInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildEnvironmentInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildRepositoryInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildTeamProjectInfo.cs
- src/Cake.Common/Build/TFBuild/Data/TFRepositoryType.cs
- src/Cake.Common/Build/TFBuild/ITFBuildProvider.cs
- src/Cake.Common/Build/TFBuild/TFBuildProvider.cs
- src/Cake.Common/Build/TFBuild/TFInfo.cs
- src/Cake.sln.DotSettings
Adds basic support for VSTS as a build system, encapsulating the majority of the pre-defined build variables.
Note that this will need to be rebased/merged after #1222 is merged, given that the `BuildSystemTests.cs` has so many changes.
Let me know if anything looks off or if is missing.
> GH1250: Add support for VSTS and TFS build system

- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
- src/Cake.Common/Tools/VSTest/VSTestSettings.cs
This adds the following parameters:
* Parallel
* EnableCodeCoverage
* UseVsixExtensions
* TestAdapterPath
* TestCaseFilter
* Diag
This is all the usable parameters as per the latest VSTest in VS2015.3, except the `/List*` parameters which didn't quite fit the flow because they return information instead of running tests.
The summaries are straight from the console documentation, except...
Major complaint: I think there is great value in copying the command line help description of each parameter. The build-enforced `Gets or sets` and `Gets or sets a value indicating whether` is frustrating to work into the summary and brings down the documentation quality here and on the website. I especially like the `If set,` because it clarifies instinctively what the default is. Also, [this made me …
> GH1279: Adding all current parameters for VSTest

- src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs
- src/Cake.Common/IO/FileAliases.cs
- src/Cake.Common/IO/FileCopier.cs
fix #899 
Here is an approach to keep the folder structure for `CopyFiles`. I add some new overloads. Yet only for patterns.
> GH899: Copy directory structure

- src/Cake.Common/Tools/VSTest/VSTestSettingsExtensions.cs
Method 'WithApVeyorLogger' should be called 'WithAppVeyorLogger' (notice the two Ps).
> (GH-1332) Fix typo in VSTestSettings extension method name

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/GlobTokenizer.cs
Affects Windows and *nix environments.
- Added @ into `_identifierRegex`.
- Added Unit Tests
- WindowsFact: Should_Parse_Glob_Expressions_With_AtSign_In_Them()
- Fact: Should_Parse_Glob_Expressions_With_AtSign_In_Them()
> GH-1342 - Unkown Token when directory contains @

- src/Cake.Common.Tests/Fixtures/Tools/XUnit2RunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs
- src/Cake.Common/Tools/XUnit/XUnit2Runner.cs
- src/Cake.Common/Tools/XUnit/XUnit2Settings.cs
x86 setting was added to XUnit2Settings to support the ability to use the x86 version of the tool.  The simplest solution was implemented and tests where added to cover the changes.
> GH-670: XUnit2 x86 support added.

- src/Cake.Core.Tests/Unit/Annotations/CakeNamespaceImportAttributeTests.cs
- src/Cake.Core/Annotations/CakeNamespaceImportAttribute.cs
- src/Cake.Core/Scripting/ScriptAliasFinder.cs
This addresses GH-1352.  Changes opens the `CakeNamespaceImportAttribute` up to be applied at the assembly level and extends the logic in `ScriptAliasFinder` to import namespaces declared for import at the assembly level.
> GH1352: add support for global namespace imports at the assembly level

- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoPackTests.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployPacker.cs
Updated OctopusDeployPacker to include the --format switch if the Format property is set to OctopackFormat.Zip. If OctopusDeployPacker.NuPkg is set, then the switch is not added and uses the default format by octo.exe.
> GH-1349: OctoPack not passing --format to octo.exe

- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/ICakeEngine.cs
- src/Cake.Core/SetupEventArgs.cs
- src/Cake.Core/TaskSetupEventArgs.cs
- src/Cake.Core/TaskTeardownEventArgs.cs
- src/Cake.Core/TeardownEventArgs.cs
This is a PoC for the events proposal from #1249. No tests as of yet, but if you think we want to go ahead with it, I can add some.
Basic principle is four events:
- `Setup`
- `Teardown`
- `TaskSetup`
- `TaskTeardown`
each called during their respective phase of the process.
Currently:
- Exceptions are logged then ignored
- Events are raised **before** their respective actions
Happy to take any feedback you have :)
> GH1249: Adds lifecycle events to the ICakeEngine

- src/Cake.Core/IO/ProcessRunner.cs
Redirection of the standard error stream using `ProcessSettings.RedirectStandardError` currently doesn't work since redirection is not enabled at all.
> Properly implement StdErr redirection

- src/Cake.Core.Tests/Data/MethodAliasGeneratorData.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalBooleanParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalCharParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalDecimalParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalEnumParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableBooleanParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableCharParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableDecimalParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableDoubleParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableEnumParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableLongParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalNullableTParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalObjectParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOptionalStringParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/ParameterEmitterTests.cs
- src/Cake.Core/Extensions/TypeExtensions.cs
- src/Cake.Core/Scripting/CodeGen/MethodAliasGenerator.cs
- src/Cake.Core/Scripting/CodeGen/ParameterEmitter.cs
@devlead 
Here is a PR for review to address GH-1166, refactoring the parameter concerns in the method alias tokenizer to support optional params.
I have added a reasonable cover of tests to prove this out, but it is not exhaustive - it does not cover all numerics, etc., but it does cover what I would consider to be the trickier of cases concerning Nullable<T> and so forth.
There are probably a couple of places where the generated code could be cleaned up for brevity, but as a first pass, I opted to be explicit, particularly in light of the fact that this isn't code that needs to be readable/maintainable, and the emphasis should be on being explicit for the sake of operability.
Happy to re-work or expand test-coverage as it might be deemed necessary.. I'm not saying "don't merge", but I …
> GH1166: refactor MethodAliasGenerator to support optional parameters

- src/Cake.Common/Tools/InnoSetup/InnoSetupAliases.cs
The comments were referring to the ".nsi" script file, which is the extension for NSIS, instead of ".iss", which is the extension for InnoSetup.
> Fix doc comments in InnoSetupAliases

- src/Cake.Common.Tests/Fixtures/Build/TeamCityInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityEnvironmentInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityProjectInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityPullRequestInfoTests.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityEnvironmentInfo.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityProjectInfo.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityPullRequestInfo.cs
- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
- src/Cake.Common/Build/TeamCity/TeamCityInfo.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
As discussed in #1416 I've used the environment variables available on the agent to expose functionality for TeamCity users. I've added:
- `TeamCityBuildInfo`: Build name & number
- `TeamCityProjectInfo`: Project name
- `TeamCityPullRequestInfo`: Pull request number if the build is a pull request build. 
The pull request functionality requires that there's a __Git_Branch__ parameter be present on the agent. The value of this parameter should be `%teamcity.build.vcs.branch.{configurationid}%` as detailed at [GitVersion docs](https://gitversion.readthedocs.io/en/latest/build-server-support/build-server/teamcity/#running-inside-teamcity)
> Add pull-request detection for TeamCity provider

- src/Cake.Common/Build/BuildSystemAliases.cs
2 char code sample fix incorrect docs
currently reads
```csharp
var isBambooBuild = Bamboo.IsRunningBamboo;
```
should read 
```csharp
var isBambooBuild = Bamboo.IsRunningOnBamboo;
```
> Correcting bamboo code sample

- src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildCommandTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildProviderTests.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildArtifactType.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildMessageData.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildRecordData.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildTaskResult.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildTaskStatus.cs
- src/Cake.Common/Build/TFBuild/ITFBuildCommands.cs
- src/Cake.Common/Build/TFBuild/ITFBuildProvider.cs
- src/Cake.Common/Build/TFBuild/TFBuildCommands.cs
- src/Cake.Common/Build/TFBuild/TFBuildProvider.cs
Initial support for TF Build logging commands. There's some minor inconsistencies between MS documentation and the real behaviour, but I've followed documentation here, so should be pretty solid.
Resolves #1399
Let me know of any issues. 
> Sidenote: Formatting might be a bit off (I have full confidence in Patrik's spotting ability) as this PR was done entirely in Rider!
> GH1399: Adds support for TF Build command messages

- src/Cake.Common.Tests/Fixtures/XmlPeekAliasesFixture.cs
- src/Cake.Common.Tests/Unit/XML/XmlPeekAliasesTests.cs
- src/Cake.Common/Xml/XmlPeekAliases.cs
- src/Cake.Common/Xml/XmlPeekSettings.cs
The `XmlPeekSettings` learned to remember a setting if warnings should be suppressed or not. That setting will be evaluated before calling `context.Log.Warning()` if the `XmlPeek` alias can not find the provided xpath.
With this new setting in place, users can now _opt out_ of displaying the warning if the xpath was not found.
This fixes (GH-1438)
> xmlpeek: Add switch to suppress warnings

- src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Common/Tools/MSBuild/MSBuildToolVersion.cs
- src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
Created enums and logic for handling MSBuild 15/VS2017 for the MSBuild runner. Also created
unit test.
> GH1369: Implemented MSBuild for VS2017

- src/Cake.Core/Constants.cs
- src/Cake.Core/Modules/CoreModule.cs
- src/Cake.Core/Polyfill/AssemblyHelper.cs
- src/Cake.Core/Reflection/AssemblyLoader.cs
- src/Cake.Core/Reflection/AssemblyVerifier.cs
- src/Cake.Core/Reflection/IAssemblyLoader.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake.Core/Scripting/ScriptRunner.cs
- src/Cake/Composition/ModuleSearcher.cs
- src/Cake/Scripting/XPlat/XPlatScriptSession.cs
* Added verification of addins, modules and directly references assemblies.
~~Haven't added functionality for letting addins decide what version of Cake they require yet.~~
I will add the attribute now for addins to use to require and we'll add the check in a later version.
> GH1293: Add mechanism to validate addins

- build.cake
- build/parameters.cake
- signclient.filter
- signclient.json
Signs the following:
* Zip files (for GitHub and Homebrew)
* NuGet packages
* Chocolatey packages
Signing will only occur at a real release.
You can suppress signing by passing the `--skipsigning=true` parameter to the bootstrapper.
Related to #1294
> GH1294: Added signing of artifacts.

- src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs
- src/Cake.Core/Scripting/ScriptRunner.cs
- src/Cake/Composition/ModuleLoader.cs
- src/Cake/Constants.cs
The default path that is used for addin installation is being constructed
by using the application root. This is not the propagated default behavior
on the website. Let's use the relative path `./tools/addins` as default.
This fixes (GH-1344)
---
It turned out that only the default of the addins installation folder was affected.
> GH1344: addin-path: Use relative default path

- src/Cake.Core.Tests/Unit/IO/NuGet/NuGetToolResolverTests.cs
- src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
On Mac, the nuget command alias should exist in `/Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget` and so we should check there first if we are going to look through the possible system paths nuget might be found in.
This fixes #1463
> GH1463: Add possible nuget path on Mac to tool resolver

- src/Cake.Core/Polyfill/EnvironmentHelper.cs
- src/Cake.Core/Polyfill/MacOSXNative.cs
Previously on mono, the PlatformID enum was being used to detect OSX.  As of mono 2.2+ the value on Mac is always returned as 4, which makes it impossible to use to distinguish from any other unix based system.
The fix uses a method that’s tried and tested in MonoDevelop (Xamarin Studio & Visual Studio for Mac) calling out to `uname` and checking if the value is Darwin.
> GH1469: Added a more reliable method to detect Mac OSX

- src/Cake.Common.Tests/Unit/Build/GoCD/GoCDProviderTests.cs
- src/Cake.Common/Build/GoCD/GoCDProvider.cs
- src/Cake.Common/Build/GoCD/IGoCDProvider.cs
A small tweak to the Go.CD GetHistory function to allow you to optionally set a GO.CD server URL.
> GH1403: Add optional Go.CD Server URL Parameter to GetHistory

- src/Cake.Common.Tests/Unit/Tools/WiX/HeatRunnerTests.cs
- src/Cake.Common/Tools/WiX/Heat/HeatRunner.cs
- src/Cake.Common/Tools/WiX/Heat/WiXOutputGroupType.cs
Fixes three issues, each of which completely prevented the parameter from working (at least with WiX 3.10):
* `-pog: x` causes Heat to not associate `x` with `-pog` and instead sets `-pog` to an empty string, giving:
```
warning HEAT1108 : The command line switch 'pog:' is deprecated. Please use 'pog' instead.
error HEAT5301 : Invalid project output group: .
```
Since the colon is deprecated anyway, I changed it simply to `-pog x`.
* `-pog binaries` causes `error HEAT5301 : Invalid project output group: binaries.`, where as `-pog Binaries` works. All output group names were capitalized.
* `Satallites` is also not recognized by Heat since it is misspelled. I also renamed the enum which is a breaking change to anyone using that value. (I suspect that number is negligible due to the fact …
> GH1363: Wixheat pog fix

- src/Cake.Common.Tests/Unit/Diagnostics/LoggingAliasesTests.cs
- src/Cake.Common.Tests/project.json
- src/Cake.Common/Diagnostics/LoggingAliases.cs
- src/Cake.Core/Diagnostics/LogExtensions.cs
- tests/integration/Cake.Common/Diagnostics/LoggingAliases.cake
Enables to log just an object and if string bypass string format allowing any string to be logged. 
* fixes #1455 `Information("{Bon}jour");`
> GH1455: Add log string & object methods

- src/Cake.Common/Tools/SignTool/SignToolSignAliases.cs
> GH1495: Fixes typo in SignTool docs

- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
I have added it to the array as an edition. Fixes #1518
> GH1518: Adding BuildTools as a version to the MSBuildResolver.

- src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs
Add ChocoPack alias for an IEnumerable<FilePath> like it already exists for [NuGetPack](http://cakebuild.net/api/Cake.Common.Tools.NuGet/NuGetAliases/811F8B9C).
Fixes #1503
> GH1503: Add ChocoPack alias for an IEnumerable<FilePath>

- src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs
Add ChocoPush alias for an IEnumerable<FilePath> like it already exists for [NuGetPush](http://cakebuild.net/api/Cake.Common.Tools.NuGet/NuGetAliases/354BEEEF)
Fixes #1504
> GH1504: Add ChocoPush alias for an IEnumerable<FilePath>

- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
This will look for the default install location of `msbuild` on _macOS_.
This is related to #1476
> GH1476: Look for msbuild in default install path on mac

- src/Cake.Common.Tests/Fixtures/Tools/SignToolResolverFixture.cs
- src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolResolverTests.cs
- src/Cake.Common/Tools/SignTool/SignToolResolver.cs
Fixes #1544
Adds the Windows 10 SDK path to the SignTool resolver.
Uses the "HKLM\Software\Microsoft\Windows Kits\Installed Roots" registry key to resolve SDK install paths.
> GH1544: Resolve Windows 10 SDK for SignTool

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs
> GH1533: Updated DotNetCoreBuild inline with Tooling v1.0

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Delete/DotNetCoreDeleterFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Delete/DotNetCoreDeleterTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleteSettings.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleter.cs
* Added DotNetCoreNugetDelete Alias for `dotnet nuget delete`
* Added unit tests
For more information see #1533
> GH1533: Added support for dotnet nuget delete inline with Tooling v1.0

- src/Cake.Common.Tests/Fixtures/Build/TeamCityInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityBuildInfoTests.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs
Change datatype of `TeamCityBuildInfo.Number` from `int` to `string`.
Fixes #1556
> (GH-1556) Change TeamCityBuildInfo.Number to string

- src/Cake.Core.Tests/Data/MethodAliasGeneratorData.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/Generic_ExtensionMethodWithGenericReturnValueAndTypeParamConstraints
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/GenericConstraintFakes.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/GenericParameterConstraintEmitterTests.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs
- src/Cake.Core/Scripting/CodeGen/GenericParameterConstraintEmitter.cs
- src/Cake.Core/Scripting/CodeGen/MethodAliasGenerator.cs
This addresses the issues described in GH-1566
Refactor logic to GenericParameterConstraintEmitter to properly generate any type constraints that might exist on the alias methods.
Add logic to handle emitting the various type constraints
Add test coverage
> GH-1566: Correct the MethodAliasGenerator to for generic type constraints

- README.md
Fixed the dead link to contribution guidelines on the Cake website.
> Fix the contribution guidelines link in the README

- README.md
Looks like the link I changed in https://github.com/cake-build/cake/pull/1604 wasn't quite right. This removes the trailing slash which broke the link. Actually tested it this time!
> Fix the contribution-guidelines link again

- src/Cake.Core/IO/ProcessSettings.cs
Documentation for `ProcessSettings.RedirectStandardError` and `ProcessSettings.RedirectStandardOutput` seems to be just a copy from `ProcessStartInfo` documentation on MSDN, which is misleading in the context of the `ProcessSettings` class.
> GH1620: Improve documentation for RedirectStandardError and RedirectStandardOutput

- src/Cake.Common.Tests/Fixtures/Tools/Chocolatey/Download/ChocolateyDownloadFixture.cs
- src/Cake.Common.Tests/Unit/Tools/Chocolatey/Download/ChocolateyDownloadTests.cs
- src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs
- src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloadSettings.cs
- src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloader.cs
Add alias for `choco download`. Mentionend in the XML comments functionality which requires Chocolatey busines or licensed editions.
Fixes #1591.
> GH1591: Add ChocolateyDownload alias

- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
DotNetCoreTest works differently for projects based on .csproj than project.json. Updated the examples to clarify the differences.
> Updated examples for DotNetCoreTest

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsTests.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs
- src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleanSettings.cs
- src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleaner.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilder.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensions.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildConsoleColorType.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildDistributedLogger.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildFileLoggerSettings.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildLoggerOutputLevel.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildLoggerSettings.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildTreatAllWarningsAs.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs
- src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
* add alias and related files to support `dotnet msbuild` for v1.0.4 of command line tools
* updated clean, restore, build, pack, publish aliases to support msbuild settings
* extension methods
* unit tests
> GH1533: Added support for dotnet msbuild inline with Tooling v1.0

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/VSTest/DotNetCoreVSTesterFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/VSTest/DotNetCoreVSTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/VSTest/DotNetCoreVSTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/VSTest/DotNetCoreVSTester.cs
* add alias and related files to support dotnet vstest for v1.0.4 of command line tools
* unit tests
> GH1533: Added support for dotnet vstest inline with Tooling v1.0

- src/Cake.Core/Polyfill/AssemblyHelper.cs
- src/Cake.Core/Reflection/AssemblyLoader.cs
This PR fix the bug #1679 by using ```path.MakeAbsolute(env)```
> Fix bug #1679 : Cake on dotnet core doesn't load reference dll correctly if referenced from a subdirectory

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Tool/DotNetCoreToolFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Tool/DotNetCoreToolTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreTool.cs
- src/Cake.Common/Tools/DotNetCore/Tool/DotNetCoreToolRunner.cs
- src/Cake.Common/Tools/DotNetCore/Tool/DotNetCoreToolSettings.cs
Created a generic DotNetCoreTool alias allowing per-project extension commands to be executed.
Example usage:
```
Task("Test")
.Does(() => {
var testProjects = GetFiles("./test/**/*.csproj");
foreach(var testProject in testProjects)
{
DotNetCoreTool(testProject, "xunit", "-xml report.xml");
}
}
);
```
Related: GH-1533
> GH-1577: DotNetCoolTool Alias 

- README.md
I only updated the url of the nuget license on the README.md
> Update nuget license url

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporterTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Result.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
This is the PR to fix #1665
This is a breaking change.
The ```Results```, ```ResultFormat``` and ```ResultTransform``` are now combined in the ```NUnit3Result``` class and creation looks like:
```csharp
settings.Results = new[]
{
new NUnit3Result { FileName = "NewTestResult.xml", Format = "nunit2", Transform = "nunit2.xslt" },
new NUnit3Result { FileName = "NewTestResult2.xml", Format = "nunit3" }
};
```
The parameters can be added like:
```csharp
settings.Params = new Dictionary<string, string>
{
["one"] = "1",
["two"] = "2",
["three"] = "3"
};
```
> GH1665: Implemented NUnit3 params and multiple results

- src/Cake.Common.Tests/Fixtures/IO/FileSystemFixture.cs
- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DeleteDirectorySettings.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/DirectoryDeleter.cs
- src/Cake.Core/IO/File.cs
- src/Cake.Core/IO/IFile.cs
- src/Cake.Testing/Extensions/FakeFileSystemExtensions.cs
- src/Cake.Testing/FakeFile.cs
- src/Cake.Testing/FakeFileSystemTree.cs
Fixes https://github.com/cake-build/cake/issues/1564
> GH1564: Allow deletion of read-only files

- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/DirectoryAliases.cs
As described in #1710, this offers a simple Alias to get a list of sub-directories for a given DirectoryPath.
> GH1711: GetSubDirectories alias

- build.cake
Enables support to build on Windows Build agents that doesn't have 4.6.2 SDK installed by setting USE_TARGETING_PACK = true
> (build) Add USE_TARGETING_PACK env var

- src/Cake.Common.Tests/Fixtures/XmlPeekAliasesFixture.cs
- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/XML/XmlPeekAliasesTests.cs
- src/Cake.Common/Xml/XmlPeekAliases.cs
This is the revised `XmlPeek` alias to address the issues described in  GH1537.
The PR is drafted from the code sample provided in the original issue nearly 1:1 with a couple of small optimizations; from reflecting the `XmlDocument` and `XPathNavigator` source, it appears that the extra `null` checks are extraneous.  I can revise accordingly if that's understood to be incorrect or otherwise desirable.
Overall, I added the test coverage given the existing sample content and also included the sample document as provided for posterity/regression.
> GH1537: Refactor XmlPeek alias to use XPathNavigator

- src/Cake.Common/ProcessAliases.cs
Adds overload for `StartProcess` which returns redircted error output. Also improved documentation for the existing `StartProcess` alias.
Fixes #1621
> GH1621: Add overload for StartProcess which returns redircted error output

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/GlobParser.cs
- src/Cake.Core/IO/Globbing/GlobParserContext.cs
- src/Cake.Core/IO/Globbing/GlobTokenizer.cs
I've added Unicode support to the Globber by rewriting the `GlobTokenizer`. This fixes https://github.com/cake-build/cake/issues/1422
- Tokens are lazily loaded into a queue
- `GlobTokenizer` now specifies 'non-identifier characters' rather than 'identifier characters'
- Globbing is 15% faster
- Unicode supported
> GH1422: Add support for Unicode globbing

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildFileLogger.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
This PR will solve #1674. It is partially a breaking change (since a FilePath is implicitly created when assigning a string).
> GH1674: MSBuild - Made LogFile a FilePath, use absolute path when using the runner

- src/Cake.Common.Tests/Unit/Tools/ILRepack/ILRepackRunnerTests.cs
- src/Cake.Common/Tools/ILRepack/ILRepackSettings.cs
When this was originally implemented, it wasn’t very obvious, but ILRepack’s `/lib:<path>` argument should actually be a directory, not a file.
This sheds a _bit_ more light:
https://github.com/gluck/il-repack/blob/master/ILRepack/RepackOptions.cs#L221
This commit fixes up the `ILRepackSettings.Libs` to be the correct type.
This should fix #1720
> ILRepackSettings.Libs should be DirectoryPaths

- tests/integration/build.sh
Currently integration tests will report success if if Mono tests fail but .NET Core succeeds.
> (build) Fix so integration tests fail if Mono fails

- src/Cake.NuGet.Tests/Unit/NuGetPackageInstallerTests.cs
- src/Cake.NuGet/NuGetPackageInstaller.cs
> GH1738: NuGetInstaller resolves correct files when package has dependencies

- src/Cake.NuGet.Tests/Fixtures/NuGetContentResolverFixture.cs
- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet/NuGetContentResolver.cs
- Will treat root assemblies as AnyFramework
- Fixes #1739
> GH1739: NuGetContentResolver finds assemblies in root

- src/Cake.Core.Tests/Fixtures/ScriptRunnerFixture.cs
- src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerResultTests.cs
- src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs
- src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs
- src/Cake.Core/Scripting/Analysis/IScriptAnalyzerContext.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzer.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzerContext.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzerError.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzerResult.cs
- src/Cake.Core/Scripting/Processors/UriDirectiveProcessor.cs
- src/Cake.Core/Scripting/ScriptRunner.cs
- ScriptAnalyzer will not throw on error. Instead the result will
indicate if analysis succeeded or not. A list of errors is also present
in the analyzer result.
- Fixes #1746
> GH1746: ScriptAnalyzer will not throw on error

- src/Cake.Core.Tests/Unit/ActionTaskTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core/ActionTask.cs
- src/Cake.Core/CakeTaskBuilderExtensions.cs
- tests/integration/Cake.Core/CakeAliases.cake
- tests/integration/build.cake
- tests/integration/resources/Cake.Core/testfile1.txt
- tests/integration/resources/Cake.Core/testfile2.txt
- tests/integration/resources/Cake.Core/testfile3.txt
This adds two new extension methods for `ActionTask`
* `DoesForEach`
* `DeferOnError`
`DoesForEach` allows a collection of items, or a delegate that returns a collection of items, to be added as actions to a given task.  In the case of the delegate returning a collection, the delegate is only executed when the task is executed.  This allows the task to look up items that don't exist when the script is first run, such as build artifacts.
`DeferOnError` allows a given task the ability to defer all exceptions until the end of the task execution.  This way tasks can run all actions to completion before failing.  This can have some value when you work with something like multiple unit test projects, or multiple publishes.  You can see the output of the entire task, and not just where it …
> Added new extension method DoesForEach

- src/Cake.Common.Tests/Unit/Tools/VSWhere/All/VSWhereAllTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Latest/VSWhereLatestTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Legacy/VSWhereLegacyTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Product/VSWhereProductTests.cs
- src/Cake.Common/Tools/VSWhere/VSWhereSettings.cs
- src/Cake.Common/Tools/VSWhere/VSWhereTool.cs
As discussed in #1754, this adds a "prerelease" flag.
I think it's more appropriate as an additional flag on the existing VSWhereXXX functionality, but happy to refactor to a VSWherePrerelease or something if that's preferred.
> GH1754 - add prerelease flag to VSWhere

- src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Testing/FakeEnvironment.cs
It is almost the same way as 3046320 did for Mac.
> GH1771: Look for msbuild in default install path on Linux

- src/Cake.Common.Tests/Fixtures/Tools/GitLink3Fixture.cs
- src/Cake.Common.Tests/Unit/Tools/GitLink/Gitlink3RunnerTests.cs
- src/Cake.Common/Tools/GitLink/GitLink3Aliases.cs
- src/Cake.Common/Tools/GitLink/GitLink3Runner.cs
- src/Cake.Common/Tools/GitLink/GitLink3Settings.cs
- src/Cake.Common/Tools/GitLink/GitLinkAliases.cs
This Pull Request relates to https://github.com/cake-build/cake/issues/1734 and updates the GitLink tool to reflect the major restructure that was done in GitLink 3.0.0.
Instead of taking a solution directory, the new GitLink tool takes singular pdb files and patches them. I've added a helper alias to allow passing a FilePathCollection to allow globbing.
> GH1734: Add GitLink 3 aliases

- src/Cake.Common.Tests/Unit/Tools/NuGet/Sources/NuGetSourcesTests.cs
- src/Cake.Common/Tools/NuGet/Sources/NuGetSources.cs
- src/Cake.Common/Tools/NuGet/Sources/NuGetSourcesSettings.cs
- tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake
- tests/integration/build.cake
- tests/integration/resources/Cake.Common/Tools/NuGet/NuGet.config
* Addresses issue with ArgumentCustomization not being used with NuGetHasSource 
* Adds ConfigFile to NuGetSourcesSettings so one can work against custom NuGet.config
* Adds NuGetSourcesSettings  ConfigFile unit tests
* Adds ArgumentCustomization unit test for NuGetHasSource 
* Adds NuGet sources integration tests (_.NET Core on posix excluded as nuget.exe won't run ootb there_)
* Adds NonInteractive which was missing from NuGetHasSource (user input no good in build scripts 😎 )
* Fixes #1773
> GH1773: Fix NuGetHasSource ArgumentCustomization & add ConfigFile to NuGetSourcesSettings

- build.cake
- build/paths.cake
- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Polyfill/EnvironmentHelper.cs
- src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj
- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake/Cake.csproj
- src/Shared.msbuild
- Cake.exe can now load netstandard1.x and netstandard2.0 libraries
@cake-build/cake-team I will try running some integration tests now locally and try this out. @devlead could you at some point start integration tests on CI servers. @Redth could you take this for a spin, at least in Unit Tests, `netstandard1.x` and `netstandard2.0` should be picked up by `NuGetContentResolver` now.
> (build) Target net461 for cake.exe and update NuGet dependencies

- src/Cake.Common/Tools/Cake/CakeRunner.cs
- src/Cake.Core/Tooling/Tool.cs
- tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
* Address Executing assembly issue
* Add support for Cake script on Cake.CoreCLR
* Remove no longer needed special .NET Core ToolPath in integration tests
* fixes #1775
> GH1775: Fix CakeScript tool resolution

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Closes #1651, NUnit3 [removed](https://github.com/nunit/nunit-console/issues/99) the `verbose` and `full` attributes.
I just added the `Obsolete` attributes to them.
> Obsolete unused NUnit3 arguments

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
Replace comma and semicolon in msbuild properties values by hex equivalent to fix issue #1625
> GH1625 Escape comma and semicolon in msbuild property values

- src/Cake.NuGet.Tests/Fixtures/NuGetModuleFixture.cs
- src/Cake.NuGet.Tests/Unit/NuGetLoadDirectiveProviderTests.cs
- src/Cake.NuGet.Tests/Unit/NuGetModuleTests.cs
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake.NuGet/Constants.cs
- src/Cake.NuGet/Install/NuGetFolderProject.cs
- src/Cake.NuGet/Install/NuGetLogger.cs
- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
- src/Cake.NuGet/Install/NuGetProjectContext.cs
- src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
- src/Cake.NuGet/NuGetLoadDirectiveProvider.cs
- src/Cake.NuGet/NuGetModule.cs
- src/Cake/Program.cs
> GH1743: Implements functionality for downloading NuGet packages

- src/Cake.Common.Tests/Fixtures/Tools/GitVersionRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
- src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
Addresses issue with malformed integers in json by having an internal proxy class accepting all strings and then parsing and passing it down the GitVersion class, it's not super elegant but it does the job, the GitVersion property is lazy loaded because how the DataContractSerializer handles object initilaztion (_it'll otherwise give an null references exception_).
* fixes #1798
> GH1798: Make GitVersion tolerate unexpected json

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests_VB.cs
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoExtensionTests.cs
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoExtensionTests_VB.cs
- src/Cake.Common.Tests/Unit/Solution/SolutionParserTests.cs
- src/Cake.Common.Tests/Unit/Tools/Fixie/FixieRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Sources/NuGetSourcesTests.cs
- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core.Tests/Unit/ActionTaskTests.cs
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core.Tests/Unit/Configuration/Parser/ConfigurationTokenizerTests.cs
- src/Cake.Core.Tests/Unit/Diagnostics/CakeBuildLogTests.cs
- src/Cake.Core.Tests/Unit/Diagnostics/FormatParserTests.cs
- src/Cake.Core.Tests/Unit/Graph/CakeGraphTests.cs
- src/Cake.Core.Tests/Unit/IO/FileExtensionsTests.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs
- src/Cake.Core.Tests/Unit/Text/QuoteAwareStringSplitterTests.cs
- src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj
- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet.Tests/Unit/NuGetLoadDirectiveProviderTests.cs
- src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
- src/Cake.Tests/Unit/Composition/ContainerBuilderAdapterTests.cs
While working on #1751, I found out that older versions of xUnit don't play well with building with .NET CLI 2.0. This PR updates xUnit to the latest version, in which this problem is fixed. 
In the process, the xunit.analyzers dependency was also updated, which lead to a bunch of compiler warnings which were converted to errors when running the build script. This PR fixes all of those xUnit warnings, thereby making the build pass again. Each fix is in its own, separate commit, to allow for easier reviewing. All fixes were made automatically using the code fix provided by the xunit analyzer.
The one oddity is the xUnit1025 rule, which looks for duplicate theory parameters. It appears that I have found a bug in the analyzer, as it erronously marks different enum values with the same …
> GH1779: Update xUnit to latest version

- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskTests.cs
- src/Cake.Core.Tests/Unit/Graph/CakeGraphBuilderTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/CakeTask.cs
- src/Cake.Core/CakeTaskBuilderExtensions.cs
- src/Cake.Core/CakeTaskDependency.cs
- src/Cake.Core/Graph/CakeGraphBuilder.cs
- src/Cake.Core/ICakeTaskInfo.cs
- src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj
* Added support for reverse dependencies.
* Dependencies can now be optional.
```csharp
Task("A");
Task("B").IsDependentOn("A", required: true);
Task("C").IsDependentOn("B").IsDependeeOf("D");
Task("D").IsDependeeOf("E", required: false);
RunTarget("D");
```
Fixes #1818
> GH1818: Support task dependees (reverse dependencies)

- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/GlobParser.cs
For #1831 
Discussed briefly in the CAKE gitter. This should be a better place for any discussions if they are needed.
> GH1831: Verify CurrentToken is not null before checking Kind property

- src/Cake.NuGet/Install/NuGetFolderProject.cs
This fixes #1838
I think that simply the wrong package identity was used here.  Instead of `package` which is the identity of the package we are evaluating dependencies for, the `dependency` instance should be used instead which will give us the correct path to the actual libraries in the dependency package.
Using `dependency` just caused the actual main package to have multiple duplicate references added.
> GH1838: Add reference to nuget dependencies

- build.ps1
- build.sh
This PR fixes a typo in PowerShell and bash scripts. The typo is `occured` instead of `occurred`.
> Fixed typo in installer scripts

- src/Cake/Program.cs
* fixes #1815 
It would seem roslyn now returns a AggregateException, with diagnostic verbosity you got the full stack strace, but with any verbosity you just got the message of the AggregateException, now it'll print the messages of the inner exceptions to if present.
> GH1815: Log inner exceptions message

- src/Cake.Common/Tools/MSBuild/MSBuildBinaryLogSettings.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj
- src/Shared.msbuild
StyleCop should now run when running MSBuild from the commandline. Not sure why it didn't work but updating the StyleCop.Analyzers package solved it.
Also had to fix the `SA1623` and `SA1624` errors to make the CI build pass, so proving that this works is kind of difficult...
Fixes #1841
> Fixes StyleCop issues

- src/Cake.NuGet/Install/Extensions/PackageReferenceExtensions.cs
- src/Cake.NuGet/Install/NuGetFolderProject.cs
- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
- Fixes #787
- Don't share project. Only share Gather Cache.
- Use DependencyBehavior.Ignore by default. Only set Lowest if load dependencies is set. This way we wont install unneccessary packages and cache gathering is faster.
> GH787: Enhance NuGet dependency handling.

- src/Cake/Scripting/DescriptionScriptHost.cs
Applies similar logic as the task result reporter does today.
* fixes #1632
> GH1632: Show description handles long task names

- src/Cake.Core.Tests/Unit/Diagnostics/FormatParserTests.cs
- src/Cake.Core/Diagnostics/Formatting/FormatParser.cs
This addresses the issues described in GH-1547 regarding escaping curlies.
As detailed in the original issue, testing this fix uncovered an additional bug (inconsistency with `string.Format` implementation)
> The one thing that I think this exposes is a bug in the LiteralToken that is being returned for escaped curlies 
>`Information("{{}} {0}", 123); outputs "{{}} 123"`
>@DixonDs is right in that this should probably output {} 123 to be consistent with expectations, namely the implementation of string.Format. I have adjusted the parser to return a single '{' or '}' in those cases and updated the tests to match.
> GH1547: Fix issue with parsing escaped curly braces in FormatParser

- src/Cake.Core.Tests/Unit/Diagnostics/CakeBuildLogTests.cs
- src/Cake.Core/Diagnostics/CakeBuildLog.cs
This addresses the regression identified in GH-1548.
Because of the changes that were made as part of 0.18.0, the `CakeBuildLog` will ultimately be consuming _some_ strings that consist solely of `{0}`.  In those cases, it doesn't make sense to change the `BackgroundColor` and `ForegroundColor` for the entire string (treating the entire string as a token argument)
These cases come into play in the `LogExtensions` methods like 
```
public static void Warning(this ICakeLog log, object value)
{
log.Warning("{0}", value);
}
public static void Warning(this ICakeLog log, string value)
{
log.Warning("{0}", value);
}
```
By introducing an extra check for the entire raw string being `{0}`, we can allow the output to be colorized in the same way it was prior to 0.18.0
> GH1548: Add logic to escape colorization for single {0} token

- src/Cake.Common.Tests/Fixtures/Build/GitLabCIInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIBuildInfoTests.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIBuildInfo.cs
- src/Cake.Common/Build/GitLabCI/GitLabCIInfo.cs
Environment variables for version 9+ of the gitlab runner have been
added with tests.
> GH1731: Adding variables for version 9+ runner.

- build.cake
- nuspec/VERIFICATION.txt
> GH1840: Added Verification.txt to Chocolatey Package

- src/Cake.Core.Tests/Unit/Tooling/ToolResolutionStrategyTests.cs
- src/Cake.Core/Tooling/ToolResolutionStrategy.cs
This addresses the failures described in GH-1607 by surrounding the attempt to access the file system (and consequently any `IFileSystem` implementation being registered via module) with a `try/catch` to suppress any errors that may be environmental so as to fully iterate the paths represented in the PATH environment variable.
> GH1607: Make ToolResolutionStrategy more resilient to exceptions 

- src/Cake.Common.Tests/Fixtures/Tools/MSpecRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSpec/MSpecRunnerTests.cs
- src/Cake.Common/Tools/MSpec/MSpecAliases.cs
- src/Cake.Common/Tools/MSpec/MSpecRunner.cs
- src/Cake.Common/Tools/MSpec/MSpecRunnerUtilities.cs
- src/Cake.Common/Tools/MSpec/MspecSettings.cs
This adds support for MSpec unit tests
- Support NET4 and X86.
- Doesn't support NET2 (assuming no one uses it anymore).
- The mspec console currently doesn't support dotnet core.
> GH74: Adds MSpec support

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildPropertyExtensions.cs
> GH-1910: MSBuild property values should escape carriage return and line feed.

- src/Cake.Core.Tests/Data/MethodAliasGeneratorData.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithOutputParameter
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/ParameterEmitterTests.cs
- src/Cake.Core/Scripting/CodeGen/ParameterEmitter.cs
This adjusts the logic in the `ParameterEmitter` to correctly handle the case described in GH-1930 and adds test coverage for the same.
If there's additional test coverage desired, please let me know.
> GH-1930: Fix ParameterEmitter to correctly handle out params

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersion.cs
- src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
Fixes #1922 
Added missing AssemblySemFileVer, which is output as part of the Json format when running GitVersion.
> Add AseemblySemFileVer to GitVersion

- build.cake
- signclient.filter
- signclient.json
Note: you'll find the updated username and password in your lastpass. both should be treated as secure variables in your build system.
> Move to signing service v2

- src/Cake.Core/Extensions/UriExtensions.cs
- src/Cake.Core/Packaging/PackageReference.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetLoadDirectiveProviderFixture.cs
- src/Cake.NuGet.Tests/Unit/NuGetLoadDirectiveProviderTests.cs
- src/Cake.NuGet/NuGetLoadDirectiveProvider.cs
> GH1874: NuGet script load: Do not add include for all cake scripts when include already specified

- src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs
- src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
Fixes issue #1933 where the properties of `NuGetPackSettings` get resolved without being quoted. Fix just uses `AppendQuoted` instead of `Append` in `NuGetPacker`.
> Failed NugetPack when using NuGetPackSettings.Properties fix #1933

- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/Tools/Chocolatey/Pack/ChocolateyPackerTests.cs
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecDependency.cs
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecTransformer.cs
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyPackSettings.cs
- src/Cake.Common/Tools/NuGet/Pack/NuSpecDependency.cs
This PR adds a Dependencies property, of type ICollection<ChocolateyNuSpecDependency>, to the ChocolateyPackSettings class (mirroring the existing behavior in the NuGet pack processing). If package dependencies are specified using this mechanism, the ChocolateyNuSpecTransformer has been modified to place those dependency records into the transformed NuSpec. The ChocolateyPackerTests have also been modified to verify that the transformed output matches expectations.
> GH1943: Allow ChocolateyPackSettings to specify dependent packages

- src/Cake.Common.Tests/Fixtures/Tools/SignToolResolverFixture.cs
- src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolResolverTests.cs
- src/Cake.Common/Tools/SignTool/SignToolResolver.cs
Addresses #1855 
Uses registry keys to find installed Windows 10 SDK versions.
> GH1855: Resolve Signtool in newer Windows 10 SDKs

- src/Cake.Common/Tools/DotNetBuildAliases.cs
> GH1796: Obsolete DotNet aliases

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj
- src/Cake.Tests/Cake.Tests.csproj
> GH1959: Update NSubstitute to remove compiler warnings

- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs
- src/Cake.Common/Tools/XUnit/XUnit2Runner.cs
- src/Cake.Common/Tools/XUnit/XUnit2Settings.cs
- src/Cake.Common/Tools/XUnit/XUnit2SettingsExtensions.cs
This addresses GH-1952.
This adds the properties to `XUnit2Settings` + correct extension methods to `XUnit2SettingsExtensions`, and the implementation to `XUnit2Runner` to pass these switches into the runner.
> GH1952: Add support for targeting namespace/class/method via xunit.console runner

- src/Cake.NuGet/NuGetLoadDirectiveProvider.cs
> GH1957: Use working directory instead if initial script path for resolving tools directory

- src/Cake.NuGet.Tests/Unit/NuGetPackageInstallerTests.cs
- src/Cake.NuGet/Constants.cs
- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
- src/Cake.NuGet/NuGetPackageInstaller.cs
Implements #1931 
With these changes you can now explicitly set the path for the NuGet.config file either through an env var or cake.config.
This should work for both the In Process client and the one invoking NuGet.exe.
> GH1931: Add ability to set NuGet.config through env var or cake.config

- src/Cake/Scripting/Roslyn/RoslynScriptSession.cs
> GH1692: Log more diagnostics from Roslyn.

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
**Note**: as this option is only available for `2.0.0` upward I reflected this in the `XML` comment. Should I handle this in another way?
Fix #1955
> GH1955: Add support for results directory to test settings

- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
The mstest path in VS2017 is more complex than previous VS versions, it contains the year and edition.
I didn't want to create a data type for this simple use case, neither did I want to create nested loop since we don't know what edition names Microsoft comes up with next.
> GH1522: MSTest.exe tool path support for VS2017

- src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs
- src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloader.cs
Add XML comment mentioning that Chocolatey licensed edition is required for `choco download`.
Fixes #1689
> (GH-1689) Add documentation that Chocolatey licensed is required

- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
According to the [docs](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-progressReportingReportingBuildProgress) there is no property "message" for "progressStart" and "progressFinish".
> GH1988: Fix writing start and end progress messages

- src/Cake.Core/IO/Path.cs
I removed the forward slash parameter because it's unnecessary because line #64 that replaces all forward slashes with backslashes. Hardly a critical bug, but as I was studying the code, saw it, and thought I'd comment. The code was introduced in commit ce0c04e3 on 6/9/2014.
> GH1989: Removed unnecessary parameter

- src/Cake.Core.Tests/Unit/Diagnostics/Formatting/PropertyTokenTests.cs
- src/Cake.Core/Diagnostics/Formatting/PropertyToken.cs
This addresses the concern outlined in GH-1987 and uses the same exception type + message as `string.Format` for consistency.
Consider the following:
`var s = string.Format("Testing message {1}", "parameter formatting");`
and 
```
Task("Default")
.Does(() => {
Information("Testing message {1}", "parameter formatting");
});
RunTarget("Default");
```
In both cases, the exception is `FormatException` with message _"Index (zero based) must be greater than or equal to zero and less than the size of the argument list."_
It is worth noting that while this is cleaner than _"Index was outside the bounds of the array."_, it will still (partially) render the content by nature of the implementation of the token parsing/rendering.
```
======================================== 
Default …
```
> GH-1987: Normalize exception handling in PropertyToken for invalid parameter index

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
* Build
* No Restore
* Pack
* No Dependencies
* No Restore
* Publish
* No Dependencoes
* No Restore
* Test
* No Restore
* fixes #1998
> GH1998: Adds missing .NET CLI dependencies/restore switches

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3SettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnitInternalTraceLevelExtensionsTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
- src/Cake.Common/Tools/NUnit/NUnitInternalTraceLevel.cs
- src/Cake.Common/Tools/NUnit/NUnitInternalTraceLevelExtensions.cs
This addresses the improvement identified in GH-1997.
A couple of things to note -
- Please feel free to comment on the name of type `NUnitInternalTraceLevel`.  I think it could conceivably be shortened (`NUnitTraceLevel`, maybe?); I don't feel strongly that we necessarily _need_ to disambiguate the type as "Internal", as there's really only one notion of "trace".
- I took this implementation in the direction of an `enum` over the `string Trace { get; set; }` implementation in the v2 implementation of `NUnitSettings`.  I believe that the usage of enums here creates a stronger API that forces users into a successful end-state by constraining their choices.  However, I acknowledge that it creates a divide between the v2 and v3 Cake API that we may not wish to introduce.  That said, the …
> GH-1997: Add support for --trace command line option for NUnit3 settings and runner

- build.cake
- build/paths.cake
- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Polyfill/EnvironmentHelper.cs
- src/Cake.Tests/Cake.Tests.csproj
- src/Cake/Cake.csproj
This PR builds `Cake.exe` for `net461` instead of `net46`, which would make it possible for addins to target `netstandard20` and avoid an unneccesary breaking change.
> GH2055: Build Cake.exe for net461

- src/Cake.Core/Reflection/AssemblyVerifier.cs
Fixed verb agreement and incorrect hyphenation. (‘Opt out’ is a verb and an adverb, ‘opt-out’ is how you turn it into a noun).
> Fixed typo 'need to'

- src/Cake.Common.Tests/Unit/Tools/NuGet/Update/NuGetUpdaterTests.cs
- src/Cake.Common/Tools/NuGet/Update/NuGetUpdateSettings.cs
- src/Cake.Common/Tools/NuGet/Update/NuGetUpdater.cs
This PR provides option to specify package version while updating and is same as doing
nuget.exe Update "FooBar.sln" -Version 1.0.0.0
> GH2047: Added option to provide version in nuget updation

- src/Cake.NuGet.Tests/Unit/NuGetSourceRepositoryProviderTests.cs
- src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
- added basic argument validation in NuGetSourceRepositoryProvider ctor
- added support for multiple feeds as suggested here #2014 
- added basic unit tests testing argument validation
- added unit tests for NuGetSourceRepositoryProvider testing added functionality
should fix #2014
> GH2014: Allow multiple NugetFeeds for InProcess-NugetClient

- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs
- src/Cake.Common/Tools/XUnit/XUnit2Runner.cs
- src/Cake.Common/Tools/XUnit/XUnit2Settings.cs
Here is the first pass over what I believe to be the most appropriate fix for GH-2039.
I've made the property on the `XUnit2Settings` class nullable.
By default, assuming a user hasn't set the value, it will not be emitted as an argument.
This maintains parity with the previous implementation where `ParallelismOptions.None`, the CLR default, would suppress the emission.  In either case, no explicit argument will allow the runner to use the default.
The _other_ option that I entertained that we could explore further would be setting the default on the `XUnit2Settings` class to `Collections` to match the runner, but I think this has the potential to create regressions for people.
Please feel free to suggest other implementations if they're more desirable.
> GH2039: Fix XUnit2Settings + XUnit2Runner to honor ParallelismOption.None

- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core/CakeEngine.cs
Add setup and teardown messages to the report if they had actions.
Use StopWatch's Restart() method instead of Reset() then Start()
> GH2005: Add setup and teardown to report if run.

- src/Cake.Common/Tools/NuGet/Push/NuGetPushSettings.cs
Document the fact that NuGetPushSettings.Source is mandatory since nuget 3.4.2 and also document the url for two of the most popular public nuget servers (nuget.org and myget).
Resolves #1213
> GH1213: Improve NuGetPushSettings.Source documentation

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensionsTests.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensions.cs
- Add set `MSBuild` `FileVersion` and `InformationalVersion` properties
- Add suppress `CS7035` (version recommended format)
Fix #2031
> GH2031: Add set FileVersion and InformationalVersion

- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeploymentQueryierFixture.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctopusDeploymentQueryTests.cs
- src/Cake.Common/Tools/OctopusDeploy/DeploymentQueryResultParser.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployDeploymentLister.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployment.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeploymentQueryArgumentBuilder.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeploymentQuerySettings.cs
- src/Cake.Testing.Xunit/ExceptionAsserts.cs
reference feature request #1908 
I am guessing you might want something cleaner for the stuff for the string in src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctopusDeploymentQueryTests.cs line 260+.
I'm open to ideas as to how you approach that, since most of the source I read was write-heavy and doesn't do too much parsing, relying mostly on return codes when you have to shell out. I figured that I'd leave it until you said otherwise, since it's pretty darn specific and going the whole embedded resource route or similar seemed a bit overkill.
> GH1908: Octo improvements - list-deployments implementation for octo.exe

- src/Cake.NuGet.Tests/Unit/NuGetSourceRepositoryProviderTests.cs
- src/Cake.NuGet/Install/Extensions/NuGetPackageManagerExtensions.cs
- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
- src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
- Don't use default sources from NuGet.Config's if nuget_source config value is provided.
- Make difference on primary and secondary sources. Target package must
be found int primary source and dependencies may be fetched from
secondary sources.
- Fixes #2081
Needs #2085 to be merged first.
> GH2081: Improve source repository handling

- build.cake
* also removes unused dotnet-core feed
* fixes #2111
> GH2111: Removes retired cli-deps NuGet feed

- src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs
- src/Cake.Core/ICakeEnvironmentExtensions.cs
- src/Cake.Core/Scripting/Analysis/ScriptAnalyzer.cs
- tests/integration/Cake.Core/Scripting/LoadDirective.cake
- tests/integration/build.ps1
- tests/integration/build.sh
This is the second PR after the first was accidentally merged. Here are my thoughts from the previous conversation:
I was thinking about to do this in `ScriptAnalyzer` but it looked quite risky to me. Maybe it is not a good idea to expand the env variables in all lines because we don't know the context. I mean it would replace variables in string, comments, etc. Furthermore this environment variable expansion is only important in the preprocessor directives. In the cake script you can easily access env vars with `EnvironmentVariable` function. But in the preprocess step it is not possible to use these functions or variables of course so my only idea was the environment variable to access various values during the preprocess step. 
That's why i implemented in `UriDirectiveProcessor` so the …
> GH2078: Expand environment variables in Uri

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Fixes #2106.
When I got to the code, I saw that the `Full` and `Verbose` options, which were in the same position, have both just been Obsoleted rather than fully removed. For consistency, I did the same for `ErrorOutputFile`.
> GH2106: Obsolete removed NUnit3 --err option

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Fixes #1557
Note: I took a straightforward approach (just a `ISet<string>` on `MSBuildSettings`), but then I realized that it should probably be made more similar to file logger parameters (which has a `MSBuildFileLogger` class with bool properties for each parameter). Let me know if I should refactor (and how: for instance, should I extract a common base class between `MSBuildFileLogger` and `MSBuildConsoleLogger`?)
> GH1557: Add support for MSBuild console logger parameters

- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet/Install/NuGetFolderProject.cs
- src/Cake.NuGet/NuGetContentResolver.cs
- Improve dependency loading, load in correct order as installed by NuGet.
- Resolve assemblies also from lib
- Fixes #2084
> GH2084: Resolve assemblies in NuGet packages located in lib

- src/Cake.NuGet/Cake.NuGet.csproj
Confirmed this results in `Newtonsoft.Json` 11.0.2 ending up in Cake bin for net46 target framework. This should resolve 90% of cases, but does not introduce a long-term fix of building a reference dependency graph and loading the newest (that'll take some time).
#2134
> GH2134: References latest Newtonsoft.Json from Cake.NuGet

- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeEngineActions.cs
- src/Cake.Core/CakeTaskBuilder.Criterias.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/ICakeEngine.cs
- src/Cake.Core/IExecutionStrategy.cs
- src/Cake.Core/ISetupContext.cs
- src/Cake.Core/Scripting/IScriptHost.cs
- src/Cake.Core/Scripting/ScriptHost.cs
- src/Cake.Core/SetupContext.cs
- src/Cake/Scripting/DryRunExecutionStrategy.cs
- tests/integration/setup.cake
* Relates to #2008, #1594 and #1772
* Changes Setup from `ICakeContext` to `ISetupContext`
* Adds target/initating task as `TargetTask` on `ISetupContext`
* Adds typed context `WithCriteria` `CakeTaskBuilder` extension methods
* Adds integration tests for `ISetupContext`/`TData` Setup and typed `WithCriteria`
> (GH2008/GH1594/GH1772) Typed context improvements

- src/Cake.Core/Constants.cs
- src/Cake.Core/Reflection/AssemblyVerifier.cs
* Warn but not fail the build for potential breaking changes
* fixes #2171
Example output:
> Add potential breaking verification

- src/Cake.Common.Tests/Fixtures/Tools/VSWhere/VSWhereFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/VSWhere/VSWhereToolFixture.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/All/VSWhereAllTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Latest/VSWhereLatestTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Legacy/VSWhereLegacyTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/Product/VSWhereProductTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSWhere/VSWhereToolTests.cs
- src/Cake.Common/Tools/VSWhere/VSWhereTool.cs
- src/Cake.Testing/Fixtures/ToolFixture`2.cs
According to https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/:
> Starting in the latest preview release of Visual Studio version 15.2 (26418.1-Preview), you can now find vswhere installed in “%ProgramFiles(x86)%\Microsoft Visual Studio\Installer” (on 32-bit operating systems before Windows 10, you should use “%ProgramFiles%\Microsoft Visual Studio\Installer”).
So, it would be nice to try to find vswhere.exe on the system if it's not registered like it happens for other tools.
Fixes #2185
> GH2185: Try to find vswhere.exe on the system if the tool is not registered.

- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
Visual Studio Test Runner is not part of the [Visual Studio Build Tools](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools "Visual Studio Build Tools 2017 component directory") but is available on NuGet as [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform).
If the user installs the `Microsoft.TestPlatform`, that should be used instead of trying to guess the path.
Solves #2152
> GH2152: try resolve vstest.console.exe before guessing it

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
Made SelfContainedproperty of DotNetPublishSettings a nullable boolean since no setting means it takes…the .Net default of true when runtime is included.  Added the logic to include false for self contain and test when running DotNetPublish.
https://github.com/cake-build/cake/issues/2140
> GH2140: PR DotNetCorePublish does not respect SelfContained DotNetCorePublishSettings property #2140

- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildCommandTests.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildPublishCodeCoverageData.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildPublishTestResultsData.cs
- src/Cake.Common/Build/TFBuild/Data/TFCodeCoverageToolType.cs
- src/Cake.Common/Build/TFBuild/Data/TFTestRunnerType.cs
- src/Cake.Common/Build/TFBuild/ITFBuildCommands.cs
- src/Cake.Common/Build/TFBuild/TFBuildCommands.cs
This pull request added  PublishTestResults and PublishCodeCoverage commands to the TFSBuilder. This is related to open issue #1609
> GH1609: Add additional VSTS actions

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
- src/Cake.Common/Tools/NUnit/NUnitRunner.cs
NUnit3Settings class does not have property SkipNonTestAssemblies
NUnit3Settings class does have property SkipNonTestAssemblies and features behind it as described here: https://github.com/nunit/docs/wiki/Console-Command-Line
v0.26.1
64
Windows
NO
> GH2095: add   skipnontestassemblies funcionality to nunit3 runner

- src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs
- src/Cake.Core/Scripting/Processors/UriDirectiveProcessor.cs
I did a fix for the issue https://github.com/cake-build/cake/issues/2154
I am not sure if the Regex is complete and valid. But i think this is a better approach then depending on the Uri.TryCreate output to decide if it is a legacy formatted Uri or not.
> GH2154: Fix problem with loading abolute path scripts with #load preprocessor

- src/Cake.Common.Tests/Unit/Tools/DotCover/Analyse/DotCoverAnalyserTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotCover/Cover/DotCoverCovererTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotCover/Merge/DotCoverMergerTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotCover/Report/DotCoverReporterTests.cs
- src/Cake.Common/Tools/DotCover/Analyse/DotCoverAnalyser.cs
- src/Cake.Common/Tools/DotCover/Cover/DotCoverCoverer.cs
- src/Cake.Common/Tools/DotCover/DotCoverSettings.cs
- src/Cake.Common/Tools/DotCover/DotCoverSettingsExtensions.cs
- src/Cake.Common/Tools/DotCover/DotCoverTool.cs
- src/Cake.Common/Tools/DotCover/Merge/DotCoverMerger.cs
- src/Cake.Common/Tools/DotCover/Report/DotCoverReporter.cs
Support for DotCover configuration file added (now properly rebased).
Based on documentation for "cover" command
https://www.jetbrains.com/help/dotcover/dotCover__Console_Runner_Commands.html
"
It is possible to specify part of the parameters or all of them in the configuration file.
usage: dotCover cover <configuration file name> [parameters]
"
configuration file name should be right after command
fixes #1401.
> GH1401: Support for DotCover configuration file added

- src/Cake.Core.Tests/Unit/CakeTaskExtensionsTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskTests.cs
- src/Cake.Core/CakeTaskCriteria.cs
- src/Cake.Core/CakeTaskDependency.cs
- src/Cake.Core/CakeTaskExtensions.cs
> GH2228: Fix CakeTaskExtensions accessibility

- src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
- src/Cake/Arguments/ArgumentParser.cs
- src/Cake/CakeOptions.cs
- src/Cake/Modules/ScriptingModule.cs
Fixes #2234 
Removed the Mono property from CakeOptions, and then removed all usages of it.
> GH2234: Removed Mono from CakeOption

- src/Cake/Commands/HelpCommand.cs
Fixes #2232 
Adds documentation for exclusive command line argument which can be passed to Cake.
> GH2232: Document exclusive argument

- .gitignore
- build.cake
- src/Cake.Common.Tests/Properties/AssemblyInfo.cs
- src/Cake.Common/Properties/AssemblyInfo.cs
- src/Cake.Core.Tests/Properties/AssemblyInfo.cs
- src/Cake.Core/Properties/AssemblyInfo.cs
- src/Cake.NuGet.Tests/Properties/AssemblyInfo.cs
- src/Cake.NuGet/Properties/AssemblyInfo.cs
- src/Cake.Testing.Xunit/Properties/AssemblyInfo.cs
- src/Cake.Testing/Properties/AssemblyInfo.cs
- src/Cake.Tests/Properties/AssemblyInfo.cs
- src/Cake/Commands/VersionCommand.cs
- src/Cake/Properties/AssemblyInfo.cs
This will place SemVer in previous empty AssemblyDescription so it can be used to display version
```
Cake.exe --version
```
Example output
```
0.31.0-GH2284-0001
```
* fixes #2284
> GH2284: Version command display SemVer

- build.cake
> GH2245: Adds symbols for Cake.Tool package

- src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/BuildServer/DotNetCoreBuildServerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/BuildServer/DotNetCoreBuildServerTests.cs
- src/Cake.Common/Tools/DotNetCore/BuildServer/DotNetCoreBuildServer.cs
- src/Cake.Common/Tools/DotNetCore/BuildServer/DotNetCoreBuildServerSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake
Example shutdown all
```cake
DotNetCoreBuildServerShutdown();
```
Example shutdown just MSBuild
```cake
DotNetCoreBuildServerShutdown(
new DotNetCoreBuildServerSettings {
MSBuild = true
});
```
* fixes #2286
> GH2286: Adds .NET Core Build Server Shutdown Alias

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Unit/IO/GlobberTests.cs
- src/Cake.Core/IO/Globbing/GlobNodeRewriter.cs
- src/Cake.Core/IO/Globbing/GlobNodeValidator.cs
- src/Cake.Core/IO/Globbing/GlobParser.cs
- src/Cake.Core/IO/Globbing/GlobParserContext.cs
- src/Cake.Core/IO/Globbing/GlobToken.cs
- src/Cake.Core/IO/Globbing/GlobTokenBuffer.cs
- src/Cake.Core/IO/Globbing/GlobTokenKind.cs
- src/Cake.Core/IO/Globbing/GlobTokenizer.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/Nodes/CurrentDirectoryNode.cs
- src/Cake.Core/IO/Globbing/Nodes/ParentDirectoryNode.cs
- src/Cake.Core/IO/Globbing/Nodes/PathNode.cs
- src/Cake.Core/IO/Globbing/Nodes/RecursiveWildcardNode.cs
- src/Cake.Core/IO/Globbing/Nodes/RelativeRootNode.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/BraceExpansionSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/BracketWildcardSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/CharacterWildcardSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/PathSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/TextSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/Segments/WildcardSegment.cs
- src/Cake.Core/IO/Globbing/Nodes/UnixRootNode.cs
- src/Cake.Core/IO/Globbing/Nodes/WildcardNode.cs
- src/Cake.Core/IO/Globbing/Nodes/WindowsRootNode.cs
- tests/integration/Cake.Common/IO/GlobbingAliases.cake
- tests/integration/build.cake
- tests/integration/utilities/io.cake
- No sequences though
Closes #2201
> GH2201: Extend supported globber patterns

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Tool/DotNetCoreToolTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/Tool/DotNetCoreToolRunner.cs
* Fixes #2300
* Adds overloads without projectPath.
> GH2300: Make DotNetCoreTool projectPath optional

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
> GH2306: Add VSTestReportPath to DotNetCoreTestSettings

- src/Cake.Common.Tests/Unit/XML/XmlPokeTests.cs
- src/Cake.Testing.Xunit/TestRuntime.cs
* fixes #2310
Before fix
```
Test run for C:\temp\dev\gh\devlead\cake\src\Cake.Core.Tests\bin\Debug\netcoreapp2.0\Cake.Core.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
[xUnit.net 00:00:01.0911952]     Cake.Core.Tests.Unit.CakeRuntimeTests+TheBuiltFrameworkroperty.Should_Return_Correct_Result_For_CoreClr [SKIP]
Skipped  Cake.Core.Tests.Unit.CakeRuntimeTests+TheBuiltFrameworkroperty.Should_Return_Correct_Result_For_CoreClr
```
after
```
Skipped  Cake.Core.Tests.Unit.CakeRuntimeTests+TheExecutingFrameworkProperty.Should_Return_Correct_Result_For_Clr
```
> GH2310: Make TestRuntime a Flags enum

- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildCommandTests.cs
- src/Cake.Common/Build/TFBuild/ITFBuildCommands.cs
- src/Cake.Common/Build/TFBuild/TFBuildCommands.cs
Added `UploadArtifactDirectory` commands for uploading directory artifacts to Azure Pipelines. The new method name was required to avoid conflicts with existing `UploadArtifact` commands since both `FilePath` and `DirectoryPath` have implicit conversion from `string`.
Fixes #2332
> GH2332: Add overloads for uploading artifact directories to Azure Pipelines

- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs
- src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
I noticed that there was a bug in the `NuGetPack` alias that would always overwrite the  `developmentDependency` and `requireLicenseAcceptance` values of the .nuspec. This probably has to do with the fact that the setting is `bool` and this always has a default value.
See this issue: #2061
To fix this, I changed it to `bool?` wich has a default of `null`, which is handled correctly.
BUT, this may be a BREAKING change since `bool` -> `bool?` just fine, but not the other way around. As a result, this may need more thought. But, since we are cool, and with it, I think this is a bug since I just discovered that my values were overwritten _and almost went out save for our automated checks we have at the door_.
~_Apologies for not submitting the PR according to the guidelines because I was …
> GH2061: NuGetPack: Fix the issue when the settings overwrite the .nuspec

- src/Cake/App.config
As described in https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/ 
Resolves #1875
Enables long path support on Windows 10 when:
- NuGet.exe v4.8.1 and above is used as external NuGet executable
- Long path support is enabled on the machine
Remarks:
- Windows 7 is not supported because does not support long paths
- I tried to upgrade the inprocess NuGet client to v4.8.0 but does not support long path's. So I removed the upgrade from my PR again
- I tried to add long path support to Cake's app.manifest but did not succeed (as described in the link above) - may anyone help me with that? Although I found that information that it may not work (tbc)
> GH1875: Enable long path support on Windows 10

- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
This PR adds a fallback path to `/usr/local/bin/msbuild` in the MSBuild detector. If `mono` is installed via homebrew, `msbuild` is symlinked to this location by convention and is not located at the default `/Library/Frameworks...` path.
> GH2384: Add fallback path for mono msbuild if installed under homebrew on MacOS

- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
Avoids any exceptions being wrapped in AggregateException, which results in end-user getting the actual underlying error displayed should an exception being thrown
Fixes #2249
Given the following Cake file:
```
#load "nuget:https://www.nuget.org/api/v2?package=Cake.Foo&version=1.2.3"
var target = Argument("target", "Default");
Task("Default")
.Does(() =>
{
Information("Hello World!");
});
RunTarget(target);
```
Without this change, you get the following output
```
C:/dev/git/cake-version-test/build.cake:1: One or more errors occurred.
Error: Errors occurred while analyzing script.
```
After this change, you get:
```
C:/dev/git/cake-version-test/build.cake:1: Unable to find version '1.2.3' of package 'Cake.Foo'.
Error: Errors occurred while analyzing script.
```
> Call GetAwaiter().GetResult() in NuGetPackageInstaller

- .travis.yml
> GH2403: Use Mono 5.12.0 on Travis

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
There's a fluent API on MSBuildSettings to set file loggers.
It would be nice to also have a fluent API on MSBuildSettings to enable the binary logger.
Fixes #2294
> GH2294: Add fluent API to enable MSBuild binary logger

- src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildCommandTests.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildPublishTestResultsData.cs
Resolves #2337 
- Changed type for TestResultsFiles from string[] to ICollection<FilePath>
- Changed selector to only call make absolute on relative paths
- Added Tests for Relative Paths and Absolute paths
- Added tests showing FilePath can be created implicitly from string
> GH2337: Fix TFBuildCommand Directory Separator Character

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/VSTest/DotNetCoreVSTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/VSTest/DotNetCoreVSTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/VSTest/DotNetCoreVSTester.cs
This PR contains some improvements to DotNetCoreVSTest and issue #2243
- Improved documentation which reflex the capability of `dotnet vstest` as it should be assembly based and not project based.
- Add support to specify the ResultsDirectory to specify where to store the test results.
> GH2243: Improve DotNetCoreVSTest with ResultsDirectory

- src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Common/Tools/MSBuild/MSBuildToolVersion.cs
- src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
Fixes #2398.
This is working for the current version of VS 2019 (preview1), but could break in future version, so as of right now, it is not used when Default(latest) is set. You have to force it to use MSBuild16.
> Added support for MSBuild16.

- src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs
Another fix for #2432.
I did a quick test with [Cake v0.33.0-alpha0016](https://www.myget.org/feed/cake/package/nuget/Cake/0.33.0-alpha0016) and everything works as expected, but then I noticed another environment variable I missed with my previous changes. [BuildSystem.TFBuild.Environment.Agent.IsHosted](https://dev.azure.com/gitfool/Cake.Dungeon/_build/results?buildId=16&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=172&lineEnd=173&colStart=1&colEnd=1) is `false` but should be `true`, if only it checked for just the `Hosted` prefix.
> GH2432: Fix TFBuildAgentInfo.IsHosted for Azure Pipelines

- src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildProviderTests.cs
- src/Cake.Common/Build/BuildProvider.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.Common/Build/TFBuild/ITFBuildProvider.cs
- src/Cake.Common/Build/TFBuild/TFBuildProvider.cs
- src/Cake.sln.DotSettings
- tests/integration/setup.cake
Fixes #2429.
- Added `BuildProvider` enum flags
- Added `Provider` property; initialized in `ctor`
- Changed `IsLocalBuild` property to use `Provider` property; initialized in `ctor`
- Added `AzurePipelines` and `AzurePipelinesHosted`
- Deprecated all things `TFS` and `VSTS` with `Obsolete` attribute
- Used xUnit theories to reduce unit tests surface area
> GH2429: Add build system provider property

- src/Cake.Common.Tests/Unit/Tools/ReportGenerator/ReportGeneratorRunnerTests.cs
- src/Cake.Common/Tools/ReportGenerator/ReportGeneratorReportType.cs
Fixes #2439.
I've fixed it as suggested by @devlead. The appropriate fact was modified to a theory to cover all possible values of the enumeration. 
I've also dared to rename `HtmlInline_AzurePipelines` to `HtmlInlineAzurePipelines`. I understand that strictly speaking this violates your suggestion not to re-format the code, but as long as the change is tiny and quite visible, I hope it is ok.
> Fix the numeric values of the enumeration

- src/Cake.Common.Tests/Unit/Tools/NuGet/Restore/NuGetRestoreSettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Restore/NuGetRestorerTests.cs
- src/Cake.Common/Tools/NuGet/Restore/NuGetRestorer.cs
- src/Cake.Common/Tools/NuGet/Restore/NugetRestoreSettings.cs
- Defaults to true (preserving current behaviour as the default)
- Setting to false means NuGet.exe is free to prompt for user input/confirmation (useful when run interactively and when combined with authorisation providers)
Implements #2345
> GH2345: Add NonInteractive property to NuGetRestoreSettings

- src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
This addresses GH-2474 and brings the `BuildProblem` method to be more consistent with the expected usage within TeamCity.
This change will suppress the "identity" token if the value provided is null or empty.  This directory resolves the issue of the provider attempting to sanitize a null reference on a value that, per Jetbrains documentation, is not required for the `buildProblem` service message
> GH2474 Refactor TeamCityProvider.BuildProblem method

- src/Cake.Common/Build/TeamCity/TeamCityDisposableExtensions.cs
- src/Cake.Common/Diagnostics/LoggingAliases.cs
- src/Cake.Core.Tests/Unit/Diagnostics/LogExtensionsTests.cs
- src/Cake.Core.Tests/Unit/DisposableTests.cs
- src/Cake.Core/Diagnostics/LogExtensions.cs
- src/Cake.Core/Disposable.cs
Fixes #2456:
- Add `Disposable` helper for creating anonymous disposables
- Refactor `TeamCityDisposableExtensions` to use `Disposable` helper
- Add logging aliases and extension methods:
- QuietVerbosity, MinimalVerbosity, NormalVerbosity, VerboseVerbosity, DiagnosticVerbosity
Example usage:
```c#
Task("Test")
.Does(() =>
{
Debug("Hide me");
using (DiagnosticVerbosity())
{
Error("Show me.");
Warning("Show me.");
Information("Show me.");
Verbose("Show me.");
Debug("Show me.");
}
Debug("Hide me again");
});
```
> GH2456: Add logging aliases to override the log verbosity

- src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs
- src/Cake.Core.Tests/Unit/IO/FilePathTests.cs
Tests for #2481.
While https://github.com/cake-build/cake/pull/2482 was still exactly the right thing to do, the exception was actually not thrown by FromString called by the operator. What actually was happening was that `new FilePath(null)` was returned from the operator. `new FilePath(null)` is a time bomb that causes the ArgumentNullException to happen much later:
https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Common/Tools/VSTest/VSTestRunner.cs#L70-L72
https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Core/IO/FilePath.cs#L125-L132
https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Core/IO/DirectoryPath.cs#L60-L64
> Null string should convert to null path object

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs
- src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs
- This implements part of #2478
> GH2478: Add additional `dotnet restore` arguments

- src/Cake.Common.Tests/Unit/EnvironmentAliasesTests.cs
- src/Cake.Common/ArgumentAliases.cs
- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Common/Tools/GitVersion/GitVersionAliases.cs
> GH2440:  Add EnvironmentVariable<T> alias

- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoCreateReleaseTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployPromoteTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployReleaseTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoPushTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctopusDeploymentQueryTests.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployArgumentBuilder.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeploySettings.cs
This adds the `--space YourSpaceName` parameter to the `OctopusDeployCommonToolSettings` and updates the implementation in `OctopusDeployArgumentBuilder`.    This covers all aliases that are currently implemented except `pack`, which doesn't accept the optional space qualifier.
As noted in the issue, this will require users to use at least v5.2.0 of `octo.exe`.
> GH2484: Add Spaces support to Octopus Deploy settings and octo.exe aliases

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Unit/IO/Globbing/GlobberTests.cs
- src/Cake.Core/IO/GlobberSettings.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/GlobVisitorContext.cs
This satisfies the feature/enhancement described in GH-1384 by adding the member to the `GlobberSettings` type and wires in
all the necessary logic, providing a clean implementation
that relies on default values (null) and a single point of entry
for invocation to provide a flexible solution without the syntactic
overhead.
This refactors/revisits a [previous attempt](https://github.com/kcamp/cake/tree/GH-1384-old) to achieve the same.
Earlier work was based on methods/implementations that would have
come to rely on method overloads (before the `GlobberSettings`
implementation was added).  Now that the settings type exists,
this represents a much stronger feature/change without any potential
risk for backward compatibility.
i.e., an implicitly typed predicate specified as `IFileSystemInfo` …
> GH1384: Add support to pass Func<IFile,bool> to globbing aliases

- src/Cake.Core/Scripting/CodeGen/MethodAliasGenerator.cs
- src/Cake.Core/Scripting/CodeGen/PropertyAliasGenerator.cs
- src/Cake.Core/Scripting/Script.cs
- src/Cake/Scripting/Roslyn/RoslynCodeGenerator.cs
- src/Cake/Scripting/Roslyn/RoslynScriptSession.cs
- tests/integration/Cake.Core/Scripting/AddinDirective.cake
> GH2487: Add alias dupe check on method/property signarture

- src/Cake.Core/Constants.cs
- src/Cake.Core/IO/ProcessRunner.cs
Following up from #2457, I can cleanly address #820 with a global setting that temporarily overrides the process runner log level.
Example usage:
```
$env:Cake_Settings_ShowProcessCommandLine='true';  .\build.ps1
```
> GH820: Add global override to show process command-line

- src/Cake/Program.cs
https://github.com/cake-build/cake/issues/2087
When the exception thrown in a task is actually a nested `AggregateException`, the output log is:
```
An error occurred when executing task 'taskName'.
Error: One or more errors occurred.
One or more errors occurred.
```
The first occurence of `One or more errors occurred.` is the message of the parent `AggregateException`. The second occurence is the message if the inner exception, which is itself another `AggregateException`.
Here we add a call to `.Flatten()`. This creates a new single instance of `AggregateException` without nesting, so that the last log line will now show the actual inner exception message.
Reference: https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.flatten?view=netframework-4.7.2
> GH2087: log nested aggregate exceptions

- src/Cake.Common.Tests/Fixtures/Tools/GitVersionRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
- src/Cake.Common/Tools/GitVersion/GitVersionSettings.cs
- src/Cake.Common/Tools/GitVersion/GitVersionVerbosity.cs
Pull request to address [2141](https://github.com/cake-build/cake/issues/2141)
A Verbosity property has been added to GitVersionSettings which can be explicitly set otherwise it defaults depending on the verbosity of Cake itself. The rationale behind defaulting is in CI environments (TeamCity in my case) where it is handy to increase verbosity of logging without having to modify the script.
> GH2141: Added Verbosity property to GitVersionSettings

- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core.Tests/Unit/CakeTaskTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeTask.cs
- src/Cake.Core/CakeTaskBuilder.Errors.cs
- src/Cake.Core/CakeTaskExtensions.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/IExecutionStrategy.cs
- src/Cake/Scripting/DryRunExecutionStrategy.cs
Fixes #2445.
In this attempt, I ended up modifying the type of the `ErrorHandler` property of the `CakeTask` class from `Action<Exception>` to `Action<Exception, ICakeContext>`. Let me know if this is not appropriate.
> GH2445: Implement generic overloads of OnError

- src/Cake.Core.Tests/Data/MethodAliasGeneratorData.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Methods/NonGeneric_ExtensionMethodWithParameterAttributes
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs
- src/Cake.Core.Tests/Unit/Scripting/CodeGen/ParameterEmitterTests.cs
- src/Cake.Core/Scripting/CodeGen/ParameterEmitter.cs
- tests/integration/Cake.Common/Diagnostics/LoggingAliases.cake
- tests/integration/utilities/xunit.cake
This addresses the shortcomings in `ParameterEmitter.cs` that were identified in #2393.
I have left this branch as two separate commits for review.
The first commit (bf50ce3) provides an exact fix to the issue surfaced by `ScriptCallerAliases` and provides matching test coverage.  It's very possible that this is the extent of the fix required or desired, and in that case, we can modify the PR to reflect that.
The second commit took the starting logic from the first and attempted to craft a more complete solution, supporting a wider range of possible parameter decorations to include both normal constructor mechanics as well as named arguments.  Based on the test cases that were implemented, I think this provides a reasonable implementation (779acfa), but obviously there are many, many test …
>  GH2393: Support attribute-decorated parameters in cake alias methods for codegen

- src/Cake.Core.Tests/Fixtures/GlobberFixture.cs
- src/Cake.Core.Tests/Fixtures/ScriptAnalyzerFixture.cs
- src/Cake.Core.Tests/Fixtures/ScriptRunnerFixture.cs
- src/Cake.Core.Tests/Unit/IO/Globbing/GlobberTests.cs
- src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs
- src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs
- src/Cake.Core/IO/Globbing/GlobVisitor.cs
- src/Cake.Core/IO/Globbing/GlobVisitorContext.cs
- src/Cake.Core/IO/Globbing/Nodes/UnixRootNode.cs
- src/Cake.Core/Scripting/Processors/Loading/FileLoadDirectiveProvider.cs
- src/Cake.NuGet/NuGetLoadDirectiveProvider.cs
- tests/integration/Cake.Core/Scripting/LoadDirective.cake
- tests/integration/resources/Cake.Core/Scripting/Globber/nothrow.cake
- tests/integration/resources/Cake.Core/Scripting/Globber/throws.cake
Fixes #2400. @patriksvensson almost there; a couple of the existing unit tests are failing though:
- [LoadDirectiveProcessorTests.cs#L168](https://github.com/gitfool/cake/blob/2ed89ca5be268818a58c3b4840a199aba0bd6af1/src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs#L168)
- [LoadDirectiveProcessorTests.cs#L206](https://github.com/gitfool/cake/blob/2ed89ca5be268818a58c3b4840a199aba0bd6af1/src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs#L206)
In both cases the globber is processing absolute paths that don't have any globber patterns in them and returning no files. Any ideas how to handle that?
> GH2400: Add globber pattern support to the #load directive

- src/Cake.Common.Tests/Unit/Tools/ReportGenerator/ReportGeneratorRunnerTests.cs
- src/Cake.Common/Tools/ReportGenerator/ReportGeneratorReportType.cs
- Also correct `HtmlInline_AzurePipelines`
Fixes #2514
> GH2514: Add additional report types to ReportGenerator

- src/Cake.Common.Tests/Unit/Text/TextTransformationExtensionsTests.cs
- src/Cake.Common/Text/TextTransformationExtensions.cs
Following up from #2375 and the recently merged #2124, I can't easily use this extension without being forced to materialize a dictionary, which is inconvenient, especially if I need to filter the keys first (using LINQ), hence this tweak to use the `IEnumerable<KeyValuePair<K, V>>` base type instead.
> Use IEnumerable<KeyValuePair<K, V>> in TextTransformation.WithTokens

- src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
Changes regarding the release of Visual Studio 2019.
Fixes #2519
> GH2519: Changes for stable Visual Studio 2019 release

- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployPackerFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployPusherFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleaseCreatorFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleaseDeployerFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleasePromoterFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/OctopusDeploymentQuerierFixture.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoCreateReleaseTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoPushTests.cs
- src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctopusDeploymentQueryTests.cs
- src/Cake.Common/Tools/OctopusDeploy/DeploymentQueryResultParser.cs
- src/Cake.Common/Tools/OctopusDeploy/OctopusDeployTool.cs
Fixes bug discussed in #2535 
Renamed to `Octo.exe` in the tests where the tool path is set explicitly to keep it consistent across the repo.
> GH2535: Rename octo.exe to Octo.exe

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Tackling issue #2551.
Brief summary of changes:
- Added `NoImplicitTarget `property to MSBuild;
- Added `SetNoImplicitTarget()` extension method to get/set the property mentioned above;
- Added some tests to validate the relevant scenarios for this change.
Some behavior details:
- If the developer provides no targets (meaning doesn't use `WithTarget()`) and doesn't use `NoImplicitTarget`, MSBuild will be called with `/target:Build`, keeping the current behavior;
- If the developer provides no targets (meaning doesn't use `WithTarget()`) and sets `NoImplicitTarget` to true, MSBuild will be called with no targets at all;
- If the developer provides targets (using `WithTarget()`) the provided targets will be used regardless of the value of `NoImplicitTarget`.
> GH2551: Implement the NoImplicitTarget property and extension method in MSBuild

- .travis.yml
- build.cake
- build/paths.cake
- src/Cake.Core/Cake.Core.csproj
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake/Cake.csproj
- tests/integration/Cake.Core/Scripting/Dynamic.cake
- tests/integration/build.cake
* fixes use of dynamic with newer versions of Microsoft.CodeAnalysis.CSharp.Scripting
* updates Microsoft.CodeAnalysis.CSharp.Scripting  to 3.1.0
* adds Cake.Tool to Integration tests
* fixes #2575
> GH2575: Fix dynamic C# issues

- src/Cake.Common/Tools/GitVersion/GitVersionVerbosity.cs
Since the docs said: "only log info", I assumed this was a flagged enum, but according to the source, it's not:
https://github.com/cake-build/cake/blob/main/src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
> Update confusing GitVersionVerbosity docs

- src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs
- src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildProviderTests.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs
- src/Cake.Common/Build/TFBuild/TFBuildProvider.cs
Fixes #2608 by regarding any agent with an `AGENT_NAME` that starts with `Hosted Agent` or `Azure Pipelines` as a hosted agent, and merges that logic into the `TFBuildAgentInfo.IsHosted` property so it's consistent with the internal logic.
This actually seems a little far-reaching so in future we might want to change to using the value of `SYSTEM_SERVERTYPE` once we know what that variable actually *does*.
> GH2608: Correctly identifies extra hosted agents in Azure Pipelines

- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
This pull request fixes #2618 
When running Cake on a machine with only VS2019 available (any version) the correct path to the MSTest runner was not found as the path resolution method didn't account for VS2019.
The 3 editions of VS2019 have been added to the collection of paths and new test cases have been added to the unit tests.
> GH2618: Added support for VS2019 in MSTest runner

- build.cake
- build/parameters.cake
* Skip MyGet push
* Create chocoloatey packages on AzureDevops if on Windows.
> (build) Skip MyGet & Choco on Azure DevOps

- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Cake.Core.csproj
- src/Cake.NuGet/Cake.NuGet.csproj
As per https://github.com/cake-build/cake/issues/2606
- Removed superfluous dependencies in `Cake.Core`
- Updating reference to `Newtonsoft.Json` in `Cake.NuGet` to 12.0.2
> Enabling use of Newtonsoft.Json > 11.0.2

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests_VB.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreatorData.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCustomAttribute.cs
@cake-build/cake-team would be good to get some thoughts on this...
Fixes #2637 and fixes #2638
> GH2637 GH2638: Update CreateAssemblyInfo alias

- build.cake
- nuspec/Cake.CoreCLR.nuspec
- nuspec/Cake.CoreCLR.symbols.nuspec
- nuspec/Cake.nuspec
- nuspec/Cake.symbols.nuspec
* Update NuGet CommandLine to version 5.3.0
* Include icon in package
* Switch from iconUrl to icon element
* Correct Cake symbols framework moniker
* Fixes #2643
> GH2643: Cake&Cake.CoreCLR nuspec self-contained icon

- src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreatorData.cs
- src/Cake.Common/Solution/Project/Properties/AssemblyInfoCustomAttribute.cs
This PR should solve #2533 in a more generic way. Rather than hardcoding for `SecurityRules` this adds opt-in behaviour to skip attribute quoting.
I'm not 100% sure on the whole "raw" naming, but I couldn't think of anything better. Other option would be to more explicit and use something like `NoQuote`.
> GH2533: Add new RawValue parameter to skip attribute value quoting

- src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildRepositoryInfoTests.cs
- src/Cake.Common/Build/TFBuild/Data/TFBuildRepositoryInfo.cs
Rename `TFBuildRepositoryInfo.Branch` to `TFBuildRepositoryInfo.SourceBranchName` and mark `TFBuildRepositoryInfo.Branch` as obsolete.
Fixes #2657
> (GH-2657) Rename TFBuildRepositoryInfo.Branch to TFBuildRepositoryInfo.SourceBranchName

- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerTests.cs
- src/Cake.Common/Tools/NuGet/Install/NuGetInstaller.cs
- src/Cake.Common/Tools/NuGet/Install/NugetInstallSettings.cs
Tackling issue #2671.
Brief summary of changes:
Added a property to define whether NonInteractive is passed or not to NuGet Install command.
The implementation is similar to the one already being used in NuGet Restore (with test included).
> GH2671: Add support for removing -NonInteractive in NuGet Install command

- src/Cake.Common.Tests/Unit/EnvironmentAliasesTests.cs
fix fail unit test on no-english #2541
In russin test fail:
```
Cake.Common.Tests.Unit.EnvironmentAliasesTests+TheEnvironmentVariableMethod.Should_Throw_If_Value_Does_Not_Convert
Source: EnvironmentAliasesTests.cs line 152
Duration: 27 ms
Message: 
Assert.Contains() Failure
Not found: not a valid value
In value:  abc не является допустимым значением для 'Int32'.
Stack Trace: 
Assert.Contains(String expectedSubstring, String actualString) line 22
TheEnvironmentVariableMethod.Should_Throw_If_Value_Does_Not_Convert() line 172
```
.Net localizes all standart exception message (in .net standart library). 
see message "In value:  abc не является допустимым значением для 'Int32'."
Not check message. Exeption have InnerExeption.
Set InvariantCulture culture before test (will use not localized …
> GH2541: fix unit test

- src/Cake.Core/Tooling/Tool.cs
* Adds "optional" `protected virtual IEnumerable<string> GetToolExecutableNames(TSettings settings)` which default to `GetToolExecutableNames()` implementation.
* fixes #2679 
This enables tool runners to switch executable based on settings example
```diff
/// Gets the possible names of the tool executable.
/// </summary>
/// <returns>The tool executable name.</returns>
-        protected override IEnumerable<string> GetToolExecutableNames()
+        protected override IEnumerable<string> GetToolExecutableNames() => throw new NotImplementedException();
+        /// <summary>
+        /// Gets the possible names of the tool executable.
+        /// </summary>
+        /// <param name="settings">The settings.</param>
+        /// <returns>The tool executable name.</returns>
+ …
```
> GH2679: Add GetToolExecutableNames(TSettings settings) to Tool

- src/Cake.Common.Tests/Fixtures/Tools/InspectCode/InspectCodeFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/InspectCode/InspectCodeRunFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/InspectCode/InspectCodeRunFromConfigFixture.cs
- src/Cake.Common.Tests/Unit/Tools/InspectCode/InspectCodeRunnerTests.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs
- This PR should handle issue #2675 
- The Resharper InspectCode tool embeds another tool `InspectCode.x86.exe` that needs to be used if you want to also analyze the C++ project that you may have in your Visual Studio solution. Note. that this tool `InspectCode.x86.exe` has the same arguments as `InspectCode.exe`
> GH2675: Add InspectCode.x86.exe tool management

- src/Cake.Core/Polyfill/AssemblyHelper.cs
- src/Cake.Core/Reflection/AssemblyLoader.cs
- src/Cake.Core/Scripting/ScriptRunner.cs
- src/Cake.NuGet.Tests/Fixtures/NuGetContentResolverFixture.cs
- src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake.NuGet/NuGetContentResolver.cs
- Fixes #2275
~~Don't know if this is the right direction to go. Basically we *should* load the runtime libs based on the current RID if running .NET Core. Problem is there's a whole lot of them (see [list or runtimes](https://github.com/dotnet/corefx/blob/7e56d8bd8b224d834b782a98bfd7035f71c3f547/pkg/Microsoft.NETCore.Platforms/runtime.json)  and [docs](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)).~~
~~@daveaglick do you have anything to add? Maybe we should consult our friends at NuGet?~~
Went with the route of correctly findint runtime assemblies and loading them, including native libraries.
> GH2275: Correctly reference runtime libraries from addins

- tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake
- tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/VSTests.cs
- tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/hwapp.tests.csproj
Adding integration tests for DotNetCoreAliases VSTest, Tool, NuGetPush, NuGetDelete, Clean, and MSBuild.
This change is to address #1571
> GH1571: Adding integration tests for DotNetCoreAliases VSTest, Tool, etc.

- src/Cake.Common.Tests/Unit/Tools/InspectCode/InspectCodeRunnerTests.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeSeverity.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeVerbosity.cs
💡 It fixes the issue https://github.com/cake-build/cake/issues/2328.
This PR adds the support of the arguments /verbosity and /severity for the tool InspectCode.
> InspectCode: Add support for /verbosity and /severity arguments

- src/Cake.Common.Tests/Fixtures/Tools/InnoSetupFixture.cs
- src/Cake.Common.Tests/Unit/Tools/InnoSetup/InnoSetupRunnerTests.cs
- src/Cake.Common/Tools/InnoSetup/InnoSetupRunner.cs
- src/Cake.Common/Tools/InnoSetup/InnoSetupSettings.cs
- src/Cake.Common/Tools/InnoSetup/InnoSetupVersion.cs
This PR adds support for the new Inno Setup 6. By default the newest available version is used, the version to use can also be set by using the Version property on the settings class.
> GH2663: Add support for Inno Setup 6

- src/Cake/Cake.csproj
* Addresses issue with Mono 6.8+
* Fixes #2695
> GH-2695: Update Microsoft.CodeAnalysis.CSharp.Scripting to 3.5.0-beta2-final

- src/Cake.Common/Xml/XmlPeekAliases.cs
A small change in file-sharing access to avoid the error: "The process cannot access the file because it is being used by another process."
Related to #2745
Please review,
> GH2745: Change file share access to Read for XmlPeekAliases

- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
This re-orders the "Year and Edition" folder path segments of VS2019 to appear
first in the list as the newest VS version, which allows any alternative tool path
resolution to resolve latest first.  This follows the patterns established where the
resolution has historically resolved VS2015 over VS2013, and so on.
This also adds tests to explicitly exercise this evaluation.  If additional coverage is desired, I can add that, but I think that's probably superfluous at this point.  As always, any feedback or change requests are welcome 👍
> GH2752: Fix precedence of VS2019 MSTest.exe to be higher than VS2017.

- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
This addresses the outstanding issue identified in GH-2077.
While acknowledging that the better-supported solution was introduced with GH-2152, this gives the Cake implementation a more complete solution, especially for users that are constrained to the Visual Studio provided executable (i.e., build server, non-homogenized environments, etc.)
This introduces the "year and edition" path querying that is implemented in the `MSTestRunner`.
The one thing worth mentioning is that I am pretty sure the inclusion of `"15.0"` in the block below isn't quite right - the `2017/` paths added in this PR most likely covers the VS2017 ("15.0") case, but given the logic employed, the implementation is most likely fully backward-compatible, and I saw no pragmatic reason to alter the existing …
> GH2077: Adds alternate tool path support to vstest.console.exe  for VS2017 + 2019

- src/Cake.Common.Tests/Unit/Tools/DupFinder/DupFinderRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/InspectCode/InspectCodeRunnerTests.cs
- src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs
- src/Cake.Common/Tools/DupFinder/DupFinderSettings.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs
Resolves #2768 
I've added an option to skip the built-in analysis part that is performed after the JetBrains command line tool is done. In our case we use another tool to do the analysis using a custom logic. That's why we do not want to output the "issues" directly.
> Added options to skip the analysis of the output file

- src/Cake.Common/Tools/MSBuild/MSBuildAliases.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
Improve documentation to make clear that project can be passed to MsBuild alias. Also change naming of the argument to make this more clear and be in line with [underlying tools documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019).
Fixes #2735
> GH2735: Improve documentation to make clear that project can be passed to MsBuild alias

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Core/Cake.Core.csproj
- src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake.Tests/Cake.Tests.csproj
- tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake
- tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/hwapp.tests.csproj
- tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/hwapp.csproj
> GH2778: Bump dependencies

- GitVersion.yml
Based on current git history, the next version number for Cake should
be 0.39.0, however, the plan is to ship 1.0.0 as the next version.  By
putting this into the GitVersion.yml file, we force GitVersion to use
1.0.0 as the next base version number.
Fixes #2818
> GH2818: Bump next version in GitVersion.yml

- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
Resolves #2811.
- Make `identity` of `BuildProblem` in `TeamCityProvider` optional
- Improve description of the arguments with more details copied from TeamCity's documentation
The current tests [already provide coverage for identity being `null`](https://github.com/cake-build/cake/blob/e4ccdab3183bae78915f587171bd4a9387fc0300/src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs#L137).
---
> Make identity of BuildProblem in TeamCityProvider optional

- src/Cake.Common/Tools/ReportGenerator/ReportGeneratorRunner.cs
When attempting to run the change that was made on my Mac, the Cake
Tool resolver still returns ReportGenerator.exe, since there is one of
these nested within the folder structure for the gloal tool.  So even
though we"want" the shim to be found, it isn't.
Workaround this by chaning the order for the tool names.  Since the
since shouldn't exist on a Windows machine, it shouldn't have any
adverse affects.
Fixes #2822
> (GH-2822) Change order for tool names

- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverHideSkippedOption.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverHideSkippedOptionExtensions.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
- Added hideskipped support for OpenCover.
- Added unit tests.
- Added extension method to fetch all valid flag values.
> GH-2703: Added hideskipped option support for OpenCover

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs
- src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
Resolves #2839
```csharp
DotNetCorePublish("./src/MyApp/MyApp.csproj", new DotNetCorePublishSettings
{
// ...
PublishReadyToRun = true,
PublishReadyToRunShowWarnings = true, // <<<
});
```
> GH-2839: Add support for PublishReadyToRunShowWarnings property in DotNetCorePublish

- src/Cake.Common.Tests/Unit/EnvironmentAliasesTests.cs
- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Core/Extensions/CakePlatformExtensions.cs
- src/Cake.Core/Polyfill/EnvironmentHelper.cs
This is very helpful for when things run on just macOS or just Linux. The Unix variant is nice for the basic Windows/not-Windows, but in some cases, the build script needs to know if Xcode should be used or some other mac-specific tool.
This actually was supposedly "added" in #741, but it never actually was?
Did I miss something? If this was excluded for a specific reason, then feel free to close.
I am also looking at the code, and not sure if this fits exactly since the Windows variant is basically !Unix, however, I can iterate on this PR based on any feedback.
> Add IsRunningOn for macOS and Linux 

- src/Cake.Common.Tests/Unit/Security/DirectoryHashCalculatorTests.cs
- src/Cake.Common.Tests/Unit/Security/HashAlgorithmBuilderTests.cs
- src/Cake.Common/Security/DirectoryHash.cs
- src/Cake.Common/Security/DirectoryHashCalculator.cs
- src/Cake.Common/Security/FileHashCalculator.cs
- src/Cake.Common/Security/HashAlgorithmBuilder.cs
- src/Cake.Common/Security/IHashAlgorithmBuilder.cs
- src/Cake.Common/Security/SecurityAliases.cs
- Add DirectoryHash represents a calculated directory hash.
- Add DirectoryHashCalculator for calculating a hash for a directory.
- Add HashAlgorithmBuilder for a common usage of creating a instance of the hash algorithm.
- Overload the ctor of FileHashCalculator with IHashAlgorithmBuilder as additional parameter.
Fixes #2755
> GH-2755: Add DirectoryHashCalculator

- src/Cake.Core/Polyfill/EnvironmentHelper.cs
- src/Cake.Core/Polyfill/Runtime.cs
> GH2859: Identify .NET 5 as CoreCLR

- src/Cake.Core.Tests/Unit/Tooling/ToolTests.cs
- src/Cake.Core/Tooling/Tool.cs
- src/Cake.Core/Tooling/ToolSettings.cs
- When true, then ProcessExitCode method is not called
> GH2825: Add HandleExitCode to ToolSettings

- .gitattributes
* fixes #2887
If already cloned repo endings can be fixed after this is merged by executing (as attributes are cached)
1. `git rm --cached -r .`
2.  `git reset --hard`
> GH2887: Enforce bash scrips LF line endings

- src/Cake.Common/Tools/DotCover/DotCoverContext.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverContext.cs
- src/Cake.Common/Tools/SpecFlow/SpecFlowContext.cs
- src/Cake.Core/CakeContextAdapter.cs
> GH2895: Custom contexts inherit CakeContextAdapter instead of ICakeContext directly

- src/Cake/Cake.csproj
> GH2911: Update Specre.CLI to 0.45.0

- src/Cake.Common.Tests/Fixtures/Build/MyGetFixture.cs
- src/Cake.Common.Tests/Unit/Build/MyGet/MyGetProviderTests.cs
- src/Cake.Common/Build/MyGet/MyGetProvider.cs
Fixes #2897 Add unit tests for MyGetProvider.
Additionally replacement of special characters was rewritten. Although original implementation (surprisingly) worked, it relied on implementation of Dictionary. Problem was that `|` should be replaced first, otherwise it would be replaced multiple times. However, `Dictionary` does not guarantee to enumerate items in the same order as they were added to the dictionary. So it was not guaranteed that `|` would be first token to replace.
I changed the replacement to iterate through characters of source string.
Also original code replaced `[` by `|['`. I assume it was type and correct replacement is `|[`
> GH-2897: Add tests for MyGetProvider

- README.md
Resolves incorrect link in Cake readme issue #2918
> (doc) Corrected ReSharper Open Source web page link in cake readme

- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
Add overload for `DotNetCoreRun` without `ProcessArgumentBuilder` parameter
Related to #2913
Please review,
> GH2913: Add overload for DotNetCoreRun without ProcessArgumentBuilder parameter

- src/Cake/Commands/DefaultCommand.cs
Adds back support for aggregate exception and that diagnostic verbosity will print a full stack trace.
* fixes #2861
> GH2861: Restore pre 1.0 error logging

- src/Cake.NuGet/Install/NuGetPackageInstaller.cs
Got hit by this one today and based on the conversation in #2595, seems like the consensus is that we should honour explicitly specified prerelease versions, even without a `prerelease` flag. From what I can test, behaviour is otherwise unchanged.
---
fixes #2595
> GH2595: Installs prerelease package versions when explicitly specified

- src/Cake.Common/Build/AzurePipelines/IAzurePipelinesCommands.cs
- src/Cake.Common/Build/ContinuaCI/IContinuaCIProvider.cs
- src/Cake.Common/Build/TFBuild/ITFBuildCommands.cs
- src/Cake.Common/Build/TravisCI/Data/TravisCIJobInfo.cs
- src/Cake.Common/IO/GlobbingAliases.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreVerbosity.cs
- src/Cake.Common/Tools/GitReleaseManager/Create/GitReleaseManagerCreateSettings.cs
- src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs
- src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs
Fixes sentences in XML comments which end with double full stops.
> Fix sentences which end with double full stop

- build/parameters.cake
> GH2928: Push Cake.Frosting and Cake.Frosting.Template to NuGet

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
[Now that GH discussions is the preferred communication channel moving forward](https://gitter.im/cake-build/cake?at=5fa5656bb86f640704354b3d).
---
Badge in the PR:
[![Join the chat at https://github.com/cake-build/cake/discussions](https://img.shields.io/badge/discussions-join%20chat-brightgreen)](https://github.com/cake-build/cake/discussions?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
> Update links to Gitter to point to GitHub discussions

- src/Cake.Core/Constants.cs
Bumps the potential breaking change property to 1.0.0.
Fixes #2930
> (GH-2930) Bump potential breaking change property to 1.0.0

- src/Cake.Core/Diagnostics/Console/AnsiDetector.cs
Honors `NO_COLOR` environment variable to opt-out of ANSI color.
---
(Partially) closes ... #2975
> GH-2975: Prevents the addition of ANSI color if NO_COLOR env. variable is present

- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
- src/Cake.Frosting/Internal/FrostingEngine.cs
Removes an unused parameter introduced with https://github.com/cake-build/cake/pull/2946
> Remove unused parameter

- src/Cake.Core/IO/ConsoleMode.cs
- src/Cake.Core/IO/ProcessRunner.cs
As described in https://github.com/cake-build/cake/issues/3018, external processes spawned by Cake have the ability to modify the current console mode, affecting the console output written by Cake itself, as is the case of SQLCMD disabling ANSI escape codes support.
This PR updates the `ProcessRunner` to take a snapshot of the current console mode (if any i.e. When running on Windows and with a console handle available) and restores it back to its original value in case the process that was executed changed the console mode.
---
Closes https://github.com/cake-build/cake/issues/3018
> GH-3018: Restore original Console Mode (if any) after running external processes

- src/Cake/Program.cs
* fixes #2961
This will adjust application name in help based on target framework moniker, examples after adjustment:
**net461**
```
USAGE:
Cake.exe [SCRIPT] [OPTIONS]
EXAMPLES:
Cake.exe
Cake.exe build.cake --verbosity quiet
Cake.exe build.cake --showtree
```
**net5.0**
```
USAGE:
dotnet cake [SCRIPT] [OPTIONS]
EXAMPLES:
dotnet cake
dotnet cake build.cake --verbosity quiet
dotnet cake build.cake --showtree
```
**netcoreapp2.0**
```
USAGE:
dotnet Cake.dll [SCRIPT] [OPTIONS]
EXAMPLES:
dotnet Cake.dll
dotnet Cake.dll build.cake --verbosity quiet
dotnet Cake.dll build.cake --showtree
```
**netcoreapp2.1**
```
USAGE:
dotnet cake [SCRIPT] [OPTIONS]
EXAMPLES:
dotnet cake
dotnet cake build.cake --verbosity quiet
dotnet cake build.cake --showtree
```
**netcoreapp3.0**
```
USAGE:
dotnet cake …
```
> GH2961: SetApplicationName based tfm

- src/Cake.Core/IO/IRegistry.cs
- src/Cake.Core/IO/WindowsRegistry.cs
Update `IRegistry` to expose the remaining standard root registry keys:
- `IRegistry.CurrentUser`
- `IRegistry.ClassesRoot`
- `IRegistry.Users`
- `IRegistry.PerformanceData`
- `IRegistry.CurrentConfig`
---
Closes #3024
> (GH-3024) Expose remaining root registry keys to Cake scripts

- src/Cake.Core/Tooling/ToolLocator.cs
- src/Cake.Frosting.Tests/Fixtures/CakeHostFixture.cs
- src/Cake.Frosting/Cake.Frosting.csproj
- src/Cake.Frosting/Extensions/CakeHostExtensions.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
- src/Cake.Frosting/Internal/FrostingEngine.cs
- src/Cake.Frosting/Internal/ToolInstaller.cs
This pull request makes sure that Cake.Frosting respect any user configuration related to the tool installation path.
> Cake Frosting should respect configuration

- src/Cake.Frosting.Template/templates/cakefrosting/build/Program.cs
Remove call to `UseWorkingDirectory` in Frosting default template, since we should not promote its usage as it can lead to some known issues.
Fixes #3069
> GH3069: Remove use of UseWorkingDirectory in default template

- src/Cake.Frosting.Example/Program.cs
- src/Cake.Frosting.Tests/CakeHostTests.cs
- src/Cake.Frosting.Tests/Tasks/DependeeTask.cs
- src/Cake.Frosting/Internal/Extensions/TaskNameHelper.cs
- src/Cake.Frosting/Internal/FrostingEngine.cs
Fixes #3072
- Fix the `FrostingEngine.ConfigureTasks()`
- Add a `.GetTaskName()` helper for `IReverseTaskDependency`
- Add unit test for `IsDependeeOf`
- Add `DependeeTask` to `Example` project
> (GH-3072) Fix [IsDependeeOf] attribute

- src/Cake.Cli/Cake.Cli.csproj
After Cake v1.0 RTM is released, we'll upgrade to a future version of Spectre.Console that fixes it
Resolves #3077
> (GH-3077) Downgrade to Spectre.Console v0.36.0 due to bug in v0.37.0 with OSX ANSI

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
This PR should fix issue #2558.
It also includes unit tests.
I don't know if `MSBuildBinaryLogSettings.FileName` should really be of type `FilePath` instead of `string` like `MSBuildFileLogger.LogFile` is.
> GH2558: fix quote filename of binary logger

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs
- src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
Added `--blame` flag to `dotnet test` command
Fixes #2932
Please review
> Add dotnet test --blame Flag to DotNetCoreTestSettings

- src/Cake.Core.Tests/Unit/IO/ProcessArgumentBuilderTests.cs
- src/Cake.Core/IO/ProcessArgumentBuilder.cs
> GH2941: Return empty process argument builder when values is null

- src/Cake.Core.Tests/Unit/Diagnostics/AnsiDetectorTests.cs
- src/Cake.Core/Diagnostics/Console/AnsiDetector.cs
Update the `AnsiDetector` to enable the `AnsiConsoleRenderer` when Cake is running on Azure Pipelines
---
Partially closes ... #2966 (one more PR to follow)
> GH-2966: Enable AnsiConsoleRenderer when running on Azure Pipelines

- src/Cake/Cake.csproj
Tests already target `netcoreapp3.1` so changes needed there.
---
Closes #3081
> GH-3081: Add netcoreapp3.1 target to Cake

- src/Cake.Common.Tests/Unit/Build/AzurePipelines/AzurePipelinesCommandTests.cs
- src/Cake.Common/Build/AzurePipelines/AzurePipelinesCommands.cs
- src/Cake.Common/Build/AzurePipelines/IAzurePipelinesCommands.cs
There is currently no way to set a output variable in Azure DevOps, this PR adds that.
Fixes #2983
> GH-2983: Add SetOuputVariable in AzurePipelinesCommands

- src/Cake.Core.Tests/Unit/Diagnostics/CakeBuildLogTests.cs
- src/Cake.Core/Constants.cs
- src/Cake.Core/Diagnostics/Console/AnsiConsoleRenderer.cs
- src/Cake.Core/Diagnostics/Console/ConsoleColorEx.cs
- src/Cake.Core/Diagnostics/Console/ConsolePalette.cs
- src/Cake.Core/Diagnostics/Console/ConsoleRenderer.cs
> Re-opening #2984 which got closed with the deletion of the `release/1.0.0` branch
Quick fix to remove the black background color when writing messages to the console, and use the default background color instead.
It seems to work well for any dark background. For white backgrounds (e.g. TeamCity) it will require a different color palette as some messages are written using white foreground color.
---
- Closes #2852
- Relates to #2976 and #2966
> Use default background color of console when ansi

- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
- src/Cake.Common/Tools/VSTest/VSTestSettings.cs
> GH-3127: Add ResultsDirectory to VSTestSettings. (see #3127)

- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/Solution/SolutionParserTests.cs
- src/Cake.Common/Solution/SolutionParser.cs
Fixes #3143 
Should I care about Rider changing unrelated lines of code in Resources.Designer.cs?
> GH-3143: Don't try to parse empty solution file lines

- src/Cake.Common.Tests/Fixtures/Build/TeamCityFixture.cs
- src/Cake.Common.Tests/Fixtures/Build/TeamCityInfoFixture.cs
- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityBuildInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityPullRequestInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs
- src/Cake.Common/Build/BuildSystemAliases.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityEnvironmentInfo.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
Adding support in the `TeamCityBuildInfo` to load the properties XML files as a key/value data store.
Files loaded as a Lazy to prevent IO when properties are not required & to also then cache the results if subsequent queries are to properties are required.
Also exposing the teamcity branch name.
NOTE: no test of loading the XML files have been added as i am unsure about the rules/convention for this sort of test for cake.
Fixes #2967
> Add Additional Information to TeamCityBuildInfo

- src/Cake.Common.Tests/Unit/Tools/ReportGenerator/ReportGeneratorRunnerTests.cs
- src/Cake.Common/Tools/ReportGenerator/ReportGeneratorReportType.cs
> GH3125: Adds ReportGenerator missing report types

- build.cake
> GH3182: Update build to addin&modules targeting Cake 1.0

- src/Cake.Common.Tests/Cake.Common.Tests.csproj
- src/Cake.Core.Tests/Cake.Core.Tests.csproj
- src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj
- src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj
- src/Cake.Tests/Cake.Tests.csproj
> GH3193: Updates MS Test SDK dependencies to 16.9.1

- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Core.Tests/Fixtures/ToolResolutionStrategyFixture.cs
- src/Cake.Core.Tests/Unit/Tooling/ToolResolutionStrategyTests.cs
- src/Cake.Core/Extensions/CakePlatformExtensions.cs
- src/Cake.Core/Polyfill/EnvironmentHelper.cs
- src/Cake.Core/Tooling/ToolResolutionStrategy.cs
- tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
Initial idea to fix #3066 - sort tool exe names by "platform affinity"; using executable extension to identify Windows specific tools.
Specifically, tool exe names ending with `bat`, `cmd` or `exe` extensions are assumed to be Windows tools. If the detected runtime platform is also Windows then such tools will be prioritized, otherwise they will be deprioritized. In both cases their relative order will be preserved.
With this fix, tool authors won't have to deal with environmental specific hacks like https://github.com/MihaMarkic/Cake.Docker/pull/84.
> Prefer tools with platform affinity

- nuspec/Cake.CoreCLR.nuspec
- nuspec/Cake.Portable.nuspec
- nuspec/Cake.nuspec
> GH-3219: Update nuspec iconUrl in packages to use CDN URL

- src/Cake.NuGet/Client/NuGetLogger.cs
> GH3216: Remap NuGetLogger Verbose/Verbose to ICakeLog Debug/Diagnostic

- src/Cake.Common.Tests/Fixtures/Build/TeamCityInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityPullRequestInfoTests.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityEnvironmentInfo.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityPullRequestInfo.cs
This PR extends #3113 and adds a fix for #3144 to use the configuration property `vcsroot.branch` if the `GIT_BRANCH` environment variable does not exist.
I have raised this as a seperate pull request so if there is any issue/contention with the change it doesn't hold up the original PR.
This has all commits in #3113 with 1 additional commit added [3e28e0aeca739f2b7927d5a1f6409224026b687d](https://github.com/cake-build/cake/pull/3145/commits/3e28e0aeca739f2b7927d5a1f6409224026b687d)
Fixes #2967
Fixes #3144
> GH-3144: TeamCityPullRequestInfo without GIT_BRANCH

- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
Closes #3190
---
```
C:\augustoproiete\TestFrostingWorkDir>dotnet run -w C:\Temp
Context ctor C:/Temp
========================================
Hello
========================================
Hello task C:/Temp
========================================
Default
========================================
Task                          Duration
--------------------------------------------------
Hello                         00:00:00.0039034
--------------------------------------------------
Total:                        00:00:00.0045129
```
> GH-3190: Set working directory before getting the build context

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
> Related discussion: [SetPlatform for the new Arm7](https://github.com/cake-build/cake/discussions/3218)
The `MSBuildSettings` extension `SetPlatformTarget` expects a valid value from the [PlatformTarget](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/PlatformTarget/) enumeration.
This PR adds an overload which accepts a custom string.
The current workaround without this PR is to either use [`.WithProperty("Platform", "...")`](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettingsExtensions/D92C8A6A) instead of [`SetPlatformTarget`](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettingsExtensions/D9A56C8C), or use [`ArgumentCustomization`](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8)
```diff
- …
```
> GH-2314: Allow setting MSBuild Platform using custom string

- src/Cake.Core.Tests/Unit/Configuration/Parser/ConfigurationParserTests.cs
- src/Cake.Core/Configuration/Parser/ConfigurationParser.cs
This pullrequests adds basic environment variable substitution to `cake.config`, as requested in #3223 
I've used the windows syntax for environment variables, as that is what nuget does for `nuget.config`.
([See Microsoft docs on this topic](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#environment-variables-in-configuration))
The effect is that environment variable substitution will work cross-platform, but windows environment variable syntax must be used.  This might look somewhat odd in unix environments, but can be justified with the .ini syntax in cake.config 😄 
This should probably be documented somehow, but I can't find any documentation in this repo?
> Issue #3223: Adding environment variable substitution support for cake.config

- build.cake
> GH3248: Remove Cake.DotNetTool.Module from build

- src/Cake.Common/Build/IBuildSystemServiceMessageWriter.cs
- src/Cake.Core/CakeConsole.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
---
```cakescript
Task("build")
.Does(() =>
{
Information("Hello from {0}! This is written to stdout (1).", "Cake");
Error("Hello from {0}! This is written to stderr (1).", "Cake");
Information("Hello from {0}! This is written to stdout (2).", "Cake");
Error("Hello from {0}! This is written to stderr (2).", "Cake");
Information("Hello from {0}! This is written to stdout (3).", "Cake");
Error("Hello from {0}! This is written to stderr (3).", "Cake");
Information("Hello from {0}! This is written to stdout (4).", "Cake");
Error("Hello from {0}! This is written to stderr (4).", "Cake");
});
RunTarget("build");
```
---
Closes #3243
> GH-3243: Ensure expected order of writes to Console by flushing after writes

- src/Cake.Frosting.Example/Cake.Frosting.Example.csproj
- src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj
- src/Cake.Frosting/Cake.Frosting.csproj
- src/Cake.NuGet.Tests/Fixtures/NuGetContentResolverFixture.cs
- src/Cake.NuGet/Installers/InProcessInstaller.cs
- src/Cake.NuGet/NuGetContentResolver.cs
- src/Cake.Tests/Cake.Tests.csproj
- tests/integration/Cake.NuGet/InProcessInstaller.cake
- tests/integration/build.cake
Fixes #2578. Derived from PR #2576 - brought up to date with some of my own tweaks and fixed integration tests.
> GH2578: Support version ranges with NuGet in-process installer

- build.cake
- src/Cake.NuGet/Cake.NuGet.csproj
- tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake
Fixes #3316. Note: [NuGet.CommandLine](https://www.nuget.org/packages/NuGet.CommandLine/) v5.9.1 is still not available.
> Bump NuGet client libraries and command-line tool

- build.cake
- tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake
Following up from #3317; [NuGet.CommandLine](https://www.nuget.org/packages/NuGet.CommandLine/) v5.9.1 is finally available so we can use the same version everywhere.
> GH3316: Bump NuGet command-line tool

- src/Cake.Frosting.Template/Cake.Frosting.Template.csproj
- src/Cake.Frosting.Template/templates/cakefrosting/.template.config/ide.host.json
- src/Cake.Frosting.Template/templates/cakefrosting/.template.config/template.json
to make the template show up in Visual Studio "new project" dialog.
Using these changes the `Cake.Frosting` .NET CLI template will show up in Visual Studio "new project" dialog. (If [the experimental feature to show .NET CLI templates](https://devblogs.microsoft.com/dotnet/net-cli-templates-in-visual-studio/) has been activated.)
The template will show up under the "Cake" project type group. (Templates from *Cake for VS* use the same group, so they all will show up nicely together.)
This will look in VS like this:
One drawback currently is the visualization in dark mode:
Somehow the image get's distorted. I hope that's temporary (showing .NET CLI templates in VS is an experimental feature, after all...) 
fixes #3330
> #3330 changes to Cake.Frosting.Template metadata

- src/Cake/Infrastructure/Scripting/RoslynScriptSession.cs
Suppress compilation diagnostics `CS1701`, `CS1702`, and `CS1705`
---
Closes #3337
> (#3337) Suppress Roslyn compilation warnings CS1701, CS1702, and CS1705

- build.cake
- src/Cake.Common.Tests/Unit/ArgumentAliasesTests.cs
- src/Cake.Core.Tests/Unit/IO/DirectoryPathConverterTests.cs
- src/Cake.Core.Tests/Unit/IO/FilePathConverterTests.cs
- src/Cake.Core/IO/DirectoryPath.cs
- src/Cake.Core/IO/DirectoryPathConverter.cs
- src/Cake.Core/IO/FilePath.cs
- src/Cake.Core/IO/FilePathConverter.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommandSettings.cs
- src/Cake/Commands/DefaultCommandSettings.cs
- src/Cake/Program.cs
- tests/integration/Cake.Common/ArgumentAliases.cake
Add support for using `DirectoryPath` and `FilePath` types directly when reading arguments passed to the Cake build.
eg.
```csharp
var outputFolder = Argument<DirectoryPath>("outputFolder");
var logFile = Argument<FilePath>("logFile");
```
---
Closes #2168
> GH2168: Support for `DirectoryPath` and `FilePath` when reading arguments

- src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs
- src/Cake.Common/Tools/NUnit/NUnit3Runner.cs
- src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Resolves #2654.
I wasn't sure if it was better to add TestParams as its own property, or to convert the Params to the new `--testparam:key=value` syntax in NUnit v3.10+. I opted for creating a new property so that we have support for both, but am willing to change to converting the output if that's deemed better. 
As it stands, the only issue that I can see with this is that we might make it confusing to allow both, but this was allows us to support multiple versions of the runner, and lets Cake scripts migrate as they're ready (for now) without any breaking changes.
> GH2654: Add Support for TestParams flag in NUnit3

- src/Cake.Common/IO/FileCopier.cs
Fix #1663 
Added if condition to filter out the empty enumerations passed.
Not raising any errors or exceptions as confirmed on the issue discussion.
> #1663 - Fix CopyFiles when empty enumeration is passed

- src/Cake.Cli/Cake.Cli.csproj
> GH3423: Update Spectre.Console to 0.41.0

- src/Cake.Frosting.Tests/CakeHostTests.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
Hello,
I added the "target" argument back to the cake arguments in Cake.Frosting for usage.
This should fix #3291.
What's the problem?
The target argument is not passed along in `Cake.Frosting` but in the `dotnet cake tool`. The difference is the `DefaultCommandSettings` object. `Cake.Frosting` specifies a "Target" property for the parsed arguments whereas the `dotnet cake tool` does not. And by specifying this property the used arguments `IRemainingArguments` do not contain the target argument since it has been parsed successfully.
What did I do?
To add the target argument back to the `CakeArguments` I need to manually add the target into the used `ILookup<String,String>` variable with the "true" remaining arguments.
> Fixes#3291: Add target argument to cake.frosting arguments list

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildToolVersion.cs
- src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
Added override for UseToolVersion method to take in a string param also added a helper method to map said string to the correct MSBuildToolVersion enum. It's a little big since I wasn't sure on what type of string we should expect. 
https://github.com/cake-build/cake/issues/3237
This is my first time contributing to a open source project so apologies for any mistakes with the process
> setup useToolVersion override

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Closes #3449
---
I created separate commits for each property/extension to make it easier to review the PR. Happy to send individual PRs if preferred:
| Commit #                                                                                                              | Message                                                                     |
|:---------------------------------------------------------------------------------------------------------------------:| --------------------------------------------------------------------------- |
| [`4d8cfcf`](https://github.com/augustoproiete-forks/cake-build--cake/commit/4d8cfcfb17b1de70dcc21e4c7c9a41aa036a61ea) | Add **Version** to DotNetCoreMSBuildSettings & MSBuildSettings              |
| …
> Add version attributes to DotNetCoreMSBuildSettings & MSBuildSettings

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs
- src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs
Add sources .NET Core build parameter.
Close #2165
> GH-2165: Add sources attribute to DotNetCoreBuildSettings

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs
- src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs
Add sources attribute to DotNetCorePackSettings.
Close #3501
> GH-3501: Add sources attribute to DotNetCorePackSettings

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/Run/DotNetCoreRunnerTests.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreRollForward.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreSettings.cs
- src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunner.cs
Add DOTNET_ROLL_FORWARD setting to DotNetCoreSettings
Closes #3065
> GH-3065: Add DOTNET_ROLL_FORWARD setting to DotNetCoreSettings

- build.cake
- nuspec/Cake.CoreCLR.nuspec
- nuspec/Cake.nuspec
- nuspec/NuGet.org.md
- src/Cake.DotNetTool.Module/Cake.DotNetTool.Module.csproj
- src/Shared.msbuild
and added it to all packages, except Cake.Cake.DotNetTool.Module.
This first version is a copy of the current README.md with only
non-working images removed, as they won't be rendered on
NuGet.org. (Namely this was the build-status and coverage sections.)
> GH3515: added NuGet.org.md as a "readme" for NuGet.org

- src/Cake.Common.Tests/Unit/IO/Paths/ConvertableDirectoryPathTests.cs
- src/Cake.Common/IO/Paths/ConvertableDirectoryPath.cs
- tests/integration/Cake.Common/IO/DirectoryAliases.cake
> GH3352: Add DirectoryPath + ConvertableDirectoryPath operator to ConvertableDirectoryPath

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetAddSourceSettings.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                      |               | DotNet synonym                    |
| ------------------------------- |:-------------:| --------------------------------- |
| `DotNetCoreNuGetAddSource`      | :arrow_right: | :new: `DotNetNuGetAddSource`      |
| `DotNetCoreNuGetSourceSettings` | :arrow_right: | :new: `DotNetNuGetSourceSettings` |
- New `DotNetNuGetAddSource` aliases are being introduced
- `DotNetNuGetAddSource` aliases contain the code of the existing `DotNetCoreNuGetAddSource` (rename/move)
- Existing `DotNetCoreNuGetAddSource` aliases are forwarding calls to newly introduced `DotNetNuGetAddSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetAddSourceSettings` class is being introduced
- `DotNetNuGetSourceSettings` class contains the code of …
> GH3555: Add DotNetNuGetAddSource aliases (synonym to DotNetCoreNuGetAddSource

- src/Cake.Core/CakeEngine.cs
```cakescript
Task("A")
.WithCriteria(() => DateTime.Now.Second % 2 == 0, "Need even seconds")
.Does(() =>
{
Information("Hello!");
});
RunTarget("A");
```
---
Closes #3647
> GH3647: Display message of criteria when task fails to run due to criteria not being met

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetDisableSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                      |               | DotNet synonym                    |
| ------------------------------- |:-------------:| --------------------------------- |
| `DotNetCoreNuGetDisableSource`  | :arrow_right: | :new: `DotNetNuGetDisableSource`  |
| `DotNetCoreNuGetSourceSettings` | :arrow_right: | :new: `DotNetNuGetSourceSettings` |
- New `DotNetNuGetDisableSource` aliases are being introduced
- `DotNetNuGetDisableSource` aliases contain the code of the existing `DotNetCoreNuGetDisableSource` (rename/move)
- Existing `DotNetCoreNuGetDisableSource` aliases are forwarding calls to newly introduced `DotNetNuGetDisableSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetDisableSourceSettings` class is being introduced
- `DotNetNuGetSourceSettings` class contains …
> GH3639: Add DotNetNuGetDisableSource aliases (synonym to DotNetCoreNuGetDisableSource)

- build/version.cake
- src/Cake.Common.Tests/Fixtures/Build/AzurePipelinesFixture.cs
- src/Cake.Common.Tests/Unit/Build/AzurePipelines/AzurePipelinesProviderTests.cs
- src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs
- src/Cake.Common/Build/AzurePipelines/AzurePipelinesProvider.cs
- src/Cake.Common/Build/AzurePipelines/Data/AzurePipelinesAgentInfo.cs
- src/Cake.Common/Build/AzurePipelines/IAzurePipelinesProvider.cs
- src/Cake.Common/Build/BuildProvider.cs
- src/Cake.Common/Build/BuildSystem.cs
- src/Cake.sln
Change IsRunningOnAzurePipelines to only check if it is running on Azure Pipelines and ignoring the type of the agent to be consistent with other build providers.
This PR introduces some breaking changes to clean up the Azure Pipelines build provider:
- `IAzurePipelinesProvider.IsRunningOnAzurePipelines` only checks if running on Azure Pipelines and ignores type of agent
- `IAzurePipelinesProvider.IsRunningOnAzurePipelinesHosted` removed. `AzurePipelinesAgentInfo.IsHosted` can be used instead
- `BuildSystem.IsRunningOnAzurePipelines` only checks if running on Azure Pipelines and ignores type of agent
- `BuildSystem.IsRunningOnAzurePipelinesHosted` removed
- `BuildProvider.AzurePipelinesHosted` enum value removed
See also discussion https://github.com/cake-build/cake/discussions/3589
Fixes …
> (GH-3654) Change IsRunningOnAzurePipelines to ignore agent type

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetEnableSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                      |               | DotNet synonym                          |
| ------------------------------- |:-------------:| --------------------------------------- |
| `DotNetCoreNuGetEnableSource`   | :arrow_right: | :new: `DotNetNuGetEnableSource`         |
|                                 | :arrow_right: | :new: `DotNetNuGetEnableSourceSettings` |
- New `DotNetNuGetEnableSource` aliases are being introduced
- `DotNetNuGetEnableSource` aliases contain the code of the existing `DotNetCoreNuGetEnableSource` (rename/move)
- Existing `DotNetCoreNuGetEnableSource` aliases are forwarding calls to newly introduced `DotNetNuGetEnableSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetEnableSourceSettings` class is being introduced
- …
> GH3640: Add DotNetNuGetEnableSource aliases (synonym to DotNetCoreNuGetEnableSource)

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetHasSourceSettings.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetListSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                 |               | DotNet synonym                        |
| -------------------------- |:-------------:| ------------------------------------- |
| `DotNetCoreNuGetHasSource` | :arrow_right: | :new: `DotNetNuGetHasSource`          |
|                            | :arrow_right: | :new: `DotNetNuGetHasSourceSettings`  |
|                            | :arrow_right: | :new: `DotNetNuGetListSourceSettings` |
- New `DotNetNuGetHasSource` aliases are being introduced
- `DotNetNuGetHasSource` aliases contain the code of the existing `DotNetCoreNuGetHasSource` (rename/move)
- Existing `DotNetCoreNuGetHasSource` aliases are forwarding calls to newly introduced `DotNetNuGetHasSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetHasSourceSettings` class is …
> GH3641: Add DotNetNuGetHasSource aliases (synonym to DotNetCoreNuGetHasSource)

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetRemoveSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                    |               | DotNet synonym                          |
| ----------------------------- |:-------------:| --------------------------------------- |
| `DotNetCoreNuGetRemoveSource` | :arrow_right: | :new: `DotNetNuGetRemoveSource`         |
|                               | :arrow_right: | :new: `DotNetNuGetRemoveSourceSettings` |
- New `DotNetNuGetRemoveSource` aliases are being introduced
- `DotNetNuGetRemoveSource` aliases contain the code of the existing `DotNetCoreNuGetRemoveSource` (rename/move)
- Existing `DotNetCoreNuGetRemoveSource` aliases are forwarding calls to newly introduced `DotNetNuGetRemoveSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetRemoveSourceSettings` class is being introduced
- `DotNetNuGetSourceSettings` class …
> GH3643: Add DotNetNuGetRemoveSource aliases (synonym to DotNetCoreNuGetRemoveSource)

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/NuGet/Source/DotNetNuGetUpdateSourceSettings.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
- src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
| DotNetCore                    |               | DotNet synonym                          |
| ----------------------------- |:-------------:| --------------------------------------- |
| `DotNetCoreNuGetUpdateSource` | :arrow_right: | :new: `DotNetNuGetUpdateSource`         |
|                               | :arrow_right: | :new: `DotNetNuGetUpdateSourceSettings` |
- New `DotNetNuGetUpdateSource` aliases are being introduced
- `DotNetNuGetUpdateSource` aliases contain the code of the existing `DotNetCoreNuGetUpdateSource` (rename/move)
- Existing `DotNetCoreNuGetUpdateSource` aliases are forwarding calls to newly introduced `DotNetNuGetUpdateSource` aliases
- New `DotNetNuGetSourceSettings` and `DotNetNuGetUpdateSourceSettings` class is being introduced
- `DotNetNuGetSourceSettings` class …
> GH3644: Add DotNetNuGetUpdateSource aliases (synonym to DotNetCoreNuGetUpdateSource)

- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
Matches [official docs on `dotnet restore`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#arguments) as of this writing:
---
Closes #1111
> GH1111: Update DotNetRestore alias XML Docs to match official docs

- src/Cake.Common/Tools/DotNet/Build/DotNetBuildSettings.cs
- src/Cake.Common/Tools/DotNet/Clean/DotNetCleanSettings.cs
- src/Cake.Common/Tools/DotNet/Pack/DotNetPackSettings.cs
- src/Cake.Common/Tools/DotNet/Publish/DotNetPublishSettings.cs
- src/Cake.Common/Tools/DotNet/Restore/DotNetRestoreSettings.cs
Closes https://github.com/cake-build/cake/issues/3683
> GH3683: Use DotNetMSBuildSettings instead of DotNetCoreMSBuildSettings on new dotnet aliases settings

- src/Cake.Common.Tests/Unit/SemVerTests.cs
- src/Cake.Common/SemanticVersion.cs
* Adds SemanticVersion equals operator
* Adds SemanticVersion not equals operator
* Fixes PreRelease sorted as newer than non PreRelease
* Adds SemanticVersion tests
* Fixes #3711
> GH3711: Fix SemanticVersion missing operators & comparer

- src/Cake.Core.Tests/Fixtures/ScriptRunnerFixture.cs
- src/Cake.Core/Scripting/IReferenceAssemblyResolver.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake/Cake.csproj
- src/Cake/Infrastructure/ContainerConfigurator.cs
- src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs
* .NET 6.0 - Basic.Reference.Assemblies.Net60
* .NET 5.0 - Basic.Reference.Assemblies.Net50
* .NET Core 3.1 - Basic.Reference.Assemblies.NetCoreApp31
* fixes #3714
> GH3714: Use Basic.Reference.Assemblies.* to ensure all reference assemblies are loaded

- build.cake
- build/parameters.cake
(_depends on updating the Cake.Tool to the next release of Cake that ships https://github.com/cake-build/cake/issues/3683 in order to use `DotNetMSBuildSettings`_)
---
Closes #3685
> GH3685: Update build to use new dotnet aliases

- src/Cake.Core/Scripting/ScriptProcessor.cs
> GH3733: Show relative path of addin assemblies that are being loaded

- src/Cake.Cli/Cake.Cli.csproj
> GH3760: Update Spectre.Console to 0.43.0

- src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsRunnerInfoTests.cs
- src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsWorkflowInfoTests.cs
- src/Cake.Common/Build/GitHubActions/Data/GitHubActionsArchitecture.cs
- src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRefType.cs
- src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRunnerInfo.cs
- src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs
- tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake
> GH3764: Add missing GitHub Actions properties

- src/Cake.Common.Tests/Fixtures/Tools/MSTestRunnerFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/VSTestRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSTest/MSTestRunner.cs
- src/Cake.Common/Tools/MSTest/MSTestSettings.cs
- src/Cake.Common/Tools/VSTest/VSTestRunner.cs
- src/Cake.Common/Tools/VSTest/VSTestSettings.cs
- src/Cake.Common/Tools/VisualStudio.cs
This also synchronized the behavior between `MSTest`, `VSTest` and `MSBuild`:
* All are now searching in the VS 2022 installation
* All are now searching the *BuildTools* edition
* All have a setting `AllowPreviewVersion` that, if set to `true` enables searching the *Preview* edition.
fixes #3772
> Added VS2022 to MSTest, VSTest

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common.Tests/Unit/Tools/VSTest/VSTestRunnerTests.cs
- src/Cake.Common/Tools/VisualStudio.cs
Contrary to all other VS2022 editions, VS2022 *BuildTools* is installed under `ProgramFiles (x86)`.
fixes #3794
> (#3794) fix detection of VS2022 BuildTools

- src/Cake.Common.Tests/Properties/Resources.Designer.cs
- src/Cake.Common.Tests/Properties/Resources.resx
- src/Cake.Common.Tests/Unit/XML/XmlTransformationTests.cs
- src/Cake.Common/Polyfill/XmlTransformationHelper.cs
- src/Cake.Common/Xml/XmlTransformation.cs
- src/Cake.Common/Xml/XmlTransformationSettings.cs
fixes #2524
I added two overloaded XmlTransform methods that accept XsltArgumentList as arguments for XSL tranformation.  Also new unit tests were added - I tried to use existing input/output sample data as much as possible so there are only two new XSL definitions (with arguments) needed.
> GH2524: Added support for XSL arguments in XmlTransform

- src/Cake.Common.Tests/Fixtures/Tools/Chocolatey/Export/ChocolateyExportFixture.cs
- src/Cake.Common.Tests/Unit/Tools/Chocolatey/Export/ChocolateyExporterTests.cs
- src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs
- src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporter.cs
- src/Cake.Common/Tools/Chocolatey/Export/ChocolateyExporterSettings.cs
- tests/integration/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cake
- tests/integration/build.cake
This command was added in 0.11.0 of Chocolatey, providing the ability
for a user to export a file that contains information about all the
currently installed Chocolatey packages on a machine.
This information can be useful, therefore creating a Cake alias to
support it makes sense.
Fixes #3771
> GH3771: Add support for Chocolatey Export Command

- GitReleaseManager.yaml
Closes https://github.com/cake-build/cake/issues/3819
ps: Frosting was never included in the automated comments, but can take the opportunity to also include it if some of you think it's a good idea.
> GH3819: Update GitReleaseManager comment template to remove Cake NuGet package and Chocolatey portable

- src/Cake.Cli/Cake.Cli.csproj
> GH3854: Update Spectre.Console to 0.44.0

- src/Cake/Commands/DefaultCommandSettings.cs
- src/Cake/Infrastructure/CakeConfigurationExtensions.cs
- src/Cake/Infrastructure/Constants.cs
- src/Cake/Infrastructure/IScriptHostSettings.cs
- src/Cake/Infrastructure/Scripting/RoslynScriptSession.cs
- src/Cake/Infrastructure/Utilities/FastHash.cs
- tests/integration/Cake/ScriptCache.cake
- tests/integration/build.cake
- tests/integration/resources/Cake/ScriptCache/build.cake
This pull request is what started RFC-02.  At the time I was not able to submit a pull request for the changes.
**Differences from RFC-02**
1. The cache argument was removed.  A new section was added to the cake.config file [Cache] with 2 possible properties Enabled and Path.  Enabled defaults to false and Path defaults cache under the tools folder.
2. I originally used a time stamp to determine if the cache was valid or not.  This worked for the way I was using Cake but would not work for all cases.  I have changed this to use a hash like pull request 2584 used.  I did change it to use SHA1CryptoServiceProvider instead of MD5 since MD5 is not FIPS compliant.
I have been using several versions of Cake with this  applied and have had no issues.
@mholo65 posted this in the RFC Comments …
> GH2099: Cache compiled script on disk

- src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs
- src/Cake.Core.Tests/Unit/IO/PathCollapserTests.cs
- src/Cake.Core/IO/DirectoryPath.cs
- src/Cake.Core/IO/PathCollapser.cs
- src/Cake.Testing.Xunit/NonWindowsFactAttribute.cs
- src/Cake.Testing.Xunit/PlatformRestrictedFactAttribute.cs
Especially different calculations of the root of a path
for windows, non-windows and UNC like paths.
To this end, I re-structured the unit test. There were no test
removed that previously existed, but only new tests added.
Also, instead of joining together the path with one specific
separator ('/'), I re-used the existing separator of the original
path. (This was the main-fix for #3859.)
> (#3858, #3859) Made PathCollapser aware of different formats

- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
Currently, if you try to apply multiple (case-sensitive) filters (with same-ish values) in your cake script like this:
```cake
var coverageInclusionFilters = new List<string>
{
"+[ModuleName*]*",
"+[moduleName*]*"
};
var openCoverSettings = new OpenCoverSettings();
//rest of the code omitted for clarity
for(var inclusionFilter in coverageInclusionFilters)
{
openCoverSettings.WithFilter(inclusionFilter);
}
```
It produces this kind of a filter argument value:
```ps
-filter:"+[ModuleName*]*" 
```
containing only the first one from the coverageInclusionFilters list from the code above.
As per https://github.com/opencover/opencover/wiki/Usage#understanding-filters
OpenCover filters are case-sensitive. 
This change enables you to apply those kind of filter values.
> GH3878: Adds support for case sensitive OpenCover filters

- src/Cake.Cli/Features/InfoFeature.cs
- src/Cake.Tests/Unit/Features/InfoFeatureTests.cs
- src/Cake.Tests/Unit/Features/VersionFeatureTests.cs
Just noticed that one of the features had a null check but no tests associated. And that there was another feature that did not have that null check so added that with an associated check.
Closes #3894
> Add null check in InfoFeature

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersion.cs
- src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
> (#3916) added ShortSha to the output

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Uninstall/DotNetWorkloadUninstallerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Uninstall/DotNetWorkloadUninstallTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Workload/Uninstall/DotNetWorkloadUninstallSettings.cs
- src/Cake.Common/Tools/DotNet/Workload/Uninstall/DotNetWorkloadUninstaller.cs
Add an alias for `dotnet workload uninstall` command
Fixes #3486
There is nothing to uninstall on the build servers, what integration test I should add here: https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake
- Install any workload in "Cake.Common.Tools.DotNetCore.DotNetCoreAliases.Setup"
- Add "Cake.Common.Tools.DotNetCore.DotNetCoreAliases.DotNetWorkloadInstall" and "Cake.Common.Tools.DotNetCore.DotNetCoreAliases.DotNetWorkloadUninstall" as dependent on the "DotNetWorkloadInstall"
- DotNetWorkloadUninstall("any") with try...catch
- Skip for now
Please review
> Add alias for dotnet workload uninstall command

- src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardErrorFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardOutFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/Command/CommandRunnerStandardOutputFixtureExtentions.cs
- src/Cake.Common.Tests/Unit/Tools/Command/CommandRunnerTests.cs
- src/Cake.Common/Tools/Command/CommandAliases.cs
- src/Cake.Common/Tools/Command/CommandRunner.cs
- src/Cake.Common/Tools/Command/CommandSettings.cs
- src/Cake.Common/Tools/Command/CommandSettingsExtensions.cs
- src/Cake.Core.Tests/Unit/Tooling/ToolSettingsExtensionsTests.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake.Core/Tooling/ToolSettingsExtensions.cs
- tests/integration/Cake.Common/Tools/Command/CommandAliases.cake
- tests/integration/build.cake
* fixes #3947 by adding new command aliases 
Command aliases in this PR are between StartProcess and the out-of-the-box typed aliases, it lets you benefit from Cake's built-in tool resolution making it easier to support tools with different executables i.e. Posix/Windows or installed using tool directive. It will default fail the build on non-zero exit codes, providing more convenient access to standard output/error.
Intentionally didn't seal `CommandSettings` as one possibly could create one's own typed settings with defaults for reuse.
Settings class in general makes it easier to reuse a tool across tasks, but there are also alias variants that just take the tool executable names.
PR also adds some ToolSettings Extensions, making it easier to work with tool settings in customization …
> GH3947: Add Command aliases

- src/Cake.Core/CakeTaskBuilder.cs
This small PR changes the constructor of CakeTaskBuilder to public in order to improve the cake extensibility.
Fixes #2591
> Make CakeTaskBuilder ctor public

- src/Cake.Core/CakeEngineActions.cs
This small PR makes the CakeEngineActions public in order to use it in a custom engine.
Fixes #3956
> Make CakeEngineActions public

- src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildPropertyExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
**Changes:**
1.  The arguments of the properties specified in the `_propertiesNotEscapeSemicolons` HashSet will not escape semicolons.
_Example_: `WithProperty("DefineConstants", "A=a;B=b");` will generate `/p:DefineConstants=A=a;B=b`
2.  If more than one property argument is passed to `WithProperty()`, the argument parameters will be concatenated using a semicolon:
_Example_: `WithProperty("C", "A=a", "B=b");` will generate `/p:C=A=a;B=b`
**Current list of properties that will not escape semicolons:**
- `DefineConstants`
- `ExcludeFilesFromDeployment`
**Notes**
If these changes are not quite what you had in mind -- or if there are any other issues, please let me know and I will do my best to amend them.
> GH1852: Incorrect escaping of semicolon in property values for msbuild

- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
Regarding the following (incomplete) PR which is now over 6 months old, https://github.com/cake-build/cake/pull/3721, I have rebased @sbwaggoner's original changes on to an up-to-date `develop` branch and made the change recommended by @devlead on 15 December 2021 during the PR review. Several unit tests have also been added to increase the code coverage of this area too.
Regarding the conditional StringSplitOptions approach recommended in the review, I tried implementing it as suggested but given .Net Core 3.1 StringSplitOptions enum doesn't include the StringSplitOptions.TrimEntries option, trimming still needed to be implemented manually in the code for that target framework. So the conditional compile logic didn't end up offering any benefit imho.
> GH2953: Feature addition target initializer msbuildsettings

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/List/DotNetWorkloadListerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/List/DotNetWorkloadListTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Workload/List/DotNetWorkloadListItem.cs
- src/Cake.Common/Tools/DotNet/Workload/List/DotNetWorkloadListSettings.cs
- src/Cake.Common/Tools/DotNet/Workload/List/DotNetWorkloadLister.cs
Add an alias for `dotnet workload list` command
Fixes #3482
When there are no workloads
Where there are workloads
Please review
> Add alias for dotnet workload list command

- src/Cake/Cake.csproj
> GH3970: Update Basic.Reference.Assemblies.* to 1.3.0

- GitVersion.yml
- src/Cake.Core/Constants.cs
There are upcoming breaking changes in Cake, so we need to start building version 3.0.0, rather than 2.4.0.
> (build) Set next version to 3.0.0

- .github/workflows/build.yml
- build.cake
- global.json
- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake/Cake.csproj
- src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs
- src/Shared.msbuild
- tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake
- tests/integration/Cake.Core/Scripting/AddinDirective.cake
- tests/integration/Cake.Core/Scripting/DefineDirective.cake
- tests/integration/Cake.Frosting/build/Build.csproj
> GH3950: Add .NET 7 Support

- src/Cake.Common.Tests/Unit/Tools/DotNet/Test/DotNetTesterTests.cs
- src/Cake.Common/Tools/DotNet/Test/DotNetTestSettings.cs
- src/Cake.Common/Tools/DotNet/Test/DotNetTester.cs
> GH3997: Remove obsolete DotNetTestSettings Logger property

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersion.cs
- src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
Newer versions of GitVersion include a number of additional asserted pieces of information, including EscapedBranchName. All of the missing information has now been included in the GitVersion classes.
Fixes #3124
> GH3124: Add missing asserted GitVersion info

- src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs
- src/Cake.Common/Tools/GitVersion/GitVersionOutput.cs
- src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
- src/Cake.Common/Tools/GitVersion/GitVersionSettings.cs
Since the initial implementation in Cake, there are a number of new command line options for GitVersion. While it is possible to set these using ArgumentCustomization, these should be supported directly within the Cake settings class.
Fixes #4006
> GH4006: Add missing GitVersion CLI options

- src/Cake.Common.Tests/Fixtures/Build/GitHubActionsCommandsFixture.cs
- src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/GitHubActions/Commands/GitHubActionsCommandsTests.cs
- src/Cake.Common/Build/GitHubActions/Commands/GitHubActionsCommands.cs
- src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRuntimeInfo.cs
- tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake
This commit adds a new SetStepSummary method, which can be used to write markdown content to known location, which will then mean that the summary is shown for the overall workflow.
Fixes #4011
> GH4011: Add SetStepSummary method to GH Provider

- src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs
- src/Cake.Common/Build/TeamCity/TeamCityProvider.cs
* Add function which sends the the build statistic servie message to TeamCity
* Add function to build status message with status to TeamCity (Append to existing, Prepend, or replace)
Fix: #4018
Fix: #4019
> TeamCity Messages Enhancements

- src/Cake.Cli/Cake.Cli.csproj
> GH3969: Update Spectre.Console to 0.45.0

- src/Cake.Common/Tools/DotNet/Run/DotNetRunSettings.cs
- src/Cake.Common/Tools/DotNet/Run/DotNetRunner.cs
> GH4038: Adds MSBuildSettings to DotNetRunSettings

- src/Cake.Common.Tests/Unit/Tools/ILMerge/ILMergeRunnerTests.cs
- src/Cake.Common/Tools/ILMerge/ILMergeRunner.cs
- src/Cake.Common/Tools/ILMerge/ILMergeSettings.cs
Using the documentation available here:
https://github.com/dotnet/ILMerge/blob/master/ilmerge-manual.md
added the missing settings that can be set when calling ilmerge.exe
Fixes #4032
> GH4032: Add missing ILMergeSettings

- src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs
- src/Cake.Core/CakeTaskBuilder.Dependencies.cs
This PR adds a new overload for `IsDependeeOf` that accepts a `CakeTaskBuilder`, same as the overload for `IsDependentOn`
Fixes https://github.com/cake-build/cake/issues/4044
> GH4044: Adds overload for IsDependeeOf with CakeTaskBuilder

- src/Cake.Cli/Hosts/BuildScriptHost.cs
- src/Cake.Cli/Hosts/DescriptionScriptHost.cs
- src/Cake.Cli/Hosts/DryRunScriptHost.cs
- src/Cake.Cli/Hosts/TreeScriptHost.cs
- src/Cake.Core.Tests/Fixtures/ScriptHostFixture.cs
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core.Tests/Unit/ExecutionSettingsTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/ExecutionSettings.cs
- src/Cake.Core/Scripting/IScriptHost.cs
- src/Cake.Core/Scripting/ScriptHost.cs
- tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
- tests/integration/resources/Cake.Common/Tools/Cake/targets.cake
This PR fully implements #2470, 'Call multiple tasks from CLI and pass them to RunTarget'
Significant unit test coverage has been added for the changes, including minor refactoring and improvements to the existing codebase when encountered.
Significant effort was undertaken to ensure the changes introduced in this PR maintained backward compatibility.
Given the following cake build script, 
```
var targets = Arguments<string>("target", "A");
Task("A");
Task("B");
Task("C");
RunTargets(targets);
```
This PR extends Cake to operate as follows:
> GH2470: call multiple tasks from cli and pass them to run target

- src/Cake.Cli/Infrastructure/CakeSpectreReportPrinter.cs
- src/Cake.Cli/Infrastructure/DoubleBorder.cs
- src/Cake.Cli/Infrastructure/SingleBorder.cs
- src/Cake.Core.Tests/Fixtures/CakeEngineFixture.cs
- src/Cake.Core.Tests/Unit/CakeReportTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeReport.cs
- src/Cake.Core/CakeReportEntry.cs
- src/Cake.Core/CakeReportPrinter.cs
- src/Cake.Core/CakeTaskCriteria.cs
- src/Cake.Core/DefaultExecutionStrategy.cs
- src/Cake.Core/ICakeReportPrinter.cs
- src/Cake.DotNetTool.Module.Tests/DotNetToolPackageInstallerFixture.cs
- src/Cake.DotNetTool.Module.Tests/DotNetToolPackageInstallerTests.cs
- src/Cake/Infrastructure/Constants.cs
- src/Cake/Infrastructure/ContainerConfigurator.cs
Via a new setting, --Settings_UseSpectreConsoleForConsoleOutput, it is
now possible to output the task headers, and task summary using
Spectre.Console.  This allows for the easy addition of a new column in
the task summary, which includes information about _why_ any given task
has been skipped.
The old CakeReportPrinter is still in play, but some implementation has
been moved from within the DefaultExecutionStrategy to the reporter
class.  Depending on the setting mentioned above, either the
Spectre.Console version of the reporter will be added to the IoC
container, or the old version will be in place.
Fixes #4055
> GH4055: Add task skip reason to task summary output

- src/Cake.Common.Tests/Fixtures/IO/FileSystemFixture.cs
- src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs
- src/Cake.Common/IO/CleanDirectorySettings.cs
- src/Cake.Common/IO/DirectoryAliases.cs
- src/Cake.Common/IO/DirectoryCleaner.cs
This PR successfully addresses #1317, 'CleanDirectory does not clean readonly files.'
I have familarised myself with #1574 when making this change (as @bjorkstromm mentioned) and in a similar manner, introduced a `CleanDirectorySettings` class which has a `Force` flag that defaults to false, but when enabled, will ensure the `DirectoryCleaner` will force clean readonly files.
I avoided making this a breaking change by creating overloads of the `DirectoryCleaner` methods that take an additional `CleanDirectorySettings` parameter, and did the same for the various `DirectoryAliases` methods. 
If it was, however, decided that every clean method should take a settings parameter, we can keep the overloaded methods and simply remove the initial methods that didn't accept …
> Ability to force clean readonly files

- src/Cake.Frosting.Tests/CakeHostTests.cs
- src/Cake.Frosting.Tests/Tasks/DummyTask2.cs
- src/Cake.Frosting.Tests/Tasks/DummyTask3.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommandSettings.cs
- src/Cake.Frosting/Internal/FrostingEngine.cs
Fixes issue #4122 which was introduced/not considered by PR #4054
> GH-4122: Make multiple arguments available in Frosting

- src/Cake.Cli/Cake.Cli.csproj
- src/Cake.Frosting/CakeHost.cs
- src/Cake/Program.cs
- tests/integration/Cake.Core/Scripting/SpectreConsole.cake
This PR upgrades spectre.console from 0.45.0 to 0.46.0 (latest) by upgrading the NuGet package reference, and the subsequent minor build issue introduced (see: https://github.com/cake-build/cake/issues/4138) has been fixed by a trivial code change.
**Background:** my interest in upgrading to the latest spectre.console is in anticipation of being able to fix this cake issue, https://github.com/cake-build/cake/issues/3279. The necessary change to spectre.console has been made and committed ([714cf179cb349597a8b775287ac8299584b18617](https://github.com/spectreconsole/spectre.console/commit/714cf179cb349597a8b775287ac8299584b18617)), although it does not reside in the 0.46.0 release and is scheduled for 0.47.0. Either way, I wanted to upgrade the version of spectre.console used by cake to the …
> Upgrade Spectre.Console to v0.46.0

- src/Cake.Core/CakeEnvironment.cs
- src/Cake.Core/ICakeEnvironment.cs
- src/Cake.Core/IO/SpecialPath.cs
- src/Cake.Core/Polyfill/SpecialPathHelper.cs
- src/Cake.Testing/FakeEnvironment.cs
> GH-4092: Add support for Environment.UserHomeDirectory

- src/Cake.Common.Tests/Unit/Tools/DotNet/Restore/DotNetRestorerTests.cs
- src/Cake.Common/Tools/DotNet/Restore/DotNetRestoreSettings.cs
- src/Cake.Common/Tools/DotNet/Restore/DotNetRestorer.cs
> GH-4109: Add PublishReadyToRun to DotNetRestoreSettings

- src/Cake.Common.Tests/Unit/Tools/DotNet/Publish/DotNetPublisherTests.cs
- src/Cake.Common/Tools/DotNet/Publish/DotNetPublishSettings.cs
- src/Cake.Common/Tools/DotNet/Publish/DotNetPublisher.cs
Add `--os <OS>` to [dotnet-publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
Fixes #4107
Please review.
> GH-4107: Add OS to DotNetPublishSettings

- global.json
- src/Cake.NuGet/Cake.NuGet.csproj
Fixes #4170 and #4171 dependencies that need to be updated together for a successful build.
Replaces #4166 & #4167
> GH4170/4171: Update NuGet.* to v6.6.1 & .NET SDK to 7.0.305

- SECURITY.md
Following [Cake Support Lifecycle](https://cakebuild.net/docs/getting-started/lifecycle) Cake 2.x is now out of support
> Mark Cake 2.x as out of suppport

- src/Cake.Common.Tests/Unit/Tools/DotNet/MSBuild/DotNetMSBuildBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/MSBuild/DotNetMSBuildSettingsExtensionsTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/MSBuild/DotNetMSBuildSettingsTests.cs
- src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs
- src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettingsExtensions.cs
- src/Cake.Common/Tools/DotNet/MSBuild/MSBuildArgumentBuilderExtensions.cs
Add NodeReuse property to DotNetMSBuildSettings and tests
Fixes #4144 
Please review,
> Add NodeReuse property to DotNetMSBuildSettings

- src/Cake.Common.Tests/Unit/Build/AzurePipelines/AzurePipelinesCommandTests.cs
- src/Cake.Common/Build/AzurePipelines/AzurePipelinesCommands.cs
- src/Cake.Common/Build/AzurePipelines/AzurePipelinesDisposableExtensions.cs
- src/Cake.Common/Build/AzurePipelines/IAzurePipelinesCommands.cs
- src/Cake.Frosting.Template/templates/cakefrosting/build/Build.csproj
- tests/integration/Cake.Common/Build/AzurePipelines/AzurePipelinesProvider.cake
- tests/integration/Cake.Common/Build/BuildSystemAliases.cake
Add Azure Logging Command to create collapsible groups. See: 
[MSDocs: Logging commands -> Formatting commands](https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands)
There were some changes in other logging commands as well. This is because they contain redundant whitespaces, which ADO does tolerate sometimes, but not always, as is the case for the `##[group]` command. It is better to avoid them if possible.
> Add Azure Pipelines group logging commands

- src/Cake.Core.Tests/Unit/IO/FileExtensionsTests.cs
- src/Cake.Core/IO/FileExtensions.cs
Context: https://github.com/cake-build/cake/issues/3996
Added filetype/extension check.
Error experienced:
```
Error: Bad IL format. 
The format of the file 
'/Users/runner/work/1/s/tools/Addins/runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple.4.3.0/runtimes/osx.10.10-x64/native/System.Security.Cryptography.Native.Apple.dylib' 
is invalid. 
An error occurred when executing task Error: .NET CLI: Process returned an error (exit code 1)
```
The error was experienced at intermittent intervals in CI (and local, but not so often) builds for 2 repos:
https://github.com/xamarin/AndroidX
https://github.com/xamarin/GooglePlayServicesComponents
In last few weeks, alsmost all builds fail regularly.
https://github.com/xamarin/GooglePlayServicesComponents/pull/801
> File type check on macosx (if file is "dylib")

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Package/Add/DotNetPackageAdderFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Add/DotNetPackageAdderTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Package/Add/DotNetPackageAddSettings.cs
- src/Cake.Common/Tools/DotNet/Package/Add/DotNetPackageAdder.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for dotnet add package command
Fixes #4187 
Please review
> Add DotNetAddPackage alias for dotnet add package command

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Package/Remove/DotNetPackageRemoverFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Add/DotNetPackageAdderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Remove/DotNetPackageRemoverTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Package/Remove/DotNetPackageRemoveSettings.cs
- src/Cake.Common/Tools/DotNet/Package/Remove/DotNetPackageRemover.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet remove package` command
Fixes #4225
Please review
> Add DotNetRemovePackage alias for dotnet remove package command

- src/Cake.Cli/Cake.Cli.csproj
- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
- src/Cake.Tests/Fixtures/BuildFeatureFixture.cs
- src/Cake.Tests/Unit/ProgramTests.cs
- src/Cake.Tests/Utilities/TestContainerConfigurator.cs
- src/Cake/Commands/DefaultCommand.cs
- src/Cake/Features/Bootstrapping/BootstrapFeature.cs
- src/Cake/Features/Building/BuildFeature.cs
- src/Cake/Features/CakeFeature.cs
- src/Cake/Infrastructure/ContainerConfigurator.cs
- src/Cake/Infrastructure/IContainerConfigurator.cs
This PR fully addresses https://github.com/cake-build/cake/issues/4157, which was preventing spectre.console from being upgraded to 0.47.0. The PR also includes the actual upgrade to spectre.console 0.47.0
The approach taken is very similar to a previous Cake.Frosting issue, which has already been fixed: https://github.com/cake-build/cake/issues/3291 
This PR follows the same pattern introduced for the fix, which was located in Cake.Frosting.Internal.DefaultCommand, here: https://github.com/cake-build/cake/blob/c3cd2af8d73b4f270d6abe585c41f049ea92a0d7/src/Cake.Frosting/Internal/Commands/DefaultCommand.cs#L82
Within Cake proper (rather than Cake.Frosting)... Cake.Commands.DefaultCommand.Execute(...) has been modified to explicitly create the CakeArguments from CommandContext.Remaining, …
> Upgrade spectre.console to 0.47.0, modifying the Cake codebase to fix a breaking change this new version includes

- src/Cake.Core/IO/File.cs
- src/Cake.Core/IO/IFile.cs
- src/Cake.Testing/FakeFile.cs
> GH-4132: Add File APIs for setting timestamps (creation time, last write time, last access time)

- .github/workflows/build.yml
- GitVersion.yml
- build.cake
- global.json
- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake.Frosting.Template/Cake.Frosting.Template.csproj
- src/Cake.Frosting.Template/templates/cakefrosting/.template.config/template.json
- src/Cake/Cake.csproj
- src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs
- src/Shared.msbuild
- tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake
- tests/integration/Cake.Common/Tools/Command/CommandAliases.cake
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
- tests/integration/Cake.Core/Scripting/AddinDirective.cake
- tests/integration/Cake.Core/Scripting/DefineDirective.cake
- tests/integration/Cake.Frosting/build/Build.csproj
- tests/integration/resources/Cake.Common/Tools/DotNet/hwapp.tests/hwapp.tests.csproj
- tests/integration/resources/Cake.Common/Tools/DotNet/hwapp/hwapp.csproj
* fixes #4252
Known issues so far
> GH4252: Update .NET SDK to 8.0.100

- src/Cake.Common/IO/ZipAliases.cs
- src/Cake.Common/IO/Zipper.cs
> GH4260: Unzip alias should support overwrite files

- SECURITY.md
Following [Cake Support Lifecycle](https://cakebuild.net/docs/getting-started/lifecycle) Cake 3.x is now out of support
> Mark Cake 3.x as out of support

- .github/workflows/build.yml
- src/Cake.Cli/Cake.Cli.csproj
- src/Cake/Commands/DefaultCommand.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
- tests/integration/Cake.Core/Scripting/AddinDirective.cake
> GH4278: Update Spectre.Console to 0.49.1

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Package/Search/DotNetPackageSearcherFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Search/DotNetPackageSearchSettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Search/DotNetPackageSearcherTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Package/Search/DotNetPackageSearchItem.cs
- src/Cake.Common/Tools/DotNet/Package/Search/DotNetPackageSearchSettings.cs
- src/Cake.Common/Tools/DotNet/Package/Search/DotNetPackageSearcher.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
The [(NuGet CLI) commands](https://learn.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference) [list](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-list) and [search](https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-search) do not exist in `dotnet nuget`.
This PR introduces `DotNetSearchPackage` that uses [`dotnet package search`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-package-search) as an alternative to [`NuGetList`](https://cakebuild.net/dsl/nuget/#List) for environments that do not have `nuget.exe` but have `dotnet.exe`.
> Add .NET package search to Cake scripts

- src/Cake.Core/IO/PathHelper.cs
This PR removes the check for the currently running platform/OS before checking whether the path is a windows path, beginning with a drive letter.
fixes #4322 
Rationale:
I feel `Path` should be a very agnostic "thing" and `C:\temp\` should be a valid (and "absolute") path on any system, even if, if I were to use it on my linux system, it would simply not work. (Probably it would, somehow, but that's besides my point.)
My guess is, that while this is not a breaking change in API/ABI, it is a breaking change in "meaning" - even if I think most likely no-one is relying on the fact that currently `C:\temp` is an absolute path, if cake is running on a windows system and a relative path if cake is not running on a windows system.
> (#4322) Removed check for OS on PathHelper.IsRooted

- src/Cake.Common.Tests/Unit/Tools/ReportGenerator/ReportGeneratorRunnerTests.cs
- src/Cake.Common/Tools/ReportGenerator/ReportGeneratorReportType.cs
Add ReportGenerator missing markdown report types.
- MarkdownSummary (5.1.10+)
- MarkdownSummaryGithub (5.1.13+)
- MarkdownAssembliesSummary (5.3.0+)
https://reportgenerator.io/usage
> Add ReportGenerator missing markdown report types

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Package/List/DotNetPackageListerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/List/DotNetPackageListerTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageList.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListAlternativePackageItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListFrameworkItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListPackageItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListProblemItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListProblemType.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListProjectItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListSettings.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageListVulnerabilityItem.cs
- src/Cake.Common/Tools/DotNet/Package/List/DotNetPackageLister.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet list package` command
Fixes #4224
Here is the basic implementation. I need your suggestion on what we should do with the output.
If the format is `console` we will receive smth like this
- hard to parse into model.
If the format is json, there could be a several different output which is dependent on the input params
when error
If we allow only JSON, then I'll be able to create models and deserialize (for `console` format it is almost impossible) and return the result for `public ListResult DotNetListPackage(...)` but what if someone just wants to get the output and that's all. 
What do you think?
> Add DotNetListPackage alias for dotnet list package command

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Reference/Remove/DotNetReferenceRemoverFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Reference/Remove/DotNetReferenceRemoverTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Reference/Remove/DotNetReferenceRemoveSettings.cs
- src/Cake.Common/Tools/DotNet/Reference/Remove/DotNetReferenceRemover.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet remove reference` command
Fixes #4352
Please review
> Add DotNetRemoveReference alias for dotnet remove reference command

- src/Cake.Core/ExecutionSettings.cs
- src/Cake.Core/Graph/CakeGraph.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommandSettings.cs
> GH4355: Frosting support Pascal Case Target argument

- build.cake
- src/Cake.Cli/Infrastructure/RemainingArgsParser.cs
- src/Cake.Frosting/Internal/Commands/DefaultCommand.cs
- src/Cake/Commands/DefaultCommand.cs
- tests/integration/Cake.Frosting/build/Tasks/Hello.cs
* Add argument to Forsting integration tests
* Unify Scripting / Frosting Spectre.Console IRemainingArguments to CakeArguments parsing
* fixes #4374
> GH4374: Fix Frosting argument parsing

- src/Cake.Common.Tests/Unit/EnvironmentAliasesTests.cs
- src/Cake.Common/EnviromentAliases.cs
- src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
- src/Cake.Core/Extensions/CakePlatformExtensions.cs
- src/Cake.Core/PlatformFamily.cs
- src/Cake.Core/Polyfill/EnvironmentHelper.cs
Closes https://github.com/cake-build/cake/issues/4310
This PR adds FreeBSD as a detected platform to Cake. It also includes a platform test. 
As .NET Standard does not support FreeBSD directly, and not to break .NET Standard compatibility, the function `RuntimeInformation.IsOSPlatform(OSPlatform.Create())` is used.
After building I did find test failures that seem to originate from `VerifyTests` as it does not support FreeBSD either. I will open a PR at that repo to address it. Tests are attached below
Even after this, Cake will not dogfood under FreeBSD as the tool `GitVersion` uses `Lib2GitSharp` which consumes a NuGet made by https://github.com/libgit2/libgit2sharp.nativebinaries that does not include a FreeBSD library. `GitVersion` uses Cake to build. 
Zip'd results using …
> Add FreeBSD Platform Detection

- .github/workflows/build.yml
- GitVersion.yml
- build.cake
- global.json
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/Add/DotNetPackageAdderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Package/List/DotNetPackageListerTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Reference/Add/DotNetReferenceAdderTests.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Reference/Remove/DotNetReferenceRemoverTests.cs
- src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs
- src/Cake.Common/Tools/OpenCover/OpenCoverRegisterOption.cs
- src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs
- src/Cake.Core/Constants.cs
- src/Cake.Core/Scripting/ScriptConventions.cs
- src/Cake.Frosting.Template/templates/cakefrosting/.template.config/template.json
- src/Cake.NuGet/Cake.NuGet.csproj
- src/Cake/Cake.csproj
- src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs
- src/Directory.Packages.props
- src/Shared.msbuild
- tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake
- tests/integration/Cake.Common/Tools/Command/CommandAliases.cake
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
- tests/integration/Cake.Core/Scripting/AddinDirective.cake
- tests/integration/Cake.Core/Scripting/DefineDirective.cake
- tests/integration/Cake.Frosting/build/Build.csproj
- tests/integration/resources/Cake.Common/Tools/DotNet/hwapp.tests/hwapp.tests.csproj
- tests/integration/resources/Cake.Common/Tools/DotNet/hwapp/hwapp.csproj
Todo #4382 (depends on .NET 9 Release) will come in a separate PR on .NET launch, would be nice to be able to integration test against Azure Artifacts pre-release feed.
> Add .NET 9, C# 13 and remove out of support .NET 6 & 7

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/Sln/List/DotNetSlnListerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/Sln/List/DotNetSlnListerTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.cs
- src/Cake.Common/Tools/DotNet/Sln/List/DotNetSlnListSettings.cs
- src/Cake.Common/Tools/DotNet/Sln/List/DotNetSlnLister.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
`dotnet sln list ` - Lists all projects in a solution file
The `dotnet sln list` command provides a convenient option to list projects for a given solution.
Docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#list
alternative PR for #3817
Please review
> Add DotNetSlnList alias for dotnet sln list command

- .github/workflows/build.yml
- src/Cake.Common.Tests/Fixtures/Build/GitHubActionsCommandsFixture.cs
- src/Cake.Common/Build/GitHubActions/Commands/Artifact/GitHubActionsArtifactService.cs
- src/Cake.Common/Build/GitHubActions/Commands/Artifact/ListArtifactsRequest.cs
- src/Cake.Common/Build/GitHubActions/Commands/Artifact/ListArtifactsResponse.cs
- tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake
Enables support for cross-job download of artifacts within the current run, by fetching job run id for specified artifact.
* fixes #4391
> GH4391: GHA cross-job download artifact support

- src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs
- src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs
- src/Cake.Common/Tools/SignTool/SignToolSignSettings.cs
\csp - Cryptographic Service Provider
\kc - Private Key Container Name
Fix for #4404
> Adds two missing parameters for SignTool

- src/Cake.Common.Tests/Unit/Build/AzurePipelines/Data/AzurePipelinesPullRequestInfoTests.cs
- src/Cake.Common/Build/AzurePipelines/AzurePipelinesInfo.cs
- src/Cake.Common/Build/AzurePipelines/Data/AzurePipelinesPullRequestInfo.cs
Fix detection of GitHub Pull Request builds in Azure Pipelines.  
This fixes the issue described in #4410.
To fix the issue, use a `long` instead of an `int` to store the current Pull Request id (read from the Azure Pipelines variable `SYSTEM_PULLREQUEST_PULLREQUESTID`).
I am aware that is a breaking change that might break all code that accesses `AzurePipelinesPullRequestInfo.Id` - however I am not aware of any other way to potentially fix this,
> Fix detection of current GitHub pull request in Azure Pipelines (#4410)

- src/Cake.Common.Tests/Fixtures/Build/GitLabCIInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIPullRequestInfoTests.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIPullRequestInfo.cs
Add properties "SourceBranch" and "TargetBranch" to GitLabCIPullRequestInfo.
This fixes #4416
> Add source and target branch to GitLabCIPullRequestInfo (#4416)

- src/Cake.Common.Tests/Fixtures/Build/GitLabCIInfoFixture.cs
- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIServerInfoTests.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIServerInfo.cs
The Url property returns the base url of the current GitLab server (read from the CI_SERVER_URL environment variable).
This fixes issue #4418
> Add Url property to GitLabCIServerInfo (#4418)

- src/Cake.Common.Tests/Unit/Build/GitLabCI/Data/GitLabCIBuildInfoTests.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIBuildInfo.cs
- src/Cake.Common/Build/GitLabCI/Data/GitLabCIPipelineSource.cs
- src/Cake.Common/Build/GitLabCI/GitLabCIInfo.cs
Add property `Source`to `GitLabCIBuildInfo` that exposes the value of the `CI_PIPELINE_SOURCE` variable that GitLab CI uses to indicate how a pipeline was triggered.
Since the variable has a finite amount of possible values, the property is modelled as an enum with constants for all values listed in the GitLab documentation (https://docs.gitlab.com/ee/ci/jobs/job_rules.html#ci_pipeline_source-predefined-variable).
To account for GitLab adding additional values in the future, `GitLabCIBuildInfo.Source` is a nullable enum that will return `null` in case the environment variable value cannot be converted to the enum.
This fixes #4431
> Add property GitLabCIBuildInfo.Source (#4431)

- src/Cake.Common.Tests/Fixtures/Tools/DotNet/MSBuild/DotNetCoreMSBuildBuilderFixture.cs
- src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs
- src/Cake.Common.Tests/Unit/Tools/DotNet/MSBuild/DotNetMSBuildBuilderTests.cs
- src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs
- src/Cake.Common/Tools/DotNet/DotNetAliases.MSBuild.cs
- src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildBuilder.cs
- src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs
- src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettingsExtensions.cs
- src/Cake.Common/Tools/DotNet/MSBuild/MSBuildArgumentBuilderExtensions.cs
- src/Cake.Common/Tools/MSBuild/MSBuildAliases.cs
- src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
- src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
- tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add support for capturing MSBuild properties, items and target results using [Evaluate items and properties and display results of targets](https://learn.microsoft.com/en-us/visualstudio/msbuild/evaluate-items-and-properties).
- Added `StandardOutputAction` properties to `DotNetCoreMSBuildBuilderFixture` and `MSBuildRunnerFixture`.
- Updated `RunTool` methods to pass `StandardOutputAction` to `Build` and `Run` methods.
- Added new test cases in `DotNetMSBuildBuilderTests` and `MSBuildRunnerTests` to verify functionality.
- Added overloads in `DotNetAliases` and `MSBuildAliases` to accept `standardOutputAction` parameter.
- Updated `DotNetMSBuildBuilder` and `MSBuildRunner` to handle `standardOutputAction` and configure process settings.
- Enhanced `MSBuildArgumentBuilderExtensions` to …
> Add support for capturing MSBuild properties, items and target results

- build.ps1
Since https://dot.net only supports TLS v1.2+, this drops older TLS/SSL versions too.
> Update build.ps1 to use TLS v1.3

- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerSettingsTests.cs
- src/Cake.Common.Tests/Unit/Tools/NuGet/Install/NuGetInstallerTests.cs
- src/Cake.Common/Tools/NuGet/Install/NuGetInstallSettings.cs
- src/Cake.Common/Tools/NuGet/Install/NuGetInstaller.cs
> GH4412: NuGetInstall Add NoHttpCache, obsolete NoCache

- src/Cake.Tests/Infrastructure/Scripting/RoslynScriptSessionTests.cs
- src/Cake/Infrastructure/Scripting/RoslynScriptSession.cs
This fixes an issue we are seeing when running on a build agent that uses random folder names for each build. This PR allows cache re-usage by replacing the working directory inside the script lines before generating the hash.
Also added unit tests for:
* hash inequality in the same directory
* hash equality in different directories
For reference: https://github.com/cake-build/cake/issues/4471
> GH4471: Improve script cache hash generation algorithm

- src/Cake.Cli/Hosts/BuildScriptHost.cs
- src/Cake.Cli/Infrastructure/CakeSpectreReportPrinter.cs
- src/Cake.Core.Tests/Unit/CakeEngineTests.cs
- src/Cake.Core/CakeEngine.cs
- src/Cake.Core/CakeReportException.cs
- src/Cake.Core/CakeReportPrinter.cs
Currently, Cake prints out a task execution summary on each successful execution.  This summary includes which tasks were executed or skipped, and the duration of the task.  However, then an execution of Cake fails, the task summary is not printed, and it is necessary to scroll through the Cake output, to find out what task failed.  You also lose the information about which tasks, if any, were skipped.
Any changes to this workflow will have to be done carefully though, as we don't want to alter how tasks are executed, in what order, or what is done in the cases of ContinueOnError, etc.  There are a number of unit tests that check for this execution, and these will need to continue to pass.
This commit aims to address this problem by introducing a new CakeReportException, which has a …
> GH4475: Always show task execution summary

- build.cake
This addin has been updated to compile against Cake.Core 5.0.0 which removes a warning that is being output as part of the build.
Fixes #4499
> GH4499: Update to Cake.Twitter 5.0.0

- src/Directory.Packages.props
> GH4505: Update Basic.Reference.Assemblies.Net* to 1.8.1

- build/parameters.cake
* Cake.Testing.Xunit.v3 missing from publishable packages
* relates to #4427
> (build) Add Cake.Testing.Xunit.v3 to build params

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.cake
- build/credentials.cake
- build/parameters.cake
- build/version.cake
* Replace AppVeyor build configuration with GitHub Actions workflows
* Add new release workflow for automated releases on version tags
* Update code signing to use Azure CLI credentials instead of client secret
* Replace MyGet publishing with Azure DevOps NuGet feed
* Add GitHub Actions specific build targets (GitHubActions, GitHubActions-Release)
* Update build parameters to detect GitHub Actions environment
* Remove AppVeyor-specific dependencies and configurations
* Update tag detection logic to work with GitHub Actions
* fixes #4561
> GH4561: Migrate to GitHub Actions for release

- global.json
- src/Directory.Packages.props
This PR updates multiple dependencies to their latest versions, including the .NET SDK and various NuGet packages.
- **.NET SDK**: Updated from 9.0.304 to 9.0.305
- **Microsoft.Extensions.DependencyInjection**: 9.0.8 → 9.0.9
- **Microsoft.NET.Test.Sdk**: 17.14.1 → 18.0.0
- **Microsoft.TestPlatform.ObjectModel**: 17.14.1 → 18.0.0
- **Newtonsoft.Json**: 13.0.3 → 13.0.4
- **Spectre.Console**: 0.50.0 → 0.51.1
- **Spectre.Console.Cli**: 0.50.0 → 0.51.1
- **System.Collections.Immutable**: 9.0.8 → 9.0.9
- **System.Reflection.Metadata**: 9.0.8 → 9.0.9
- **System.Security.Cryptography.Pkcs**: 9.0.8 → 9.0.9
- **Verify.XunitV3**: 30.7.3 → 30.19.2
- **xunit.v3**: 3.0.1 → 3.1.0
- **xunit.v3.assert**: 3.0.1 → 3.1.0
- **xunit.v3.extensibility.core**: 3.0.1 → 3.1.0
- **xunit.runner.visualstudio**: 3.1.4 …
> Update dependencies to latest versions

- src/Cake.Common/Build/AzurePipelines/Data/AzurePipelinesAgentInfo.cs
As described in the linked issue. Currently `AzurePipelinesAgentInfo` returns `FilePaths` for properties that are directory paths. This means than a build author needs to convert the file paths to `DirectoryPath` before being able to combine the path with other paths.
So in this PR I am changing the properties to return `DirectoryPath` instead.
This is likely a breaking change.
Fixes #4534
> GH-4534 Fix AzurePipelinesAgentInfo returning FilePaths instead of DirectoryPaths

- src/Cake.Core/Polyfill/EnvironmentHelper.cs
> GH4603: Fix .NET framework version detection

- src/Cake.Cli/Hosts/DescriptionScriptHost.cs
- src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs
- src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecTransformer.cs
- src/Cake.Common/Tools/XBuild/XBuildRunner.cs
- src/Cake.Core/CakeEnvironmentExtensions.cs
- src/Cake.Core/Configuration/CakeConfiguration.cs
- src/Cake.Core/Configuration/CakeConfigurationProvider.cs
- src/Cake.Core/Tooling/ToolRepository.cs
- src/Cake.DotNetTool.Module/DotNetToolContentResolver.cs
- src/Cake.DotNetTool.Module/DotNetToolPackageInstaller.cs
- src/Cake.NuGet/Client/PackageReferenceExtensions.cs
- src/Cake.NuGet/Installers/InProcessInstaller.cs
- src/Cake.NuGet/Installers/OutOfProcessInstaller.cs
- src/Cake.NuGet/NuGetContentResolver.cs
- src/Cake.Testing/FakeEnvironment.cs
- src/Cake.Testing/FakeFileSystemTree.cs
> avoid duplicate dictionary lookups

- src/Cake.Common/Build/GitHubActions/Commands/Artifact/GitHubActionsArtifactService.cs
- src/Cake.Common/Net/HttpClientExtensions.cs
> async usings
