src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs, src/Cake.Core.Tests/Unit/CakeTaskTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/CakeTask.cs, src/Cake.Core/CakeTaskBuilderExtensions.cs
As requested in Issue #131. Not sure about the naming though...
=> Added finally handler and error reporter for tasks.

src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs, src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs, src/Cake.Core/IO/DirectoryPath.cs
=> Added Copy Directory support.

src/Cake.Common/Solution/Project/ProjectAliases.cs, src/Cake.Common/Solution/SolutionAliases.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/SignTool/Sign/SignToolSignAliases.cs
Added XML example code for
* SignTool
* ParseSolution
* ParseProject
* Nuget commands
=> Added XML Example code

src/Cake.Common/ArgumentAliases.cs, src/Cake.Common/EnviromentAliases.cs, src/Cake.Common/ProcessAliases.cs, src/Cake.Common/ReleaseNotesAliases.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoAliases.cs
Wrote some more sample last for some alias methods, now xml:fied it ;)
=> Added more code examples

src/Cake.Common.Tests/Unit/Tools/NUnit/NUnitRunnerTests.cs, src/Cake.Common/Tools/NUnit/NUnitRunner.cs
=> Added NUnit Multiple Assembly Support.

src/Cake.Common/Tools/NUnit/NUnitRunner.cs
=> Fixed NUnit Stylecop issues

src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs, src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs, src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Common/IO/FileAliases.cs
An implementation of the functions mentioned in #177.
```csharp
if (FileExists("file.txt"))
{
}
if (DirectoryExists("./dir"))
{
}
```
=> Implemented DirectoryExists and FileExists.

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/NSISFixture.cs, src/Cake.Common.Tests/Unit/Tools/NSIS/MakeNSISRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/NSIS/NSISAliasesTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/NSIS/MakeNSISRunner.cs, src/Cake.Common/Tools/NSIS/MakeNSISSettings.cs, src/Cake.Common/Tools/NSIS/NSISAliases.cs
I've implemented NSIS support in response to #111.
```csharp
// Compile script with default settings.
MakeNSIS("./path/to/script.nsi");
// Compile script with defines.
MakeNSIS("./path/to/script.nsi", new MakeNSISSettings
{
Defines = new Dictionary<string, string>
{
{ "Foo", "Bar" },
{ "Define", string.Empty }
}
});
```
=> Implemented NSIS runner.

src/Cake.Common/Tools/NuGet/Pack/NuSpecTransformer.cs
Changed xpath to select `packages` by local name..
Tested with a few nuspecs including  Cake & issue #198 supplied nuspec.
=> Adjusted nuspec xpaths, Fixes #198

src/Cake/Commands/HelpCommand.cs
Added available verbosities to Cake usage, so don't need to lookup docs for these.
=> Added available verbosities to Cake usage

src/Cake.Common/Tools/ILMerge/ILMergeRunner.cs, src/Cake.Common/Tools/ILMerge/TargetPlatform.cs
There was 3 StyleCop errors and 2 FXCop errors in release mode.
Not sure why AppVeyor didn't say anything about this, but I will investigate that as well.
=> Made minor changes to ILMerge tool to make StyleCop and FXCop happy.

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/NuGetUpdateFixture.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Update/NuGetUpdateSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Update/NuGetUpdaterTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/NuGet/Update/NuGetUpdateSettings.cs, src/Cake.Common/Tools/NuGet/Update/NuGetUpdater.cs
Should resolve #219 when (if) merged.
=> Added support for NuGet update command.

README.md
Corrected the URI for the contribution guidelines and the list of contributors.
=> Updated URI in the README

src/Cake.Common/Tools/SignTool/SignToolSignAliases.cs, src/Cake.Core.Tests/Fixtures/CakeContextFixture.cs, src/Cake.Core/CakeContext.cs, src/Cake.Core/ICakeContext.cs, src/Cake.Core/IO/WindowsRegistry.cs, src/Cake/Program.cs
During refactor seems to have snuck in a little null issue.
=> Fix for missing registry creation

src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs
So we can chain them when starting a process.
````csharp
StartProcess("./test.exe", new ProcessSettings {
Arguments = new ProcessArgumentBuilder().Append("-f").AppendQuoted("./file.txt")
});
```
=> Made process argument methods fluent.

build.ps1, tools/packages.config
Added bootstrapper support for running Cake with new Roslyn bits.
```
PS> ./build.ps1 -Experimental
```
=> Added experimental switch to bootstrapper.

build.ps1
This adds validation and tab completion for `-Configuration` and `-Verbosity` in `PowerShell` when using `build.ps1`.
=> Added validation set for more help with/typed parameters

CONTRIBUTING.md
Added CONTRIBUTING.md which will be shown when a PR is proposed. 
Read more [here](https://github.com/blog/1184-contributing-guidelines)
=> Added Contributing Guidelines to repo

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs, src/Cake.Common/Build/TeamCity/TeamCityDisposableExtensions.cs, src/Cake.Common/Build/TeamCity/TeamCityProvider.cs, src/Cake.Common/Cake.Common.csproj
PoC for TeamCity (and any other buildsystem) integration. Planning to use as basis for MyGet provider.
=> Add TeamCity BuildSystem.

src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.Core.Tests/Unit/IO/ProcessSettingsTests.cs, src/Cake.Core/Cake.Core.csproj, src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs, src/Cake.Core/Extensions/ProcessSettingsExtensions.cs, src/Cake.Core/IO/Arguments/QuotedArgument.cs, src/Cake.Core/IO/Arguments/SecretArgument.cs, src/Cake.Core/IO/Arguments/TextArgument.cs
Extension methods for adding a fluent interface to ProcessSettings
=> ProcessSettings extension methods

src/Cake.Common/Build/AppVeyor/IAppVeyorProvider.cs, src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs, src/Cake.Common/Build/TeamCity/TeamCityDisposableExtensions.cs, src/Cake.Common/Build/TeamCity/TeamCityProvider.cs, src/Settings.StyleCop
The method `UpdatedBuildVersion` was missing in the `IAppVeyorProvider` interface declaration. Also fixed some minor, build system related StyleCop issues.
=> Fixed issue where method was missing on interface declaration.

src/Cake.Common/Cake.Common.csproj, src/Cake.Common/IO/ZipAliases.cs, src/Cake.Common/IO/Zipper.cs
This is a simple method to Unzip a specified file to a given directory.
=> Unzip alias

src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptProcessorTests.cs, src/Cake.Core/Cake.Core.csproj, src/Cake.Core/Scripting/Processors/ShebangProcessor.cs, src/Cake.Core/Scripting/ScriptProcessor.cs
=> Added shebang line processor.

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/DupFinderRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DupFinder/DupFinderRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/DupFinder/DupFinderAliases.cs, src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs, src/Cake.Common/Tools/DupFinder/DupFinderSettings.cs
=> Adds DupFinder support

README.md
Link to docs page for bootstrapper. See #402
=> Update readme - link to bootstrapper

appveyor.yml
* Added caching of tools to speed up builds
* Changed to use PowerShell command to fix AppVeyor layout issues
=> Added tool cache & changed to PS command

src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs
Rebased as one commit as asked in https://github.com/cake-build/cake/pull/386#issuecomment-137929149
=> Adding documentation for OctoCreateRelease alias

src/Cake.Common/Tools/SignTool/SignToolSignAliases.cs
=> Fixed an error in sample code for signing assemblies

src/Cake.Common/IO/DirectoryCleaner.cs, src/Cake.Common/IO/DirectoryCreator.cs, src/Cake.Common/IO/DirectoryDeleter.cs, src/Cake.Common/IO/FileCopier.cs, src/Cake.Common/IO/FileDeleter.cs, src/Cake.Common/IO/FileMover.cs, src/Cake.Common/IO/Zipper.cs
=> Added verbose logging for file and directory aliases.

src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/NuGet/Update/NuGetUpdater.cs, src/Cake.Core/IO/NuGet/NuGetToolResolver.cs
- Including the removal of some whitespace in files
=> Fixing up typos and errors in documentation

src/Cake.sln
- the utilities.cake file no longer seems to exist in source control, so
removing it from the build solution folder
=> (maint) Removing missing file from solution

.editorconfig
- To help with overall maintenance of project files
- More information here:
http://editorconfig.org
- Requires the installation of this extension:
https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328
=> (GH-442) Adding EditorConfig file

src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/MyGet/IMyGetProvider.cs, src/Cake.Common/Build/MyGet/MyGetBuildStatus.cs, src/Cake.Common/Build/MyGet/MyGetProvider.cs, src/Cake.Common/Cake.Common.csproj
As documented here:
http://docs.myget.org/docs/reference/build-services
As requested here https://github.com/cake-build/cake/issues/148
=> Add MyGet Build System Support

src/Cake.Core/Cake.Core.csproj, src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs, src/Cake.Core/IO/Arguments/SwitchArgument.cs
So, instead of doing this:
```
builder.Append("-c");
builder.AppendQuoted(settings.CacheLocation);
```
You would be able to use:
```
builder.AppendSwitchQuoted("--version", settings.Version);
```
=> Add extension for ProcessArgumentBuilder

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseNotesRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseNotes/GitReleaseNotesRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAddAssetsSettings.cs, src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesAliases.cs, src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesIssueTracker.cs, src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesRunner.cs, src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesSettings.cs
@devlead @patriksvensson would love it if you could review this.
Thanks!
=> Add GitReleaseNotes alias

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/GitVersionRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/GitVersion/GitVersion.cs, src/Cake.Common/Tools/GitVersion/GitVersionAliases.cs, src/Cake.Common/Tools/GitVersion/GitVersionOutput.cs, src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs, src/Cake.Common/Tools/GitVersion/GitVersionSettings.cs
Also reworked process and process arguments.
=> Add GitVersion alias.

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/ReportGeneratorRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/ReportGenerator/ReportGeneratorRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorAliases.cs, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorReportType.cs, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorRunner.cs, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorSettings.cs, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorVerbosity.cs
#462
@gep13 Some real-life testing would be appriciated.
=> Adds ReportGenerator support

src/Cake.Common/Tools/ReportGenerator/ReportGeneratorAliases.cs
Fix missing context parameter validation.
=> Added missing ReportGenerator parameter validation

src/Cake.Common/Tools/GitReleaseNotes/GitReleaseNotesAliases.cs
=> Corrected error in documentation

src/Cake.Common/Tools/OpenCover/OpenCoverAliases.cs
=> Fixed error in OpenCover example.

src/Cake.Common.Tests/Fixtures/Tools/DupFinder/DupFinderRunnerConfigFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DupFinder/DupFinderRunnerFixture.cs, src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Tools/DupFinder/DupFinderRunnerTests.cs, src/Cake.Common/Tools/DupFinder/DupFinderAliases.cs, src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs, src/Cake.Common/Tools/DupFinder/DupFinderSettings.cs
This is a first stab at implementing the following:
https://github.com/cake-build/cake/issues/452
@patriksvensson  @devlead  What are your thoughts on this approach?
@yvschmid I would be interested to hear your thoughts as well.
Thanks!
=> Fail build on finding Duplicates

src/Cake.Core.Tests/Fixtures/GlobberFixture.cs, src/Cake.Core.Tests/Unit/IO/GlobberTests.cs, src/Cake.Core/IO/Globbing/GlobTokenizer.cs
Also ties up a "TODO" comment regarding plus sign in path
=> Fixing issue #497 when path includes an ampersand

src/Cake.Core/CakeEngine.cs
Minor bug when reporting an error.
=> Added string replacement token to error-log call.

src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs, src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs
=> Gracefully handle the potential for missing attributes

src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs, src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
=> Removing incorrect parameter for GitVersion

src/Cake.Core.Tests/Unit/Text/TextTransformationTemplateTests.cs, src/Cake.Core/Text/TextTransformationTemplate.cs
=> Added regex fix for text transform placeholders.

src/Cake.Common.Tests/Fixtures/Build/AppVeyorInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/AppVeyor/Data/AppVeyorEnvironmentInfoTests.cs, src/Cake.Common/Build/AppVeyor/Data/AppVeyorEnvironmentInfo.cs
- Named APPVEYOR_JOB_NAME
- This was added into AppVeyor here: https://github.com/appveyor/ci/issues/522
=> (GH-541) Adding new AppVeyor Environment Variable

src/Cake.Core/CakeEnvironment.cs, src/Cake.Core/IO/NuGet/INuGetAssemblyCompatibilityFilter.cs, src/Cake.Core/IO/NuGet/INuGetFrameworkCompatibilityFilter.cs, src/Cake.Core/IO/NuGet/PackageReferenceBundler.cs, src/Cake.Core/IO/NuGet/Parsing/AssemblyFilePathFrameworkNameParser.cs
=> Added fix for framework name on Mono.

src/Cake.Core/IO/ProcessRunner.cs
=> Fix Quote ProcessStartInfo filename

CODEOFCONDUCT.md
=> Added code of conduct.

src/Cake.Core/IO/ProcessRunner.cs, src/Cake.Core/IO/ProcessWrapper.cs
This Fixes #535 raised by @Redth 
Currently StartProcess hangs when standard output is redirected and the process outputs large amounts of data.
This is test script
```csharp
var TARGET = Argument ("target", Argument ("t", "Default"));
Task ("Default").Does (() =>
{
IEnumerable<string> stdout;
Information("Starting process");
if (IsRunningOnWindows ()) {
Information("Windows");
StartProcess ("cmd.exe", new ProcessSettings {
Arguments = "/C dir C:\\Windows /S",
RedirectStandardOutput = true,
}, out stdout);
} else {
Information("Unix");
StartProcess ("cat", new ProcessSettings {
Arguments = "data.txt",
RedirectStandardOutput = true,
}, out stdout);
}
Information("Got: {0} lines", stdout.Count());
});
RunTarget(TARGET);
```
Above script outputs and hangs before script
``` …
```
=> Changes to async read of redirected console output

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/PlatformTarget.cs
=> Added Win32 platform target.

src/Cake.Core/CakeEnvironment.cs, src/Cake.Core/Extensions/TypeExtensions.cs, src/Cake.Core/IO/Globbing/GlobTokenizer.cs, src/Cake.Core/IO/NuGet/Parsing/AssemblyFilePathFrameworkNameParser.cs, src/Cake.Core/Scripting/CodeGen/PropertyAliasGenerator.cs, src/Cake.Core/Scripting/ScriptAliasFinder.cs, src/Cake.Core/Scripting/ScriptConventions.cs
This brings Cake.Core up from 94.12% to 96.15% :sparkles: The rest needs #ifdefs :disappointed:
=> Move Cake.Core towards a more .NET Core-friendly surface area

src/Cake.Common/Security/FileHashCalculator.cs, src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecTransformer.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
This brings Cake.Common up from 97.50% to 98.68% :sparkles: The rest needs #ifdefs :disappointed:
=> Move Cake.Common towards a more .NET Core-friendly surface area

src/Cake.Common/Tools/DNU/Build/DNUBuildSettings.cs, src/Cake.Common/Tools/DNU/Pack/DNUPackSettings.cs
Changed DNUBuildSettings.OutputDirectory and DNUPackSettings.OutputDirectory property type to DirectoryPath.
Fixes #624
=> Fixed #624 (DNU Settings OutputDirectory)

src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerAliases.cs
=> (GH-630) Add additional aliases for GitReleaseManager commands

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/GitLinkFixture.cs, src/Cake.Common.Tests/Unit/Tools/GitLink/GitlinkRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/GitLink/GitLinkAliases.cs, src/Cake.Common/Tools/GitLink/GitLinkRunner.cs, src/Cake.Common/Tools/GitLink/GitLinkSettings.cs
=> (GH-619) Added GitLink Support with Tests

src/Cake.Core.Tests/Unit/IO/FilePathTests.cs
OCD: TheGetExtensionProperty test -> TheGetExtensionMethod test
=> Corrected Class Name Associated with Unit Test

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Build/ContinuaCIFixture.cs, src/Cake.Common.Tests/Fixtures/Build/ContinuaCIInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/ContinuaCIProviderTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/Data/ContinuaCIBuildInfoTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/Data/ContinuaCIChangesetInfoTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/Data/ContinuaCIConfigurationInfoTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/Data/ContinuaCIEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/ContinuaCI/Data/ContinuaCIProjectInfoTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/ContinuaCI/ContinuaCIInfo.cs, src/Cake.Common/Build/ContinuaCI/ContinuaCIMessageType.cs, src/Cake.Common/Build/ContinuaCI/ContinuaCIProvider.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIBuildInfo.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIChangesetInfo.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIConfigurationInfo.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIEnvironmentInfo.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIProjectInfo.cs, src/Cake.Common/Build/ContinuaCI/IContinuaCIProvider.cs, src/Cake.Common/Cake.Common.csproj
Added provider to support integration with [Continua CI](https://www.finalbuilder.com/continua-ci)
* Access to Continua CI build objects and variables
* Methods for writing to Continua CI build log, updating build version and variables
=> Continua CI build system support

build.cake, tools/packages.config
- Use GitReleaseManager to add asset to release, publish GitHub release, and close associated milestone.
Relates to #569
=> (GH-569) One more automation step

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/NuGet/Packer/NuGetPackerWithProjectFileFixture.cs, src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
This is based on pending PR #662, but wanted to get the changes in for review. Once that PR is merged, I'll rebase to develop and remove the WIP label.
=> Added support for packing NuGet project files (#637)

LICENSE
=> Update license to current team & year

src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
=> Nuget properties argument support

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/DotCover/Analyse/DotCoverAnalyserFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotCover/DotCoverFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotCover/Analyse/DotCoverAnalyseSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/DotCover/Analyse/DotCoverAnalyserTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/DotCover/Analyse/DotCoverAnalyseSettings.cs, src/Cake.Common/Tools/DotCover/Analyse/DotCoverAnalyseSettingsExtensions.cs, src/Cake.Common/Tools/DotCover/Analyse/DotCoverAnalyser.cs, src/Cake.Common/Tools/DotCover/DotCoverAliases.cs, src/Cake.Common/Tools/DotCover/DotCoverContext.cs, src/Cake.Common/Tools/DotCover/DotCoverProcessRunner.cs, src/Cake.Common/Tools/DotCover/DotCoverReportType.cs, src/Cake.Common/Tools/DotCover/DotCoverTool.cs
Still needs some work. Wanted to check if I'm on the right path here before doing more work. Plan is to also add support for other [commands](https://www.jetbrains.com/dotcover/help/dotCover__Console_Runner_Commands.html) than analyse, e.g. cover, merge, report and delete 
Fixes issue #658
=> dotcover support

.gitignore, build.cake, tools/packages.config
This still needs some work, but the basics are there.
Thoughts?
=> Add GitVersion to Cake Build Process

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/ILRepackRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/ILRepack/ILRepackRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/ILRepack/ILRepackSettingsTests.cs
=> (GH-694) Added tests for ILRepack

appveyor.yml
=> (GH-697) Added building of release branches

README.md
And a few trailing spaces. :wink:
=> Removed year from © in readme

GitVersionConfig.yaml, build.cake
- This time with a GitVersionConfig.yaml file
- Which will correctly identify main as the "master" branch, and version accordingly
=> (GH-567) Added back in the execution of GitVersion

src/Cake.Core.Tests/Unit/IO/PathTests.cs
=> Fix for PathTests Segements property test

build.ps1, build.sh
This is a suggested fix for #733
=> Changes nuget version bootstrapper downloads

src/Cake.Core.Tests/Unit/IO/PathCollapserTests.cs, src/Cake.Core/IO/PathCollapser.cs
As discussed (briefly) on Gitter. Feel free to suggest additional tests or changes.
=> Adds support for collapsing "." in paths

src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecDependency.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
This added the property Dependencies to NuGetPackSettings allowing dependencies to be specified in the cake file.
=> Adding dependencies to NuGetPackSettings

src/Cake.Common.Tests/Fixtures/Tools/XUnitRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/XUnit/XUnitRunnerTests.cs, src/Cake.Common/Tools/XUnit/XUnitAliases.cs, src/Cake.Common/Tools/XUnit/XUnitRunner.cs
This reverts regression and fixes #744
=> Reverts XUnit 1 multiple assembly

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Build/JenkinsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/JenkinsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsBuildInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsJobInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsNodeInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsRepositoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/JenkinsEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/JenkinsProviderTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsBuildInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsEnvironmentInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsJobInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsNodeInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsRepositoryInfo.cs, src/Cake.Common/Build/Jenkins/IJenkinsProvider.cs, src/Cake.Common/Build/Jenkins/JenkinsInfo.cs, src/Cake.Common/Build/Jenkins/JenkinsProvider.cs, src/Cake.Common/Cake.Common.csproj
Added support for the following environment variables:
- BUILD_NUMBER
- BUILD_ID
- BUILD_DISPLAY_NAME
- BUILD_URL
- BUILD_TAG
- EXECUTOR_NUMBER
- NODE_NAME
- NODE_LABELS
- WORKSPACE
- JENKINS_HOME
- JENKINS_URL
- JOB_NAME
- JOB_URL
- SVN_REVISION
- SVN_URL
- GIT_COMMIT
- GIT_BRANCH
- CVS_BRANCH
=> (GH-693) Added Jenkins CI build system support

build.ps1, build.sh
Hey guys! I came across your project while browsing the Reddit the other day, thought it was pretty cool.
This PR forwards the arguments from build.ps1 and build.sh to the Cake script, so it's possible to communicate with the script.
=> Forward arguments to Cake from the bootstrapper scripts

nuspec/Cake.Portable.nuspec
As suggested during the Chocolatey Moderation process
=> (GH-760) Removed (Install) from title of Choco Package

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Build/BitriseFixture.cs, src/Cake.Common.Tests/Fixtures/Build/BitriseInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseApplicationInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseBuildInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseDirectoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseProvisioningInfo.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseRepositoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Bitrise/Data/BitriseWorkflowInfoTests.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common/Build/Bitrise/BitriseInfo.cs, src/Cake.Common/Build/Bitrise/BitriseProvider.cs, src/Cake.Common/Build/Bitrise/Data/BitriseApplicationInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseBuildInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseDirectoryInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseEnvironmentInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseProvisioningInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseRepositoryInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseWorkflowInfo.cs, src/Cake.Common/Build/Bitrise/IBitriseProvider.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.sln
Pull Request exposes the following environment variables from the Bitrise CI System.
References #644 
**Variable** | **Comment**
------------ | -------------
BITRISE_BUILD_NUMBER | build number of the build on bitrise.io
GIT_REPOSITORY_URL | git repository URL
BITRISE_APP_TITLE | app title on bitrise.io
BITRISE_APP_URL | app URL on bitrise.io
BITRISE_APP_SLUG | app slug on bitrise.io
BITRISE_BUILD_URL | build's URL on bitrise.io
BITRISE_BUILD_SLUG | build's slug on bitrise.io
BITRISE_BUILD_TRIGGER_TIMESTAMP | triggered at timestamp of the build
BITRISE_GIT_BRANCH | the branch which triggered the build
BITRISE_GIT_TAG | tag which triggered the build (if any)
BITRISE_GIT_COMMIT | commit hash which triggered the build (if any)
BITRISE_PULL_REQUEST | Pull Request ID, which triggered the build …
=> (GH644) Added Bitrise CI build system support

src/Cake.Common.Tests/Unit/Tools/NuGet/Sources/NuGetSourcesSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Sources/NuGetSourcesTests.cs, src/Cake.Common/Tools/NuGet/Sources/NuGetSources.cs, src/Cake.Common/Tools/NuGet/Sources/NuGetSourcesSettings.cs
* Enables possibility to add NuGet source with password stored in plain text
* Fixes GH774
=> Added StorePasswordInClearText to NuGetSourcesSettings

src/Cake.Core/Cake.Core.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.Testing/Cake.Testing.csproj, src/Cake/Cake.csproj
=> Adjust tool version

src/Cake.Core/Tooling/ToolSettings.cs
=> Added sample code for ArgumentCustomization

src/Cake.Common/Xml/XmlPeekAliases.cs, src/Cake.Common/Xml/XmlTransformationAlias.cs
Added sample code + removed some unused code.
=> Added missing sample code for XML aliases

src/Cake.Common/IO/DirectoryAliases.cs
Simple clarification of wording to resolve issue #769
=> Clarify behaviour in summary of CopyDirectory method alias

src/Cake.Common.Tests/Unit/IO/FileAliasesTests.cs, src/Cake.Common/IO/FileAliases.cs, src/Cake.Testing/Extensions/FakeFileSystemExtensions.cs
Relates to #791
```csharp
FileSize("./build.cake");
```
=> Add FileSize alias

src/Cake.Common/Tools/DupFinder/DupFinderAliases.cs
=> Added DupFinder Sample Code

src/Cake.Common/Tools/DupFinder/DupFinderAliases.cs, src/Cake.Common/Tools/InspectCode/InspectCodeAliases.cs
=> Added InspectCode Sample Code

src/Cake.Common/Tools/NUnit/NUnitAliases.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/WiX/WiXAliases.cs
Another couple alias examples to move #750 along.
Cheers.
=> GH-750 alias examples for NuGet, NUnit, WiX

src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs, src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs
- Rather than opening the File, thus locking it, use a Stream to dispose
of the lock on the file when working with it has completed.
=> (GH-805) Correcting issue with locked file

build.cake, build/parameters.cake
* Added main branch check
* Added nuget api url setting
* Added publish nuget to the AppVeyor target
* Added publish chocolatey to AppVeyor target
* Added tag check for publish
* Added log if IsTagged
=> Added nuget publish to AppVeyor

src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
=> Add support for IncludeReferencedProjects to NuGetPacker

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Build/TravisCIFixture.cs, src/Cake.Common.Tests/Fixtures/Build/TravisCIInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/TravicCI/Data/TravisBuildInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TravicCI/Data/TravisJobInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TravicCI/Data/TravisRepositoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TravicCI/TravisCIEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TravicCI/TravisCIProviderTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/TravisCI/Data/TravisCIBuildInfo.cs, src/Cake.Common/Build/TravisCI/Data/TravisCIEnvironmentInfo.cs, src/Cake.Common/Build/TravisCI/Data/TravisCIJobInfo.cs, src/Cake.Common/Build/TravisCI/Data/TravisCIRepositoryInfo.cs, src/Cake.Common/Build/TravisCI/ITravisCIProvider.cs, src/Cake.Common/Build/TravisCI/TravisCIDisposableExtensions.cs, src/Cake.Common/Build/TravisCI/TravisCIInfo.cs, src/Cake.Common/Build/TravisCI/TravisCIProvider.cs, src/Cake.Common/Cake.Common.csproj
I am marking this WIP because I am looking for feedback on [Travis Fold](https://github.com/cake-build/cake/compare/develop...RLittlesII:GH742?expand=1#diff-c5e51703b71fb865ef84a947b9548557R10) and the [Write Message](https://github.com/cake-build/cake/compare/develop...RLittlesII:GH742?expand=1#diff-60795439dcfc3f16aa5dc9ab99ac75ddR119) format. Also, are there any other Travis functions we want to expose besides fold?
I will update with all the environment information that was required in #742
=> (GH742) Added TravisCI build system support

src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs, src/Cake.Common/Tools/MSTest/MSTestRunner.cs, src/Cake.Common/Tools/MSTest/MSTestSettings.cs
Add filtering option to MSTestSettings. Feedback welcome.
=> Add TestCategoryFilter to MSTestSettings issue #716

src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Xml/XmlPeekAliases.cs, src/Cake.Core/Cake.Core.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.NuGet/Properties/AssemblyInfo.cs, src/Cake.Testing/Cake.Testing.csproj, src/Cake/Cake.csproj
Also suppressed a forgotten FxCop warning.
=> Fixed issue with StyleCop not running in release configuration.

src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs, src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs, src/Cake.Common/Tools/SignTool/SignToolSignSettings.cs
Signed-off-by: Austin Morton <amorton@eaglabs.com>
=> (GH-524) Signtool: Add support for description (/d)

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Fixtures/Tools/TextTransform/TextTransformFixture.cs, src/Cake.Common.Tests/Unit/Tools/TextTransform/TextTemplateAliasTests.cs, src/Cake.Common.Tests/Unit/Tools/TextTransform/TextTransformRunnerTests.cs, src/Cake.Common/Cake.Common.csproj, src/Cake.Common/Tools/TextTransform/TextTransformAliases.cs, src/Cake.Common/Tools/TextTransform/TextTransformRunner.cs, src/Cake.Common/Tools/TextTransform/TextTransformSettings.cs
Pull Request to add Mono.TextTransform support to Cake (#814)
=> (GH814) Added Text Transform support

src/Cake.Core/Tooling/Tool.cs, src/Cake.Core/Tooling/ToolSettings.cs
=> Adds timeout to Tool/ToolSettings

src/Cake.Common.Tests/Unit/Tools/DNU/Build/DNUBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DNU/Pack/DNUPackerTests.cs, src/Cake.Common.Tests/Unit/Tools/DNU/Restore/DNURestorerTests.cs, src/Cake.Common/Tools/DNU/Build/DNUBuilder.cs, src/Cake.Common/Tools/DNU/Pack/DNUPacker.cs, src/Cake.Common/Tools/DNU/Restore/DNURestorer.cs
Same as https://github.com/cake-build/cake/pull/834
Rebased on develop for release with 0.11.0
Thanks!
=> DNU doesn't like semi-colons anymore.  It uses multiple args for the same flag.

build/paths.cake, tests/integration/.gitignore, tests/integration/Cake.Common/ArgumentAliases.cake, tests/integration/Cake.Common/EnvironmentAliases.cake, tests/integration/Cake.Common/IO/DirectoryAliases.cake, tests/integration/build.cake, tests/integration/build.ps1, tests/integration/build.sh, tests/integration/utilities/io.cake, tests/integration/utilities/paths.cake, tests/integration/utilities/xunit.cake, tests/integration/windows.cake
This is currently a work in progress where I try to add the initial code for our integration tests. Expect things to change until this is ready.
```
./tests/integration/build.ps1
```
````
./tests/integration/build.sh
```
```
./tests/integration/build.ps1 -Target "Cake.Common.IO.DirectoryAliases.CreateDirectory"
```
```
./tests/integration/build.sh -t "Cake.Common.IO.DirectoryAliases.CreateDirectory"
```
````
./tests/integration/build.ps1 -SkipBuildingCake
```
```
./tests/integration/build.sh -s
```
This require Cake to be present somewhere under `./build/`.
Closes #362
=> Integration tests

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> (GH-850) Added Issue and PR Templates

src/Cake/Commands/HelpCommand.cs
=> (GH-852) Added information about mono flag

build.cake
=> (GH-859) Upload nuget/choco artifacts

build.cake
=> (GH-860) Attempt all publishing tasks

build/paths.cake
=> (GH-875) Added Cake.pdb to zip file

.gitignore, build.cake
* Added polly addin
* Added Restore policy & handling when invoking NuGetRestore alias
* Added Tooltimeout to the NuGetRestore NuGetRestoreSettings
This fixes  #881
=> Restore-NuGet-Packages retry handling

src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs, src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs, src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
Hi.
A small PR to add 2 options on OpenCover settings and runner.
Regards
=> Added register and return target code offset opencover options

src/Cake/Scripting/Roslyn/Nightly/DebugRoslynNightlyScriptSession.cs, src/Cake/Scripting/Roslyn/Stable/DebugRoslynScriptSession.cs
Makes the style cop gods happy by specified culture to string.Format
=> Specify culture for Roslyn debug string formats

src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs
* Added InvariantCulture to ReturnTargetCodeOffset ToString to avoid globalization issues
* Removed white space from DirectoryAliases
Fixes some minors missed in PR review.
=> Fix globalization & white space issue

src/Cake.Common/Tools/ILMerge/ILMergeAliases.cs, src/Cake.Common/Tools/ILRepack/ILRepackAliases.cs
- About how to include the necessary tool to get the aliases working correctly
Relates to #601
=> Added information to summary tag

nuspec/Cake.Common.nuspec
=> Added developmentDependency flag to Cake.Common.nuspec

src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, src/Cake.Core/Cake.Core.csproj, src/Cake.Core/Scripting/Analysis/ScriptAnalyzer.cs, src/Cake.Core/Scripting/Processors/BreakDirectiveProcessor.cs, src/Cake.Core/Scripting/Processors/LineProcessor.cs, src/Cake.Core/Scripting/Processors/LoadDirectiveProcessor.cs, src/Cake.Core/Scripting/Processors/ReferenceDirectiveProcessor.cs, src/Cake.Core/Scripting/Processors/ShebangProcessor.cs, src/Cake.Core/Scripting/Processors/UriDirectiveProcessor.cs, src/Cake.Core/Scripting/Processors/UsingStatementProcessor.cs
=> Added #break directive

src/Cake.Common/Tools/GitVersion/GitVersion.cs
Added:
- CommitsSinceVersionSource
- CommitsSinceVersionSourcePadded
- CommitDate
=> Add missing GitVersion return values

src/Cake.Common/Tools/GitVersion/GitVersion.cs
=> Added missing GitVersion Variables

src/Cake.Common/Tools/DNU/DNUAliases.cs
=> Obsoleted DNU Aliases

src/Cake.Common/Tools/ILMerge/ILMergeAliases.cs
=> Corrected summary documentation

src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
=> GH897: Adds support for DevelopmentDependency to NuGetPackSettings

src/Cake.Core/Tooling/ToolRepository.cs
=> Cake.Core.Tooling.ToolRepository.Register(FilePath) path null check

src/Cake.Core/Tooling/Tool.cs
=> GH937: Corrected Obsolete Documentation

build/parameters.cake
=> Fixes invalid AppVeyor check in parameters.cake

src/Cake.Common.Tests/Fixtures/AssemblyInfoParserFixture.cs, src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoParser.cs
=> GH943: Correcting AssemblyInfo Parsing

src/Cake.Core/Properties/Namespaces.cs
=> GH951: Added namespace docs for Cake.Core.Tooling.

build.cake
=> Use new Setup defintion

src/Cake.Core/Modules/CoreModule.cs, src/Cake.NuGet/NuGetModule.cs, src/Cake/Composition/ContainerRegistry.cs, src/Cake/Modules/ArgumentsModule.cs, src/Cake/Modules/CakeModule.cs, src/Cake/Modules/ConfigurationModule.cs, src/Cake/Modules/ScriptingModule.cs
=> Added parameter null checks

src/Cake.Common/Xml/XmlPokeAliases.cs
=> Removed obsoleted XmlPoke aliases

GitReleaseManager.yaml
=> GH980: Support Breaking change in GitReleaseManager

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
=> GH900: Fix AnyCPU platform target when building a project

src/Cake.Common.Tests/Unit/Tools/MSTest/MSTestRunnerTests.cs, src/Cake.Common/Tools/MSTest/MSTestRunner.cs, src/Cake.Common/Tools/MSTest/MSTestSettings.cs
Resolves #421 
Picking up on @marcosnz 's original PR #527 but including @patriksvensson 's feedback. Let me know if it needs any more work.
Hopefully this time I've got branches and commits right :)
=> GH421: Add support for testsettings file to MSTestRunner

src/Cake.Common/Tools/DotNetBuildAliases.cs
=> resolved error in documentation example

build.cake
=> GH923: Increase log verbosity on main branch.

src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs
* CA1062: Validate arguments of public methods
=> Fix OctoPush alias CA1062

src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs
=> Fix OctopusDeploy addin doc

GitReleaseManager.yaml, appveyor.yml, build.cake
=> GH1040: Added new GitReleaseManager

src/Cake.Common.Tests/Fixtures/Tools/GitVersionRunnerFixture.cs, src/Cake.Common.Tests/Fixtures/XmlPokeFixture.cs, src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs, src/Cake.Common.Tests/Unit/XML/XmlTransformationTests.cs, src/Cake.Core.Tests/Fixtures/MethodAliasGeneratorFixture.cs, src/Cake.Core.Tests/Fixtures/PropertyAliasGeneratorFixture.cs, src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Testing/Extensions/FakeDirectoryExtensions.cs, src/Cake.Testing/Extensions/FakeFileExtensions.cs, src/Cake.Testing/Extensions/FakeFileSystemExtensions.cs, src/Cake.Testing/Extensions/FakeLogExtensions.cs, src/Cake.Testing/Extensions/ToolFixtureExtensions.cs, src/Cake.Testing/FakeConsole.cs, src/Cake.Testing/FakeFileSystemTree.cs, src/Cake.Testing/FakeLog.cs, src/Cake.Testing/Fixtures/ToolFixtureResult.cs, src/Cake.Testing/Fixtures/ToolFixture`2.cs, src/Cake.Testing/Properties/AssemblyInfo.cs, src/Cake.Tests/Fixtures/MonoScriptProcessorFixture.cs
=> GH1044: Fix tests code analyze violations

build.sh
build.sh is broken, can be seen here https://travis-ci.org/cake-build/cake/jobs/145653224
=> Reverted build.sh from changes in commit eb1c4e9

src/Cake.Common/IO/GlobbingAliases.cs
=> GH981: Fixes alias signatures for globbing.

src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptHostTests.cs, src/Cake.Core.Tests/Unit/TaskSetupContextTests.cs, src/Cake.Core.Tests/Unit/TaskTeardownContextTests.cs, src/Cake.Core.Tests/Unit/TeardownContextTests.cs, src/Cake.Core/Cake.Core.csproj, src/Cake.Core/CakeContextAdapter.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/DefaultExecutionStrategy.cs, src/Cake.Core/ICakeEngine.cs, src/Cake.Core/IExecutionStrategy.cs, src/Cake.Core/ITaskSetupContext.cs, src/Cake.Core/ITaskTeardownContext.cs, src/Cake.Core/ITeardownContext.cs, src/Cake.Core/Scripting/IScriptHost.cs, src/Cake.Core/Scripting/ScriptHost.cs, src/Cake.Core/TaskSetupContext.cs, src/Cake.Core/TaskTeardownContext.cs, src/Cake.Core/TeardownContext.cs, src/Cake/Scripting/DryRunExecutionStrategy.cs, src/Cake/Scripting/Mono/CodeGen/CakeBuildScriptImplBase.cs
=> GH1089: Add additional context information to Teardown

src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs
=> GH1115: Changed .csx to .cake

src/Cake.Common.Tests/Fixtures/Tools/NuGet/Pusher/NuGetPusherFixture.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Common/Tools/NuGet/Push/NuGetPusher.cs
=> GH970: Added documentation and logging for NuGetPush

GitVersion.yml
=> GH1139: Changed to alpha tag

bitbucket-pipelines.yml
Updated to an docker image with .NET Core and Mono. Also changed target from the default Travis one.
=> Changed Bitbucket Pipelines to .NET Core docker image

README.md
To me it makes more sense to show pre-release version for MyGet shield.
=> Changed README so MyGet shield shows pre-release package

src/Cake.NuGet/project.json, src/Cake/project.json
=> GH1162: Update to latest NuGet.Core to support netstandard

tests/integration/build.cake, tests/integration/build.ps1, tests/integration/build.sh, tests/integration/utilities/xunit.cake
=> Enabled integration tests on CoreCLR

build.ps1
=> GH1158: Added build.ps1 path & item null checking

src/Cake.Core/Composition/ICakeContainerRegistry.cs, src/Cake/Composition/ContainerRegistry.cs
=> Adds constraint for ICakeContainerRegistry.RegisterInstance<T>

tests/integration/Cake.Common/IO/FileAliases.cake, tests/integration/build.cake, tests/integration/build.ps1, tests/integration/utilities/io.cake
* relates to #1173
* also fixes some inconsistencies and cache issues in build.ps1 and adds some new io convenience methods
=> Adds Cake.Common.FileAliases integration tests

src/Cake.Common/Net/DownloadFileSettings.cs, src/Cake.Common/Net/HttpAliases.cs
=> GH1178: Allow creation of Basic credentials

README.md
@patriksvensson @devlead also, can you take a look at this addition? Thanks!
=> (doc) Add MyGet to thanks section

src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs, src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs, src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
=> GH1188: Added MergeOutput Property

README.md, build.cake, build/credentials.cake, build/parameters.cake, build/paths.cake
=> GH856: Added pushing Code Coverage results

tests/integration/Cake.Common/ReleaseNotesAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/ReleaseNotes.md
=> Adds integration tests for Cake.Common.ReleaseNotesAliases

tests/integration/Cake.Common/Text/TextTransformationAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/Text/customtemplate.txt, tests/integration/resources/Cake.Common/Text/template.txt
=> GH1173: Adds integration tests for Cake.Common.Text.TextTransformationAliases

tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/Tools/Cake/build.cake, tests/integration/resources/Cake.Common/Tools/Cake/test.cake, tests/integration/utilities/xunit.cake
=> GH1173: Adds integration tests for Cake.Common.Tools.Cake.CakeAliases

tests/integration/Cake.Common/Diagnostics/LoggingAliases.cake, tests/integration/build.cake
=> GH1173: Adds integration tests for Cake.Common.Diagnostics.LoggingAliases

tests/integration/Cake.Common/Security/SecurityAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/Security/testfile.txt
=> GH1173: Adds integration tests for Cake.Common.Security.SecurityAliases

tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.common/Greeter.cs, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.common/project.json, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/Tests.cs, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/project.json, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/Program.cs, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/project.json
=> GH1173: Adds integration tests for Cake.Common.Tools.DotNetCore.DotNetCoreAliases

build.cake
=> GH1200: Disable AppVeyor test uploads

src/Cake.Common/Modules/CommonModule.cs, src/Cake.Common/project.json, src/Cake.Core/project.json, src/Cake.NuGet/project.json, src/Cake.Testing/project.json, src/Cake/Program.cs, src/Cake/project.json
=> Fixed debugging of CoreCLR scripts.

build.cake, build/parameters.cake
Relates to #856 
Makes running OpenCover configurable.
=> GH856: Made running OpenCover configurable

build.cake, nuspec/Cake.CoreCLR.symbols.nuspec, nuspec/Cake.symbols.nuspec
=> Adds debugging symbols to Cake & Cake.CoreCLR

build.ps1, build.sh, build/version.cake, src/Cake.Common.Tests/project.json, src/Cake.Common/project.json, src/Cake.Core.Tests/project.json, src/Cake.Core/project.json, src/Cake.NuGet.Tests/project.json, src/Cake.NuGet/project.json, src/Cake.Testing.Xunit/project.json, src/Cake.Testing/project.json, src/Cake.Tests/project.json, src/Cake/project.json
=> GH1230: Add missing assembly properties

nuspec/Cake.CoreCLR.nuspec
=> Added missing files to Cake.CoreCLR.nuspec

src/Cake.Common/Build/AppVeyor/AppVeyorProvider.cs, src/Cake.Common/Build/AppVeyor/Data/AppVeyorEnvironmentInfo.cs, src/Cake.Common/Build/AppVeyor/Data/AppVeyorRepositoryInfo.cs, src/Cake.Common/Build/AppVeyor/IAppVeyorProvider.cs
* aslo validates exit code
* added sample code
* fixes #1241
=> GH1242: Waiting for AppVeyor process to exit

src/Cake.Core/Tooling/ToolResolutionStrategy.cs
=> GH1287: Adds a try-catch around code that reads PATH environment variable

src/Cake.Common.Tests/Fixtures/Build/GoCDFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GoCDInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/GoCD/Data/GoCDEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GoCD/Data/GoCDPipelineInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GoCD/Data/GoCDRepositoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GoCD/Data/GoCDStageInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GoCD/GoCDProviderTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GoCD/Data/GoCDEnvironmentInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDPipelineInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDRepositoryInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDStageInfo.cs, src/Cake.Common/Build/GoCD/GoCDInfo.cs, src/Cake.Common/Build/GoCD/GoCDProvider.cs, src/Cake.Common/Build/GoCD/IGoCDProvider.cs
Added support for Go.CD. See documentation here: https://docs.go.cd/current/faq/environment_variables.html
=> GH1280: Added Go.CD build provider

src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoCreateReleaseTests.cs, src/Cake.Common/Tools/OctopusDeploy/CreateReleaseArgumentBuilder.cs, src/Cake.Common/Tools/OctopusDeploy/CreateReleaseSettings.cs
this is needed to create octopus releases for a specific channel
=> GH1251: added channel param to CreateReleaseArgumentBuilder

src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs, src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Common/IO/DirectoryMover.cs, src/Cake.Core/IO/Directory.cs, src/Cake.Core/IO/IDirectory.cs, src/Cake.Testing/FakeDirectory.cs, src/Cake.Testing/FakeFileSystemTree.cs
Adds new MoveDirectory alias and associated support methods and tests, #260
=> GH260: MoveDirectory alias

README.md
Added a link to the .NET Foundation Contribution License Agreement to the README.
=> Add CLA link to README.

src/Cake.Common.Tests/Unit/Tools/Roundhouse/RoundhouseRunnerTests.cs, src/Cake.Common/Tools/Roundhouse/RoundhouseAliases.cs, src/Cake.Common/Tools/Roundhouse/RoundhouseRunner.cs, src/Cake.Common/Tools/Roundhouse/RoundhouseSettings.cs
Made changes as discussed in the ticket.
=> GH1292: Roundhouse Improvements

src/Cake.Common.Tests/Unit/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporterTests.cs, src/Cake.Common/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReportSettings.cs, src/Cake.Common/Tools/SpecFlow/TestExecutionReport/SpecFlowTestExecutionReporter.cs
=> GH1160: Specflow throws if intercepted process returns non-zero

src/Cake.Common/Tools/OctopusDeploy/CreateReleaseArgumentBuilder.cs, src/Cake.Common/Tools/OctopusDeploy/DeployReleaseArgumentBuilder.cs
=> (GH-1314) Adds CultureInfo.InvariantCulture when converting DateTime to string

src/Cake.Common.Tests/Fixtures/Build/GoCDFixture.cs, src/Cake.Common.Tests/Unit/Build/GoCD/GoCDProviderTests.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GoCD/Data/GoCDBuildCauseInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDHistoryInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDMaterialRevisionsInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDModificationInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDPipelineHistoryInfo.cs, src/Cake.Common/Build/GoCD/GoCDProvider.cs, src/Cake.Common/Build/GoCD/IGoCDProvider.cs
See https://github.com/cake-build/cake/issues/1296
=> GH1296: Add Go.CD build history API call

src/Cake.Common.Tests/Fixtures/Tools/InnoSetupFixture.cs, src/Cake.Common.Tests/Unit/Tools/InnoSetup/InnoSetupAliasesTests.cs, src/Cake.Common.Tests/Unit/Tools/InnoSetup/InnoSetupRunnerTests.cs, src/Cake.Common/Tools/InnoSetup/InnoSetupAliases.cs, src/Cake.Common/Tools/InnoSetup/InnoSetupQuietMode.cs, src/Cake.Common/Tools/InnoSetup/InnoSetupRunner.cs, src/Cake.Common/Tools/InnoSetup/InnoSetupSettings.cs
Fixes #1311
This is a minimal implementation, I haven't implemented mappings for all command-line switches yet.
=> GH1311: Add support for Inno Setup

src/Cake.Core.Tests/Fixtures/GlobberFixture.cs, src/Cake.Core.Tests/Unit/IO/GlobberTests.cs, src/Cake.Core/IO/Globbing/GlobTokenizer.cs
=> GH1312: Added ! to alphanumeric chars allowed in glob

src/Cake.Core/CakeEnvironment.cs
=> GH1319: Warn & ignore, not fail duplicate envvar

src/Cake.Core/Polyfill/ProcessHelper.cs
=> WIP GH1326: Address ProcessStartInfo envvar case sensitivite issue

src/Cake.Core.Tests/Unit/IO/PathTests.cs, src/Cake.Core/IO/Path.cs
=> GH1338: Validate path before using

src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs, src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs, src/Cake.Common/Tools/SignTool/SignToolSignSettings.cs
Just another way to select a certificate
=> GH887: Add certificate subject name setting for SignTool

src/Cake.Common.Tests/Fixtures/IO/FileDeleteFixture.cs
Fixed minor spelling mistake while investigating issue 1317
CreatFile -> CreateFile
=> Fixed Spelling Mistake.

src/Cake.Core/IO/IProcess.cs
=> Fix typo in comment

src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs, src/Cake.Common.Tests/Fixtures/Build/TFBuildInfoFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleaseDeployerFixture.cs, src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployReleaseTests.cs, src/Cake.Common/Build/GitLabCI/GitLabCIProvider.cs, src/Cake.Common/Tools/DotCover/DotCoverSettings.cs, src/Cake.Common/Tools/DotCover/Report/DotCoverReportSettings.cs, src/Cake.Common/Tools/DotCover/Report/DotCoverReporter.cs, src/Cake.Common/Tools/MSBuild/MSBuildFileLoggerOutput.cs, src/Cake.Common/Tools/MSBuild/MSBuildLogger.cs, src/Cake.Common/Tools/SignTool/SignToolDigestAlgorithm.cs, src/Cake.Core/ActionTask.cs, src/Cake.Core/Polyfill/ProcessHelper.cs, src/Cake.Core/Polyfill/UnixNative.cs, src/Cake.Core/Polyfill/WindowsNative.cs, src/Cake.ruleset, src/Cake/Scripting/Roslyn/Nightly/DebugRoslynNightlyScriptSession.cs, src/Cake/Scripting/XPlat/DebugXPlatScriptSession.cs, src/Test.ruleset, src/stylecop.json
=> GH1357: Removed StyleCop SA1633 rule supression

src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs, src/Cake.Common/Tools/XUnit/XUnit2Runner.cs, src/Cake.Common/Tools/XUnit/XUnit2Settings.cs, src/Cake.Common/Tools/XUnit/XUnitRunnerUtilities.cs
=> GH1374: Added option to specify XUnit Report Name

src/Cake.Common/Build/BuildSystemAliases.cs
Adding the missing imports for TeamCity, MyGet, and Bamboo.
=> GH1386: Adding missing NamespaceImports for Build Aliases

src/Cake.Common.Tests/Fixtures/Tools/Chocolatey/Uninstaller/ChocolateyUninstallerFixture.cs, src/Cake.Common.Tests/Unit/Tools/Chocolatey/Uninstall/ChocolateyUninstallerSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/Chocolatey/Uninstall/ChocolateyUninstallerTests.cs, src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs, src/Cake.Common/Tools/Chocolatey/ChocolateySettings.cs, src/Cake.Common/Tools/Chocolatey/ChocolateyTool.cs, src/Cake.Common/Tools/Chocolatey/Install/ChocolateyInstallSettings.cs, src/Cake.Common/Tools/Chocolatey/Install/ChocolateyInstaller.cs, src/Cake.Common/Tools/Chocolatey/Uninstall/ChocolateyUninstallSettings.cs, src/Cake.Common/Tools/Chocolatey/Uninstall/ChocolateyUninstaller.cs, src/Cake.Common/Tools/Chocolatey/Upgrade/ChocolateyUpgradeSettings.cs, src/Cake.Common/Tools/Chocolatey/Upgrade/ChocolateyUpgrader.cs
=> GH1377: Support for uninstall packages using Chocolatey 

src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests_VB.cs, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoExtensionTests.cs, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoExtensionTests_VB.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreatorData.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoCustomAttribute.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettings.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettingsExtensions.cs
Relates to #1381 
**NOTE:** This requires #1380 to be merged first.
=> GH1381: Add ability to create Custom Attributes on AssemblyInfo files

src/Cake.Core/Scripting/CodeGen/ParameterEmitter.cs
=> Make optional parameter codegen Invariant

build.cake, build/credentials.cake, build/parameters.cake
=> GH568: Added Gitter and Twitter Notifications

src/Cake.Testing.Xunit/project.json, src/Cake.Testing/project.json
=> Removes xUnit dependency in Cake.Testing

src/Cake.Common.Tests/Fixtures/Tools/DotCover/Merge/DotCoverMergerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotCover/Merge/DotCoverMergerTests.cs, src/Cake.Common/Tools/DotCover/DotCoverAliases.cs, src/Cake.Common/Tools/DotCover/Merge/DotCoverMergeSettings.cs, src/Cake.Common/Tools/DotCover/Merge/DotCoverMerger.cs
Adds DotCover Merge Alias
Fixes #1301
=> (GH-1301) Adds DotCover Merge

src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs, src/Cake.Core.Tests/Unit/Text/QuoteAwareStringSplitterTests.cs, src/Cake.Core/Scripting/Processors/LineProcessor.cs, src/Cake.Core/Scripting/Processors/Loading/FileLoadDirectiveProvider.cs, src/Cake.Core/Text/QuoteAwareStringSplitter.cs, src/Cake/Program.cs, tests/integration/Cake.Core/Scripting/LoadDirective.cake, tests/integration/build.cake, tests/integration/resources/Cake.Core/Scripting/file with spaces.cake
=> Fixed problems with spaces in #l and #r directives

src/Cake.Common.Tests/Properties/PropertyList-1.0.dtd, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/project.json
This prevents network call in `XmlDocucument.Load` to load the DTD
=> GH1424: Store & Load DTD locally

src/Cake.Common.Tests/Fixtures/Tools/NUnitRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/NUnit/NUnitRunnerTests.cs, src/Cake.Common/Tools/NUnit/NUnitRunner.cs, src/Cake.Common/Tools/NUnit/NUnitSettings.cs
=> GH1466: Support X86 property for NUnit

src/Cake.Common/Tools/GitLink/GitLinkAliases.cs
=> GH1472: Corrected Alias Category Name

src/Cake.Common.Tests/Fixtures/Tools/WiX/HeatFixture.cs, src/Cake.Common/Tools/WiX/Heat/HeatRunner.cs, src/Cake.Common/Tools/WiX/WiXAliases.cs
=> GH1276: Changed WixHeat IEnumerable<FilePath> to FilePath

src/Cake.Common/Tools/GitVersion/GitVersionAliases.cs
=> Fix typos in GitVersion documentation

src/Cake.Testing.Xunit/project.json
Removed the duplicate entries and succesfully performed a build from
Visual Studio and using Cake.  All tests pass.
=> GH1483: Removed the duplicate entries for xunit core

src/Cake.Common.Tests/Fixtures/Tools/Chocolatey/New/ChocolateyNewFixture.cs, src/Cake.Common.Tests/Unit/Tools/Chocolatey/New/ChocolateyNewTests.cs, src/Cake.Common/Tools/Chocolatey/ChocolateyAliases.cs, src/Cake.Common/Tools/Chocolatey/New/ChocolateyNewSettings.cs, src/Cake.Common/Tools/Chocolatey/New/ChocolateyScaffolder.cs
Add new alias for running `choco new`.
Fixes #1492
=> GH1492: Add ChocolateyNew Alias

src/Cake.Common.Tests/Fixtures/Tools/NuGet/Add/NuGetAdderFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/NuGet/Init/NuGetIniterFixture.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Add/NuGetAddSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Add/NuGetAdderTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Init/NuGetInitSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Init/NuGetIniterTests.cs, src/Cake.Common/Tools/NuGet/Add/NuGetAdder.cs, src/Cake.Common/Tools/NuGet/Add/NugetAddSettings.cs, src/Cake.Common/Tools/NuGet/Init/NuGetIniter.cs, src/Cake.Common/Tools/NuGet/Init/NugetInitSettings.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs
This is the implementation for the NuGet Add and Init commands.  Unit tests are included.
=> GH1481: Implementation and unit tests for NuGet Add, Init

src/Cake.Common/Net/HttpAliases.cs
=> GH1501: Fixes typo in DownloadFile XMLDoc

src/Cake.Common/Tools/NuGet/NuGetMSBuildVersion.cs
=> GH1510: Update enum for VS 2017

src/Cake.Common.Tests/Fixtures/Tools/SignToolSignRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs, src/Cake.Common/Tools/SignTool/SignToolSignAliases.cs, src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs
=> GH1513: Sign multiple files at once

src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolSignRunnerTests.cs, src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs
=> Make password optional when using certificate file

src/Cake.Common.Tests/Fixtures/Tools/VSWhere/All/VSWhereAllFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/VSWhere/Latest/VSWhereLatestFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/VSWhere/Legacy/VSWhereLegacyFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/VSWhere/Product/VSWhereProductFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/VSWhere/VSWhereFixture.cs, src/Cake.Common.Tests/Unit/Tools/VSWhere/All/VSWhereAllTests.cs, src/Cake.Common.Tests/Unit/Tools/VSWhere/Latest/VSWhereLatestTests.cs, src/Cake.Common.Tests/Unit/Tools/VSWhere/Legacy/VSWhereLegacyTests.cs, src/Cake.Common.Tests/Unit/Tools/VSWhere/Product/VSWhereProductTests.cs, src/Cake.Common.Tests/Unit/Tools/VSWhere/VSWhereAliasesTests.cs, src/Cake.Common/Tools/VSWhere/All/VSWhereAll.cs, src/Cake.Common/Tools/VSWhere/All/VSWhereAllSettings.cs, src/Cake.Common/Tools/VSWhere/Latest/VSWhereLatest.cs, src/Cake.Common/Tools/VSWhere/Latest/VSWhereLatestSettings.cs, src/Cake.Common/Tools/VSWhere/Legacy/VSWhereLegacy.cs, src/Cake.Common/Tools/VSWhere/Legacy/VSWhereLegacySettings.cs, src/Cake.Common/Tools/VSWhere/Product/VSWhereProduct.cs, src/Cake.Common/Tools/VSWhere/Product/VSWhereProductSettings.cs, src/Cake.Common/Tools/VSWhere/VSWhereAliases.cs, src/Cake.Common/Tools/VSWhere/VSWhereSettings.cs, src/Cake.Common/Tools/VSWhere/VSWhereTool.cs
=> GH1517: add vswhere support

src/Cake.Common/Diagnostics/LoggingAliases.cs
=> GH1532: Categorize logging aliases by level

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
=> (GH-1546) Quote MSBuilder Logger Path

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Execute/DotNetCoreExecutorTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Run/DotNetCoreRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreSettings.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreTool.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreVerbosity.cs, src/Cake.Common/Tools/DotNetCore/Execute/DotNetCoreExecutor.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs, src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs, src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs, src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunner.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
Base pr for #1533, will contain any changes that are cross-cutting between branches.
**Changes:**
* Added new verbosity enum inline with new tooling (common for most commands)
* Added support for diagnostic output
=> GH1533: Common changes for DotNetCore Alias

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Execute/DotNetCoreExecutorTests.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreSettings.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreTool.cs, src/Cake.Common/Tools/DotNetCore/Execute/DotNetCoreExecuteSettings.cs, src/Cake.Common/Tools/DotNetCore/Execute/DotNetCoreExecutor.cs
* Added FrameworkVersion Settings
* Added/Updated unit tests
See  #1533 for more info
=> GH1533: Updated DotNetCoreExecute inline with Tooling v1.0

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
=> GH1533: Updated DotNetCorePublish inline with Tooling v1.0

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs
* Added new arguments as settings and updated packer
* Updated unit tests
=> GH1533: Updated DotNetCorePack inline with Tooling v1.0

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
* Added new arguments as settings and updated tester
* Updated unit tests
=> GH1533: Updated DotNetCoreTest inline with Tooling v1.0

src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Clean/DotNetCoreCleanerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Clean/DotNetCoreCleanTests.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleanSettings.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleaner.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
* Added DotNetCoreClean Alias for `dotnet clean`
* Added unit tests
For more information see #1533
=> GH1533: Added support for `dotnet clean` inline with Tooling v1.0

src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployReleaseTests.cs, src/Cake.Common/Tools/OctopusDeploy/DeployReleaseArgumentBuilder.cs, src/Cake.Common/Tools/OctopusDeploy/OctopusDeployReleaseDeploymentSettings.cs
Added the `channel` argument for the `OctopusDeploy` tool when deploying releases, as detailed in #1587.
=> Added channel argument for Octopus Deploy Release.

src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Push/DotNetCorePusherFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Push/DotNetCorePushTests.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPushSettings.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusher.cs
* Added DotNetCoreNugetPush Alias for dotnet nuget push
* Added unit tests
For more information see #1533
=> GH1533: Added support for dotnet nuget push inline with Tooling v1.0

build.ps1, build.sh, tests/integration/build.sh
=> Update DotNetInstallerUri to https://dot.net/v1/

build.cake, build.ps1, build.sh, src/Cake.Common/Cake.Common.csproj, src/Cake.Core/Cake.Core.csproj, src/Cake.Testing/Cake.Testing.csproj, tests/integration/build.sh
=> (GH-1635) Fix so all nuget packages are created

README.md, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs
=> GH1595: Added Alistair and Martin names

src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Much nicer than having to google for the official documentation.
=> Added documentation link to NUnit3Settings.Where

build.cake, tests/integration/build.sh
* Fixed integration tests artifact copy
* Frixes #1638
=> (GH-1638) Dynamic add .NET Core published files to nuget

build.cake, build/version.cake, tests/integration/build.ps1
* Remove project.json/newtonsoft fallback
* Fallback to solution info
* Fixes #1640
* Fix integration script script link
=> (GH-1640) Fix version fallback

build.cake, build/parameters.cake, src/Cake.NuGet/Cake.NuGet.csproj
=> GH1603: Push Cake.NuGet to MyGet/NuGet

src/Cake.Common/Tools/ReportUnit/ReportUnitAliases.cs
=> GH1654: Fix link to ReportUnit project site

global.json
=> (build) global.json fix

build.cake
=> GH1682: Add version to restore, to fix package reference issue

src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs
Also use FilePath for all overloads
Fixes #1685
=> GH1685: Add DotNetCoreTool settings overload

src/Cake.Core/Polyfill/AssemblyHelper.cs
=> GH1686: Made root path absolute for the AssemblyLoadContext.

src/Cake.Common.Tests/Unit/Tools/Chocolatey/Download/ChocolateyDownloadTests.cs, src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloadSettings.cs, src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloader.cs
Add support for choco download --internalize-all-urls
Fixes #1667
=> GH1667: Add support for choco download --internalize-all-urls

src/Cake.Common/Build/TeamCity/Data/TeamCityEnvironmentInfo.cs
This just changes the inheritance to the correct abstract class.
=> GH1614:  Corrected inheritance issue.

src/Cake.Core/CakeContextAdapter.cs
=> GH1697: Add ICakeContext to CakeContextAdapter

src/Cake.Core/Polyfill/ProcessHelper.cs
=> GH1693: Fix key not used when setting process environment variable

src/Cake.Common/Xml/XmlPeekAliases.cs
=> GH1727: Corrected documentation for XmlPeek alias

src/Cake.NuGet.Tests/Fixtures/NuGetPackageInstallerFixture.cs, src/Cake.NuGet.Tests/Unit/NuGetPackageInstallerTests.cs, src/Cake.NuGet/NuGetPackageInstaller.cs
If a version is specified when using either `#load`, `#tool` or `#addin`,
the package folder on disk will be suffixed with the version number.
Not specifying a version will keep the current behavior.
Closes #1572
=> GH753: Version NuGet package references on disk.

src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptProcessorTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs, src/Cake.Core/Scripting/IScriptProcessor.cs, src/Cake.Core/Scripting/ScriptProcessor.cs, src/Cake.Core/Scripting/ScriptRunner.cs
- No need to pass the whole analyzer result.
- Fixes #1745
=> GH1745: Change signature of methods for IScriptProcessor

src/Cake.Common/Net/HttpAliases.cs
=> GH1752: Add AutomaticDecompression to HttpClientHandler

src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs, src/Cake.Core.Tests/Unit/IO/PathTests.cs, src/Cake.Core.Tests/Unit/Text/TextTransformationTemplateTests.cs
This PR fixes #1742.
The issue prevent non-English developers from contributing this great product!
=> GH1742: Fix locale-sensitive unit tests

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildFileLogger.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildVerbosityExtensions.cs
=> GH1602: Fix MSBuild file logger verbosity issue

src/Cake.sln
The nuspec solution items had incorrect paths. This PR fixes that.
=> Fix nuspec solution item paths

src/Cake.Core/Constants.cs
=> GH1785: Bump LatestBreakingChange to 0.22.0

src/Cake/App.config
=> Update target framework in app.config

src/Cake.Core/Reflection/AssemblyVerifier.cs
* Adds opt-out configuration information in error message
* Outputs detailed debug information about assemblies that verifier would throw on if enabled
* fixes #1787
If opt-out you see something like this so you know which assemblies are referencing the wrong Cake version
On error it'll just as before fail & throw on first assembly
=> GH1787: Detailed assembly version verification message

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildBinaryLogImports.cs, src/Cake.Common/Tools/MSBuild/MSBuildBinaryLogSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs
Option to enable binary logging for feature request #1791
=> GH1791: Add option for MSBuild binary logging (msbuild 15.3+)

src/Cake.Common.Tests/Fixtures/Build/JenkinsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsChangeInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsJobInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsNodeInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsRepositoryInfoTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/JenkinsEnvironmentInfoTests.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsBuildInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsChangeInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsEnvironmentInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsJobInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsNodeInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsRepositoryInfo.cs
=> GH1719: Cleaned old and added new Jenkins variables

src/Cake.Common.Tests/Unit/Tools/OpenCover/OpenCoverTests.cs, src/Cake.Common/Tools/OpenCover/OpenCoverLogLevel.cs, src/Cake.Common/Tools/OpenCover/OpenCoverRunner.cs, src/Cake.Common/Tools/OpenCover/OpenCoverSettings.cs
=> GH1670: Added more arguments to OpenCoverSettings

src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
Fixes #1807 
Not sure which branch I should target, so I picked the hotfix branch for the moment. Feel free to update as required.
=> Fix mappings for NuGetVersion and CommitDate. 

src/Cake.Core/Scripting/ScriptAliasFinder.cs, src/Cake/Scripting/Roslyn/RoslynScriptSession.cs
=> Do not add null namespace for aliases.

src/Cake.NuGet.Tests/Unit/NuGetPackageInstallerTests.cs, src/Cake.NuGet/NuGetPackageInstaller.cs, src/Cake.sln.DotSettings
=> GH1757: Remove installation folder if nuget install fails.

src/Cake.Core.Tests/Fixtures/ScriptHostFixture.cs, src/Cake.Core.Tests/Unit/ActionTaskTests.cs, src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs, src/Cake.Core/ActionTask.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/CakeTask.cs, src/Cake.Core/CakeTaskBuilderExtensions.cs, src/Cake.Core/DefaultExecutionStrategy.cs, src/Cake.Core/ICakeEngine.cs, src/Cake.Core/IExecutionStrategy.cs, src/Cake.Core/Scripting/IScriptHost.cs, src/Cake.Core/Scripting/ScriptHost.cs, src/Cake.Tests/Unit/Scripting/BuildScriptHostTests.cs, src/Cake.Tests/Unit/Scripting/DescriptionScriptHostTests.cs, src/Cake.Tests/Unit/Scripting/DryRunExecutionStrategyTests.cs, src/Cake.Tests/Unit/Scripting/DryRunScriptHostTests.cs, src/Cake/Scripting/BuildScriptHost.cs, src/Cake/Scripting/DescriptionScriptHost.cs, src/Cake/Scripting/DryRunExecutionStrategy.cs, src/Cake/Scripting/DryRunScriptHost.cs, tests/integration/Cake.Common/IO/FileAsync.cake, tests/integration/build.cake
Issue: https://github.com/cake-build/cake/issues/1032
I have some time inbetween jobs so trying to do this as I attempted to do an async Task.
I'm confused on how to test out an actual script.  I tried to do an integration test.
I went the route of "async by default" so the execute of the `ActionTask` transforms an Action into a Func<Task> then just handle it from there.
=> GH1032: Support Async tasks

signclient.filter
=> GH1816: Sign net46 nuget content

src/Cake.NuGet/Install/NuGetFolderProject.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs
=> GH1801: Set correct Target Framework when installing addins.

src/Cake.NuGet/Install/NuGetFolderProject.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs, src/Cake.NuGet/Install/NuGetProjectContext.cs, src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
=> GH1825: Share project for same package type (addins/tools)

build.cake, build.ps1, build.sh
=> GH1810: Updated to Cake 0.22.x compat addins

src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs, src/Cake.Common/Tools/GitVersion/GitVersion.cs, src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs
=> GH1805: Change GitVersion settings to use nullable integer

src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildConsoleColorType.cs, src/Cake.Common/Tools/GitVersion/GitVersionInternal.cs, src/Cake.Common/Tools/MSBuild/MSBuildVerbosityExtensions.cs, src/Cake.Common/Tools/NUnit/NUnit3Result.cs, src/Cake.Core.Tests/Unit/CakeRuntimeTests.cs, src/Cake.NuGet/Install/NuGetFolderProject.cs, src/Cake.NuGet/Install/NuGetLogger.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs, src/Cake.NuGet/Install/NuGetProjectContext.cs, src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
Some files were missing license headers, I'll go a head an merge if CI's successful.
=> (build) Add missing license headers

src/Cake.Core.Tests/Unit/Packaging/PackageReferenceTests.cs, src/Cake.Core/Extensions/UriExtensions.cs
=> GH1842: URI params are case insensitive.

src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs, src/Cake.NuGet/NuGetContentResolver.cs
=> GH1843: Don't load reference assemblies

src/Cake.Common.Tests/Fixtures/Tools/NuGet/List/NuGetListFixture.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/List/NuGetListSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/List/NuGetListTests.cs, src/Cake.Common/Tools/NuGet/List/NuGetList.cs, src/Cake.Common/Tools/NuGet/List/NuGetListItem.cs, src/Cake.Common/Tools/NuGet/List/NuGetListSettings.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs
- fixes #1821 
Added an implementation for the NuGet list method. Only the non-verbose output is used.
=> GH1821: Implement NuGet list

src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerResultTests.cs, src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptTests.cs, src/Cake.Core/Scripting/Analysis/IScriptInformation.cs, src/Cake.Core/Scripting/Analysis/ScriptAnalyzerResult.cs, src/Cake.Core/Scripting/Analysis/ScriptInformation.cs, src/Cake.Core/Scripting/Processors/UsingStatementProcessor.cs, src/Cake.Core/Scripting/Script.cs, src/Cake.Core/Scripting/ScriptRunner.cs, src/Cake/Cake.csproj, src/Cake/Scripting/Roslyn/RoslynCodeGenerator.cs, tests/integration/Cake.Core/Scripting/UsingDirective.cake, tests/integration/build.cake
* fixes #1853
* updates Microsoft.CodeAnalysis.CSharp.Scripting to 2.3.2
=> GH1853: Adds using static directive support

src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerResultTests.cs, src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptTests.cs, src/Cake.Core/Scripting/Analysis/IScriptInformation.cs, src/Cake.Core/Scripting/Analysis/ScriptAnalyzer.cs, src/Cake.Core/Scripting/Analysis/ScriptAnalyzerResult.cs, src/Cake.Core/Scripting/Analysis/ScriptInformation.cs, src/Cake.Core/Scripting/Processors/DefineDirectiveProcessor.cs, src/Cake.Core/Scripting/Script.cs, src/Cake.Core/Scripting/ScriptRunner.cs, src/Cake/Scripting/Roslyn/RoslynCodeGenerator.cs, tests/integration/Cake.Core/Scripting/DefineDirective.cake, tests/integration/build.cake
=> GH1766: Adds define directive

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
=> GH1856: Adds support for MSBuild warnaserror & warnasmessage

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs, src/Cake.Common/Tools/MSBuild/MSBuildPropertyExtensions.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs
=> GH1404: Escape space in properties

.travis.yml, build.ps1, build.sh, global.json, src/Cake/Cake.csproj, src/Shared.msbuild, tests/integration/build.ps1, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/hwapp.tests.csproj, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/hwapp.csproj
* fixes #1880
* Updated Roslyn Scripting to 2.4.0
=> GH1880: Update to .NET Core 1.0.7 & SDK 1.1.4

src/Cake.Common.Tests/Unit/Tools/NUnit/NUnit3RunnerTests.cs, src/Cake.Common/Tools/NUnit/NUnit3Labels.cs, src/Cake.Common/Tools/NUnit/NUnit3Settings.cs
Adding Before and After options for NUnit3Labels enum with tests.
Relates to #1653.
=> GH1653: Adding Before and After options

src/Cake.Common.Tests/Fixtures/XmlPokeFixture.cs, src/Cake.Common.Tests/Unit/XML/XmlPokeTests.cs, src/Cake.Common/Xml/XmlPokeAliases.cs
=> Used encoding with XmlPoke

src/Cake.Common.Tests/Fixtures/Tools/SignToolResolverFixture.cs, src/Cake.Common.Tests/Unit/Tools/SignTool/SignToolResolverTests.cs, src/Cake.Common/Tools/SignTool/SignToolResolver.cs
Relates to #1855.
I did not add any ARM paths.  I didn't see the best way to handle that as there isn't any explicit ARM flags inside of the environment that I could find.
=> GH1855: Adding support for additional locations.

src/Cake.Common.Tests/Unit/Tools/NUnit/NUnitRunnerTests.cs, src/Cake.Common/Tools/NUnit/NUnitRunner.cs, src/Cake.Common/Tools/NUnit/NUnitSettings.cs
Labels switch was added along with tests.
=> GH1833: Added support for NUnit2 labels

build.ps1, build.sh, global.json, src/Shared.msbuild, tests/integration/build.ps1, tests/integration/build.sh, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/hwapp.tests.csproj, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/hwapp.csproj
=> GH1918: Update to .NET Core 1.0.8 / SDK 1.1.5

src/Cake.Core/IO/ProcessRunner.cs
=> GH1915: Working directory is now optional

build.cake
* Updates SignTool to 0.9.1
* Fixes #1809
=> GH1809: Use tool resolution for SignClient

src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackSettingsTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
#1946 Add nuget pack option for redirecting to the tools folder
=> GH1946: Expose the Tool nuget pack option in Cake

src/Cake/Cake.csproj
=> GH1960: Update Roslyn to 2.6.1

src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs, src/Cake.Core/IO/Path.cs
=> GH1652: Remove redundant UNIX compile time checks

src/Cake.Common/Build/AppVeyor/Data/AppVeyorEnvironmentInfo.cs, src/Cake.Common/Build/Bamboo/Data/BambooEnvironmentInfo.cs, src/Cake.Common/Build/BitbucketPipelines/Data/BitbucketPipelinesEnvironmentInfo.cs, src/Cake.Common/Build/Bitrise/Data/BitriseEnvironmentInfo.cs, src/Cake.Common/Build/ContinuaCI/Data/ContinuaCIEnvironmentInfo.cs, src/Cake.Common/Build/GitLabCI/Data/GitLabCIEnvironmentInfo.cs, src/Cake.Common/Build/GoCD/Data/GoCDEnvironmentInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsEnvironmentInfo.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildEnvironmentInfo.cs, src/Cake.Common/Build/TeamCity/Data/TeamCityEnvironmentInfo.cs, src/Cake.Common/Build/TravisCI/Data/TravisCIEnvironmentInfo.cs
Just wanted to get this out there to make sure that the documentation is exactly what is expected before I do the rest. Fixes #1811 @devlead
=> GH1811: Adding examples for build properties.

src/Cake.NuGet/Install/NuGetPackageInstaller.cs
=> GH1924: Set User Agent string for in-process NuGet

src/Cake.Core/Modules/CoreModule.cs, src/Cake.Core/Reflection/AssemblyLoader.cs, src/Cake.Core/Reflection/AssemblyVerifier.cs, src/Cake.Core/Reflection/IAssemblyVerifier.cs
Fixes #1968
Please review this small changes.
Thank you in advance.
=> GH1968: Add interface for AssemblyVerifier so that it can be mocked

src/Cake.Common.Tests/Unit/Tools/DotCover/Cover/DotCoverCovererTests.cs, src/Cake.Common/Tools/DotCover/DotCoverCoverageSettings.cs, src/Cake.Common/Tools/DotCover/DotCoverCoverageSettingsExtensions.cs, src/Cake.Common/Tools/DotCover/DotCoverCoverageTool.cs
This PR solves issue [#1912](https://github.com/cake-build/cake/issues/1912)
Kind regards,
Ronald
=> GH1912: Add support for processfilter in dotcover

src/Cake.Core/Scripting/ScriptConventions.cs, tests/integration/Cake.Core/Scripting/SystemCollections.cake, tests/integration/build.cake
=> GH1974: Added System.Collections work around for Mono

build.ps1, build.sh, global.json, src/Shared.msbuild, tests/integration/build.ps1, tests/integration/build.sh, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp.tests/hwapp.tests.csproj, tests/integration/resources/Cake.Common/Tools/DotNetCore/hwapp/hwapp.csproj
=> GH1992: Update to .NET Core 1.0.9 / SDK 1.1.7

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildVerbosityExtensionsTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildVerbosityExtensions.cs
=> GH1994: Update MSBuildVerbosityExtensions.cs

src/Cake.NuGet/Install/Extensions/NuGetPackageManagerExtensions.cs, src/Cake.NuGet/Install/NuGetFolderProject.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs, src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
- Fixes #1937
- Borrows some code from NuGet.Client
Pushing just to get reviews.... 😄
=> GH1937: Speed up in-process NuGet

src/Cake.NuGet.Tests/Unit/NuGetModuleTests.cs, src/Cake.NuGet/NuGetModule.cs
Makes new NuGet handling opt-out instead of opt-in, fixes #1995
=> GH1995: Make In-Proc NuGet addin/tool installtion default

src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs, src/Cake.Core/Scripting/Processors/LoadDirectiveProcessor.cs, src/Cake.Core/Scripting/Processors/UriDirectiveProcessor.cs, tests/integration/Cake.Core/Scripting/LoadDirective.cake, tests/integration/build.ps1
Expanding environment vaariables in `UriDirectiveProcessor`.
=> [Proof of concept] Expand environment variables during preprocess

build.cake
=> GH2058: Update GitReleaseManager to 0.7.0

src/Cake.Core/Scripting/ScriptConventions.cs, tests/integration/Cake.Core/Scripting/AddinDirective.cake, tests/integration/build.cake, tests/integration/resources/Cake.Core/Scripting/netstandard2.addin/MyCakeExtension.cs, tests/integration/resources/Cake.Core/Scripting/netstandard2.addin/netstandard2.addin.csproj
=> GH2063: Adds netstandard 2 to script conventions

src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoCreatorTests.cs, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoExtensionTests.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreator.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoCreatorData.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoMetadataAttribute.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettings.cs, src/Cake.Common/Solution/Project/Properties/AssemblyInfoSettingsExtensions.cs
This pull request implement the feature request #2003. The unit tests are extended for the new assembly info attribute.
=> GH2003: Support for AssemblyMetadata attributes in CreateAssemblyInfo

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Added support directly from settings API for the MSBuild /restore option. Fix for issue https://github.com/cake-build/cake/issues/2051
=> GH2051: Added support for recently added MSBuild.exe /restore option

src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
=> GH2079: Set default nuget sources

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs, src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs, src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestorer.cs
=> GH1887: Adds a mapping for the --force option of dotnet restore

src/Cake/Commands/HelpCommand.cs
Made small improvement according to issue #2036. Please review. Thx
=> GH2036: Outputted how to invoke the help command when an error occurred

build.cake, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.NuGet/Install/Extensions/NuGetPackageManagerExtensions.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs, src/Cake.NuGet/Install/NuGetProjectContext.cs, src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs
=> Update NuGet.Client libraries to 4.6.0

src/Cake.Core/Cake.Core.csproj, src/Cake/Scripting/Roslyn/RoslynScriptSession.cs, src/Cake/Scripting/Roslyn/ScriptAssemblyResolver.cs
=> GH2116: Updates Newtonsoft.Json package to latest and adds a runtime assembly resolver

src/Cake.NuGet/Install/Extensions/NuGetPackageManagerExtensions.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs
- Fixes #2113 
Should speed up things, and make it more pleasant to work offline...
Merge #2114 first....
=> GH2113: Check local NuGet sources before trying remote

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs, tests/integration/Cake.Core/Scripting/AddinDirective.cake
Missing DotNetCorePublishSettings added
* Force
* SelfContained
* Sources
* Fixes #2119
=> GH2119: Added missing .NET Core publish parameters

src/Cake/Cake.csproj
=> GH2163: Update Roslyn to 2.8.2

src/Cake.Common/Xml/XmlPokeAliases.cs
Resolves https://github.com/cake-build/website/issues/520
=> Fixes closing </example> tags in XML comments

src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core/CakeDataService.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/CakeEngineActions.cs, src/Cake.Core/CakeReport.cs, src/Cake.Core/CakeReportEntry.cs, src/Cake.Core/CakeReportEntryCategory.cs, src/Cake.Core/CakeReportPrinter.cs, src/Cake.Core/ICakeDataService.cs, tests/integration/setup.cake, tests/integration/teardown.cake, tests/integration/utilities/context.cake
* Also fixed formatting in report for certain items.
Closes #2174
=> Added support for multiple Setup/Teardown.

src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core/CakeEngine.cs
=> Only show skipped tasks once in the report.

src/Cake.NuGet/Install/NuGetFolderProject.cs, src/Cake.NuGet/Install/NuGetPackageInstaller.cs
=> Package referencing Cake.Core or Cake.Common should not yield warning.

src/Cake.Common.Tests/Fixtures/Tools/OctopusDeployReleasePromoterFixture.cs, src/Cake.Common.Tests/Unit/Tools/OctopusDeploy/OctoDeployPromoteTests.cs, src/Cake.Common/Tools/OctopusDeploy/OctopusDeployAliases.cs, src/Cake.Common/Tools/OctopusDeploy/OctopusDeployPromoteReleaseSettings.cs, src/Cake.Common/Tools/OctopusDeploy/OctopusDeployReleasePromoter.cs, src/Cake.Common/Tools/OctopusDeploy/PromoteReleaseArgumentBuilder.cs
Added Octopus Deploy Promote release support.
=> GH2203: Feature/octo promote

README.md, nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.CoreCLR.symbols.nuspec, nuspec/Cake.Portable.nuspec, nuspec/Cake.nuspec, nuspec/Cake.symbols.nuspec, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs, src/Shared.msbuild
Think I have got all the required places
=> GH2193: Added new maintainers

src/Cake.Core.Tests/Fixtures/ScriptHostFixture.cs, src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/ExecutionSettings.cs, src/Cake.Core/ICakeEngine.cs, src/Cake.Core/Scripting/ScriptHost.cs, src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs, src/Cake.Tests/Unit/Scripting/BuildScriptHostTests.cs, src/Cake.Tests/Unit/Scripting/DescriptionScriptHostTests.cs, src/Cake.Tests/Unit/Scripting/DryRunScriptHostTests.cs, src/Cake/Arguments/ArgumentParser.cs, src/Cake/CakeOptions.cs, src/Cake/Commands/BuildCommand.cs, src/Cake/Scripting/BuildScriptHost.cs, src/Cake/Scripting/DryRunScriptHost.cs
=> GH-2094: Allow execution of single task (without dependencies)

src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.NuGet/Install/NuGetProjectContext.cs
=> GH2207: Update to NuGet 4.7.0

src/Cake.Common.Tests/CrossCutting/ToolSettingsTests.cs, src/Cake.Common/Tools/Cake/CakeSettings.cs, src/Cake.Common/Tools/DupFinder/DupFinderSettings.cs, src/Cake.Common/Tools/ILRepack/ILRepackSettings.cs, src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs, src/Cake.Common/Tools/NSIS/MakeNSISSettings.cs, src/Cake.Common/Tools/NUnit/NUnit3Settings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/OctopusDeploy/CreateReleaseSettings.cs, src/Cake.Common/Tools/WiX/CandleSettings.cs, src/Cake.Common/Tools/WiX/LightSettings.cs, src/Cake.Core/Tooling/ToolSettings.cs, src/Cake.Testing/Extensions/ReflectionExtensions.cs, src/Cake.Testing/MemberTestInfo.cs, src/Cake.Testing/MemberTestingUtils.cs
Fixes #2146 
Only eleven properties needed to be changed! I had run into four of them in real life.
=> GH2146: Enabled initializer syntax for all collection properties

src/Cake/Commands/HelpCommand.cs
=> GH2233: Documented bootstrap argument

src/Cake.Common/DryRunAliases.cs, src/Cake/Scripting/DryRunExecutionStrategy.cs
=> GH2208: Execute setup and teardown when dry running script.

nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.CoreCLR.symbols.nuspec, nuspec/Cake.nuspec, nuspec/Cake.symbols.nuspec
Add repository metadata to NuGet packages
Fixes #2238
=> (GH-2238) Add repository metadata to NuGet packages

build.cake, src/Cake/Cake.csproj
=> GH2265: Update Roslyn to 2.9.0

src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
=> Add NuGetPackSettings.VersionSuffix option.

build.sh, src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptRunnerTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/Scripting/ScriptRunner.cs, src/Cake.NuGet/NuGetPackageInstaller.cs, tests/integration/build.ps1, tests/integration/build.sh
Continues on from https://github.com/cake-build/cake/pull/1835 and fixed #2267
=> GH2267: Fix more 'occured' and 'occuring' typos

src/Cake.Core.Tests/Fixtures/ScriptProcessorFixture.cs, src/Cake.Core/Constants.cs, src/Cake.Core/Scripting/ScriptProcessor.cs
Please review. If it will be ok then I add some unit tests. #2255
Thanks in advance.
=> GH2259: Show warning when referenced package is missing version number

.gitignore, src/Cake.Tests/Unit/Arguments/ArgumentParserTests.cs, src/Cake.Tests/Unit/CakeApplicationTests.cs, src/Cake/Arguments/ArgumentParser.cs, src/Cake/CakeApplication.cs, src/Cake/CakeOptions.cs, src/Cake/Commands/CommandFactory.cs, src/Cake/Commands/HelpCommand.cs, src/Cake/Commands/ICommandFactory.cs, src/Cake/Commands/InfoCommand.cs, src/Cake/Commands/VersionCommand.cs, src/Cake/Modules/CakeModule.cs
Closes #2277 
Additional work will be required to augment the "new" info command with additional information, as per discussions in meeting, however, a design document will be created with details about what should be included.
=> GH2277: Add basic implementation of info command

nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.CoreCLR.symbols.nuspec, nuspec/Cake.nuspec, nuspec/Cake.symbols.nuspec, src/Shared.msbuild
=> GH2246: Add & unify nupkg project urls

src/Cake.Common.Tests/Fixtures/IO/FileCopyFixture.cs, src/Cake.Common.Tests/Fixtures/IO/FileDeleteFixture.cs, src/Cake.Common.Tests/Fixtures/XmlDocExampleCodeParserFixture.cs, src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Common/IO/FileCopier.cs, src/Cake.Common/IO/GlobbingAliases.cs, src/Cake.Core.Tests/Fixtures/GlobberFixture.cs, src/Cake.Core/IO/Globber.cs, src/Cake.Core/IO/GlobberExtensions.cs, src/Cake.Core/IO/GlobberSettings.cs, src/Cake.Core/IO/Globbing/GlobParser.cs, src/Cake.Core/IO/Globbing/GlobVisitor.cs, src/Cake.Core/IO/IGlobber.cs
=> GH2198: Adds settings for globber

src/Cake.Core.Tests/Extensions/StringExtensions.cs, src/Cake.Core.Tests/Fixtures/GlobberFixture.cs, src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs, src/Cake.Core.Tests/Unit/IO/FilePathTests.cs, src/Cake.Core.Tests/Unit/IO/Globbing/GlobberTests.cs, src/Cake.Core.Tests/Unit/IO/Globbing/UncGlobberTests.cs, src/Cake.Core.Tests/Unit/IO/Globbing/WindowsGlobberTests.cs, src/Cake.Core.Tests/Unit/IO/PathTests.cs, src/Cake.Core/IO/FilePath.cs, src/Cake.Core/IO/Globbing/GlobNodeRewriter.cs, src/Cake.Core/IO/Globbing/GlobNodeValidator.cs, src/Cake.Core/IO/Globbing/GlobParser.cs, src/Cake.Core/IO/Globbing/GlobParserContext.cs, src/Cake.Core/IO/Globbing/GlobTokenBuffer.cs, src/Cake.Core/IO/Globbing/GlobTokenizer.cs, src/Cake.Core/IO/Globbing/GlobVisitor.cs, src/Cake.Core/IO/Globbing/GlobVisitorContext.cs, src/Cake.Core/IO/Globbing/Nodes/PathNode.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/BraceExpansionSegment.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/BracketWildcardSegment.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/CharacterWildcardSegment.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/PathSegment.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/TextSegment.cs, src/Cake.Core/IO/Globbing/Nodes/Segments/WildcardSegment.cs, src/Cake.Core/IO/Globbing/Nodes/UncRootNode.cs, src/Cake.Core/IO/Path.cs, src/Cake.Core/IO/PathHelper.cs, src/Cake.Core/IO/RelativePathResolver.cs
- Adds UNC support for paths
- Adds UNC support for globbing
Closes #2200
Closes #2105
Closes #1883
Closes #720
=> GH2200: Adds UNC support

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
- Always output value for parameter "--self-contained"
Fixes #2342
=> Output default value for IsSelfContained

src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2RunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/XUnit/XUnit2SettingsTests.cs, src/Cake.Common/Tools/XUnit/XUnit2Runner.cs, src/Cake.Common/Tools/XUnit/XUnit2Settings.cs
Add JUnit support for output format to XUnit2Runner descriped in issue #2341
=> Add JUnit support for output format to XUnit2Runner #2341

ReleaseNotes.md, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusher.cs, src/Cake.Core/Extensions/UriExtensions.cs, src/Cake.Core/IO/Path.cs
Ran into a few in the last PR.
=> It's → its

src/Cake.Common/Build/BuildSystem.cs
=> Fix typo in example

src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
=> GH2387: Add additional Tool names for GitVersion

src/Cake.NuGet.Tests/Unit/NuGetSourceRepositoryProviderTests.cs, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.NuGet/Install/NuGetPackageInstaller.cs, src/Cake.NuGet/Install/NuGetProjectContext.cs
- Fixes #2272
Didn't have time to fix the tests... At least @pascalberger can test the artifact.
=> GH2272: Update NuGet to 4.9.1

src/Cake/Cake.csproj
=> GH2369: Update Roslyn to 2.10.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH2391: Updated to NuGet 4.9.2 client libs

src/Cake.Common.Tests/CrossCutting/ToolSettingsTests.cs, src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyPackSettings.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs, src/Cake.Common/Tools/DotNetCore/Restore/DotNetCoreRestoreSettings.cs, src/Cake.Common/Tools/NUnit/NUnit3Settings.cs, src/Cake.Common/Tools/NuGet/Install/NugetInstallSettings.cs, src/Cake.Common/Tools/NuGet/List/NuGetListSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs, src/Cake.Common/Tools/NuGet/Restore/NugetRestoreSettings.cs, src/Cake.Common/Tools/NuGet/Update/NuGetUpdateSettings.cs, src/Cake.Common/Tools/OctopusDeploy/OctopusPackSettings.cs, src/Cake.Common/Tools/ReportGenerator/ReportGeneratorSettings.cs, src/Cake.Testing/Extensions/ReflectionExtensions.cs
Actually fixes #2146. Missed a few (27) in https://github.com/cake-build/cake/pull/2147. I thought something was missing at the time. 🤦‍♂️
=> GH2146: Enabled initializer syntax for all collection properties (for real this time)

src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerTool.cs
=> (GH-2417) Add additional Tool names for GitReleaseManager

src/Cake.Common.Tests/Fixtures/Build/TFBuildFixture.cs, src/Cake.Common.Tests/Unit/Build/TFBuild/TFBuildCommandTests.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildPublishCodeCoverageData.cs, src/Cake.Common/Build/TFBuild/ITFBuildCommands.cs, src/Cake.Common/Build/TFBuild/TFBuildCommands.cs
=> (GH-2412) Added PublishCodeCoverage overloads

src/Cake.Common.Tests/Unit/Tools/TextTransform/TextTransformRunnerTests.cs, src/Cake.Common/Tools/TextTransform/TextTransformRunner.cs, src/Cake.Common/Tools/TextTransform/TextTransformSettings.cs, tests/integration/Cake.Common/Tools/TextTransform/TextTransformAliases.cake, tests/integration/build.cake, tests/integration/resources/Cake.Common/Tools/TextTransform/HelloWorld.tt
* Adds t4 & t4.exe for tool resolution
* Adds Properties & Class to TextTransformSettings
* Integration tests for TransformTemplate
* Fixes #2410
=> GH2410: T4 Global tool support

src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerLabellerFixture.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Label/GitReleaseManagerLabellerTests.cs, src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerAliases.cs, src/Cake.Common/Tools/GitReleaseManager/Label/GitReleaseManagerLabelSettings.cs, src/Cake.Common/Tools/GitReleaseManager/Label/GitReleaseManagerLabeller.cs
=> GH2420: Added new label alias for GitReleaseManager

src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerAssetsAdderFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerCreatorFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerExporterFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerLabellerFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerMilestoneCloserFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/GitReleaseManager/GitReleaseManagerPublisherFixture.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAssetsAdderTests.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Close/GitReleaseManagerMilestoneCloserTests.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Create/GitReleaseManagerCreatorTests.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Export/GitReleaseManagerExporterTests.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Label/GitReleaseManagerLabellerTests.cs, src/Cake.Common.Tests/Unit/Tools/GitReleaseManager/Publish/GitReleaseManagerPublisherTests.cs, src/Cake.Common/Tools/GitReleaseManager/AddAssets/GitReleaseManagerAssetsAdder.cs, src/Cake.Common/Tools/GitReleaseManager/Close/GitReleaseManagerMilestoneCloser.cs, src/Cake.Common/Tools/GitReleaseManager/Create/GitReleaseManagerCreator.cs, src/Cake.Common/Tools/GitReleaseManager/Export/GitReleaseManagerExporter.cs, src/Cake.Common/Tools/GitReleaseManager/GitReleaseManagerAliases.cs, src/Cake.Common/Tools/GitReleaseManager/Label/GitReleaseManagerLabeller.cs, src/Cake.Common/Tools/GitReleaseManager/Publish/GitReleaseManagerPublisher.cs
This builds on #2420 and will need to rebased once that is merged.
Fixes #2419
=> GH2419: Add token parameter to GitReleaseManager

src/Cake.Common.Tests/Unit/Tools/VSWhere/Latest/VSWhereLatestTests.cs, src/Cake.Common/Tools/VSWhere/Latest/VSWhereLatest.cs, src/Cake.Common/Tools/VSWhere/Latest/VSWhereLatestSettings.cs
- should fix #1973
- has unit tests
=> GH1973: Added "-products" to VSWhereLatestSettings

src/Cake.Common/Tools/Chocolatey/Pack/ChocolateyNuSpecTransformer.cs
=> GH2426: Fixes Choco pack empty checks

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
Closes #2415.
Added RestoreLockedMode property to MSBuildSettings and SetRestoreLockedMode to MSBuildSettingsExtensions.
=> GH2451: Add support for MSBuild RestoreLockedMode.

src/Cake.Common.Tests/Fixtures/Build/TFBuildInfoFixture.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs, src/Cake.Common/Build/TFBuild/TFBuildProvider.cs
=> GH2432: Fixes for Azure Pipelines build system

src/Cake.Common/Tools/MSpec/MSpecAliases.cs
=> GH2025: Corrected NuGet Package name

src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/PlatformTarget.cs
=> GH2449: Add ARM64 target platform

src/Cake.Common/Tools/Roundhouse/RoundhouseRunner.cs
=> GH2465: Add additional tool names for Roundhouse

src/Cake.Core/IO/DirectoryPath.cs, src/Cake.Core/IO/FilePath.cs
=> Implicit operators should not throw

src/Cake.Common.Tests/Unit/Tools/NuGet/Restore/NuGetRestorerTests.cs, src/Cake.Common/Tools/NuGet/Restore/NuGetRestorer.cs, src/Cake.Common/Tools/NuGet/Restore/NugetRestoreSettings.cs
=> GH2459: Extended NuGetRestoreSettings and added Tests

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Restore/DotNetCoreRestorerTests.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreTool.cs
=> (GH-2468) Convert the DotNetCoreVerbosity to lowercase

src/Cake.Common/Tools/DotCover/DotCoverContext.cs, src/Cake.Common/Tools/OpenCover/OpenCoverContext.cs, src/Cake.Common/Tools/SpecFlow/SpecFlowContext.cs, src/Cake.Core.Tests/Fixtures/CakeContextFixture.cs, src/Cake.Core.Tests/Unit/CakeContextTests.cs, src/Cake.Core/CakeContext.cs, src/Cake.Core/CakeContextAdapter.cs, src/Cake.Core/ICakeContext.cs
=> GH2472: Expose ICakeConfiguration on CakeContext

src/Cake.Common.Tests/Fixtures/Build/TFBuildInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildAgentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildInfoTests.cs, src/Cake.Common.Tests/Unit/Build/TFBuild/Data/TFBuildPullRequestInfoTests.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildAgentInfo.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildInfo.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildPullRequestInfo.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildRepositoryInfo.cs, src/Cake.Common/Build/TFBuild/Data/TFBuildTriggeredBy.cs
Add additional Azure DevOps build variables
- Implements #2491
=> GH2491: TF build variables

build/version.cake
=> GH2501: Prevent exclusion of non-windows

src/Cake.Core.Tests/Unit/TaskSetupContextTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/ITaskTeardownContext.cs, src/Cake.Core/TaskTeardownContext.cs
=> GH2130: Adding exception to TaskTeardownContext

src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs, src/Cake.Core/CakeTask.cs, src/Cake.Core/CakeTaskBuilder.Execution.cs, src/Cake.Core/CakeTaskExtensions.cs
=> GH2463: Support Context for items function in DoesForEach

src/Cake.Common/Build/TFBuild/Data/TFBuildPublishCodeCoverageData.cs
=> GH2512: Correct minor typo in xml comments

src/Cake/Cake.csproj
=> GH2521: Updated Roslyn to 3.0.0

src/Cake/Cake.Tool.csproj
=> GH2523: Cake.Tool nuget package description

src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecContentFile.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecDependency.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecFrameworkAssembly.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecLicense.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecPackageType.cs, src/Cake.Common/Tools/NuGet/Pack/NuSpecReference.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
=> GH2156: New NuGet pack settings

src/Cake.Common.Tests/Fixtures/XmlPokeFixture.cs, src/Cake.Common.Tests/Unit/XML/XmlPokeTests.cs, src/Cake.Common/Xml/XmlPokeAliases.cs, src/Cake.Common/Xml/XmlPokeSettings.cs
=> GH2536: Additional formatting options for XmlPoke

src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
A local NET build has been successfully tested.
=> GH2157 - NuGetPack works with nuspec with contentFiles

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Clean/DotNetCoreCleanTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Run/DotNetCoreRunnerTests.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleanSettings.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleaner.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs, src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunSettings.cs, src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunner.cs
=> GH2560 missing runtime property

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
=> GH2556: Added missing Runtime property for dotnet test

src/Cake.NuGet/Install/NuGetPackageInstaller.cs
=> GH2161: Make NuGet.Config path absolute.

src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityPullRequestInfoTests.cs, src/Cake.Common/Build/TeamCity/Data/TeamCityPullRequestInfo.cs
=> GH1618: Enhance the Teamcity Provider's PullRequest detection

src/Cake/Cake.csproj
=> GH2599: Updated Autofac to 4.9.4

src/Cake/Cake.csproj
=> GH2601: Updated Microsoft.CodeAnalysis.CSharp.Scripting to 3.2.1

build.cake
=> (build) Updated GitVersion tool to version 5.0.0

src/Cake/Commands/HelpCommand.cs
Usage: Cake.exe [script] **[--target=value]** [--verbosity=value]
[--showdescription] [--dryrun] [..]
Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription
Options:
**--target=value       Specifies the target to build. Surround with quotes if target contains special chars.**
--verbosity=value    Specifies the amount of information to be displayed.
(Quiet, Minimal, Normal, Verbose, Diagnostic)
--debug              Performs a debug.
--showdescription    Shows description about tasks.
--showtree           Shows the task dependency tree.
--dryrun             Performs a dry run.
--exclusive          Execute a single task without any dependencies.
--bootstrap          Download/install modules defined by #module directives
--version …
=> GH2585: Helpcommand includes help about Target

src/Cake.Common.Tests/Unit/Tools/NuGet/Push/NuGetPusherTests.cs, src/Cake.Common/Tools/NuGet/Push/NuGetPushSettings.cs, src/Cake.Common/Tools/NuGet/Push/NuGetPusher.cs
Fixes https://github.com/cake-build/cake/issues/2625
=> Add SkipDuplicate flag to NuGetPushSettings

README.md, nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.CoreCLR.symbols.nuspec, nuspec/Cake.Portable.nuspec, nuspec/Cake.nuspec, nuspec/Cake.symbols.nuspec, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs, src/Shared.msbuild
=> GH2628: Add Jérémie to copyright & nuspec

build.cake, build/parameters.cake, build/paths.cake
=> GH2634: Move from global vars to typed context

src/Cake.Common/Build/TFBuild/Data/TFBuildPullRequestInfo.cs
Improve documentation for TFBuildPullRequestInfo.Id and TFBuildPullRequestInfo.Number
Fixes #2652
=> (GH-2652) Improve documentation for TFBuildPullRequestInfo.Id and TFBuildPullRequestInfo.Number

src/Cake.Core.Tests/Unit/CakeTaskBuilderExtensionsTests.cs, src/Cake.Core.Tests/Unit/CakeTaskTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/CakeTask.cs, src/Cake.Core/CakeTaskBuilder.Errors.cs, src/Cake.Core/CakeTaskExtensions.cs, src/Cake.Core/DefaultExecutionStrategy.cs, src/Cake.Core/IExecutionStrategy.cs, src/Cake/Scripting/DryRunExecutionStrategy.cs, tests/integration/Cake.Core/CakeAliases.cake
=> GH2661: Support async implementations of error handling

.github/workflows/build.yml, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsPullRequestInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsWorkflowInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/GitHubActionsProviderTests.cs, src/Cake.Common/Build/BuildProvider.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsEnvironmentInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsPullRequestInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs, src/Cake.Common/Build/GitHubActions/GitHubActionsInfo.cs, src/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cs, src/Cake.Common/Build/GitHubActions/IGitHubActionsProvider.cs
=> GH2677: Add GitHub Actions build provider

src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs, src/Cake.Core/Scripting/Processors/Loading/FileLoadDirectiveProvider.cs, tests/integration/Cake.Core/Scripting/LoadDirective.cake, tests/integration/resources/Cake.Core/Scripting/TestClass.cs
Fixes https://github.com/cake-build/cake/issues/2527
=> GH2527: #load directives that explicitly look for a specific extension will include all matching files

src/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cs, src/Cake.Common/Build/GitLabCI/GitLabCIProvider.cs, src/Cake.Common/Build/TeamCity/ITeamCityProvider.cs, src/Cake.Common/Build/TeamCity/TeamCityProvider.cs, src/Cake.Common/Build/TravisCI/TravisCIProvider.cs
Following up from #2677, I noticed something that tweaks my OCD, so this tweaks the provider property order for consistency across all providers.
=> GH2677: Tweak provider property order for consistency

src/Cake.Common.Tests/Unit/Build/BuildSystemAliasesTests.cs, src/Cake.Common/Build/BuildSystemAliases.cs
=> GH2691: Add GitHub Actions alias

src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Push/DotNetCorePushTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Push/NuGetPusherTests.cs, src/Cake.Common/Tools/Chocolatey/ApiKey/ChocolateyApiKeySetter.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleter.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusher.cs, src/Cake.Common/Tools/NuGet/Push/NuGetPusher.cs
=> GH2701: Api keys should be secret

src/Cake/Scripting/Roslyn/RoslynScriptSession.cs
=> GH2708: Always emit debug information

src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsRunnerInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsWorkflowInfoTests.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsEnvironmentInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRunnerInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs
=> GH2710: Add new GitHub Actions environment variables

src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Delete/DotNetCoreDeleterTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Push/DotNetCorePushTests.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleteSettings.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleter.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPushSettings.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusher.cs
=> GH2715: Add missing dotnet nuget command options

src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettings.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensions.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildBinaryLoggerImports.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildBinaryLoggerSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
=> GH2718: Add binary logger to dotnet msbuild settings

src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleterFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusherFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetAddSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetDisableSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetEnableSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetHasSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetListSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetRemoveSourceFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcerFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetUpdateSourceFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Delete/DotNetCoreNuGetDeleterTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusherTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcerTests.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourceSettings.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Source/DotNetCoreNuGetSourcer.cs
=> GH2728: Add dotnet nuget source commands

src/Cake.Common.Tests/Fixtures/Build/JenkinsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/BuildSystemTests.cs, src/Cake.Common.Tests/Unit/Build/Jenkins/Data/JenkinsChangeInfoTests.cs, src/Cake.Common/Build/BuildSystem.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsChangeInfo.cs, src/Cake.Common/Build/Jenkins/Data/JenkinsRepositoryInfo.cs
=> GH2764: Additional Jenkins information

src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs, src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs, src/Cake.Core/Tooling/Tool.cs, src/Cake.Core/Utilities/Tool.cs
=> GH2730: Scrape errors from process output

src/Cake.Common.Tests/Unit/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusherTests.cs, src/Cake.Common/Tools/DotNetCore/NuGet/Push/DotNetCoreNuGetPusher.cs
=> GH2721: Add quotes for nuget package name argument.

src/Cake.Core/Scripting/ScriptProcessor.cs
=> GH2714: Squash warning when skip package version check

src/Cake.Common.Tests/Fixtures/Tools/NuGet/SetApiKey/NuGetSetApiKeyFixture.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/SetApiKey/NuGetSetApiKeyTests.cs, src/Cake.Common/Tools/NuGet/SetApiKey/NuGetSetApiKey.cs, tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake
=> GH2733: Remove redundant process output checks

build.cake, tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake, tests/integration/Cake.Core/Scripting/AddinDirective.cake
=> GH2770: Bump script dependencies

src/Cake.Core.Tests/Unit/IO/FilePathCollectionTests.cs, src/Cake.Core.Tests/Unit/IO/FileSystemExtensionsTest.cs, src/Cake.Core.Tests/Unit/IO/PathCollectionTests.cs
- Tests for FileSystemExtensions
- Tests for FilePathCollections
- Tests for PathCollections
I rebased the commits in #2517, but since the PR came from an unknown repository, I needed to send a new PR.
=> GH2777: Added tests for Cake.Core.IO

src/Cake/Cake.csproj
=> GH2778: Update Roslyn to 3.6.0

README.md, nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.Portable.nuspec, nuspec/Cake.nuspec, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs, src/Shared.msbuild
Added @ecampidoglio information to the required places.
=> (doc) Add Enrico to author/copyright info

src/Cake.Common.Tests/Fixtures/Tools/NuGet/Deleter/NuGetDeleterFixture.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Delete/NugetDeleterTests.cs, src/Cake.Common/Tools/NuGet/Delete/NuGetDeleter.cs, src/Cake.Common/Tools/NuGet/Delete/NugetDeleteSettings.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs
Added NuGet Delete function to NuGet tools. I based my changes on the Push function implementation.
Relates to #2784
=> GH2784: Added NugetDelete function to Cake.Common.Tools.Nuget

build/version.cake, src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Properties/Cached_Obsolete_ExplicitWarning_WithMessage, src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Properties/Cached_Obsolete_ImplicitWarning_NoMessage, src/Cake.Core.Tests/Unit/Scripting/CodeGen/Expected/Properties/Cached_Obsolete_ImplicitWarning_WithMessage, src/Cake.Core/Scripting/CodeGen/PropertyAliasGenerator.cs
=> GH2786: Suppress cached proprerties obsoletion

src/Cake.Common/IO/Zipper.cs, tests/integration/Cake.Common/IO/ZipAliases.cake
=> GH2803: Ensure Valid Zip LastWriteTime

src/Cake.Core.Tests/Unit/Diagnostics/CakeBuildLogTests.cs, src/Cake.Core.Tests/Unit/Diagnostics/FormatParserTests.cs, src/Cake.Core/Diagnostics/Console/AnsiConsoleRenderer.cs, src/Cake.Core/Diagnostics/Formatting/CharReader.cs, src/Cake.Core/Diagnostics/Formatting/FormatParser.cs, tests/integration/Cake.Core/Diagnostics/ICakeLog.cake, tests/integration/build.cake
=> GH2798: Fix logging brace escaping

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Build/DotNetCoreBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Clean/DotNetCoreCleanTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuildSettings.cs, src/Cake.Common/Tools/DotNetCore/Build/DotNetCoreBuilder.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleanSettings.cs, src/Cake.Common/Tools/DotNetCore/Clean/DotNetCoreCleaner.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
=> GH2792: Add dotnet nologo options

src/Cake.Core.Tests/Fixtures/ToolResolutionStrategyFixture.cs, src/Cake.Core.Tests/Unit/Tooling/ToolLocatorTests.cs, src/Cake.Core.Tests/Unit/Tooling/ToolResolutionStrategyTests.cs, src/Cake.Core/Tooling/IToolLocator.cs, src/Cake.Core/Tooling/IToolResolutionStrategy.cs, src/Cake.Core/Tooling/Tool.cs, src/Cake.Core/Tooling/ToolLocator.cs, src/Cake.Core/Tooling/ToolResolutionStrategy.cs
=> GH2743: Tool resolution for multiple names should be breadth first

src/Cake.Common/Tools/ReportGenerator/ReportGeneratorRunner.cs
=> (GH-2822) Add support for .Net Global Tool

src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsWorkflowInfoTests.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs
=> GH2847: Add new GitHub Actions URL environment variables

src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Test/DotNetCoreTesterFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
=> GH2844: Add missing dotnet test options

src/Cake.Core/CakeArguments.cs, src/Cake/Cake.csproj
=> GH-2853: Make custom arguments case insensitive

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
=> GH2866: Support multiple dotnet test options

README.md
Remove example from README and link to website instead.
Fixes #2836
=> (GH-2836) Link to website for example in README

src/Cake.Core/Reflection/AssemblyVerifier.cs, src/Cake.Core/Scripting/ScriptProcessor.cs
Update links printed out in message to new URLs
Fixes #2879
=> (GH-2879) Update to new URLs

README.md
Add sponsors and backers to README
=> Add sponsors and backers to README

src/Cake/Infrastructure/Scripting/ScriptAssemblyResolver.cs
Fixes #2734  
Will need to find out a simple way to create a integration test for this. Maybe an addin with a resx file compiled to a satellite `.resource` file that's missing when addin is loaded.
=> GH2734: Tries to resolve assembly if not .resources file is found.

src/Cake.Core/Polyfill/EnvironmentHelper.cs, src/Cake.Core/Polyfill/Runtime.cs
Fixes #2908 (using approach recommended in https://github.com/dotnet/runtime/issues/12124#issuecomment-712523511).
=> GH2908: Future proof .NET [Core] detection

src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Execute/DotNetCoreExecutorFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Run/DotNetCoreRunnerFixture.cs, src/Cake.Common.Tests/Fixtures/Tools/DotNetCore/Test/DotNetCoreTesterFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Core/Extensions/EnumerableStringExtensions.cs, src/Cake.Core/IO/ProcessArgumentBuilder.cs
=> GH2870: Add helpers for adding multiple strings to ProcessArgumentBuilder

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.Tests/Cake.Tests.csproj, src/Cake/Cake.csproj
* .NET 5 RC2 related 
* Microsoft.NET.Test.Sdk 16.9.0-preview-20201020-06
* Microsoft.TestPlatform.ObjectModel 16.9.0-preview-20201020-06
* Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0-5.final
* System.Collections.Immutable 5.0.0-rc.2.20475.5
* System.Reflection.Metadata 5.0.0-rc.2.20475.5
* Autofac 6.0.0
=> (build) Bump dependencies

build.cake, tests/integration/Cake.Common/Tools/NuGet/NuGetAliases.cake
=> GH2920: Bump script dependencies

src/Cake.Frosting/Cake.Frosting.csproj, src/Cake.Frosting/CakeHostBuilder.cs, src/Cake.NuGet.Tests/Fixtures/NuGetAddinContentResolverFixture.cs, src/Cake.NuGet.Tests/Fixtures/NuGetContentResolverFixture.cs, src/Cake.NuGet.Tests/Fixtures/NuGetModuleFixture.cs, src/Cake.NuGet.Tests/Fixtures/NuGetPackageInstallerFixture.cs, src/Cake.NuGet.Tests/Fixtures/NuGetToolContentResolverFixture.cs, src/Cake.NuGet.Tests/Properties/AssemblyInfo.cs, src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs, src/Cake.NuGet.Tests/Unit/NuGetLoadDirectiveProviderTests.cs, src/Cake.NuGet.Tests/Unit/NuGetModuleTests.cs, src/Cake.NuGet.Tests/Unit/NuGetSourceRepositoryProviderTests.cs, src/Cake.NuGet.Tests/Unit/OutProcNuGetPackageInstallerTests.cs, src/Cake.NuGet/Client/NuGetLogger.cs, src/Cake.NuGet/Client/NuGetSourceRepositoryComparer.cs, src/Cake.NuGet/Client/NuGetSourceRepositoryProvider.cs, src/Cake.NuGet/Client/PackageReferenceExtensions.cs, src/Cake.NuGet/Installers/InProcessInstaller.cs, src/Cake.NuGet/Installers/OutOfProcessInstaller.cs, src/Cake.NuGet/NuGetContentResolver.cs, src/Cake.NuGet/NuGetLoadDirectiveProvider.cs, src/Cake.NuGet/NuGetModule.cs, src/Cake.NuGet/NuGetPackageInstaller.cs, src/Cake/Infrastructure/ContainerConfigurator.cs
This will make it possible to install NuGet tools in Frosting. 
I also cleaned up the code a bit to make it possible to initialize a NuGet module without providing a Cake configuration.
=> GH-2933: Add NuGet provider in Frosting

build/version.cake
=> GH2929: Use SemVer for milestones

src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs, src/Cake.Common/IO/DirectoryAliases.cs, tests/integration/Cake.Common/IO/DirectoryAliases.cake
=> GH2838: MakeRelative alias

src/Cake.Frosting.Template/Cake.Frosting.Template.csproj, src/Cake.Frosting.Template/templates/cakefrosting/build/Program.cs
=> Fix Frosting template

src/Cake.Frosting/Internal/Commands/DefaultCommand.cs, src/Cake.Frosting/Internal/Commands/DefaultCommandSettings.cs, src/Cake/Commands/DefaultCommand.cs, src/Cake/Commands/DefaultCommandSettings.cs
Updates CLI switches so that script runner and Frosting support the same switches.
Fixes #3007
=> (GH-3007) Support same CLI switches for script runners and Frosting

src/Cake.Core/CakeDataService.cs
=> GH3009: Make Cake Core CakeDataService Public

src/Cake.Cli/Cake.Cli.csproj, src/Cake.Frosting/CakeHost.cs, src/Cake.Frosting/Internal/Commands/DefaultCommand.cs, src/Cake.Frosting/Internal/Commands/DefaultCommandSettings.cs, src/Cake.Frosting/Internal/TypeRegistrar.cs, src/Cake.Frosting/Internal/TypeResolver.cs, src/Cake.Tests/Fakes/FakeRemainingArguments.cs, src/Cake.Tests/Fixtures/BuildFeatureFixture.cs, src/Cake.Tests/Unit/ProgramTests.cs, src/Cake.Tests/Utilities/TestContainerConfigurator.cs, src/Cake/Commands/DefaultCommand.cs, src/Cake/Commands/DefaultCommandSettings.cs, src/Cake/Features/Bootstrapping/BootstrapFeature.cs, src/Cake/Features/Building/BuildFeature.cs, src/Cake/Features/CakeFeature.cs, src/Cake/Infrastructure/Composition/AutofacTypeRegistrar.cs, src/Cake/Infrastructure/Composition/AutofacTypeResolver.cs, src/Cake/Infrastructure/ContainerConfigurator.cs, src/Cake/Infrastructure/IContainerConfigurator.cs, src/Cake/Program.cs
=> GH3020: Migrate from Spectre.Cli->Console

src/Cake.Frosting.Template/templates/cakefrosting/build/Build.csproj, src/Cake.Frosting.Template/templates/cakefrosting/build/Program.cs
Fix Frosting template on Linux.
Fixes #3032
=> (GH-3032) Fix Frosting template on Linux

src/Cake.Frosting/Extensions/CakeHostExtensions.cs, src/Cake.Frosting/Extensions/ServiceCollectionExtensions.cs
=> Fix typos in XML comments

src/Cake.Core.Tests/Unit/CakeArgumentsTests.cs, src/Cake.Core/Extensions/CakeArgumentsExtensions.cs
=> Add ICakeArguments.GetArgument extension

src/Cake/Program.cs
=> GH-3083: Update --tree usage example to match option in the help info

README.md, nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.Portable.nuspec, nuspec/Cake.nuspec, src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs, src/Cake.Frosting.Template/templates/cakefrosting/.template.config/template.json, src/Shared.msbuild
Added myself and Nils to the required places
=> (doc) Add Augusto & Nils to author/copyright info

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Publish/DotNetCorePublisherTests.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublishSettings.cs, src/Cake.Common/Tools/DotNetCore/Publish/DotNetCorePublisher.cs
=> GH3133: Add IncludeNativeLibrariesForSelfExtract and IncludeAllContentForSelfExtract to DotNetCorePublishSettings

src/Cake.Common.Tests/Fixtures/Build/TeamCityInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/TeamCity/Data/TeamCityBuildInfoTests.cs, src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs
=> GH-2955: Add Build Start Date & Time to TeamCity build information

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3188: Update Cake.NuGet dependencies

src/Cake/Cake.csproj
=> GH3191: Update Roslyn to 3.9.0-4.final

src/Cake.Core/Configuration/CakeConfigurationProvider.cs, src/Cake.Frosting/Extensions/ServiceCollectionExtensions.cs, src/Cake.Frosting/Internal/Commands/DefaultCommand.cs, src/Cake.Frosting/Internal/FrostingConfiguration.cs, tests/integration/Cake.Frosting/build/Build.csproj, tests/integration/Cake.Frosting/build/Program.cs, tests/integration/Cake.Frosting/cake.config
* Frosting utilize CakeConfigurationProvider, enables config
* Frosting IServiceCollection.UseToolPath
* cake.config file
* environment variables
* command line arguments
* Tools path should be resolved using configuration
* fixes #2904
=> GH2904: Frosting cake.config&tool config support

nuspec/Cake.CoreCLR.nuspec, nuspec/Cake.nuspec
=> GH-3213: Add iconUrl fallback to Cake and Cake.CoreCLR NuGet packages

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> GH-3228: Pin Ubuntu builds to ubuntu-18.04 (from ubuntu-latest)

src/Cake.Cli/Cake.Cli.csproj, src/Cake.Frosting/Internal/TypeRegistrar.cs, src/Cake/Infrastructure/Composition/AutofacTypeRegistrar.cs
=> GH3246: Upgrade to Spectre.Console 0.38.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3255: Update NuGet client libraries to 5.9.0

src/Cake.Common.Tests/Unit/Tools/GitVersion/GitVersionRunnerTests.cs, src/Cake.Common/Tools/GitVersion/GitVersionRunner.cs
=> #3281 - Remap existing verbosity values to valid GitVersion values

src/Cake.Common/Tools/GitVersion/GitVersionAliases.cs
=> #3283 - Update GitVersion alias reference page with dotnet tool usage example

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Pack/DotNetCorePackerTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePackSettings.cs, src/Cake.Common/Tools/DotNetCore/Pack/DotNetCorePacker.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs, src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs
=> GH2362: Add support for snupkg symbol packages

src/Cake.Core/CakeTaskBuilder.Criterias.cs, src/Cake.Core/CakeTaskBuilder.Errors.cs, src/Cake.Core/CakeTaskBuilder.Execution.cs
=> GH3294: Clean up task builder extensions

src/Cake.Common/Tools/VSTest/VSTestAliases.cs
=> GH3355: Update VSTestAliases.cs

src/Cake.Core/Scripting/ScriptConventions.cs, tests/integration/Cake.Core/Scripting/SpectreConsole.cake, tests/integration/build.cake
=> GH3360: Load Spectre.Console.dll by Default

src/Cake.Common/Tools/NuGet/NuGetAliases.cs
=> (#3365) Fix typo in documentation of NuGetAdd alias

src/Cake.Cli/Cake.Cli.csproj
=> GH3370: Update Spectre.Console to 0.39.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3372: Update Microsoft.NET.Test.Sdk to 16.9.4

src/Cake.Cli/Cake.Cli.csproj, src/Cake/Cake.csproj
=> GH3374: Update Autofac to 6.2.0

src/Cake/Features/Building/BuildFeature.cs, src/Cake/Infrastructure/Scripting/ScriptAssemblyResolver.cs
=> GH3226: Resolve neutral culture assembly if .resources file is not found.

src/Cake.Common/Tools/NuGet/Sources/NuGetSources.cs
#2030 
Made string comparison case insensitive to fix the issue.
=> #2030 - Fix case-sensitive nuget url compare

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3425: Update NuGet Client libraries to 5.11.0

src/Cake/Cake.csproj
=> GH3427: Update Microsoft.CodeAnalysis.CSharp.Scripting to 3.11.0

src/Cake.Frosting/Cake.Frosting.csproj
=> GH3429: Update Microsoft.Extensions.DependencyInjection to 5.0.2

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3431: Update Microsoft.NET.Test.Sdk to 16.11.0

.github/workflows/codeql-analysis.yml, build.cake
=> GH3440: Update GitVersion.Tool to version 5.7.0

src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core.Tests/Unit/CakeReportTests.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/CakeReport.cs, src/Cake.Core/CakeReportPrinter.cs, src/Cake.Core/CakeTaskExecutionStatus.cs
As per twitter and github discussion
https://twitter.com/pitermarx/status/1397844508495302663
https://github.com/cake-build/cake/discussions/3378
=> GH3445: Add Failed Task Status

src/Cake.Common.Tests/Unit/IO/DirectoryAliasesTests.cs, src/Cake.Common/IO/DirectoryAliases.cs, src/Cake.Common/IO/EnsureDirectoryDoesNotExistSettings.cs
@gep13 @augustoproiete @devlead - For #1882
=> GH-1882: Added Alias EnsureDirectoryDoesNotExist

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3455: Update Microsoft.NETCore.Platforms to 6.0.0-preview.7.21377.19

src/Cake.Common.Tests/Unit/Tools/InspectCode/InspectCodeRunnerTests.cs, src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs, src/Cake.Common/Tools/InspectCode/InspectCodeSettings.cs
=> (#3452) added an option to append --build / --no-build to InspectCodeSettings

src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs, src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsTests.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettings.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildSettingsExtensions.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs, src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs, src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs
=> GH3447: Add ContinuousIntegrationBuild to DotNetCoreMSBuildSettings & MSBuildSettings

src/Cake.Common.Tests/Fixtures/Tools/MSBuildRunnerFixture.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs, src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs, src/Cake.Common/Tools/MSBuild/MSBuildToolVersion.cs, src/Cake.Common/Tools/MSBuild/MSBuildVersion.cs
=> GH3464: Add support for MSBuild 17 / VS2022

src/Cake.Cli/Infrastructure/ExceptionLogger.cs, src/Cake.Core.Tests/Exceptions/CustomeExitCodeTests.cs, src/Cake.Core/CakeException.cs, src/Cake.Core/Tooling/Tool.cs, src/Cake.Frosting/Internal/Commands/DefaultCommand.cs, src/Cake/Commands/DefaultCommand.cs, src/Shared.msbuild, tests/integration/Cake.Common/Tools/Cake/CakeAliases.cake
added overload constructor that sets the exit code of the app and has the default code set to 1
I wasn't sure how to make a unit test(s) for this since setting the exit code kills the app
https://github.com/cake-build/cake/issues/2104
=> GH2104: Added custom exit code to CakeException

Directory.Build.props, src/Directory.Build.props
=> Disable NETSDK1138 warning ('netcoreapp3.0' is out of support ...)

src/Cake.Common.Tests/Properties/Resources.Designer.cs, src/Cake.Common.Tests/Properties/Resources.resx, src/Cake.Common.Tests/Unit/Solution/SolutionParserTests.cs, src/Cake.Common/Solution/SolutionParser.cs
Closes https://github.com/cake-build/cake/issues/3477
=> GH3477: Update SolutionParser to allow projects with absolute paths

src/Cake.Common.Tests/Unit/Tools/DotNetCore/MSBuild/DotNetCoreMSBuildBuilderTests.cs, src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs
=> GH3493: Quote dotnet build binary log filename

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Run/DotNetCoreRunnerTests.cs, src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunSettings.cs, src/Cake.Common/Tools/DotNetCore/Run/DotNetCoreRunner.cs
Add sources attribute to DotNetCoreRunSettings
Close #3502
=> GH-3502: Add sources attribute to DotNetCoreRunSettings

src/Cake.Common.Tests/Unit/Tools/DotNetCore/Test/DotNetCoreTesterTests.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs, src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTester.cs
Add sources attribute to DotNetCoreTestSettings
Close: #3503
=> GH-3503: Add sources attribute to DotNetCoreTestSettings

build.cake
=> GH3513: Update NuGet.CommandLine to 5.11.0

src/Cake.Core/IO/DirectoryPath.cs, src/Cake.Core/IO/FilePath.cs, src/Cake.Core/IO/PathComparer.cs, tests/integration/Cake.Core/IO/Path.cake, tests/integration/build.cake
=> Add IEquatable to FilePath and Directory Path

.github/workflows/build.yml, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsCommandsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Commands/GitHubActionsCommandsTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsEnvironmentInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsRunnerInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsRuntimeInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Data/GitHubActionsWorkflowInfoTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/GitHubActionsProviderTests.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GitHubActions/Commands/ArtifactResponse.cs, src/Cake.Common/Build/GitHubActions/Commands/CreateArtifactParameters.cs, src/Cake.Common/Build/GitHubActions/Commands/GitHubActionsCommands.cs, src/Cake.Common/Build/GitHubActions/Commands/PatchArtifactSize.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsEnvironmentInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRunnerInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRuntimeInfo.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs, src/Cake.Common/Build/GitHubActions/GitHubActionsInfo.cs, src/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cs, src/Cake.Common/Build/GitHubActions/IGitHubActionsProvider.cs, tests/integration/Cake.Common/Build/BuildSystemAliases.cake, tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake, tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake, tests/integration/build.cake
* Adds GitHub Actions Commands
* AddPath, fixes #3627
* SetEnvironmentVariable, fixes #3628
* UploadArtifact, fixes #3629
* Adds GitHub Actions
* Runtime Info
* Runner Name
* Workflow ActionPath
* fixes #3630
* Refactors GitHub Actions Paths, fixes #3631
* Initial work on BuildSystem integration tests
* Adds GitHub Actions Commands integration tests
=> GH3627, GH3628, GH3629, GH3630, GH3631: Refactor GitHub Actions Provider

src/Cake/Cake.csproj
=> GH3662: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.0.0-6.final

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3664: Update Microsoft.NET.Test.Sdk to 17.0.0

src/Cake.Core/Constants.cs
Bumps latest potential breaking change to 2.0.0
Fixes #3673
=> Bump latest potential breaking change to 2.0.0

src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildRunnerTests.cs, src/Cake.Common/Tools/MSBuild/MSBuildResolver.cs
=> GH3671: Detect VS2022 MSBuild when only Build Tools are installed

src/Cake.Core.Tests/Unit/CakeEngineTests.cs, src/Cake.Core/AfterSetupEventArgs.cs, src/Cake.Core/AfterTaskSetupEventArgs.cs, src/Cake.Core/AfterTaskTeardownEventArgs.cs, src/Cake.Core/AfterTeardownEventArgs.cs, src/Cake.Core/BeforeSetupEventArgs.cs, src/Cake.Core/BeforeTaskSetupEventArgs.cs, src/Cake.Core/BeforeTaskTeardownEventArgs.cs, src/Cake.Core/BeforeTeardownEventArgs.cs, src/Cake.Core/CakeEngine.cs, src/Cake.Core/ICakeEngine.cs
This allows for any logic required after each section to be executed.
Fixes #3151
=> GH-3151: Add events to ICakeEngine to invoke at the end of Setup/Teardown

global.json
=> GH3686: Update .NET SDK to 6.0.100 RTM

src/Cake/Infrastructure/Scripting/ScriptAssemblyResolver.cs
=> GH3681: Move `ScriptAssemblyResolver` logging to debug/diagnostic level

src/Cake.Frosting/Cake.Frosting.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake/Cake.csproj
* Update System.Collections.Immutable to 6.0.0
* fixes #3688
* Update System.Reflection.Metadata to 6.0.0
* fixes #3689
* Update Microsoft.Extensions.DependencyInjection to 6.0.0
* fixes #3690
* Update Microsoft.NETCore.Platforms to 6.0.0
* fixes #3691
=>  GH3688,3689,3690,3691: Update assemblies to .NET 6.0.0

src/Cake/Program.cs
Closes https://github.com/cake-build/cake/issues/3697
=> GH3697: Register DefaultCommandSettings with Autofac

src/Cake.Frosting/Internal/TypeResolver.cs, src/Cake/Infrastructure/Composition/AutofacTypeResolver.cs
=> (#3699) ITypeResolvers do not throw on Resolve

src/Cake.Common.Tests/Unit/ArgumentAliasesTests.cs, src/Cake.Common/ArgumentAliases.cs, tests/integration/Cake.Common/ArgumentAliases.cake
=> GH3709: Add Arguments ICollection fallback

src/Cake.Core/Scripting/Processors/UsingStatementProcessor.cs, tests/integration/Cake.Core/Scripting/UsingDirective.cake
=> GH2665: Support blockless using statment

GitReleaseManager.yaml
* fixes #3561
@gep13 is this enough?
=> GH3561: Change GRM Label order

src/Directory.Build.props
=> GH3727: Update Microsoft.SourceLink.GitHub to v1.1.1

src/Cake.Common.Tests/Unit/SemVerTests.cs, src/Cake.Common/SemanticVersion.cs
=> GH3743: Enable null SemVer comparing

build.cake
* fixes #3748
* fixes #3747
* fixes #3746
=> GH3748, GH3747, GH3746: Update GitVersion.Too to 5.8.1, Update SignClient to 1.3.15, GitReleaseManager.Tool to 0.12.1

build.cake
=> GH3750: Update Cake.Twitter to 2.0.0

build.cake
=> GH3754: Update Cake.Gitter to 2.0.0

src/Cake.Cli/Cake.Cli.csproj
=> GH3758: Update Autofac to 6.3.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3756: Update NuGet.* to 6.0.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3769: Update Microsoft.NETCore.Platforms to 6.0.1

src/Cake.Core/CakeEngine.cs
=> GH2746: Log task duration at the end of a task

src/Cake.Common.Tests/Fixtures/Tools/DotNet/SDKCheck/DotNetSDKCheckerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/SDKCheck/DotNetSDKCheckTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/SDKCheck/DotNetSDKCheckSettings.cs, src/Cake.Common/Tools/DotNet/SDKCheck/DotNetSDKChecker.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add alias for dotnet sdk check command
Fixes #3480
Please review
=> Add alias for dotnet sdk check command

global.json
=> GH3807: Update .NET SDK to 6.0.102

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3813: Update NSubstitute to 4.3.0

global.json
=> GH3840: Update .NET SDK to 6.0.201

src/Cake/Cake.csproj
=> GH3846: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.1.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3848: Microsoft.NET.Test.Sdk to 17.1.0

src/Cake/Cake.csproj
=> GH3851: Update System.Reflection.Metadata to 6.0.1

src/Cake.Common/Net/HttpAliases.cs, src/Cake.Common/Net/UploadFileSettings.cs
Closes #2431 
I did not find any unit tests for the changed functions, not sure if I should create some
=> GH2431: Add UploadFileSettings to UploadFile functions

src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs, src/Cake/Infrastructure/Scripting/ScriptAssemblyResolver.cs
=> GH3823: Only load valid versioned assmblies

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Search/DotNetWorkloadSearcherFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Search/DotNetWorkloadSearchTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Workload/Search/DotNetWorkload.cs, src/Cake.Common/Tools/DotNet/Workload/Search/DotNetWorkloadSearchSettings.cs, src/Cake.Common/Tools/DotNet/Workload/Search/DotNetWorkloadSearcher.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add alias for dotnet workload search command
Fixes #3485
Please review
=> GH3485: Add alias for dotnet workload search command

tests/integration/Cake/ScriptCache.cake, tests/integration/resources/Cake/ScriptCache/Config/build.cake, tests/integration/resources/Cake/ScriptCache/Config/cake.config
* fix `ScriptCacheHashPath` not being checked correctly
* add environment variable drive cache path example
* relates to #2099
=> GH2099: Fix and add script cache integration test

src/Cake/Infrastructure/Scripting/RoslynScriptSession.cs, tests/integration/Cake/ScriptCache.cake
* Include script host in the cache filename
* Move hash from file to the cache filename
* fixes #3879
* fixes #3880
=> GH3879/3880: Scope cache per script host

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3890: Update NuGet.* to 6.2.0

global.json
=> GH3895: Update .NET SDK to 6.0.301

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3897: Update NuGet.* to 6.2.1

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3899: Microsoft.NETCore.Platforms to 6.0.4

src/Cake/Cake.csproj
=> GH3901: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.2.0

src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3903: Update Microsoft.NET.Test.Sdk to 17.2.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3905: Update xunit.runner.visualstudio to 2.4.5

build.cake
=> GH3911: Update GitVersion.Tool to 5.10.3

global.json
=> GH3918:  Update .NET SDK to 6.0.302

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3920: Update Microsoft.NETCore.Platforms to 6.0.5

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3922: Update NSubstitute to 4.4.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH9933: Update NuGet.* to 6.3.0

global.json
=> GH3935: Update .NET SDK to 6.0.400

src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3938: Update Microsoft.NET.Test.Sdk to 17.3.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj, tests/integration/resources/Cake.Common/Tools/DotNet/hwapp.tests/hwapp.tests.csproj
=> GH3940: Update xunit to 2.4.2

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3942:  Castle.Core to 5.1.0

.github/workflows/build.yml, src/Cake.Core/Polyfill/AssemblyHelper.cs, src/Cake.Core/Reflection/AssemblyLoader.cs, src/Cake.Core/Scripting/ScriptConventions.cs, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.NuGet/NuGetContentResolver.cs, src/Cake/Infrastructure/Composition/ModuleSearcher.cs, tests/integration/Cake.Core/Scripting/AddinDirective.cake
* Better RID detection on OSX
* Support libdl 2
* Better OSX dylib support
* Native library integration tests
* Assembly load diagnostic logging
* Build & test on Ubuntu 22.04
* fixes #3931
=> GH3931: Improve posix native library loading

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Install/DotNetWorkloadInstallerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Install/DotNetWorkloadInstallTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Workload/Install/DotNetWorkloadInstallSettings.cs, src/Cake.Common/Tools/DotNet/Workload/Install/DotNetWorkloadInstaller.cs
Add an alias for dotnet workload list command
Fixes #3481
Please review
=> Add alias for dotnet workload install command

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Repair/DotNetWorkloadRepairerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Repair/DotNetWorkloadRepairTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Workload/Repair/DotNetWorkloadRepairSettings.cs, src/Cake.Common/Tools/DotNet/Workload/Repair/DotNetWorkloadRepairer.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet workload repair` command
Fixes #3483
Please review
=> Add alias for dotnet workload repair command

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Update/DotNetWorkloadUpdaterFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Update/DotNetWorkloadUpdateTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Workload/Update/DotNetWorkloadUpdateSettings.cs, src/Cake.Common/Tools/DotNet/Workload/Update/DotNetWorkloadUpdater.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet workload update` command
Fixes #3487
Please review
=> Add alias for dotnet workload update command

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Workload/Restore/DotNetWorkloadRestorerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Workload/Restore/DotNetWorkloadRestoreTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Workload/Restore/DotNetWorkloadRestoreSettings.cs, src/Cake.Common/Tools/DotNet/Workload/Restore/DotNetWorkloadRestorer.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet workload restore` command
Fixes #3484
Please review
=> Add alias for dotnet workload restore command

global.json
=> GH3963: Update .NET SDK to 6.0.401

src/Cake/Cake.csproj
=> GH3965: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.3.1

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH3967: Update Microsoft.NET.Test.Sdk to 17.3.2

src/Cake.NuGet/Cake.NuGet.csproj
=> GH3976: Update NuGet.* to 6.3.1

src/Cake.Frosting/Cake.Frosting.csproj
=> GH3978: Microsoft.Extensions.DependencyInjection to 6.0.1

global.json
=> GH3980: Update .NET SDK to 6.0.402

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> GH3985/GH3986: Remove deprecated Ubuntu-18.04 GitHub Action env

src/Cake.Testing.Xunit/WindowsFactAttribute.cs
Fixes https://github.com/cake-build/cake/issues/3867
Rename attribute WindowsFact->WindowsFactAttribute.
=> #3867 Rename attribute WindowsFact-> WindowsFactAttribute

.github/workflows/build.yml, appveyor.yml, build.cake, src/Cake.Frosting.Template/Cake.Frosting.Template.csproj, src/Cake.Frosting.Template/templates/cakefrosting/.template.config/template.json, src/Cake.Frosting.Template/templates/cakefrosting/build/Build.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake/Cake.csproj, src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs, src/Shared.msbuild, tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake, tests/integration/Cake.Common/Tools/TextTransform/TextTransformAliases.cake, tests/integration/Cake.Core/Scripting/AddinDirective.cake, tests/integration/Cake.Core/Scripting/DefineDirective.cake, tests/integration/Cake.Frosting/build/Build.csproj, tests/integration/resources/Cake.Common/Tools/DotNet/hwapp.tests/hwapp.tests.csproj, tests/integration/resources/Cake.Common/Tools/DotNet/hwapp/hwapp.csproj
Fixes #3972 and #3949
Please review
=> Remove .NET Core 3.1 and .NET 5 TFM

.github/workflows/build.yml, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsCommandsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsInfoFixture.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Commands/GitHubActionsCommandsTests.cs, src/Cake.Common/Build/GitHubActions/Commands/GitHubActionsCommands.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsRuntimeInfo.cs, tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake, tests/integration/Cake.Common/Build/GitHubActions/ValidateGitHubActionsProvider.cake
=> GH4009: Add GitHub Actions SetOutputParameter command

src/Cake/Cake.csproj, src/Cake/Infrastructure/Scripting/ReferenceAssemblyResolver.cs
=> GH4020:  Update Basic.Reference.Assemblies.* to 1.4.0

.github/workflows/codeql-analysis.yml
=> GH4024: Update CodeQL Action to v2

src/Cake.Frosting/IFrostingTask.cs, src/Cake.Frosting/Internal/FrostingEngine.cs
=> GH3329: Frosting: Support criteria description

src/Cake.Common.Tests/Fixtures/Build/GitLabCIFixture.cs, src/Cake.Common.Tests/Unit/Build/GitLabCI/GitLabCICommandsTests.cs, src/Cake.Common.Tests/Unit/Build/GitLabCI/GitLabCIProviderTests.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GitLabCI/GitLabCICommands.cs, src/Cake.Common/Build/GitLabCI/GitLabCIProvider.cs, src/Cake.Common/Build/GitLabCI/IGitLabCIProvider.cs
=> GH4028: Add GitLab CI SetEnvironmentVariable command

src/Cake.Frosting.Tests/Fakes/FakeLifetime.cs, src/Cake.Frosting/FrostingLifetime.cs, src/Cake.Frosting/FrostingSetup.cs, src/Cake.Frosting/IFrostingLifetime.cs, src/Cake.Frosting/Internal/FrostingEngine.cs, tests/integration/Cake.Frosting/build/Lifetime.cs
=> GH3946: Add ISetupContext to Frosting lifetime

src/Cake.Common.Tests/Fixtures/Build/GitLabCIInfoFixture.cs, src/Cake.Common/Build/GitLabCI/Data/GitLabCIRunnerInfo.cs
=> GH4030: Fix GitLab CI runner tags

src/Cake.Common.Tests/Fixtures/Build/GitHubActionsCommandsFixture.cs, src/Cake.Common.Tests/Fixtures/Build/GitHubActionsFixture.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/Commands/GitHubActionsCommandsTests.cs, src/Cake.Common.Tests/Unit/Build/GitHubActions/GitHubActionsProviderTests.cs, src/Cake.Common/Build/BuildSystemAliases.cs, src/Cake.Common/Build/GitHubActions/Commands/GitHubActionsCommands.cs, src/Cake.Common/Build/GitHubActions/Data/GitHubActionsAnnotation.cs, src/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cs, tests/integration/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cake
Fixes #2863.
Note: implementation guided by looking at:
* https://github.com/actions/runner/blob/main/src/Runner.Common/ActionCommand.cs
* https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts
@devlead I'd love to squeeze in this pull request just in time for [Hacktoberfest](https://hacktoberfest.com). 😉
=> GH2863: Add GitHub Actions workflow commands

src/Cake.Common/Tools/DotNet/Test/DotNetTestSettings.cs, src/Cake.Common/Tools/DotNet/Test/DotNetTester.cs
=> GH4036: Adds MSBuildSettings to DotNetTestSettings

src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildBuilder.cs, src/Cake.Common/Tools/DotNet/MSBuild/MSBuildArgumentBuilderExtensions.cs, src/Cake.Core/IO/ProcessArgumentBuilder.cs
=> GH4034: Enable .NET MSBuild Settings ArgumentCustomization

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> GH4040: Update GitHub actions checkout & setup-dotnet to v3

src/Cake/Cake.csproj
=> GH4052: Update Basic.Reference.Assemblies.* to 1.4.1

SECURITY.md, global.json, src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.Frosting/Cake.Frosting.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.Tests/Cake.Tests.csproj, src/Cake/Cake.csproj
* fixes #4057
* fixes #4058
* fixes #4059
* fixes #4060
* fixes #4061
* fixes #4063
* fixes #4023
=> GH4057/GH4058/GH4059/GH4060/GH4061/GH4063: Update released .NET 7 assemblies & SDK

src/Cake.NuGet/Cake.NuGet.csproj
=> GH-4085 Update NuGet libraries to v6.4.0

src/Cake/Cake.csproj
=> GH-4090 Update Microsoft.CodeAnalysis.CSharp.Scripting to v4.4.0

src/Cake.Cli/Cake.Cli.csproj, src/Cake/Cake.csproj
=> GH-4086 Update Autofac to v6.5.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH4087: Update Newtonsoft.Json to 13.0.2

src/Cake.Common/ArgumentAliases.cs, tests/integration/Cake.Common/ArgumentAliases.cake
…Arguments versus context.Argument
=> GH-4128: Fix Inconsistent determination of positional Argument when using context.Arguments versus context.Argument

build.cake, build/credentials.cake, build/parameters.cake
=> GH-4134: Remove posting messages to Gitter now that it has moved to Matrix

build.cake
=> GH4107/GH4178: Update GitVersion.Tool to 5.12.0 & GitReleaseManager.Tool to 0.13.0

src/Cake.Cli/Cake.Cli.csproj, src/Cake/Cake.csproj
* fixes #4181
* fixes #4182
* fixes #4183
* fixes #4184
=> GH4181/GH4182/GH4183/GH4184: Update Cake.Tool dependencies

build.cake
=> GH4189: Update Cake.Twitter to 3.0.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Common.Tests/Unit/ReleaseNotesParserTests.cs, src/Cake.Common.Tests/Unit/Tools/MSBuild/MSBuildSettingsExtensionsTests.cs, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.Core.Tests/Unit/Graph/CakeGraphTests.cs, src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, src/Cake.Core.Tests/Unit/Scripting/Processors/LoadDirectiveProcessorTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptAliasTests.cs, src/Cake.Core.Tests/Unit/Scripting/ScriptTests.cs, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.NuGet.Tests/Unit/NuGetContentResolverTests.cs, src/Cake.NuGet.Tests/Unit/NuGetLoadDirectiveProviderTests.cs, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4191: Update xunit to 2.5.0

global.json
=> GH4207: Update .NET SDK to 7.0.401

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4208: Update xunit to 2.5.1

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4211: Update Microsoft.NET.Test.Sdk to 17.7.2

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4213: Update NSubstitute to 5.1.0

src/Cake.Cli/Cake.Cli.csproj, src/Cake/Cake.csproj
=> GH4215: Update Autofac to 7.1.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH4217: Update NuGet.* to 6.7.0

src/Cake/Cake.csproj
=> GH4219: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.7.0

global.json
=> GH4238: Update .NET SDK to 7.0.403

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4240: Update xunit to 2.5.3

build.cake
=> GH4242: Update GitReleaseManager.Tool to 0.15.0

build.cake
=> GH4244: Update sign tool to 0.9.1-beta.23530.1

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.Frosting/Cake.Frosting.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj, src/Cake/Cake.csproj
* (GH-4251) Update System.Reflection.Metadata 8.0.0
* (GH-4250) Update System.Collections.Immutable to 8.0.0
* (GH-4249) Update Microsoft.Extensions.DependencyInjection to 8.0.0
* (GH-4248) Update Microsoft.NET.Test.Sdk to 17.8.0
* (GH-4247) Update xunit to 2.6.1
=> GH4251/4250/4249/4248/4247: Update dependencies

src/Cake.Core.Tests/Cake.Core.Tests.csproj
=> GH4264: Update Verify.Xunit to 22.5.0

src/Directory.Build.props
=> GH4262: Update Microsoft.SourceLink.GitHub to 8.0.0

src/Cake.Core/Constants.cs
=> GH4266: Update LatestPotentialBreakingChange to 4.0.0

build.cake
=> GH4268: Update GitReleaseManager.Tool to 0.16.0

src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj
=> GH4272: Update xunit to 2.6.2

src/Cake/Cake.csproj
=> GH4274: Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.8.0

src/Cake.NuGet/Cake.NuGet.csproj
=> GH4276: Update NuGet.* to 6.8.0

src/Cake.Cli/Cake.Cli.csproj, src/Cake.Common.Tests/Cake.Common.Tests.csproj, src/Cake.Core.Tests/Cake.Core.Tests.csproj, src/Cake.Core.Tests/Unit/Scripting/CodeGen/MethodAliasGeneratorTests.cs, src/Cake.Core.Tests/Unit/Scripting/CodeGen/PropertyAliasGeneratorTests.cs, src/Cake.DotNetTool.Module.Tests/Cake.DotNetTool.Module.Tests.csproj, src/Cake.Frosting.Tests/Cake.Frosting.Tests.csproj, src/Cake.NuGet.Tests/Cake.NuGet.Tests.csproj, src/Cake.NuGet/Cake.NuGet.csproj, src/Cake.Testing.Xunit/Cake.Testing.Xunit.csproj, src/Cake.Tests/Cake.Tests.csproj, src/Cake/Cake.csproj
* (GH-4306) Update Autofac to 8.0.0
* (GH-4305) Update Microsoft.CodeAnalysis.CSharp.Scripting to 4.9.2
* (GH-4304) Update Basic.Reference.Assemblies.* to 1.5.0 
* (GH-4303) Update Microsoft.NET.Test.Sdk to 17.9.0
* (GH-4302) Update Verify.Xunit to 23.5.2
* (GH-4301) Update xunit to 2.7.0 
* (GH-4300) Update NuGet.* to 6.9.1
=> GH4300/GH4301/GH4302/GH4303/GH4304/GH4305/GH4306: Update dependencies

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Reference/Add/DotNetReferenceAdderFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Reference/Add/DotNetReferenceAdderTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Reference/Add/DotNetReferenceAddSettings.cs, src/Cake.Common/Tools/DotNet/Reference/Add/DotNetReferenceAdder.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet add reference` command
Fixes #4282
Please review
=> Add DotNetAddReference alias for dotnet add reference command

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Reference/List/DotNetReferenceListerFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Reference/List/DotNetReferenceListerTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Reference/List/DotNetReferenceListSettings.cs, src/Cake.Common/Tools/DotNet/Reference/List/DotNetReferenceLister.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
Add an alias for `dotnet list reference` command
Fixes #4353
Please review
=> Add DotNetListReference alias for dotnet list reference command

README.md
=> Fix the link for "Setting up a new project"

.github/ISSUE_TEMPLATE/bug-report.yml
=> Add FreeBSD to Bug Report issue template

.github/ISSUE_TEMPLATE/bug-report.yml
* Remove .NET Framework runner
* Remove .NET Core runner
* Replace 32-bit architecture with x86
* Replace 64-bit architecture with x64
* Add Arm64 architecture
=> Issue template remove unsupported runners & unify system architecure 

global.json, src/Directory.Packages.props
=> GH4382: Update to Stable versions of dependencies

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Sln/Add/DotNetSlnAdderFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Sln/Add/DotNetSlnAdderTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Sln/Add/DotNetSlnAddSettings.cs, src/Cake.Common/Tools/DotNet/Sln/Add/DotNetSlnAdder.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
`dotnet sln add ` - Adds one or more projects to the solution file.
Docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#add
alternative PR for #3817
Please review
=> Add DotNetSlnAdd alias for dotnet sln add command

src/Cake.Common.Tests/Fixtures/Tools/DotNet/Sln/Remove/DotNetSlnRemoverFixture.cs, src/Cake.Common.Tests/Unit/Tools/DotNet/Sln/Remove/DotNetSlnRemoverTests.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.cs, src/Cake.Common/Tools/DotNet/Sln/Remove/DotNetSlnRemoveSettings.cs, src/Cake.Common/Tools/DotNet/Sln/Remove/DotNetSlnRemover.cs, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake
`dotnet sln remove` - Removes a project or multiple projects from the solution file.
Docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln#remove
alternative PR for #3817
Please review
=> Add DotNetSlnRemove alias for dotnet sln remove command

src/Directory.Packages.props
- #4420
- #4421
- #4422
- #4423
- #4424
- #4425
- #4426
=> GH4420/4421/4422/4423/4424/4425/4426: Update Dependencies

global.json
=> GH4433: Update .NET SDK to 9.0.101

src/Directory.Packages.props
* #4437
* #4438
* #4439 
* #4440
=> GH4437/4438/4439/4440: Update xunit.v3 to 1.0.1, xunit to 2.9.3, Verify.XunitV3 to 28.8.1, Basic.Reference.Assemblies.Net80 to 1.8.0

global.json
=> GH4443: Update .NET SDK to 9.0.102

build.cake, src/Cake.Common/ArgumentAliases.cs, src/Cake.Common/EnviromentAliases.cs, src/Cake.Common/IO/GlobbingAliases.cs, src/Cake.Common/ProcessAliases.cs, src/Cake.Common/ReleaseNotesAliases.cs, src/Cake.Common/Solution/Project/XmlDoc/XmlDocAliases.cs, src/Cake.Common/Solution/SolutionAliases.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.MSBuild.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.Package.cs, src/Cake.Common/Tools/DotNet/DotNetAliases.Test.cs, src/Cake.Common/Tools/MSBuild/MSBuildAliases.cs, src/Cake.Common/Tools/NuGet/NuGetAliases.cs, src/Cake.Core.Tests/Unit/Scripting/Analysis/ScriptAnalyzerTests.cs, tests/integration/Cake.Common/Build/AzurePipelines/AzurePipelinesProvider.cake, tests/integration/Cake.Common/IO/FileAsync.cake, tests/integration/Cake.Common/IO/GlobbingAliases.cake, tests/integration/Cake.Common/Tools/DotNet/DotNetAliases.cake, tests/integration/build.ps1, tests/integration/utilities/comparers/ProjectParserResultEqualityComparer.cake, tests/integration/utilities/comparers/SolutionParserResultEqualityComparer.cake, tests/integration/utilities/io.cake
Corrected the usage of the following blocks:
* if
* using
* foreach
Once seen, these could not be _unseen_!
=> (maint) Fixed formatting of several files

build.cake
=> GH4561: Fix Publish AzureDevOps/Integration Test dependency

build.cake
=> GH4589: Upload GitHub Artifacts

build.ps1, build.sh
=> GH4597: Add option to install supported SDKs in build.sh/ps1

GitVersion.yml
=> GH4591: Update GitVersion next version to 6.0.0

src/Directory.Packages.props
=> GH4606: Update Verify.XunitV3 to 30.20.1
